### ISSUE TITLE
[BUG] Misspelling found

### ISSUE THREAD

**Issue by 3DFans** [prusa3d/Prusa-Firmware-Buddy#1037]
![IMG_20201106_212525](https://user-images.githubusercontent.com/59125879/98413793-8a1a2400-207a-11eb-89fb-e472fcd14709.jpg)
Just a little thing that can be fixed quickly. 
Because the error devil has crept into the calibration menu. 
There it says: "bis der Filament am", but it must read "bis **das** Filament am". 

regards

**Comment by JustAnother1** [comment]
"Druck**blech**" ? That should be "Druck**bett**" !Also "Knopf **D**rehen" should be "Knopf **d**rehen"

**Comment by 3DFans** [comment]
> "Druck**blech**" ? That should be "Druck**bett**" !Also "Knopf **D**rehen" should be "Knopf **d**rehen"

The pressure plate is already correct because it means the edition. ;) Print bed would be the whole.

**Comment by JustAnother1** [comment]
@3DFans If with "edition" you mean the removable print surface / the PEI coated sheet. Then calling that a "Blech" is correct. But as this test is executed with the print surface being placed onto of the print bed it is correct to refer to the print surfaces in the assembled situation as the print bed.
As a native speaker I still think that "Druck**bett**" is the better word here.
But consistency is more important than the best word here. The printer should always refer to the print bed with the same words. If that is the "Blech" than so be it. It is better if the user smiles about the "Blech" than the user being confused what the printer wants now.

**Comment by JohnnyDeer** [comment]
Hi @3DFans thank you for reporting.

**Comment by Chips83** [comment]
There are to many punctuation marks (,) and some words are in strange places for a native german speaker. I think it would be better to write "Sobald der Drucker beginnt Kunststoff zu extrudieren, stellen Sie die Höhe der Düse durch drehen des Knopfes ein, solange bis das Filament am Druckblech haftet."
