### ISSUE TITLE
[FEATURE REQUEST]offset for temperature when non-brass nozzles are installed

### ISSUE THREAD

**Issue by oopsitsaflame** [prusa3d/Prusa-Firmware-Buddy#1038]
Hi,

a while ago i tried to add a hardened steel nozzle to my mini. And failed miserably. As most of you know, steel conducts heat way slower than brass, so it needs to be higher in temp to make this up.

Any time i tried loading filament the extruder grinded into it because the pre defined temps for filaments were to low and it could not be molten fast enough.

**Comment by JohnnyDeer** [comment]
Hi @oopsitsaflame thank you for suggestion. We noted this as possible future feature.

**Comment by RichiH** [comment]
As Prusa released blog posts, live video, etc around food-safe plastics and the emphasis on using non-brass nozzles due to their lead content, is this a confirmed feature now?

**Comment by SM-26** [comment]
Dumb question, but I've now added a Harden steel nozzle.
If we do a PID tune, and add the value in the start of gcode, should this be negated?

**Comment by oopsitsaflame** [comment]
> Dumb question, but I've now added a Harden steel nozzle.
> If we do a PID tune, and add the value in the start of gcode, should this be negated?

no it should not, the thermistor is in the heating block
