### ISSUE TITLE
[FEATURE REQUEST] Run part cooling fan while cooling nozzle

### ISSUE THREAD

**Issue by blerrgh** [prusa3d/Prusa-Firmware-Buddy#1057]
Often we are waiting on the Mini nozzle to cool down, especially if we're preheated to filament temps but then need to drop down to 170C for bed leveling.

Running the part cooling fan should blow some extra air over the nozzle and speed up cooling somewhat, and I can't really think of any downsides.

**Comment by JohnnyDeer** [comment]
Hi @blerrgh this feature is on our to do list.

**Comment by blerrgh** [comment]
Awesome, thanks!
