### ISSUE TITLE
[BUG]Printing time display error

### ISSUE THREAD

**Issue by Iqwertz** [prusa3d/Prusa-Firmware-Buddy#1088]
**Printer type** - [MINI]

**Printer firmware version**-  [e.g. 4.0.5, ...]

**Original or Custom firmware** [Original/Custom]

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
 USB drive

**Describe the bug**
At the End (1hour before finish)  of the Print the remaining printing Time is suddenly 37days

**How to reproduce**
It doesnt really depend on the .gcod file because I had it with most of my prints! So it propably has something to do with the slicer... (prusaslicer 2.3.0 alpha)

**Expected behavior**
 Show the correct remaining printing Time at the End

3MF File:
[https://drive.google.com/file/d/1vFVSJlbCC9j5iOScxoaFGJvS7mYkAwK9/view?usp=sharing](Drive Linkt to .3mf)

Image:

![image](https://user-images.githubusercontent.com/36999445/100284595-b0432d80-2f6f-11eb-8b4b-d242abfd45f2.png)

**Comment by JohnnyDeer** [comment]
Hi @Iqwertz this issue is fixed by PrusaSlicer 2.3.0 final and MINI FW 4.3.0. Should not happen anymore. I´m closing this issue.
