### ISSUE TITLE
Heat block crashing into heatbed positioning screws during skirt printing at the very end of the bed

### ISSUE THREAD

**Issue by LuckyBenni** [prusa3d/Prusa-Firmware-Buddy#109]
I recently sliced with PrusaSlicer a huge set of parts completely filling the heatbed.
While printing the skirt the heater block kept crashing into the heatbed positioning screws (firmware 4.0.1).
Can such occurence be avoided either by PrusaSlicer or even better through firmware?

**Comment by michalxfanta** [comment]
This issue is probably related to a previously reported issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/108 We're working to improve Mesh Bed Leveling and detect a damaged MINDA sensor.
