### ISSUE TITLE
SW 4.2.1 Display task issue, blue screen.

### ISSUE THREAD

**Issue by marcingajewski** [prusa3d/Prusa-Firmware-Buddy#1106]
I bought the reprap printer with bigger screen. 
I updated the printer's SW to latest version of 4.2.1 and it goes into blue screen when want to return from version info.
![WP_20201130_15_38_03_Pro](https://user-images.githubusercontent.com/4764699/100623579-a2502c80-3322-11eb-9c4a-9c4d010f0ce9.jpg)
![WP_20201130_15_38_08_Pro](https://user-images.githubusercontent.com/4764699/100623654-bbf17400-3322-11eb-8e90-ef3082bfd9e9.jpg)
![WP_20201130_15_37_49_Pro](https://user-images.githubusercontent.com/4764699/100623734-d6c3e880-3322-11eb-9e9d-4420c7b928c2.jpg)

**Comment by JohnnyDeer** [comment]
Hi @marcingajewski what exact type of printer you are using? Did you just flash the printer and checked version info followed with blue screen or you did something before? Thank you for more info.

**Comment by marcingajewski** [comment]
Hi Johny,

I bought this printer as reprap from local man in Poland. He claims that only difference is bigger screen, I don’t have MPN unfortunately.
After a flashing to newer software (old was working fine) and getting to check the version it does it every time. The printer can work, print, do all stuff, but always when getting there and exit (sometimes it no need to exit, doing it after a while)
, blue screen appears. 

![WP_20201208_12_34_22_Pro](https://user-images.githubusercontent.com/4764699/101479816-10b07280-3953-11eb-86ea-7e21eca51a16.jpg)

**Comment by JohnnyDeer** [comment]
@marcingajewski thank you for information. Can you please try it on 4.3.0-RC1? Thank you

**Comment by JohnnyDeer** [comment]
@marcingajewski could you please test it on latest FW version?

**Comment by marcingajewski** [comment]
Sorted on 4.3.1. All works, thanks for sorting it
