### ISSUE TITLE
[BUG] 4.3.0-RC1 Sensor info screen shows "M.I.N.D.A" instead of "SuperPINDA"

### ISSUE THREAD

**Issue by merdok** [prusa3d/Prusa-Firmware-Buddy#1158]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

Printer type - [MINI]

Printer firmware version- [e.g. 4.0.5, ...]
4.3.0-RC1

Original or Custom firmware [Original/Custom]
Original

Optional upgrades - [e.g. Filament Runout Sensor]
Filament Runout Sensor

USB drive or USB/Octoprint
USB

Describe the bug
Not that big of a deal, but in the info menu in the sensor info screen it shows "M.I.N.D.A" even that i have the SuperPINDA installed.  Not sure if you can detect the leveling sensor type but it would be nice if you could show the exact sensor which is installed and not just use the "M.I.N.D.A" placeholder.

Expected behavior
"SuperPINDA" text instead of "M.I.N.D.A"

**Comment by vintagepc** [comment]
I don't think the printer can tell the difference. On the MK3S you can because the v2 has a thermistor and the new part does not. But both the MINDA and the superpinda don't have thermistors.
