### ISSUE TITLE
[BUG] Corrupted characters on Mini

### ISSUE THREAD

**Issue by chillygithub** [prusa3d/Prusa-Firmware-Buddy#1195]
**Printer type** - MINI+

**Printer firmware version**-  4.3.0-RC1

**Original or Custom firmware** Original

**Optional upgrades** - SuperPINDA

**USB drive**

**Describe the bug**
  The last column of pixels in the letter "m" on the remaining time is missing.

**How to reproduce**
  Behaviour is seen on all prints.
  Mini is set to English language.

**Expected behaviour**
  The full letter "m" should be shown.

**G-code**
   Pre-sliced Benchy and Whistle supplied on USB stick with the Mini. 

**Picture**
![2020_12_28 14_44 Office Lens](https://user-images.githubusercontent.com/76703458/103236892-fb20de00-493d-11eb-9f6f-5da59be93485.jpg)

**Comment by JohnnyDeer** [comment]
Hi @chillygithub, we know about this issue and working on it. Thank you for reporting.

**Comment by DRracer** [comment]
@chillygithub could you please verify the rendering is correct in FW 4.3.0?

**Comment by chillygithub** [comment]
Thanks, this appears to be resolved.
I have only done shorts prints less than 1 hour. But on those the final line of the `m` is correct.

**Comment by JohnnyDeer** [comment]
@chillygithub thank you for confirming, then can we close this issue as solved?

**Comment by chillygithub** [comment]
Yes, this can be closed.
