### ISSUE TITLE
[FEATURE REQUEST] Option to set Sheet Profile in Filament menu

### ISSUE THREAD

**Issue by chillygithub** [prusa3d/Prusa-Firmware-Buddy#1196]
**Printer type** - MINI+
**Optional upgrades** - SuperPINDA

**Describe the expected functionality**
  Option to set the sheet profile from the "Filament" menu.

  Sheet profiles are typically change when changing filament / filament type.
  An option be included to change the Sheet Profile from the "Filament" menu, would save the need to go to the "Setting" menu.

**Comment by AlexDCode** [comment]
I think this should be issued on the PrusaSlicer repository [here](https://github.com/prusa3d/PrusaSlicer)

**Comment by Tomcus** [comment]
Closing this issue as duplicate: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3465

Please refer to the second issues with ideas and improvements in this area.
