### ISSUE TITLE
Mid-print tuning results in far too drastic temperature swings at the nozzle

### ISSUE THREAD

**Issue by laposheureux** [prusa3d/Prusa-Firmware-Buddy#12]
For example, I just was printing at 230 and used tuning to set the printer to 220. The software reported that it knew it needed to heat when the screen showed 219 and it got all the way to 214 before the temperature stopped declining and headed back up. If I weren't already printing way above the necessary temperature, this could result in under extrusion or clogging.

**Comment by michalxfanta** [comment]
Thanks for reporting this issue. We improving PID regulation right now.
