### ISSUE TITLE
[ENHANCEMENT] Change default extruder z,x axis position to be top left back corner?

### ISSUE THREAD

**Issue by AlvaroLuken** [prusa3d/Prusa-Firmware-Buddy#1210]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**all printers

**Is your suggested improvement related to an existing problem? Please describe.**
After every print, at least for my MK3S, the nozzle places itself in like mid-center heatbed level - it makes it hard to clean the heat-bed + nozzle after each print as I have to waste time manually going in and moving the z-axis to >200 so that I can get a good angle for a nozzle clean and the bed is liberated from the nozzle being an obstruction for a wipe-down. If after every print (and really by default) the nozzle head would move to the upper top left corner, it would make it much more efficient to print and clean!*

* I was just in a car crash the other day and can't move/crane/angle my neck much - I had noticed this being an issue before but I really can't even bend over to do a quick check of the nozzle...

**Describe the expected functionality**
The default nozzle head position should be the upper top left corner for easier cleaning and printing.

**Comment by ogland** [comment]
You can do this yourself very easily in your end gcode.

**Comment by AlvaroLuken** [comment]
I am not an expert user, why not either make the default position easy to change from the menu controls?
