### ISSUE TITLE
[BUG] Filament Change Failure

### ISSUE THREAD

**Issue by FrenzyIncarnate** [prusa3d/Prusa-Firmware-Buddy#1225]
[MINI]
4.2.1 Final
Bondtech Extruder
USB flash drive

**the bug**
I encounter a problem when I unload a higher temperature material and load a lower temperature material through printer's filament menu. When I unload PETG and load PLA, some amount of PETG remains in the nozzle. And since PLA's temperature is not enough to melt PETG, the extruder rams the PLA filament against solid PETG and this causes the olives at the extruder side to give way. This rendered my printer unusable until I replace the PTFE tube.

**How to reproduce**
  Use printer's filament change option and swap from PETG to PLA (probably few times)

**Expected behavior**
Hotend temp should be stayed at previous filament loading temp if its higher. Otherwise it shouldn't be a problem
**G-code**
 No G-code . its the firmware issue

**Crash dump file**
No dump file

**Video**
No video

**Comment by JohnnyDeer** [comment]
Hi @FrenzyIncarnate, we are doing this kind of changes on daily basis without any problems. Looks more like you had bad piece of olive, or badly assembled one. Please try it with replaced one, video would be very helpful. Thank you

**Comment by FrenzyIncarnate** [comment]
Hello @JohnnyDeer . This issue happened to me twice.  First one as you can guess with the factory assembled one. And I have used the spare olives and made one myself. After few months that also gave way .. I had to take another spares from Metatechtr.  I also know that some people use the last used material from load filament list to prevent this kind of issue.

**Comment by FrenzyIncarnate** [comment]
![badge](https://user-images.githubusercontent.com/33299655/120319819-18d9e100-c2ea-11eb-9495-c38d2fd94e03.jpeg)
Hello @JohnnyDeer I have uploaded it.

**Comment by JohnnyDeer** [comment]
I have found that assembling of this part was changed together with a new molding tool, unfortunately bowden on your printer was assembled before this changes. So this really looks like faulty piece. If you will have another similar problem, do not hesitate to contact our Tech Support.

**Comment by Prusa-Support** [comment]
Hello @FrenzyIncarnate! Was the issue resolved in the meantime through our Technical Support? In case there are more issues related with this, do not hesitate to let me know info@prusa3d.com mentioning me ("attn: Alessandro"), we'll find a solution for it. Closing the issue for now based on the info shared by @JohnnyDeer. 

Alessandro Pantaleo
Prusa Research
