### ISSUE TITLE
4.3.0 RC2 No retraction after first layer cal.

### ISSUE THREAD

**Issue by markgol** [prusa3d/Prusa-Firmware-Buddy#1259]
It appears that their is not a filament retraction when the first layer cal completes.  It leaves a long string of filament from the last print point connected to the print head which continues extruding filament after reaching the park position.  Ignoring the long string of filament, it extrudes about another 3cm or more after parking.  It does not do this in the V4.2.1 release.

**Comment by markgol** [comment]
I was printing with PETG.

**Comment by reedy** [comment]
Seems to be the same on the 4.3.0 final release too

**Comment by reedy** [comment]
4.3.1 too.

![image](https://user-images.githubusercontent.com/67615/109176277-8d96ff80-777e-11eb-83e7-3fe06a5c2b30.jpeg)

**Comment by danopernis** [comment]
I can confirm that this is still an issue even in 6.0.0

**Comment by reedy** [comment]
Not notably fixed...
