### ISSUE TITLE
www rozhraní na firmware Buddy_4.3.0-RC2+2729.bbf

### ISSUE THREAD

**Issue by grosiln** [prusa3d/Prusa-Firmware-Buddy#1267]
Od této verze se www rozhraní po načtení buď zasekne a nebo se nenačte a zůstane na černé obrazovce
mám ve svém okolí 7x prusa mini na tomto firmware a na 5 to děla a na dvouch ne.
Předtím byl firmware prusa3d_fw_4_2_1_MINI.bbf
 Ještě nás zajímá zda je možný downgrade firmware

**Comment by Ondrashek** [comment]
Downgrade FW:

Vypnout tiskárnu
Zandat USB flashku s firmwarem
Zapnout tiskárnu a po zobrazení bootloaderu zmáčknout kolečko
Vybrat Flash

**Comment by zoltan-l** [comment]
@grosiln 
dělá to i v současné 4.3.4 verzi? prosím potvrdit

**Comment by grosiln** [comment]
ano prostredi se snazi nacist ale to je vsepokud budete chtit poslu videotestovano na nekolika prohlizecich nekolaka pc tabletech a telefonechcekal js ze posledni aktualizace to vyresi ale nezdarilo sejeste to otestuji kdyz tiskarna natiskne to jsem na posledni verzi firmware nezkouselm.g.Dne 20. 1. 2022 11:33 napsal uživatel Zoltan-l ***@***.***>:

@grosiln

dělá to i v současné 4.3.4 verzi? prosím potvrdit
