### ISSUE TITLE
Filament detection and measuring

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware-Buddy#128]
If you swap filament detection ball with Bondtech wheel and point detector to the teeth you will get pulse signal every time filament moves. Thus you can measure speed of filament movement. This can:

1) detect nozzle clog
2) detect filament breakage
3) detect filament grinding
4) detect presence of filament (during move)
5) detect if and when extruder grabs filament
6) measure extruder multiplier (extruder gears can squish soft filaments which changes gear ratio)

If you add semitransparent cylinder at the wheel, you can detect even spaces between teeth. Then you can detect 3 states:

1) no filament
2) filament, no tooth
3) filament, tooth

This provides detection of filament without any move.

Filament is thin so movement of wheel to the detector is very small. Still, you can add axis so the wheel is not moved but rotated. The end of the wheel will move faster and further. Finally, you don't need to use Bondtech wheel but you can print yourself with more optimal teeth shape (squared).

**Comment by michalxfanta** [comment]
Thank you for your interesting idea.
