### ISSUE TITLE
[ENHANCEMENT] "Print will end Today at..."

### ISSUE THREAD

**Issue by reedy** [prusa3d/Prusa-Firmware-Buddy#1287]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** MINI

**Printer firmware version** 4.2.1, 4.3.0

**Original or Custom firmware** Original

**Optional upgrades** Filament Runout Sensor

**USB drive or USB/Octoprint**
USB

**Describe the bug**
Saying "Print will end Today at <time in past>" is not helpful after the print is finished.

**How to reproduce**
Let a print finish

**Expected behavior**
Rather than "Print will end Today at <time in past>", display something like "Print finished Today at <time in past>"; something that indicates the print is finished, and what time it was

Similar when it is cancelled; the message should change appropriately

**G-code**
N/A

**Crash dump file**
N/A

**Video**
N/A

**Comment by reedy** [comment]
Please feel free to change to an enhancement as appropriate

**Comment by DRracer** [comment]
good point, thank you

**Comment by reedy** [comment]
Still valid.
