### ISSUE TITLE
[BUG]after update to 4.3 lcd go creasy

### ISSUE THREAD

**Issue by Af5211** [prusa3d/Prusa-Firmware-Buddy#1289]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI +]

**Printer firmware version**-  [e.g. 4.3, ...]

**Original or Custom firmware** [Original/]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/**
  Via usb

**Describe the bug**
  After update to 4.3 lcd go creasy

**How to reproduce**
After update from 4.2.1 to 4.3 the display go everywhere by touching. 

**Expected behavior**
  By 4.3 the lcd display go by touching everywhere.

https://user-images.githubusercontent.com/78602880/107196690-3a3d5700-69f3-11eb-9e7e-953c051e202e.MOV

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by Af5211** [comment]
After update Prussia Mini to 4.3 the display is going creasy he jump everywhere when I push the button. 
I have no control.

**Comment by murk-sy** [comment]
You will need to provide a video because your description could mean a bug or a faulty button or something else entirely

**Comment by JohnnyDeer** [comment]
Hi @Af5211, please open issue again following the template. Thank you

**Comment by Af5211** [comment]
> Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.
> 
> **Printer type** - [MINI +]
> 
> **Printer firmware version**- [e.g. 4.3, ...]
> 
> **Original or Custom firmware** [Original/]
> 
> **Optional upgrades** - [Filament Runout Sensor]
> 
> **USB drive or USB/**
> Via usb
> 
> **Describe the bug**
> After update to 4.3 lcd go creasy
> 
> **How to reproduce**
> After update from 4.2.1 to 4.3 the display go everywhere by touching.
> 
> **Expected behavior**
> By 4.3 the lcd display go by touching everywhere.
> 
>  IMG_0609.MOV 
> 
> **G-code**
> Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.
> 
> **Crash dump file**
> Please attach the crash dump file. This will make it easier for us to investigate the bug.
> 
> **Video**
> Please attach a video. It usually helps to solve the problem.


https://user-images.githubusercontent.com/78602880/107198231-25fa5980-69f5-11eb-838c-cc93d90805fc.MOV
