### ISSUE TITLE
System crash after long idle period

### ISSUE THREAD

**Issue by WarrenSchultz** [prusa3d/Prusa-Firmware-Buddy#13]
Firmware 4.0.1.
Printed a benchy, plugged into the network, realized that the network doesn’t do anything, left idle. After an unknown number of hours, the system crashed.
![D7DDA6A7-8E52-433D-B11B-8984F1282483](https://user-images.githubusercontent.com/8450968/71317150-af924500-244a-11ea-89f7-b6326cdb8083.jpeg)

**Comment by schiffer-soft** [comment]
Hi

Self problem. But not afer long idle period.
While printing I want to view the web connect site.
First connect worke fine. After 2 minutes I refresh the site.
Then print stopped with bluescreen.

![20200207_185134](https://user-images.githubusercontent.com/32165814/74066810-26ce6900-49f8-11ea-9a5e-521d08400850.jpg)


MFG Chris

**Comment by JohnnyDeer** [comment]
Hi, bluescreen bug is already fixed on newest versions of firmware, i´m closing this issue.
