### ISSUE TITLE
[BFW-4898] [FEATURE REQUEST] Rename Custom Sheet Profiles

### ISSUE THREAD

**Issue by Gromit21** [prusa3d/Prusa-Firmware-Buddy#1318]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
Printer type - MINI+
Optional upgrades - SuperPinda

Describe the expected functionality

The ability to rename the custom sheet profiles in the Settings menu.
This will help to match the profile to the multiple custom steel sheet being used.

**Comment by Gordontgopher** [comment]
This would be especially useful as the satin sheet is now available for the mini.

**Comment by Dev01-D** [comment]
Super helpful as i have all 3 sheets and we could also have aditional such as Glass etc.

**Comment by ulab** [comment]
I was quite confused, because I am able to rename the sheets on my MK3S, but not on the Mini+. 

And now I have to use my satin one as "Custom1" sheet which doesn't do it justice.

**Comment by Kalimero13** [comment]
Change the configuration using a file on a USB flash drive, similar to an upgrade firmware.
For example, the contents of a text file (config.ini):

[sheet]
1=smooth PLA
2=satin  PLA
3=textured PLA
4=smooth PETG
5=satin PETG
6=textured PETG

It is possible to change other constants in EEPROM with this configuration file.
For example, setting the steps for the extruder when replacing the extruder:

[step]
E=415

**Comment by ulab** [comment]
Do you have a link to any kind of documentation on this? I can't find anything related to the Mini and a config.ini file?

**Comment by Kalimero13** [comment]
This is my idea, the link leads to my head.

**Comment by TerTerro** [comment]
Would second this. It's annoying to not have option to change names and like the option of USB config file just for sheet names for example.

**Comment by DiomedesDominguez** [comment]
I'd love to know 2 things:
1) How many sheets configurations we can create if we could use the whole or at most the 90% of the EEPROM space for this task
2) Can we select the sheet profile through gcode or any special code from the prusaslicer?

Let's say that we can have up to 12 sheets instead of 6. This way we can have not only for PLA and PETG, but also for ASA/ABS and TPU

**Comment by Prusa-Support** [comment]
Thank you all for bringing this to our attention.

We may consider an option to rename the sheet profiles in the future but at the moment there are only 8 pre-sets available: 2x smooth sheet profiles + 2x textured sheet profiles + 4x custom sheet profiles.
These profiles are pre-set and can't be renamed but please notice, except for the naming, there are no differences between them. The user may save any value on any profile, regardless of what the sheet is actually called.

This menu was modified recently in the past by introducing satin sheet profiles, but I seem to understand these were accidentally removed. This may change again in the near future.

Michele Moramarco
Prusa Research

**Comment by TeslaCT** [comment]
I still think this should happen. I would also like to see if we could link the sheet profile to a nozzle. I use my .6 nozzle a lot. I can and will use some of the other profiles for when I use different nozzles. but without being able to rename the profiles it could be dangerous to use the profiles.  my .6 CHT nozzle is very different than the standard brass. so if I confuse the profiles I could easily crash the nozzle

**Comment by Kyeld** [comment]
The ability to rename the profiles would be a nice quality of life update for the Buddy firmware, its a bit of a let-down that the current generation of printers lack this feature.

**Comment by SnowB0und14** [comment]
It also appears to be missing from the MK3.5 upgrade as well.  I wonder if they could at least add the satin sheets to factory list.

**Comment by big-fudge** [comment]
For an outsider this seems like a pretty quick change. The idea is around for over 3 years now and still might dust away in some backlog. Is there a priority problem with this or is it just not planned and won't be in the feature list for future updates alt all? Could someone from @Prusa-Support please clarify? It really would help A LOT to have any option to rename those sheets. Especially with the presence of different nozzle diameters and materials to print on different sheets.

**Comment by frogale** [comment]
+1

**Comment by m-kozlowski** [comment]
This FR really needs some love.
Just finished upgrading four mk3s to mk3.5 and of all quality of life features lost in the process, this is the one I miss most.

**Comment by danopernis** [comment]
This issue is on our radar. Suggested solution using INI file is valid, but feels a bit hack-ish. We are debating implementing a virtual keyboard for our printers, which would unblock this and many other feature requests.

**Comment by m-kozlowski** [comment]
Hackish? Maybe. But having a choice between manually renaming 8 labels using touchscreen keyboard or uploading and applying preconfigured file, I'll take the ini way, hands down. Especially having multiple printers to configure.

**Comment by big-fudge** [comment]
What he said.

**Comment by maciii** [comment]
I will also like it on MK3.5.

**Comment by jsrumsey** [comment]
I would also like the renaming of steel sheet profiles in MK3.5, like we used to have.

**Comment by CZDanol** [comment]
Hello, we're working on this feature.
Internal ticket: BFW-4898

**Comment by big-fudge** [comment]
Thx for the heads up, but that doesn’t cover a custom naming for the sheets. The offset doesn’t do anything for me. Nor the sheet name. I still can’t do anything with that in terms of used nozzle diameters or sheet/nozzle combinations. 

Would be useless as it currently is with just the offset attached to it.

**Comment by CZDanol** [comment]
@big-fudge I don't understand?

**Comment by big-fudge** [comment]
Bc it’s the essence of the linked ticket?

**Comment by CZDanol** [comment]
Yes, and?

**Comment by murk-sy** [comment]
Implemented in [6.1.2](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.1.2)

**Comment by CZDanol** [comment]
Indeed :) Closing the issue.
