### ISSUE TITLE
[ENHANCEMENT]<Enter comprehensive title>

### ISSUE THREAD

**Issue by Co0olboi** [prusa3d/Prusa-Firmware-Buddy#1323]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI]
**Optional upgrades** - [e.g. Filament Runout Sensor]

**Is your suggested improvement related to an existing problem? Please describe.**

**Describe the expected functionality**
  A clear and concise description of expected functionality.

**Comment by JohnnyDeer** [comment]
Hi @Co0olboi this issue is empty, please try to fill it again. Thank you
