### ISSUE TITLE
[BUG] nozzle and bed keeps heating after filament unload

### ISSUE THREAD

**Issue by jbnjohnathan** [prusa3d/Prusa-Firmware-Buddy#1331]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version**-  [4.3.1+2759]

**Original or Custom firmware** [Original]

**Describe the bug**
After unloading filament, nozzle and bed remains heated

**How to reproduce**
Select "Filament unload"
The nozzle and bed begins to heat.
When nozzle reach the correct temperature the filament is unloaded (the bed will continue to heat to reach the set temperature)
Even after exiting the filament unload menu the nozzle and bed is still kept heated, or if the bed has not reached the set temperature it will continue to increase in temperature until it does, and then be kept at set temperature.

**Expected behavior**
A prompt should be displayed after the filament has attempted to be unloaded
"Was the filament unloaded successfully?"
If answer is yes, then nozzle and bed should begin cooldown.
OR
If exiting the Unload filament menu, the bed and nozzle should begin cooldown.

Since the selection was made to unload filament, as opposed to "change filament" an assumption can be made that no printing will occur in the near term.

This is loosely connected to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/706 but I think this issue, that the bed and nozzle remains heated even after unload, is slightly different from why the bed is heated when doing unload or load filament.

**Comment by chillygithub** [comment]
Another vote for this.
