### ISSUE TITLE
[FEATURE REQUEST]Change Color Theme of display

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#1343]
**Printer type** - [MINI]

The idea is that there should be an option where you could change the color theme of the display.
Since the display can display rgb color it should be possible to implement.
The benefits of such a feature would be that if you reprint all printable parts of the printer (the orage ones for example) and replace them with green or other coloured parts, then the display would match these colors way better.

A way of implementing this could be an interface where each color has a category like "text" "icons" "numbers" and then you could assing a certain color to that category.
Picking the color could be done with an interface where the knob adjusts r,g and b from 0 to 255.

**Comment by espr14** [comment]
Change of button color is easy because it is generated on the fly but font (letters & numbers) and icons are stored images. This would require non-trivial algorithms for analysis and generating of new image.
