### ISSUE TITLE
[FEATURE REQUEST] print starts without filament loaded

### ISSUE THREAD

**Issue by dahuafschmied** [prusa3d/Prusa-Firmware-Buddy#1344]
MINI 4.3.2 beta1
no Filament Runout Sensor

It is possible to start a print without loaded Filament.
My feature request is to ask the user if he wants to load filament if a printjob is started and no filament is loaded.

thank you

**Comment by OJFord** [comment]
There are filament options in the 'Tune' menu from the print screen, but they don't do anything.
