### ISSUE TITLE
4.0.1 firmware told me I had a thermal runaway during self test. After a power cycle the error went away and I've been using it for over an hour since with no problems.

### ISSUE THREAD

**Issue by iandouglas** [prusa3d/Prusa-Firmware-Buddy#14]
I downloaded 4.0.1 and moved the 4.0.0 firmware off of the USB drive and installed 4.0.1 as soon as I powered the Mini on for the first time. During the self test it told me there was a thermal runaway (I liked the big red screen) and to check my cables. Everything had clicked in place just fine so I power cycled the machine and the self test passed just fine the second time.

**Comment by michalxfanta** [comment]
Thanks for reporting this issue. We improving PID regulation right now.
