### ISSUE TITLE
Please show the sheet profile name in the calibration and print screens

### ISSUE THREAD

**Issue by PaulDC** [prusa3d/Prusa-Firmware-Buddy#1429]
I think the different sheet profiles is an excellent feature. However I've often forgotten to change the sheet profile when changing to a different sheet texture. I've usually realised this just after the print has started and then had to abandon the print to change the sheet profile.

Please would be it be possible to show the sheet profile selected  in the Calibration screen and the Live print screen ? I would then  realise before the print has started that I've not changed to the correct sheet profile.

Many thanks,
Paul C.

**Comment by JohnnyDeer** [comment]
Hi @PaulDC thank you for suggestion.

**Comment by chillygithub** [comment]
Can I suggest adding it to the "Change Filament" menu. As this is when you typically also need to change the sheet.

**Comment by tverett** [comment]
Agree to both requests mentioned here. Showing on main screen and grouping with change filament.

**Comment by darraghbr** [comment]
Another way to do this might be to interrogate the user every time a print is started which sheet is installed. This might be especially helpful when multiple people are using one printer. Clearly this would be something that the user could enable and disable as some would find it excessive.

**Comment by Prusa-Support** [comment]
Hello! Thank you for your ideas and sorry for the late response from my side. All noted, still under consideration from our side - sadly, no guarantees yet that anything would be implemented, but we'll consider it. 

Alessandro Pantaleo
Prusa Research
