### ISSUE TITLE
crash recognition at mesh bed leveling is not working, printer will destroy itselfe

### ISSUE THREAD

**Issue by pinguforce** [prusa3d/Prusa-Firmware-Buddy#145]
firmware 4.0.1 offizial Prusa Driver site release.

yesterday i forgotten that i took of the spring steel plate and started a print. a few minutes later i looked after it.

the nooze crashed so forcefull into the hotbed, that it got scrached very deep (you can scratched and bentded cooper), bented about 3 cm and even remained a massive dent. have to try out this evening if its still usable. i think i need a new hotbed :(

so be carefull, crash recognition on the mesh bed leveling does not work!
THIS SHOULD BE DEFINITLY BE HOTFIXED

**Comment by michalxfanta** [comment]
In the next firmware version, there will be an improvement in the Z-axis crash detection, which should avoid such a situation. Contact our support for a heatbed replacement.

**Comment by x10102** [comment]
I have this bug too, it destroyed my PEI sheet. This needs a fix ASAP!!!

**Comment by zoltan-l** [comment]
The bug is fixed, At the print start when the first probing fails - the nozzle gets lower than allowed the print stops and reports the Probing error.
If the user intentionaly remove the MBL code from GCODE and removes the sheet from bed is on his/her own risk
