### ISSUE TITLE
[FEATURE REQUEST] Option to edit steel sheet profiles

### ISSUE THREAD

**Issue by JustAnother1** [prusa3d/Prusa-Firmware-Buddy#1452]
**Printer type** - [MINI]

**Is your feature request related to an existing problem? Please describe.**

After levelling the steel sheet on prints I detected elephants foot. I therefore suspect that I levelled the nozzle to close to the sheet. I just want to increase the distance between build plate and nozzle a bit. But I can not do that without running(and printing) the first layer calibration wizard thing.

**Describe the expected functionality**
I want to select the profile of the sheet and change the Nozzle offset in the menu without the 1st layer calibration print.

**Comment by Jonas-Mikkelsen** [comment]
You should be able to change the live-z value under calibrate and it should save that to the profile.

Works like that in my experience!

**Comment by JustAnother1** [comment]
@Jonas-Mikkelsen Thank you for the hint. That was not obvious to me.

It would still be nicer to have this option also available in the sheet menu. That would allow to check in on the current value and change values without the need to select the sheet first.

**Comment by JohnnyDeer** [comment]
Hi @JustAnother1, as @Jonas-Mikkelsen wrote you can do that in calibration menu. 
Your suggestion in comment is already existing issue #1445. 
I'm closing this issue as invalid.
