### ISSUE TITLE
[FEATURE REQUEST] Allow setting of time left metric

### ISSUE THREAD

**Issue by chris72205** [prusa3d/Prusa-Firmware-Buddy#1474]
**Printer type** - Prusa Mini+
**Optional upgrades** - N/A

**Is your suggested improvement related to an existing problem? Please describe.**
No, this is not related to an existing problem.

**Describe the expected functionality**
I would like to be able to set whether the printer displays remaining time or when print will end based on a setting.  I have my printer connected to LAN but it's more straight forward (most of the time) for me to see how much longer is left instead of print will end at (and then doing the mental math to figure out how much longer is left).

Ideally when connected to LAN, it would show "Print will end" as it does now but also show remaining time next to the percent completed metric: `48% - 2h8m left`

**Comment by reedy** [comment]
Dupe of #648?

**Comment by chris72205** [comment]
> Dupe of #648?

Ah yeah, I tried searching before making a new issue but missed that one I guess.

**Comment by reedy** [comment]
Search isn't the best on GitHub :)
