### ISSUE TITLE
[ENHANCEMENT] XY Skew correction

### ISSUE THREAD

**Issue by ericclinedinst** [prusa3d/Prusa-Firmware-Buddy#1486]
Printer type- MINI

Can we please get xy skew compensation and an xyz calibration just like the mk3 and mk2 please? Seen lots of threads on prusa reddit, the prusa forum, and my own experience with having to manually manipulate the xy planes on the mini. The  calibration spots are on the bed, so why don't we have the feature enabled yet?

Thanks

**Comment by matthewlloyd** [comment]
Llama Mini firmware enables 3-plane skew compensation: https://github.com/matthewlloyd/Llama-Mini-Firmware#llama-mini. It doesn't use the calibration spots, but you can just print the STL, measure with calipers, and use the supplied spreadsheet to calculate the correction factors.

**Comment by ericclinedinst** [comment]
> Llama Mini firmware enables 3-plane skew compensation: https://github.com/matthewlloyd/Llama-Mini-Firmware#llama-mini. It doesn't use the calibration spots, but you can just print the STL, measure with calipers, and use the supplied spreadsheet to calculate the correction factors.

Yeah, that's exactly what I want to do. Cut the appendix and void my warranty. Thanks but no thanks. I think a lot of us would like to see xyz calibration in the initial configuration of the printer just like we had for mk2s and mk3.

**Comment by krcm0209** [comment]
Duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/385

**Comment by jmrp98** [comment]
I agree, I would really like to have XYZ calibration like the MK3 and MK2. The mini has a big problem with not being aligned and it is frustrating.

**Comment by SiegelDaniel** [comment]
@Gaugeforever Can you supply a link to this mod? I cannot find it.

**Comment by Gaugeforever** [comment]
Certainly, this is a link to my reply on the topic but you can navigate to the first page.
[Link](https://forum.prusaprinters.org/forum/user-mods-octoprint-enclosures-nozzles/prusa-mini-silicone-bed-leveling-mod/paged/15/#post-518551)

**Comment by espr14** [comment]
See #385 for the possibility to set the skew compensation. Automatic calibration may come later.
Since the MINI has the lowest priority compared to MK3/XL/AFS etc. don't expect the skew compensation in original FW soon.

**Comment by Prusa-Support** [comment]
Thanks for your input.
Same as https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/385, our developers could consider this feature request in future firmware developments.

Michele Moramarco
Prusa Research
