### ISSUE TITLE
MMU2S not supported

### ISSUE THREAD

**Issue by HutyJarl** [prusa3d/Prusa-Firmware-Buddy#149]
it is not possible to use MMU2S in mini prusa for a software problem says a guy from PRUSA support.

how can we go around the problem?
Prusa's technical support adds that even other MMs (multi materials) are not compatible.

HELP BOYS :(

Is anyone trying to work on it?

**Comment by JustAnother1** [comment]
Did you damage your board? Only people that damage their electronics and therefore loose the warranty can test firmware that is not signed by Prusa.

**Comment by Lichtjaeger** [comment]
MMU2S can only work with a direct extruder with integrated filament sensor.
The Mini has a Bowden extruder.

But you can use [Palette 2S](https://www.mosaicmfg.com/products/palette-2s) if you need multi-colour/multi-material.

**Comment by HutyJarl** [comment]
palette2s is the best solution for me

to use more colors I saw that you also have an application that manages the
manual color change. it is correct ? . is it compatible with MINI?

**Comment by HutyJarl** [comment]
you.. ahaha PRUSA*

**Comment by Lichtjaeger** [comment]
> to use more colors I saw that you also have an application that manages the manual color change. it is correct ?

If you are referring to "colour change by layer": This is supported by every printer. You can add the colour steps during slicing.

**Comment by HutyJarl** [comment]
perfect :))
thank u
