### ISSUE TITLE
Collision detection, lubrication self test

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware-Buddy#155]
During self test, printer should test the force needed to move from one end to the other for X and Y axes. In case of high force or variable force needed, user should be notified that rods may need lubrication. Otherwise, false collision detections can occur during printing.

As well as belts are quantified in numbers, the lubrication of rods / state of bearings could be as well for X, Y, and Z axes.

If collision detection occurs, printer should home an axis and go to the end of the axis to find out if it was caused by collision or by friction of rods (bearings). If it finds axis too short, it should pause the print. Otherwise, shifted layers will occur.

**Comment by michalxfanta** [comment]
Thank you for your interesting idea.
