### ISSUE TITLE
[BUG] Wrong text / Translation 

### ISSUE THREAD

**Issue by Mryck** [prusa3d/Prusa-Firmware-Buddy#1575]
**Printer type** - [MINI, MINI+]

**Printer firmware version** - [4.3.3 RC]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
 USB Printing

**Describe the bug**
 Tinkering with the new version and menu came across a strange text in the hidden Hardware menu.
(Thanks for this nice FW update)

**How to reproduce**
Go to Hidden menu, *French Translation*

**Expected behavior**
Something clear at least in English.

![PrusaMini](https://user-images.githubusercontent.com/15244869/132411448-4fcda83e-f0a5-4d5f-8442-bbee5d62103d.jpg)

**Comment by JohnnyDeer** [comment]
Hi @Mryck, thank you for reporting.

**Comment by Mryck** [comment]
Hi @JohnnyDeer thanks it's fixed on official release
