### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by fragged3d** [prusa3d/Prusa-Firmware-Buddy#1603]
What file do I need to flash to the mini?

**Comment by Gordontgopher** [comment]
You need a .bbf file. The file for the latest release is at the bottom of this page: https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.3.2

**Comment by JohnnyDeer** [comment]
Exactly as @Gordontgopher write, thank you. @fragged3d was you attempt to flash printer successful?

**Comment by fragged3d** [comment]
Yes, but I’m not seeing the way to reverse the extruder motor and the steps! So I’m still working on it!

Thanks,
Ryan Sherer

**Comment by Gordontgopher** [comment]
In that case you need the 4.3.3 Release Candidate https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.3.3-RC there are details there on changing steps etc.

**Comment by fragged3d** [comment]
Thanks!

**Comment by fragged3d** [comment]
That’s the firmware on it and still no options!

**Comment by Gordontgopher** [comment]
Have you read the release notes? There is a section there(Support for custom extruders) which includes the instruction "To adjust settings for your custom extruder, go to LCD Menu -> Settings -> HW settings -> then long-press the knob. Similarly to a MK3S+ a new “Experimental” submenu will appear on the screen, where you can tweak the following:...."

If you are on 4.3.3 RC1 and can't activate the hidden sub menu following these instructions then I'd suggest that you need to close this issue and open a new one specific to the problem you are seeing, so the developers can take a look.

**Comment by fragged3d** [comment]
I figured it out thanks!

**Comment by JohnnyDeer** [comment]
@fragged3d great to hear, so can you please close this issue?
