### ISSUE TITLE
[BUG] ODOMETER: "Print time" is not updated when printing from Pronterface

### ISSUE THREAD

**Issue by jcjames13009** [prusa3d/Prusa-Firmware-Buddy#1619]
**Printer type** - [MINI]

**Printer firmware version** - [4.3.3-RC]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [None]

**USB drive or Pronterface**
  
**Describe the bug**
Checking Odometer feature, "Print time" is not updated when printing from Pronterface 😟 Other data is ok (X Y Z axis and filament)
All data is recorded properly when printing from USB stick 👍 

**How to reproduce**
Launch any print from Pronterface and check that "Print time" is not updated
Launch any print from USB and check that "Print time" is updated

**Expected behavior**
Have "Print time" updated when using Pronterface

**Comment by kohend** [comment]
Seen a similar case with the i3 firmware.

**Comment by gimpfenlord** [comment]
same with octoprint
