### ISSUE TITLE
[ENHANCEMENT] Don't heat bed when loading/changing/unloading filament

### ISSUE THREAD

**Issue by Gyrxiur** [prusa3d/Prusa-Firmware-Buddy#1635]
Printer type - [MINI]
Optional upgrades - Don't heat bed when loading/changing/unloading filament

I think it is wasting of time and energy if I only want to change filament, to head bed. For example, if I have ASA loaded and plan to print with PLA, it makes no sense to head the bed to 100°C when I won't use that temp.

**Comment by JohnnyDeer** [comment]
Hi @Gyrxiur, this issue is duplicate of #706. I´m closing this one.
