### ISSUE TITLE
Prusa Mini Preview Issue with 2.4.0 PrusaSlicer Files

### ISSUE THREAD

**Issue by SiberSilverFox** [prusa3d/Prusa-Firmware-Buddy#1646]
### Version
Version 2.4.0-alpha3+win64

### Operating system type + version
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19042), 

### 3D printer brand / version + firmware version (if known)
Prusa Mini running prusa3d_fw_3_3_3

### Behavior
After slicing a file in the Version 2.4.0 alpha versions when previewing the file on the prusa mini it shows unknown for print time and material information. This happens on all files that are sliced, but am attaching the specific file shown in the image.

#### Project File (.3MF) where problem occurs
[Greeblies Set 6 2-4-3aphha.zip](https://github.com/prusa3d/PrusaSlicer/files/7358285/Greeblies.Set.6.2-4-3aphha.zip)

![IMG_4412 2](https://user-images.githubusercontent.com/92651477/137602610-f054df60-19af-4a92-9087-98f822508704.png)

**Comment by JohnnyDeer** [comment]
This bug is solved by 4.3.4-RC. I´m closing this issue.
