### ISSUE TITLE
[FEATURE REQUEST] Add a "Pause Printing" menu option

### ISSUE THREAD

**Issue by rgesswein** [prusa3d/Prusa-Firmware-Buddy#1662]
**Printer type** - Mini+

**Describe the expected functionality**
  Sometimes I need to pause printing while the printer is connected over serial port (Octoprint), would be nice to have that option in the Tune menu with similar behavior of **Change Filament,** but just pause printing. Actually there are a Pause option in the main menu, but does not working properly.

**Comment by rgesswein** [comment]
.

**Comment by hertzi** [comment]
@rgesswein  add label 'octoprint' and delete the first three lines - its a bit confusing
