### ISSUE TITLE
[BUG] Filament load, "STOP" button not working on "purge filament" - 4.3.3

### ISSUE THREAD

**Issue by SnickCH** [prusa3d/Prusa-Firmware-Buddy#1670]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI+]

**Printer firmware version** - [4.3.3]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
USB Drive, but it is the same with USB-stick and without UBS-stick

**Describe the bug**
During the load of the filament at some point it is purging the filament. It ask you then if the colour is correct. If you press "no" it purges again. If you press then the knob for the "STOP" option, nothing happens.

**How to reproduce**
Load filament, when ask if colour is correct press "no". Then it purges filament again. Try to press "stop".

**Expected behavior**
When "stop" is selected and the kob is pressed: it should stop purging filament and finish the "load filament"

**G-code**
 no g-code involved

**Crash dump file**
There is no crash

**Comment by JohnnyDeer** [comment]
Hi @SnickCH, the stop button is inactive in all filament process. This issue is duplicate of #222.
I´m closing this one.
