### ISSUE TITLE
[BUG] Blue screen after the remove filament process

### ISSUE THREAD

**Issue by Yohannfra** [prusa3d/Prusa-Firmware-Buddy#1683]
**Printer type** - Prusa Mini+

**Printer firmware version** - 4.3.3

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
The bug happen with USB and with octoprint

**Describe the bug**
This blue screen appear after the remove filament process (Filament -> Unload filament) finishes.

![IMG_0164](https://user-images.githubusercontent.com/36271388/141381101-5f0bbfec-5800-4af8-bbad-8b7acb3d3d5f.jpeg)

**How to reproduce**
  Click Filament -> Unload filament and it sometimes happen.

**Expected behavior**
No blue screen

Thanks you

**Comment by JohnnyDeer** [comment]
Hi @Yohannfra, can you please provide more information? How often it happens? It is happening in same part of unloading? Do you have OctoPrint or ethernet plugged in when this happen? With what material it is happening? 
Thank you

**Comment by Yohannfra** [comment]
Hello,
It happens sometimes mut not all the time, it's a bit random.
I had the issue with Octoprint connected but also without it.

It happened with ABS and PLA but I didn't use any other material.

It happens at the end of the process and I think and it is always the case, I will try to catch it on vidéo to show you.

Thanks.

**Comment by JohnnyDeer** [comment]
@Yohannfra thank you for info. Yes please video would be helpful.

**Comment by Yohannfra** [comment]
Hello @JohnnyDeer,
Here is the video from the boot of the prusa mini to the crash after the remove filament process : 

https://www.youtube.com/watch?v=rE6tmUYNync

Thanks you.

**Comment by JohnnyDeer** [comment]
@Yohannfra thank you. Unfortunately we are not able to reproduce it. 
Can you please upload also crash dump?

**Comment by JohnnyDeer** [comment]
One more thing could help to troubleshoot it, please try to unplug E-motor and then do unload procedure. Thank you

**Comment by Yohannfra** [comment]
Hello @JohnnyDeer how can I generate the crash dump ?

Unplug E-motor so it won't remove the filament ?

Thanks

**Comment by JohnnyDeer** [comment]
@Yohannfra to download the Crash Dump file, insert a USB drive into the printer first and then head to “Settings -> Save Crash Dump”.
Unplig E-motor to determine if the BSOD is caused by an undervoltage on the motor.
Thank you

**Comment by mtaumike** [comment]
This is the same kind of bug that sometimes happens when you are in a sub-menu and reconnect USB serial (like Octoprint) and has been reported before.

It is very random.

**Comment by DavidB1975** [comment]
I get the exact same error if i use the unload/load function - if I use change filament I don't think it happened yet.

**Comment by jpautom** [comment]
It happens to me ~33% of the times I "change" filament. It happens immediately after the old filament has been unloaded. See crash dump.

[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/7757518/dump.zip)

**Comment by Yith1** [comment]
I get this happening about 33% of the time, but only during a manual filament change, changes performed during a print with Octoprint work fine for me. I don't print from USB ever.
