### ISSUE TITLE
Won't start printing

### ISSUE THREAD

**Issue by Kasperc88** [prusa3d/Prusa-Firmware-Buddy#17]
Most of the time if you plug the usb stick into the printer while its on, and try to start a print nothing happens.

Reset or turn the printer off and on lets you start the print.

**Comment by michalxfanta** [comment]
We are aware of this problem and are working on a solution.

**Comment by eskeyaar** [comment]
I had this issue, but after i start to eject the USB stick properly, its printing fine. Without Ejecting properly facing issue.

**Comment by JohnnyDeer** [comment]
Hi @Kasperc88 , is issue still actual? Did you tried latest FW version,  if bug happens too? Good point @eskeyaar , ejecting usb stick is higly recommended.

**Comment by hawwwran** [comment]
It's not fixed and the commit of @michalrudolf mentioned above seems to have no connection to this issue what so ever.

**Comment by JohnnyDeer** [comment]
FW 4.1.0-RC1 have changes in USB detection. Please try if issue is still there. Thank you.

**Comment by hawwwran** [comment]
> FW 4.1.0-RC1 have changes in USB detection. Please try if issue is still there. Thank you.

This problem is not present in FW 4.1.0-RC1. Confirmed.

**Comment by JohnnyDeer** [comment]
@hawwwran thank you. I´m closing issue as solved.
