### ISSUE TITLE
[ENHANCEMENT] It would be better to change the "Wrong" to "Invert"

### ISSUE THREAD

**Issue by RunzeJustin** [prusa3d/Prusa-Firmware-Buddy#1703]
https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/e3cc6187fcc694228024e2ba7a981df0d6cbaf31/src/guiapi/include/MItem_experimental_tools.hpp#L80-L83

**Comment by der-pw** [comment]
I would like to support this proposal. :-)

**Comment by Czarnyszarf** [comment]
It is a Easter Egg in software... Have some fun

**Comment by Eldenroot** [comment]
+1 - it is confusing now
