### ISSUE TITLE
[FEATURE REQUEST] Add a "shutdown after printing" option in TUNE menu

### ISSUE THREAD

**Issue by RunzeJustin** [prusa3d/Prusa-Firmware-Buddy#1709]
**Printer type** - [MINI]

**Describe the expected functionality**
I often start printing in the morning and then go to work, and I want to have a feature that cool down after printing and then automatically shutdown the printer :)

**Comment by Eldenroot** [comment]
+1

**Comment by Prusa-Support** [comment]
Thanks for the suggestion.

I suspect this may require additional hardware.
For example, the SL1 printer has a dedicated "programmable" power button for booting operation (and allows _auto power off_). The MINI can only be powered on and off via the physical rocker switch instead.

Power-saving options for the screen, in general, would be nice to have but, as emerged in the issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/660, even that would not be easy to implement.

I can't tell if this feature can ever be implemented but the issue will stay open for now.
Thanks for understanding.

Michele Moramarco
Prusa Research
