### ISSUE TITLE
[ENHANCEMENT] Switch Sheets Without OctoPrint Disconnect

### ISSUE THREAD

**Issue by chrishilbert** [prusa3d/Prusa-Firmware-Buddy#1711]
**Printer type** - [MINI]
**Optional upgrades** - Satin Sheet/Textured Sheet/PEI Sheet

**Is your suggested improvement related to an existing problem? Please describe.**
To switch sheet profiles, you must disconnect OctoPrint in order to do so.

**Describe the expected functionality**
Add to the Tune menu an option to switch the sheet profiles without requiring an OctoPrint disconnect/reconnect.

**Comment by HolgerMA** [comment]
+1

**Comment by tverett** [comment]
+1 tune menu is an obvious place for it.

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.

Octoprint is a third-party software. Several options may not be compatible as of now.
Our developers are following tight and intense development plans at the moment but they should get their chance to look into this in the future.

Michele Moramarco
Prusa Research
