### ISSUE TITLE
[BUG] Bed won't stop heating even bed heater is unplugged 

### ISSUE THREAD

**Issue by kevinpita** [prusa3d/Prusa-Firmware-Buddy#1756]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MINI

**Printer firmware version** - 4.3.3

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**Describe the bug**
Putting heatbed to heat while having bed heater disconnected won't do anything

**How to reproduce**
Unplug heatbed heater from the board

**Expected behavior**
Printer should stop heating or restart itself

**Comment by JohnnyDeer** [comment]
Hi @kevinpita, all safety features are tested before every release. Thermal runaway on heatbed takes 4 minutes to trigger, please try it again and give printer more time to reaction. If watchdog will still not trigger there might be some different problem. Thank you

**Comment by zoltan-l** [comment]
Can yu pls. specify in more detail Printer does not do anything when
you use 
Settings->Temperature-.heatbad
Start -> Print
Preheat -> FIlament type

**Comment by Prusa-Support** [comment]
Hello @kevinpita, can you please update us on the situation? Was the situation ending in a BED PREHEAT ERROR or THERMAL RUNAWAY after the 4 minutes interval? In case of anything more to review, let me know at any time. 

Alessandro Pantaleo
Prusa Research

**Comment by kevinpita** [comment]
Hi, sorry for not answering, I do not longer have a prusa mini

**Comment by Prusa-Support** [comment]
Hello! No problem at all and thank you for letting me know, I'll close the thread for now. 

Alessandro Pantaleo
Prusa Research
