### ISSUE TITLE
[ENHANCEMENT] Change filament without OctoPrint disconnect

### ISSUE THREAD

**Issue by gimpfenlord** [prusa3d/Prusa-Firmware-Buddy#1758]
Printer type - [MINI]

Is your suggested improvement related to an existing problem? Please describe.
To change filament, you must disconnect OctoPrint in order to do so.

Describe the expected functionality
Add to the Tune menu an option to change filament without requiring an OctoPrint disconnect/reconnect.

**Comment by imatasic** [comment]
Do you know you can run M600 in octoprint console, while the hotend is sufficiently hot?
using the custom control editor plugin, you can even create a button for it on the control interface.

**Comment by gimpfenlord** [comment]
thx for this
i just found this plugin https://plugins.octoprint.org/plugins/simple_filament_change_buttons/
exactly what i was searching for :)

but having that option also on the printer display menu would be cool too.

**Comment by Pitel** [comment]
> Describe the expected functionality
> Add to the Tune menu an option to change filament without requiring an OctoPrint disconnect/reconnect.

It is there, in the Tune menu. But it's grayed out. Why?

**Comment by coaxial** [comment]
> it's grayed out. Why?

I wonder too and seems to make swapping filaments while on serial unnecessarily complicated.
