### ISSUE TITLE
[ENHANCEMENT] Skip "First Setup Wizard" and save this decision

### ISSUE THREAD

**Issue by SnickCH** [prusa3d/Prusa-Firmware-Buddy#1782]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI/Mini+]
**Optional upgrades** - [e.g. doesn't matter]

**Is your suggested improvement related to an existing problem? Please describe.**
My printer did a reset on itself for no reason (I used the fan testing, software crashed and now I have a factory reset printer-). I have to do the initial wizard thing, that now everything gets tested. Including my nozzle heating up to 290 degrees. I have no need for this, I only need to do the first level wizard again. If I press "no" on the question to do the initial setup, the question keeps coming every start on the printer.

**Describe the expected functionality**
If I say "no" to the initial setup, it should skip it but also save my decision.

**Comment by rinkek** [comment]
This is a very old topic, but yes, please.
I have a heavily modded mini (Bear) which works perfectly fine, but doesn't get through this selftest.
