### ISSUE TITLE
"feature request" preheat nozzle to 170

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware-Buddy#182]
Wouldn't it make sense to generally set the nozzle to 170 degrees when preheating, if I now take ASA, for example, the nozzle heats up to 260 degrees and then cools down to 170 for leveling and then heats up again to 260,

**Comment by michalxfanta** [comment]
Thank you for an interesting idea, we will consider its implementation.

**Comment by gwildavies** [comment]
agreed

**Comment by jhenley01** [comment]
Totally agree! I'm not sure why you would want to pre-heat the nozzle to full temp and have it oozing filament only have to wait for it to cool back down to 170 before the bed leveling starts.
