### ISSUE TITLE
[FEATURE REQUEST] Bowden length compensation setting

### ISSUE THREAD

**Issue by Lichtjaeger** [prusa3d/Prusa-Firmware-Buddy#1836]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MINI]
**Optional upgrades** - [Revo Hotend Upgrade]

**Describe the expected functionality**
That new experimental HW menu is nice. But could you please add a setting to adjust the extruder to nozzle distance to compensate for different hot-ends or Bowden lengths?

**Comment by TerTerro** [comment]
Sounds like a great suggestion.

**Comment by torkildr** [comment]
Haven't done this myself, but I would guess something like this would be pretty essential for a proper direct drive conversion.

**Comment by GuidoHendriks** [comment]
This would be an amazing feature. Is it currently possible to achieve the same result using Gcode?

**Comment by ardenpm** [comment]
Indeed this would be helpful. The E3D Revo upgrade has you cutting the bowden tube down a tiny bit (though it does also describe how to remake at the correct length), as a result when loading the filament reaches the nozzle a touch earlier and the extruder has a hard time of it.

**Comment by Prusa-Support** [comment]
Hello! Sorry for the late response on this thread. Thank you for the feedback and comments, I brought this to our devs attention so that it can be further evaluated. In case of more info we'll update on this thread. 

Alessandro Pantaleo
Prusa Research

**Comment by SnickCH** [comment]
This would be graet. Then I could upgrade to an orbiter and just add the new lenght
