### ISSUE TITLE
[FEATURE REQUEST] nozzle changing setting

### ISSUE THREAD

**Issue by printerer** [prusa3d/Prusa-Firmware-Buddy#1838]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MINI]

**Describe the expected functionality**
 an option for you to select that will retract the filament a set amount of distance to allow a nozzle change without the chance of hot filament causing any issues

**Comment by TerTerro** [comment]
Sounds a nice idea. Like having menu, change Nozzle, that retracts filament and after change, you can set back to push filament in.

**Comment by printerer** [comment]
> Sounds a nice idea. Like having menu, change Nozzle, that retracts filament and after change, you can set back to push filament in.

Yeah, exactly! Only thing is you can do it manually once the printer reaches a certain temperature… didn’t know that until after I posted
