### ISSUE TITLE
[QUESTION] <Why is the master branch still version 4.3.3>

### ISSUE THREAD

**Issue by MinnesotaMean** [prusa3d/Prusa-Firmware-Buddy#1861]
I am using prusaslicer 2.4.1 which takes advantage of some firmware improvements that version 4.3.4 of the buddy firmware also uses. 
I want to compile some changes from the master branch and realized that it is only on version 4.3.3. Just wondering why it is a version behind.

Thanks

**Comment by zoltan-l** [comment]
Hi @MinnesotaMean ,
we know about it and we will synchronize master (which is a development branch) in short time period. Feel free to merge those differences into your fork. There are AFAIK 12 commits.

**Comment by DRracer** [comment]
@MinnesotaMean the master branch has now all the features from 4.3.x. As I wrote elsewhere, please hold on with your compilation of the master branch (bbf file size and related bootloader changes)
