### ISSUE TITLE
[QUESTION] Feature toggle on the master branch

### ISSUE THREAD

**Issue by GatCode** [prusa3d/Prusa-Firmware-Buddy#1890]
Hi everyone,
I would like to ask if there is some kind of feature toggle on the current master branch, so that I can disable some of the experimental features, get rid of the grey background on the menu items and somehow save some flash memory such that there is no issue with the ESP Wifi setup?
Basically my goal is to have a setup which is exactly like the official 4.3.4 release but with the ESP thing enabled. Is this possible?
Thanks!

**Comment by MinnesotaMean** [comment]
The master branch is not on 4.3.4

**Comment by GatCode** [comment]
This was not what I was asking

**Comment by DRracer** [comment]
@GatCode please stay tuned, the new stable networking is really shaping up and once it reaches some level of maturity, we'll clean up the master branch and release the first tested and signed beta of FW 4.4. The plan is to do so in March 2022.

**Comment by GatCode** [comment]
Aah ok thank you very much.
