### ISSUE TITLE
Fail to print from sub-folders (Folder/topic/"file"

### ISSUE THREAD

**Issue by zoomfoto** [prusa3d/Prusa-Firmware-Buddy#19]
Was not able to print a job from sub/sub folder like

Folder/topic/"file"

The temperature indication line for extruder and bed was flashing blue, and never increase.

By moving the same file to : Folder/"File" was positive.

**Comment by michalxfanta** [comment]
This known bug, we will fix this as soon as possible.

**Comment by hawwwran** [comment]
Still not fixed and the commit of @michalrudolf mentioned above seems to have no connection to this issue.

**Comment by JohnnyDeer** [comment]
Hi, this issue is fixed on 4.1.0-RC1. I'm closing as solved.
