### ISSUE TITLE
[FEATURE REQUEST] Default option after a print should be HOME

### ISSUE THREAD

**Issue by Area5142** [prusa3d/Prusa-Firmware-Buddy#1930]
Prusa Mini+
Firmware version: 4.3.4 and all earlier

**Describtion:**
After a print the dialog with the options _Tune/Reprint/Home_ is shown with _Reprint_ as the default:
![P1160232 - GH Mini](https://user-images.githubusercontent.com/1320126/159022277-1e9e3847-243d-4fce-93dc-474986e870e0.JPG)

In 99% of cases I don't want to reprint, but want to print another model and _Home_ should be the default.

Accidentally pressing the selector starts a reprint and it is cumbersome to back out of the operation and select a new print.

**Describe the expected functionality**
I expect the default operation after a print to be more safe like the _Home_ choice.
The current _Reprint_ choice is more suited if the printer is to be used primary in a printing factory, where a lot of equal parts is mass produced.

After all, the just printed part has to be removed and bed prepared for the next print before _Reprint_ makes sense to use - too easy to start a print before the previous print is removed...

**Comment by murk-sy** [comment]
The assumption is that if you'll be starting a different print, you will (at least currently) most likely remove and replug the USB storage to get a newly sliced print, which would take you to the home screen anyway.
Not sure how common that type of use is, but I am *much* more likely to reprint the current gcode file or remove the USB storage than I am to print an older gcode file.

**Comment by Area5142** [comment]
I never remove my USB storage as I am using a Toshiba-FlashAir and manages the print files over WiFi.
No need to remove the USB storage when I can send the next print file over WiFi while the current is printing.
Still a default of _Home_ after a print is finished would be more safe option and avoiding starting a reprint by accident.

**Comment by vanboom** [comment]
From the screen shown, clicking "Home" does not take you back to the home screen, instead it browses over to the storage listing for the next print.  At least half of the time we are changing filaments, or submitting print jobs remotely from PrusaLink.  Clicking the "Home" selection from this screen should actually take you to the home screen.

**Comment by Prusa-Support** [comment]
Hello! Thank you for the post and for the comments, sorry for the reply being so late from my end. In the meantime, I put this to our devs attention, both the aspect on the original post and the latest comment, it will be further reviewed from our devs. 

Alessandro Pantaleo
Prusa Research
