### ISSUE TITLE
[FEATURE REQUEST] Change length of rapid move in unload/load filament routine

### ISSUE THREAD

**Issue by darraghbr** [prusa3d/Prusa-Firmware-Buddy#1932]
**Printer type** - MINI

**Is your feature request related to an existing problem? Please describe.**
  I have just finished installing the E3D Revo Micro onto my Mini, and now the filament path is now shorter than it was (due to slightly shorter PTFE tube and overall length of the hotend). This means that when the filament load/unload routine is used the rapid movement pushes the filament all the way through the hotend leading to some unhappy sounds from the extruder as it rams the filament into the hotend at full chat. 

**Describe the expected functionality**
  Perhaps an extension to the existing ['Experimental Menu'](https://help.prusa3d.com/en/article/experimental-menu-mini-mini_264396/) could work with a nominal rapid distance value that can be changed and is then used by the filament load and unload routines.

**Comment by SnickCH** [comment]
+1

**Comment by darraghbr** [comment]
Duplicate of #1836
