### ISSUE TITLE
Can't flash .bbf generated by master branch[BUG] <Enter comprehensive title>

### ISSUE THREAD

**Issue by MinnesotaMean** [prusa3d/Prusa-Firmware-Buddy#1960]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - 4.3.4]

**Original or Custom firmware** - [Custom]

**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint

**Describe the bug**
  After compiling the latest updates to the master branch and generating a bbf, the printer displays the error "firmware file has invalid size" I checked and the bbf is 1277 kb and my previous compilation of 4.3.3 was around 600.  

**How to reproduce**
  Please describe steps to reproduce the behavior.

**Expected behavior**

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by DRracer** [comment]
@MinnesotaMean thank you for reporting, however this is not a bug at this stage of development. We are working our way to leveraging the XFLASH for static resources thus freeing the CPU FLASH for code. That also brings some changes to the bbf and bootloader. Please hold on until the first 4.4 beta1 gets released.
