### ISSUE TITLE
[BUG] The Octoprint logo is displayed on the Serial Print Screen no matter what is actually connected

### ISSUE THREAD

**Issue by k7zpj** [prusa3d/Prusa-Firmware-Buddy#2008]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - 4.3.4

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint** - Palette 3 Pro

**Describe the bug**
  The Octoprint logo is displayed on the Serial Print Screen no matter what is actually connected / controlling the printer.
  This leads users to think that  there is an active Octoprint session in progress and / or the serial print screen (M876 P1) is just for Octoprint. 

**How to reproduce**
  The Octoprint logo is displayed on the Serial Print Screen whenever the screen is displayed no matter what is connected to the printer. 

**Expected behavior**
 The Serial Print screen should have a graphic image that indicates that there is a USB serial connection active instead of an Octoprint session. 

**G-code**
 M876 P1

**Crash dump file**
 N/A

**Video**
  Please attach a video. It usually helps to solve the problem.
![1645922968-IMG_0317](https://user-images.githubusercontent.com/24995323/162590470-69958d81-3323-4163-ad31-0e78b165089b.jpg)

**Comment by plaetzchen** [comment]
I see the issue and would suggest to maybe have Serial Messages (M73 I believe) displayed on the printer display.
