### ISSUE TITLE
[BUG] selftest does not detect wrong connected fans

### ISSUE THREAD

**Issue by MLWORKX** [prusa3d/Prusa-Firmware-Buddy#2017]
**Printer type** - [MINI]

**Printer firmware version** - [4.3.4]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint** [USB only]

**Describe the bug**
Both fans -print fan and hotend fan- have a 3pin connector which is plugged in on the board next to each other.
Got a replacepent board and mixed them up: plugged the hotend fan in the print and the print in the hotend
Selftest was **successful** and could print several hours but then had a heat-creep.

**How to reproduce**
Change positions of both fans and run a selftest

**Expected behavior**
The routine at self-test should test the fans seperately as this may also happen at factory.
Yes, this was my fault but would be nice of the selftest could indicate this.

**Comment by Prusa-Support** [comment]
Hello! Thank you for bringing this to our attention. We'll try to reproduce the issue to confirm the firmware bug so that it can be resolved on the next release. In case of more info we'll update the thread here! 

Alessandro Pantaleo
Prusa Research
