### ISSUE TITLE
[QUESTION] Where is the hotend fan PWM setting in firmware?

### ISSUE THREAD

**Issue by HyronNotEZ** [prusa3d/Prusa-Firmware-Buddy#2081]
Hey there,
My question is simple and just as in the title. Where can I find the set PWM for the hotend fan? I know there already are some open questions about this, but in ticket #997 somebody mentioned that it is not valid any more. I've searched in the files a bit, but didn't find it. Maybe somebody else who is more experienced with the current mini firmware can help me out and tell me where I can find what I'm looking for.
For background, I need it since I swapped the fan to a Noctua and with the current set PWM, it runs quite slow.

**Comment by threepoint2** [comment]
file: /src/common/hwio_buddy_2209_02.cpp

line 524: void digitalWrite(uint32_t marlinPin, uint32_t ulVal) 
case MARLIN_PIN(FAN1):
#ifdef NEW_FANCTL
if (hwio_fan_control_enabled) fanctl_set_pwm(1, ulVal ? (100 * 50 / 255) : 0);
#else. ...

change to
  if (hwio_fan_control_enabled) fanctl_set_pwm(1, ulVal ? 50 : 0);

**Comment by Prusa-Support** [comment]
Hello! Sorry for replying so late to the thread. There was a renaming/refactoring from "a3ides" to "buddy", the hardcoded PWM and RPM intervals are now on this file: https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/src/common/config_buddy_2209_02.h 

Alessandro Pantaleo
Prusa Research

**Comment by HyronNotEZ** [comment]
Thanks for the replies @threepoint2 and @Prusa-Support.
I've modified the 3.4.3 release version in the file /src/common/hwio_a3ides_2209_02.cpp line 620 with: 
#ifdef NEW_FANCTL
            if (hwio_fan_control_enabled)
                fanctl_set_pwm(1, ulVal ? 69 : 0);
which worked great with the Noctua fan. Now I'm getting a solid fan speed.
What you @Prusa-Support mentioned is in the new master which will help when you update to a new release version. For now i did't want to user the master since it is a prerelease and i still want my printer to run with no problems.
