### ISSUE TITLE
Filament Menu Cooling Down Option

### ISSUE THREAD

**Issue by PhilippeGalid** [prusa3d/Prusa-Firmware-Buddy#2097]
Thanks for your hard work ,can we please have in the Filament Menu a cooling down Option for Bad and Hotent after Unload Filament for the next Firmware relases,that will be where nice for many user ? Thanks Prusa for your Hard work.

**Comment by Gordontgopher** [comment]
There is a 'cooldown' option under the 'preheat' menu, are you looking for something different?
