### ISSUE TITLE
[ENHANCEMENT] Remove ".gcode" extension from file name when file is printing

### ISSUE THREAD

**Issue by gjsman** [prusa3d/Prusa-Firmware-Buddy#2108]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - Mini (with Mini+ upgrade)
**Optional upgrades** - Filament Runout Sensor, SuperPINDA

This is a minor change request - but the file printing screen has ".gcode" at the end of every filename, and considering that only a ".gcode" is actually printable, it's unnecessary to have it at the end of an animated title displaying the file being printed. This mainly comes up when it's something short that would fit on the screen (like most of my files) but unnecessarily scroll to show ".gcode" at the end.

**Comment by Prusa-Support** [comment]
Issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2629 actually duplicates this one but let me close this one in advantage of the other because, to date, the other got arguably more participation.

Thanks for your input.

Michele Moramarco
Prusa Research
