### ISSUE TITLE
Bootloader not getting updated

### ISSUE THREAD

**Issue by MinnesotaMean** [prusa3d/Prusa-Firmware-Buddy#2188]
I don't want to open a bug report because it may not officially be a bug. However, I am unable to update the bootloader to anything above 1.0.0. Are there any official .bbf's that update to 1.1.1 or 1.0.1? 

I've tried so many combinations and custom builds but no luck getting the bootloader up to the 2.0.2 that I need to use esp's.

Thank you!

**Comment by murk-sy** [comment]
I believe the next release - 4.4.0 - will have bootloader updating, guessing mostly on a few commits I've seen. As far as official releases go, I don't believe there's any way (or even reason) to update it yet. This is assuming you aren't compiling code yourself.

**Comment by MinnesotaMean** [comment]
> I believe the next release - 4.4.0 - will have bootloader updating, guessing mostly on a few commits I've seen. As far as official releases go, I don't believe there's any way (or even reason) to update it yet. This is assuming you aren't compiling code yourself.

Yes, I understand that 4.4 requires 2.0.2 bootloader. The new v2 bbf and old v1 bbf's were not working with the code I compiled. I was able to manually flash v2.0.2 using DFU but get a boot loop when flashing any firmware that isn't 4.3.4. 

Basically at the mercy of the Prusa dev team to finally release v4.4 or 4.4-rc.

**Comment by CarlosGS** [comment]
You are right, flashing the current version produces a white screen. A bit scary, so thank you for the heads up :)
Fortunately the bootloader is still 1.0.0 working OK, and it is possible to reflash easily.

Not sure how to debug this, I'd also love to help make the upgrade process more robust.

**Comment by CarlosGS** [comment]
Found the problem! At the setup of the external flash chip, the code is checking for a specific manufacturer ID. When the memory chip has a different manufacturer, this yields a white screen without any message, unfortunately causing a brick.

@MinnesotaMean you need to replace [this line](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/6c0b9d1a3782febc4a206ad8bb33dc0675e26bae/src/common/w25x.cpp#L361) with `return ((w25x_devid == DEVID) || (w25x_devid == DEVID_NEW));`

I'd strongly recommend to move the MFRID check to later in the code, where it is possible to properly inform the user of the situation while keeping a working machine. The current implementation would [brick their printers when upgrading to 4.4.0+](https://hackaday.com/2014/10/22/watch-that-windows-update-ftdi-drivers-are-killing-fake-chips/) :confused:

**Comment by MinnesotaMean** [comment]
> Found the problem! At the setup of the external flash chip, the code is checking for a specific manufacturer ID. When the memory chip has a different manufacturer, this yields a white screen without any message, unfortunately causing a brick.
> 
> @MinnesotaMean you need to replace [this line](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/6c0b9d1a3782febc4a206ad8bb33dc0675e26bae/src/common/w25x.cpp#L361) with `return ((w25x_devid == DEVID) || (w25x_devid == DEVID_NEW));`
> 
> I'd strongly recommend to move the MFRID check to later in the code, where it is possible to properly inform the user of the situation while keeping a working machine. The current implementation would [brick their printers when upgrading to 4.4.0+](https://hackaday.com/2014/10/22/watch-that-windows-update-ftdi-drivers-are-killing-fake-chips/) 😕



You are fantastic!! I will test this out on Monday. I do have a few cloned buddy boards due to cost and lead time. Thank you so much for your deep dive into locating the problem for me.

**Comment by CarlosGS** [comment]
Oh! it seems this was introduced two years ago and has simply shown up now the memory chip is being used :)
Will submit a PR to fix it. Thank you for reporting as it helped to pinpoint the issue!

**Comment by Prusa-Support** [comment]
Hello.
I can confirm that the bootloader will be possible to be updated via firmware in the future.
Until then, if you are interested in firmware 4.4.0 and ESP WiFi module testing, building the firmware is at your risk.
You can refer to this guidepost https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/master/doc/ESP and pull request #1751.

While the discussion goes on, please consider closing the issue if you think that your question was addressed adequately.

Michele Moramarco
Prusa Research

**Comment by CarlosGS** [comment]
@Prusa-Support Hi! We found the root cause of this issue and made PR https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/2203, it would be resolved when that fix is merged.

Let's keep this open until it is actually resolved, I don't want 4.4.0+ to brick any board :+1:

**Comment by thisiskeithb** [comment]
PR #2203 is still pending, but it needs to be rebased/updated to current code and tested.
