### ISSUE TITLE
Print not being shown as completed 

### ISSUE THREAD

**Issue by pleumann** [prusa3d/Prusa-Firmware-Buddy#22]
I had several prints that did not "end" properly, meaning the Mini would be in "pause" rather than saying the print was successful. First I though it might have beeen caused by a print that was exactly 18 cm in height, but then I saw the same for smaller prints, too.

**Comment by pleumann** [comment]
Firmware 4.0.1.

**Comment by AndyThirtover** [comment]
I have seen the same on all my prints since 4.0.1 -- have to manually mark them as complete.

**Comment by ryanpriore** [comment]
This is the same for me as well with pre-sliced files from the USB stick or files that I have sliced.

**Comment by Area5142** [comment]
Firmware 4.0.1
Same problem here. Printer just waits after print is finished. Have to select stop to end print.
Tried a simple G-code file with just a single G-code "G0 Z100" and some comments - same result, it executes and just waits.
Looks like the firmware never detects end of file (EOF).

**Comment by LuckyBenni** [comment]
Same here - but not with all prints though :-(

**Comment by JohnnyDeer** [comment]
Hi, this bug is fixed in 4.0.5., i'm closing this issue.
