### ISSUE TITLE
Relase of Firmware 4.4.0 ?

### ISSUE THREAD

**Issue by PhilippeGalid** [prusa3d/Prusa-Firmware-Buddy#2202]
Please tell me when you will Relase Firmware 4.4.0 with Wifi Support.
There is very long time no Firmware Update for Prusa Mini,is Prusa not interrest to make the Mini better.
For me it looks that Prusa Mini is a dead Projekt now by Prusa ?
Thanks for your hard work, and very good Software and Hardware but so long time no New Firmware is not ok.

Thanks

**Comment by reedy** [comment]
While I agree over 6 months since a release is a long time.. The repository is very active - https://github.com/prusa3d/Prusa-Firmware-Buddy/compare/v4.3.4...master with 1,366 commits to master since the v4.3.4 commit.

A roadmap and/or timeline for releases would be good, for sure.

**Comment by CarlosGS** [comment]
Yes, they have been working very hard to bring a lot of awesome new features. 4.4.0 is definitely worth the wait :+1:

**Comment by PhilippeGalid** [comment]
Soory for my strict words, Josef explained the firmware issue and the USB issue in the last live Youtube blog which is being worked on and will come in the next few weeks. Prusa team thanks for your great products and your great support every day.
