### ISSUE TITLE
Stop button inactive during loading of filament 4.0.3-RC1 

### ISSUE THREAD

**Issue by simonbugler** [prusa3d/Prusa-Firmware-Buddy#222]
During the loading of filament the Stop butting is inactive (greyed out).

As the printer is doing some quite fast movements if anything is wrong then being able to Stop is important.

If this is not doable - then the Stop button should be removed from the screen.

As I was testing to make sure I was correct with this issue - I accidentally loaded the filament that was wrapped through the reel, it tried to drag the reel through - I really needed the stop button to be working.

**Comment by loglow** [comment]
In this kind of situation, isn't this precisely what the hardware panic (reset) button is for?

I do strongly agree that if the "stop" button doesn't do anything then it should be removed from the interface.
