### ISSUE TITLE
"Feature Request" Multiple sheets choice from menu (PEI and TXT) 

### ISSUE THREAD

**Issue by Jivens75** [prusa3d/Prusa-Firmware-Buddy#223]
It would be usefully !

**Comment by x10102** [comment]
YES PLEASE! It would be so great if you could have different saved Z-offsets for different sheets

**Comment by michalxfanta** [comment]
We will add this feature in some of the next releases.

**Comment by JohnnyDeer** [comment]
This request is already implemented, I´m closing this issue.
