### ISSUE TITLE
[FEATURE REQUEST] Add option to invert filament sensor

### ISSUE THREAD

**Issue by CuriousTimo** [prusa3d/Prusa-Firmware-Buddy#2295]
I have modified my mini to an [MK3s style extruder.](https://www.printables.com/model/56487-mk3s-extruder-for-prusa-mini)
This includes the MK3s filament sensor.
All is working perfectly. I can change the E-Stepper steps and Extruder dir in the hidden menu.

The MK3s style filament sensor is inverted however. It would be perfect if we could add an option to the hidden menu to invert the filament sensor.

**Comment by Prusa-Support** [comment]
Hello! Thank you for the post, I put the tag so that it can be reviewed by our devs and possibly implemented on a future release as part of the secret menu. 

Alessandro Pantaleo
Prusa Research
