### ISSUE TITLE
Beep buzzer after print is finished. 

### ISSUE THREAD

**Issue by x10102** [prusa3d/Prusa-Firmware-Buddy#230]
After finishing a print and homing the printer could beep a few times to let the user know the print is finished. It would take just a few minutes to implement but it's a handy feature.

**Comment by loglow** [comment]
I second this request, but please make it an optional setting.

**Comment by x10102** [comment]
> I second this request, but please make it an optional setting.

Yes, it could be enabled by default and you could disable it in settings as it can be annoying for some

**Comment by michalxfanta** [comment]
Thank you for an interesting idea, we will consider its implementation.

**Comment by om2kw** [comment]
beep at the end can be done byM300 gcode (play tone) as a last command.
M300 should be supported according to marlin docs

**Comment by x10102** [comment]
> beep at the end can be done byM300 gcode (play tone) as a last command.
> M300 should be supported according to marlin docs

M300 doesn't do anything

**Comment by JohnnyDeer** [comment]
Updated informations, in next FW version will be sound notifications. M300 will still not being supported.
