### ISSUE TITLE
[BUG] Octoprint Graphic Missing

### ISSUE THREAD

**Issue by chrishilbert** [prusa3d/Prusa-Firmware-Buddy#2300]
**Printer type** - [MINI]

**Printer firmware version** - 4.4.0 Beta 2

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
Octoprint

**Describe the bug**
The Octoprint octopus is missing now, it just gives a black screen in the center.

**Comment by DRracer** [comment]
this is a know limitation of the 4.4.0 beta2, we'll fix that in next releases

**Comment by Prusa-Support** [comment]
The issue should be fixed in the final [FW 4.4.0](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.4.0) release now. Please check it out.

Michele Moramarco
Prusa Research
