### ISSUE TITLE
[ENHANCEMENT] Allow password manager to fill API key field on Prusa Connect

### ISSUE THREAD

**Issue by darraghbr** [prusa3d/Prusa-Firmware-Buddy#2302]
It would be nice if the field that shows up when you load the web UI could be filled with a password manager plugin (bitwarden etc)

![image](https://user-images.githubusercontent.com/31858409/181429194-b5875119-e9d9-4e4f-a904-90242d9de5b8.png)

Because it is an API key it is probably best kept in an appropriate keystore such as a password manager, and it would be nice if it could be autofilled by said password manager. 

![image](https://user-images.githubusercontent.com/31858409/181429497-f3d7bf49-6c47-445e-9ce5-ffc40ffef827.png)

A very small enhancement but may be nice, especially if you had a number of these machines!

If this is merely a temporary solution and will not work this way once the full version of Prusa Connect is up and running then I can understand if this is not necessary.

**Comment by chrishilbert** [comment]
I wish it would just remember that I provided the API key once.

**Comment by Lichtjaeger** [comment]
Agree. It would be fine if the page would store the key in the Local Storage or Indexed DB of the browser.

**Comment by Prusa-Support** [comment]
Thank you for your comments.

This issue should be listed in the Prusa Link repository but we already have such issue recorded there.
https://github.com/prusa3d/Prusa-Link-Web/issues/222

Please allow me to close this one as a duplicate and feel free to join or monitor the conversation on the issue mentioned above.
