### ISSUE TITLE
4.0.3 RC1 display label mismatch

### ISSUE THREAD

**Issue by dtackgrounded** [prusa3d/Prusa-Firmware-Buddy#231]
Minor issue: 
Boot screen reports 4.0.2RC1 firmware version and Info screen correctly reports 4.0.3RC1
see attached screenshots

![PR_Mini_BootScreen](https://user-images.githubusercontent.com/867563/74696495-8e30a980-51ac-11ea-9eec-bb6ec9745621.png)
![PR_Mini_InfoScreen](https://user-images.githubusercontent.com/867563/74696501-912b9a00-51ac-11ea-8c96-b1166dc04cf2.png)

**Comment by gjsman** [comment]
Resolved with 4.0.3 final. No longer needs fixing.
