### ISSUE TITLE
[BUG] Filament change after runout runs above printed part rather than the corner

### ISSUE THREAD

**Issue by murk-sy** [prusa3d/Prusa-Firmware-Buddy#2323]
**Printer type** - [MINI+]

**Printer firmware version** - [4.4.0-BETA2]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**Describe the bug**
During a print when filament runout triggers and new filament is loaded, filament loading occurs at the new "filament load" position, about X40, rather than at X0. This causes filament to be extruded over the printed part, possibly causing visible marks if it makes contact and is not removed quickly enough.

**How to reproduce**
Start print and run out of filament - the filament change will happen at the new filament load location, which quite easily happens to be above a printed part.

**Expected behavior**
Load filament and purge at X0 Y0 as in 4.3.0

**Comment by DRracer** [comment]
@murk-sy hmmm, this looks like a regression from the "prevent piercing of the PTFE tube" issue where we move the extruder to a specific X position. Thanks for reporting, we'll look into it.
