### ISSUE TITLE
Blue screen of death. 

### ISSUE THREAD

**Issue by threepoint2** [prusa3d/Prusa-Firmware-Buddy#2342]
### Description of the bug

2.5.0 alpha 3, printing to mini 4.4.0 Beta 2. WiFi module AZDelivery ESP8266 https://amzn.eu/d/7gxdKkG, fully flashed and working fine. 

File upload over WiFi worked fine but printer crashed with error in screen shot. Printed fine after reboot. Many prints work fine over WiFi initiated printing just this one failed. 
![31CC3437-A879-4289-80AA-38FEF9D80960](https://user-images.githubusercontent.com/10359537/182333595-317d3b63-1687-4614-a1b6-0b052a4f6493.jpeg)
![986C7D0A-AA05-4EBA-A813-531F98410543](https://user-images.githubusercontent.com/10359537/182333600-6a607361-db7e-4522-a2e7-0d3c04e5fb63.jpeg)

### Project file & How to reproduce

Prusalink print. 

### Checklist of files included above

- [ ] Project file
- [X] Screenshot

### Version of PrusaSlicer

2.5.0 Alpha 3

### Operating system

Windows 11

### Printer model

Mini

**Comment by laloch** [comment]
Hi @rtyr, thanks for reporting. This seems to be a duplicate of #2315.

Could you please go to the "Settings" menu at your printer, do "Save Crash Dump" in there and send us the crash dump file that's gonna be created on your flash drive?

**Comment by rtyr** [comment]
You probably meant @threepoint2

**Comment by laloch** [comment]
Yep, you're right, thanks ;)
