### ISSUE TITLE
[ENHANCEMENT] Park head higher on Z axis when doing filament change mid print

### ISSUE THREAD

**Issue by reedy** [prusa3d/Prusa-Firmware-Buddy#2366]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MINI
**Optional upgrades** - Filament Runout Sensor

**Is your suggested improvement related to an existing problem? Please describe.**
No

**Describe the expected functionality**
Don't know whether this is a request that belongs here, or over at https://github.com/prusa3d/PrusaSlicer (though I haven't noticed a setting), but when you do a filament change mid print, the head is parked in the bottom left (nearest the front), but not at a very high Z axis height. When you're doing a big colour change (for example, Black to White), it's useful to be able to clean some of the residue off the nozzle. Unfortunately, with the default height, it's pretty difficult to do that as there's not much room to get even a small brush like [these spark plug bruses](https://ffx.co.uk/product/Get/Lessman-Les125111-4017359003312-Spark-Plug-Brush-2-Row-Brass-Wire)

Will get a photo when the next change comes up in a bit (though that's white to black, but still representative).

**Comment by reedy** [comment]
![image](https://user-images.githubusercontent.com/67615/183462210-9360b0a4-cac8-4c66-bd2a-3ed18908e920.jpeg)![image](https://user-images.githubusercontent.com/67615/183462224-47def41a-16d8-4cc1-9446-709fd528cd16.jpeg)![image](https://user-images.githubusercontent.com/67615/183462261-7975c772-f070-4f96-8f24-440d53ef9bf8.jpeg)

**Comment by Prusa-Support** [comment]
Thank you for the suggestion. It sounds like a legit request.
I'll make sure to bring this to the attention of our developers.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
This behavior was already improved by PR https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/1063, solving issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/637.

This issue is actually a duplicate but requests a further enhancement on top of the previous one, so I'd leave it open for now.

Michele Moramarco
Prusa Research
