### ISSUE TITLE
[BUG] <Nozzle temperature2 time displayed>

### ISSUE THREAD

**Issue by Hauzman** [prusa3d/Prusa-Firmware-Buddy#2393]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI+]

**Printer firmware version** - [4.4.0 beta 2]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [ Filament Runout Sensor]

**USB drive or USB/Octoprint** -[ USB ]

**Describe the bug**
In the main menu it apeare the nozzle temperature 2 time,
The second one is in the right down corner i think this do not need to be there 
![20220812_183229.jpg](https://user-images.githubusercontent.com/56076331/184477787-cedacd16-3adf-42ab-b195-78cbdded159b.jpg)

**Comment by kellertk** [comment]
In the beta firmware, the footer is customizable. You need to go into the [experimental menu](https://help.prusa3d.com/article/experimental-menu-mini-mini_264396) to change it.

**Comment by Hauzman** [comment]
Hello Sorry I did not know i got the mini a few day
Thanks for the information 👍
