### ISSUE TITLE
PID Autotune enabled in GUI

### ISSUE THREAD

**Issue by FrankCellini** [prusa3d/Prusa-Firmware-Buddy#2401]
The Mini printer can do PID auto tune however it would be good to add this function to graphical user interface so that it can be easily done and saved in “configuration.h” file. Even just show current values on display somewhere, maybe front page?

Enter what type of printer or upgrade the enhancement applies to.
**MINI**
**PID Autotune**
**Unable to set different PID values when altering hotted configuration eg adding silicon sock, changing heat break**
**Easily do PID Autotune and set new values in “configuration.h” file**

**Comment by rbronco21** [comment]
I read that PID tuning work work in custom g-code. Is that true? I'd be happy running an autotune (from menu or g-code) that only output PID values and then manually entering them into my g-code.

**Comment by FrankCellini** [comment]
Yes PID Auto tune is a function you can do on printer and this gives you values that you can then put into G Codes on a print job in Slicer.  You have to connect to printer serial port and use terminal software on a connected computer.
<img width="614" alt="Mini PID settings" src="https://user-images.githubusercontent.com/111335517/192446543-118d97e1-bcf5-4a96-b869-14ff26bf2ef5.png">
