### ISSUE TITLE
[BUG] Wrong file name shown on LCD while printing

### ISSUE THREAD

**Issue by chrishilbert** [prusa3d/Prusa-Firmware-Buddy#2415]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - 4.4.0 Beta 2

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
  USB

**Describe the bug**
The wrong file name being printed is shown on the LCD display.

**How to reproduce**
 Change filament in the middle of a print, filename being printed changes on the LCD to something else on the USB drive.  Web UI shows correct filename.

**Comment by Prusa-Support** [comment]
Hello! Thank you for your report and sorry for the late response from my side. I brought this to our devs attention, we'll review this in more detail and fix it as soon as possible. 

Alessandro Pantaleo
Prusa Research
