### ISSUE TITLE
[ENHANCEMENT] Add PA Polyamide/Nylon to filament list 

### ISSUE THREAD

**Issue by murk-sy** [prusa3d/Prusa-Firmware-Buddy#2416]
**Printer type** - MINI+

**Is your suggested improvement related to an existing problem? Please describe.**
Printing Nylon on the Mini works (with a lot of asterisks of course), but it is not available in the list of materials. That means you have to pick PC setting to ensure temperatures are high enough for filament changes and for first layer calibration.
Additionally, with filament type check now available, it may cause usability problems further down the road. See also #1919

**Describe the expected functionality**
One of the following options:
1. NYLON becomes available in the filament change menu (it may be recommended to change it to PA? That's more something for the slicer team, I'll make a feature request there too)
2. Add "Custom" options with settable extruder/bed temperatures
3. Add "Unsupported materials" in a submenu; selecting them uses the closest available temperature.

### Edit: "Futureproofing" option:
4. List only materials that have been used so far on the printer (with maybe an option to remove them). That would mean the stock material/filament list would look like this:

- PLA
- More materials
  - ASA
  - PETG
  - TPU
  - PC
  - Etc.
- (Cooldown)

After using a few materials already, the list looks like this:

- PLA
- PETG
- TPU
- More materials
  - ASA
  - PC
  - Etc.
- (Cooldown)

This allows basically all filaments to be listed (unsupported would be crossed out/red but still selectable to nearest available temperature), and makes the menu easy to use on a day to day basis - digging deeper into the menu happens only once when a new material is added - which, for the vast majority of printer users, happens *maybe* twice per printer. This means cooldown is also much faster to access for the vast majority of users.

**Comment by Prusa-Support** [comment]
Hello! Thank you for the request and for the ideas, sorry for the late response from my side. I brought this to our devs attention to review and possibly implement as soon as possible. In case of more info from our side we'll update on this thread. 

Alessandro Pantaleo
Prusa Research

**Comment by ThomasCZ** [comment]
+1 for Nylon

**Comment by murk-sy** [comment]
PA has been added with 5.1.0-alpha, closing

Will make a new FR in the future with the material list improvement
