### ISSUE TITLE
[ENHANCEMENT] Update tune screen values when changed by gcode during print

### ISSUE THREAD

**Issue by derenma** [prusa3d/Prusa-Firmware-Buddy#2417]
**Printer type** - MINI
**Optional upgrades** - Runout sensor; Bondtech extruder; ESP-01S

**Is your suggested improvement related to an existing problem? Please describe.**
During a print, and in the tune menu, please update values to reflect what has been sent by gcode.

For example: If I am in the tuning menu and the gcode changes a value (like fan speed) please update the display settings to reflect the current value that is being used.

**Why this matters**
Gcode takes priority over manual tuning settings. When live testing things like bed temp, nozzle temp and fan speed settings it would be nice to know the new value that has been set and can change a setting based on the actual running values.

**Describe the expected functionality**
Values update automatically in tuning menu

**Comment by Prusa-Support** [comment]
Hello! Thank you for the request, I brought it to our devs attention - in case of more info from our side, I'll update on this thread. 

Alessandro Pantaleo
Prusa Research
