### ISSUE TITLE
[ENHANCEMENT] Allow manual override of gcode in print tuning menu (option to force manual settings over gcode)

### ISSUE THREAD

**Issue by derenma** [prusa3d/Prusa-Firmware-Buddy#2418]
**Printer type** - MINI
**Optional upgrades** - Runout sensor, Bondtech extruder, ESP-01S

**Is your suggested improvement related to an existing problem? Please describe.**
Please add a selector to force priority of manual tuning settings over gcode. When experimenting with cooling speeds and temperatures, it would be nice to ignore any new gcode values that will override manual settings.

**Describe the expected functionality**
Add selector: Manual Tuning Override: [yes/no]
New manual values for temperature, fan speed, etc.. are not changed.

**Comment by Prusa-Support** [comment]
Hello! Thank you for the request, I brought it to our devs attention - in case of more info from our side, I'll update on this thread.

Alessandro Pantaleo
Prusa Research
