### ISSUE TITLE
[FEATURE REQUEST] Allow naming of printer on network

### ISSUE THREAD

**Issue by alan412** [prusa3d/Prusa-Firmware-Buddy#2421]
**Printer type** 
MINI

**Describe the expected functionality**
 I use DHCP for the Prusa mini.   It would be great if I could give it a name such that I could tell prusa slicer to connect to <myprintername>.local and then I wouldn't have to update the IP address when something caused the device to get a different address.

**Comment by Prusa-Support** [comment]
Hello! Thank you for your request, I passed this on to our devs for them to further review and possibly implement, in case of more info on this from our side we'll update on this thread. 

Alessandro Pantaleo
Prusa Research

**Comment by krupkaj** [comment]
Also need this feature. This is really important when there is more than one printer in the network.

**Comment by Prusa-Support** [comment]
This is theoretically already possible but only when flashing the "core" Prusa Link image on [Raspberry Pi Zero W](https://help.prusa3d.com/guide/prusalink-and-prusa-connect-setup-mk3-s-_221744#304787) or [Raspberry Pi 3/4](https://help.prusa3d.com/guide/prusalink-prusa-connect-with-rpi-3-4-usb-mk2-5-s-mk3-s-_469341#470087).

Moreover, the new option to set Prusa Connect as the Host Type in Prusa Slicer will allow this without the use of additional boards as soon as Prusa MINI will be enabled on Prusa Connect (coming soon).
  
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/103262060/e5c3d286-b592-4ea2-884c-df5f40a59079)

Can this issue be closed?

Michele Moramarco
Prusa Research

**Comment by alan412** [comment]
I don't use Prusa Connect as it is on a closed network.   I would rather be able to assign a name and have it work with bonjour (sorry, I forget the generic term for this) so that I could connect to it by name.

**Comment by alan412** [comment]
I would still like this feature as I use it on a closed network.

**Comment by danopernis** [comment]
Hi @alan412 seems like you are actually requesting mdns support which should be already implemented as indicated in https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3809

**Comment by alan412** [comment]
It does work now.   I would recommend it be put into release notes.

**Comment by alan412** [comment]
Technically this should be closed as done in #3809 instead
