### ISSUE TITLE
[BUG] Broken filament change procedure

### ISSUE THREAD

**Issue by mix579** [prusa3d/Prusa-Firmware-Buddy#2423]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]
Mini +

**Printer firmware version** - [e.g. 4.0.5, ...]
4.4.0-beta2

**Original or Custom firmware** - [Original/Custom]
Original

**Optional upgrades** - [e.g. Filament Runout Sensor]
Prusa Filament sensor

**USB drive or USB/Octoprint**
  From PrusaLink

**Describe the bug**
Printing a model with a manual filament change. At the change point it unloaded properly and prompted to insert new filament. I didn't push it far enough so it didn't get pulled into the extruder. So when asked whether color is corrected, I selected Retry.
After ramming and unloading it asked me whether unload was successful. I replied yes, and immediately the printer went back to the new starting position and started printing without asking me to insert new filament and confirming it has been loaded, so it was printing without filament. 

**How to reproduce**
  See above

**Expected behavior**
After selecting retry and subsequent ejection of old filament, the printer should prompt for the new filament, confirm correct load, and then reinitiate the print.

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by Prusa-Support** [comment]
Hello! Thank you for your report. We'll review it in more depth with devs, but not sure it can be classified as bug, but will leave the tag for now - at a first glance, I don't believe it's "broken code" but more a consequence of how the fil. sensor works, and its position "before the printer", so still the printer wouldn't "know" if filament is before or after the gearing. Still brought it to our devs attention, perhaps there might be some UI improvements to avoid this type of situation, in case of more info from our side I'll update on this thread. 

Alessandro Pantaleo
Prusa Research
