### ISSUE TITLE
[BUG] Print fan not spinning error after changing from 0% to 30%

### ISSUE THREAD

**Issue by derenma** [prusa3d/Prusa-Firmware-Buddy#2424]
**Printer type** - MINI

**Printer firmware version** - 4.4.0b1

**Original or Custom firmware** - Original

**Optional upgrades** - Runout sensor, bondtech extruder, ESP-01s

**USB drive or USB/Octoprint** - USB

**Describe the bug**
During the first few layers, the print fan stops at random. Both hotend fans self-test as OK.

The fan speed error can happen during the first few layers when the fan is supposed to be at 0%. The firmware seems to not like the 0% fan setting now.

**_Workaround_**: I currently have menu timeout disabled and open the "tune" menu after the print starts. After the "fan not spinning error" happens I can press the "continue" button as the UI reverts to the last open menu. (Since I have the tune menu open, the UI reverts to that, not the home screen.) I then make a print fan speed adjustment so I can see the fan turn back on. One the fan is turned back on, I can resume the print.

**_Workaround 2_**: Disable fan checks. (Not ideal.)

In some cases, the above steps have to be taken 2-3 times before the print continues as normal.

**How to reproduce**
(In my case) Have the print fan at 0% for the first few layers and the print will halt with a recoverable error.

**Expected behavior**
The fan starts and stops as expected and the fan speed check is done correctly.

**G-code**

[AllanKey_Wall v1.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/9388156/AllanKey_Wall.v1.zip)

**Crash Dump**

I have it, but github will not let me attach it for some reason??

**Video**

- Printer is finishing layer 3 (Fan at 0%, Time 0:57)
- Fan is spun up to 30%
- Layer 4 starts and then stops shortly after
- Fan speed is manually set to 30% and print is resumed
- Print continues as normal

https://youtu.be/UlY2WSc2rA0?t=57

**Comment by murk-sy** [comment]
Duplicate of #2314

**Comment by derenma** [comment]
@murk-sy Closed as dup.

https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2314#issue-1320879737
