### ISSUE TITLE
[BUG] posted in the wrong place

### ISSUE THREAD

**Issue by wjcampbe** [prusa3d/Prusa-Firmware-Buddy#2449]
Posted in the wrong place

**Comment by derenma** [comment]
@wjcampbe It is possible for you to close your own issue in GitHub.

**Comment by wjcampbe** [comment]
you learn something every day - i learned i can close an item and you learned you don't have to offer guidance. Some people can work things out for themselves

**Comment by derenma** [comment]
@wjcampbe ¯\_(ツ)_/¯
