### ISSUE TITLE
[BUG] Stuck head heating

### ISSUE THREAD

**Issue by ThomasCZ** [prusa3d/Prusa-Firmware-Buddy#2495]
I have to start and stop printing to stop head heating after I unload a filament. Expected behavior: Head heating stop immediately after the filament is unloaded.

**Comment by ThomasCZ** [comment]
It is not right, because heat bed is also heating and whole process is waiting for that. When I am unloading a filament, it is just wasting of energy. I think, it is wasting of energy in 100% of cases, because when I select "unload filament", I want to unload a filament. If I wanted to print with another filament, I can select "Change filament". Safety timer does not solve wasting of energy.

Anyway, could you please add at least some "eco" check box, that will not heating heat bed and turn off heating immediately?

**Comment by Prusa-Support** [comment]
> It is not right, because heat bed is also heating and whole process is waiting for that. When I am unloading a filament, it is just wasting of energy. I think, it is wasting of energy in 100% of cases, because when I select "unload filament", I want to unload a filament. If I wanted to print with another filament, I can select "Change filament". Safety timer does not solve wasting of energy.
> 
> Anyway, could you please add at least some "eco" check box, that will not heating heat bed and turn off heating immediately?

Duplicate. https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/221#issuecomment-1256177154

Michele Moramarco
Prusa Research
