### ISSUE TITLE
Only first 19 letters of long filename is shown

### ISSUE THREAD

**Issue by Area5142** [prusa3d/Prusa-Firmware-Buddy#25]
Firmware: 4.0.1

When selecting the G-code file to be printed, only the first 19 letters are shown. Filenames generated by PrusaSlicer can be very long and different versions is hard to distinguish if they only differ in the last part of the filename.

On the small display of Prusa MKs the filename is scrolled to display the full filename.

If scrolling the name in the file list is impossible, the full name could be shown after selection - The display should be large enough to display a lot more of the filename (Screen with model icon).
This will give a last change to check if the correct file is selected - print or go back to file list and select another file.

**Comment by michalxfanta** [comment]
We prepare scrolling of long filenames. This feature will be released in the next firmware version.
