### ISSUE TITLE
[BUG] No unique serial number in 4.4.0-RC1

### ISSUE THREAD

**Issue by paukstelis** [prusa3d/Prusa-Firmware-Buddy#2558]
**Printer type** -
Mini

**Printer firmware version** - 
4.4.0-RC1

**Original or Custom firmware** - [Original/Custom]
Original

**Optional upgrades** - [e.g. Filament Runout Sensor]
None

**USB drive or USB/Octoprint**
Both

**Describe the bug**
 Updating bootloader and firmware to 4.4.0-RC1 results in disruption of the unique serial number. Serial number is now reported as: SerialNumber: 00000000001A

**How to reproduce**
Install bootloader and firmware.

**Expected behavior**
 Unique serial numbers should be retained. This is the most useful way for identifying individual printers using udev rules for host control systems (OctoPrint).

Related but not identical to issue raised here: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2542

**Comment by Prusa-Support** [comment]
The issue should be fixed in the final [FW 4.4.0](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.4.0) release now. Please check it out.

Michele Moramarco
Prusa Research
