### ISSUE TITLE
[BUG] Random translation during filament change

### ISSUE THREAD

**Issue by Mryck** [prusa3d/Prusa-Firmware-Buddy#2579]
**Printer type** - [MINI]

**Printer firmware version** - 4.4.0 RC 1
 
**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**Describe the bug**
With the mini in French language when the filament is already in the sensor to early during a filament change it ask for "mot de passe" with means "password" instead of remove filament or something like that 

**How to reproduce**
 Put mini in French change filament and insert filament before it's ask to

**Expected behavior**

I can put image if needed

**Comment by Prusa-Support** [comment]
Thank you for reporting.

Because 'Prusa Research' is the direct maintainer of this language, I will forward this translation mistake to the competent department.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
Please allow me to close this issue as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2883 and potentially solved.

Michele Moramarco
Prusa Research
