### ISSUE TITLE
[ENHANCEMENT] Hide filename extensions

### ISSUE THREAD

**Issue by ThomasCZ** [prusa3d/Prusa-Firmware-Buddy#2629]
Showing file name extensions are unnecessary.

**Comment by Eldenroot** [comment]
I agree, if the file extension is not supported you should not be able to see the file... this could save some space :)

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.
Our developers will take this into consideration.

Michele Moramarco
Prusa Research

**Comment by espr14** [comment]
Related to #2108
