### ISSUE TITLE
[BUG] Low temp Move E at 230°C

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware-Buddy#2633]
**Printer type** - MINI

**Printer firmware version** - 4.3. or 4.4 RC

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - USB flash

**Describe the bug**
I was unable to move the E axis but the temperature was 230 °C.

**How to reproduce**
Preheat the printer (for PETG), go to Move axis and try to move E.

**Expected behavior**
E should move with at the 230 °C.

**G-code**
No G code, just menu entries.

**Crash dump file**

**Video**
![IMG_20221020_101856s](https://user-images.githubusercontent.com/46957311/197328558-e73f9d08-b181-429d-adb4-128597fa9081.jpg)

**Comment by Prusa-Support** [comment]
Hello! Thank you for reporting this, we are looking into this aspect with our devs, in case of any additional info from our side, we'll post it here. 

Alessandro Pantaleo
Prusa Research
