### ISSUE TITLE
[BUG] Visual glitches in buttons - Czech lang - /System info+Wifi settings/

### ISSUE THREAD

**Issue by Eldenroot** [prusa3d/Prusa-Firmware-Buddy#2636]
**Printer type** - [MINI+]

**Printer firmware version** - [4.4.0-RC1]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
  USB flash drive

**Describe the bug**
  Visual glitches - buttons

**How to reproduce**
  Please describe steps to reproduce the behavior.
1) WIFI setup - button is not full width, something is on the right side
2) System info - missing part of the word "Konec" (Czech), button is too short

**Expected behavior**
- Both should be fixed, align the text and button width

**G-code**
---

**Crash dump file**
---

**Video**
- check images
![1666559322046](https://user-images.githubusercontent.com/778890/197418486-38e29c27-6e2d-4d37-ab15-6310a99c5636.jpg)
![1666559322059](https://user-images.githubusercontent.com/778890/197418488-739b21e5-2ff7-42fa-8ee9-b0d7c82b7966.jpg)

**Comment by Prusa-Support** [comment]
Hello, thank you for the report, all noted and passed on to our devs for them to review and fix it! 

Alessandro Pantaleo
Prusa Research

**Comment by Eldenroot** [comment]
4.4.1 still valid
