### ISSUE TITLE
Resuming print not cleaning noozle

### ISSUE THREAD

**Issue by tmeinlschmidt** [prusa3d/Prusa-Firmware-Buddy#264]
firmware 4.0.2

steps to reproduce:
- start print
- pause
- wait until some filament starts exiting the noozle
- resume print

expected behaviour:
- noozle is cleaned up outside printing area with simple short line

**Comment by Bertware** [comment]
This currently causes paused prints to fail, as the nozzle will ooze onto the print, causing a blob and failed prints as a result.

**Comment by isopterix** [comment]
Yes, please add this!!! I just ran into the same issue... luckily I was quick enough to take out the blob with some sizzlers... Otherwise it would have been a complete fail.

**Comment by Bertware** [comment]
A special case would be a print that is paused multiple times. In this case, the printer should either stack the "wipe lines" or find another unused area to wipe the nozzle. In the meanwhile, a fix where this only happens for the first pause of a print would be nice already!

**Comment by Eldenroot** [comment]
If not #2760 then we need this one. This could save a lot of time and avoid issues because of pausing
