### ISSUE TITLE
[BUG] TASK: network. Precise data access error, precise

### ISSUE THREAD

**Issue by smstroble** [prusa3d/Prusa-Firmware-Buddy#2640]
**Printer type** - MINI

**Printer firmware version** - 4.4.0-RC1

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
  USB drive (original drive)

**Describe the bug**
  Mid print blue screen crash
![crash](https://user-images.githubusercontent.com/6299833/197421564-159e32e5-b1b4-43fb-8f01-f05a6e5b2cc9.png)

**How to reproduce**
  Unknown, I have printed this exact gcode on this firmware without encountering this error before.

**Expected behavior**
  Continue printing normally

**G-code**
[gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/9847674/gcode.zip)

**Crash dump file**
[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/9847677/dump.zip)

**Comment by Prusa-Support** [comment]
Hello, thank you for the report, I notified our devs on this issue to find a way to troubleshoot it and find a resolution. We'll update you here with more info as soon as possible. 

Alessandro Pantaleo
Prusa Research
