### ISSUE TITLE
USB still not 100 % ok

### ISSUE THREAD

**Issue by Pitel** [prusa3d/Prusa-Firmware-Buddy#265]
I still have to go to some menu section and back to the main screen when reinserting the USB drive. Otherwise, the _Print_ menu item is disabled.

**Comment by Lino77** [comment]
I still have print on the display, even though the stick was pulled out. not always, but now and then

**Comment by runemart** [comment]
Confirmed here, still an issue (using the USB key I got with the Mini). 
USB icon in top right corner changes state (bright vs dim) correctly, but Print menu icon does not. 
Video of the behaviour: https://www.youtube.com/watch?v=6rMDdcDB7Tc

**Comment by x10102** [comment]
Confirmed here also.

**Comment by kdpainter** [comment]
I have seen this as well.

**Comment by 0xygen8** [comment]
The Original USB stick works 99% of the time other Intenso USB 3 sticks only work when the Mini is booted with the stick inserted. Inserting Intenso (and others) when Mini is booted fail 95%  of the time

**Comment by Pitel** [comment]
We can close this in favor of #21.
