### ISSUE TITLE
[ENHANCEMENT] Increase printing screen timing text size

### ISSUE THREAD

**Issue by MrTrick** [prusa3d/Prusa-Firmware-Buddy#2662]
✅ Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI]
**Optional upgrades** - N/A

**Is your suggested improvement related to an existing problem? Please describe.**
When running, the **main** reason I look at the printer is to see how much time remains.
The time information is very small and difficult to read, especially from an angle!

Other areas of the printer use pictograms to save space, how about here?

**Describe the expected functionality**
Here's a very quick-n-hacky mockup of the suggested enhancement:
![gui_current_vs_proposed](https://user-images.githubusercontent.com/127012/198302193-48fd3d29-2451-4d6d-982e-bbe4e2453d76.jpg)

Maybe the size of the elements in this screen could be generally evaluated by their importance?
If overall screen real-estate is an issue, maybe the action icons don't always need to be visible?

**Comment by Eldenroot** [comment]
I dont like your idea - if you connect the printer to the internet, you will get the time and date feature - so the space will display the exact date and time when the print will be finished.... So there is no space if you wanna change it in your way.

**Comment by Eldenroot** [comment]
You can use wifi module (I have been using it for 3 weeks and I am so happy)! It costs about 2USD

**Comment by Gordontgopher** [comment]
I have no strong view on this, I use Octoprint to view time elapsed / remaining. In case this idea is taken forward I just thought I would mention the hourglass's' on your mock up are the wrong way round, the elapsed time would be with the 'fill' in the bottom, and the remaining time the fill would be in the top.

**Comment by MrTrick** [comment]
@Gordontgopher it is a bit confusing, depends whether you think black or white is the "filled" part.
Plenty of other pictograms; little checkered flag, arrows, even just adding a second colour would clarify things.
(and ultimately it's not about that, just the teeny tiny text size)

**Comment by Eldenroot** [comment]
![IMG_20221028_154623](https://user-images.githubusercontent.com/778890/198697636-91a2af98-ff47-4636-838f-789f5d8341f4.jpg)

This is how you can see the time remaining if you are connected to the internet.
