### ISSUE TITLE
[BUG] Missing translations (Czech) - print screen

### ISSUE THREAD

**Issue by Eldenroot** [prusa3d/Prusa-Firmware-Buddy#2665]
**Printer type** - [MINI+]

**Printer firmware version** - [4.4.0RC1]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
  print via USB flash drive

**Describe the bug**
  Screen during the print (starting) - there are displaying texts which are not translated - for example heating bed, e heating, e cooling, bed cooling etc.

**How to reproduce**
  Start the printing, check the print screen. Text is displayed in the area where "estimated time/elapsed time/ are normally displayed.

**Expected behavior**
  These texts should be translated.

**G-code**
  ---

**Crash dump file**
  ---

**Video**
  ---

**Comment by Eldenroot** [comment]
I will add some photos, give me few minutes.

**Comment by Eldenroot** [comment]
![IMG_20221028_154603](https://user-images.githubusercontent.com/778890/198697457-20ddcc7f-50e1-4e75-b9b1-c4b87dd4e2a8.jpg)
![IMG_20221028_154614](https://user-images.githubusercontent.com/778890/198697468-41198fd5-da7b-4c2a-a243-54c6efc40129.jpg)

![IMG_20221028_154616](https://user-images.githubusercontent.com/778890/198697472-91ea50ac-20ee-49b4-a684-b90f72057a96.jpg)
![IMG_20221028_154623](https://user-images.githubusercontent.com/778890/198697474-91d54164-bb6c-4746-ace1-bda997e007ac.jpg)
3 photos - you can see English text, last photo - just to see that I use Czech language

**Comment by Kalimero13** [comment]
Tahle chyba je tam bohužel už několik let.

**Comment by Eldenroot** [comment]
> Tahle chyba je tam bohužel už několik let.

Thats why I had created the report :) this should be fixed. Czech product but missing translation :)

**Comment by Prusa-Support** [comment]
Hello, thank you for reporting this, I passed this on to our devs, hopefully it can be fixed soon. 🙂 

Alessandro Pantaleo
Prusa Research

**Comment by Kalimero13** [comment]
Thank you.

**Comment by CZDanol** [comment]
Hey, we are slowly migrating to a new print status message API, so the messages should get eventually all translated - this will possibly happen over a few releases.
