### ISSUE TITLE
[BUG] Missing translations for experimental menu (Czech) + change "wrong" to "reverse"

### ISSUE THREAD

**Issue by Eldenroot** [prusa3d/Prusa-Firmware-Buddy#2678]
**Printer type** - [MINI]

**Printer firmware version** - [4.4.0_RC1]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor + Bondtech IFS extruder]

**USB drive or USB/Octoprint**
  USB

**Describe the bug**
  Experimental menu is not translated (Czech).

**How to reproduce**
  Open experimental menu.

**Expected behavior**
  I think that "Experimental menu" should be translated. Also the direction phrase "wrong" should be renamed to "reversed".

**G-code**
  ---

**Crash dump file**
  ---

**Video**
![image](https://user-images.githubusercontent.com/778890/199612012-338c05e7-b247-4d3a-bdd6-e5dc296d4fd8.png)

**Comment by Eldenroot** [comment]
Also this notice is not translated - it is displayed when you wanna save the new values in the menu (Experimental settings)

![image](https://user-images.githubusercontent.com/778890/199613234-b9defe4f-2aa4-434c-82d5-60c42ef9acd3.png)

**Comment by Prusa-Support** [comment]
Hello, thank you for reporting these missing translations, I passed this on internally so that it can be corrected asap. 

Alessandro Pantaleo
Prusa Research
