### ISSUE TITLE
[BUG] "Ramming" is not translated (Czech)

### ISSUE THREAD

**Issue by Eldenroot** [prusa3d/Prusa-Firmware-Buddy#2692]
**Printer type** - [MINI+]

**Printer firmware version** - [4.4.0_RC1]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor + Bondtech IFS + Wifi module]

**USB drive or USB/Octoprint**
  USB

**Describe the bug**
  Word "Ramming" is not translated into Czech language. This word does not exist in the Czech language,

**How to reproduce**
  Set the Czech language and go to the filament page.

**Expected behavior**
  "Ramming" should be translated.

**G-code**
  ---

**Crash dump file**
  ---

**Video**
  ---

**Comment by Prusa-Support** [comment]
Hello! Thank you for noticing this, passed this on to our devs so that the translation can be included. 

Alessandro Pantaleo
Prusa Research
