### ISSUE TITLE
X-axis crash

### ISSUE THREAD

**Issue by pleumann** [prusa3d/Prusa-Firmware-Buddy#27]
I just had a case where I needed to cancel a print during the first layer. I think it was still in the skirt. The x-carriage crashed into the right side (well, maybe that's a harsh word, but it obviously did not find the endstop). Single case so far. Firmware 4.0.1.

**Comment by Area5142** [comment]
Firmware 4.0.1
Stopped print in third layer as the model had gone loose. The print head lifted up and x-carriage moved right and crashed into end stop. Motor did not stop on end stop, but was running for about a second more, making a clicking noise.
I have only seen this happen once.

**Comment by GitSteeK** [comment]
Same here... stopped printing in one of the first levels an the print head lifted up and crashed into the end stop ... terrible noise ans white powder fall on the heatbed.

**Comment by pleumann** [comment]
I just had a case where the same happened for the y-axis. Again, after canceling a print. So maybe this issue can be merged with #16.

**Comment by Lightn** [comment]
I had this happen twice at the start of printing the sample tree frog included on the USB drive.  At least I think it was the X-axis, I hit reset pretty quick when it happened.

**Comment by laposheureux** [comment]
Have also had this happen with 4.0.1 on the x-axis. It was after I'd canceled a print as well. It's like the printer loses track of where the print head is upon cancellation and then also fails to detect when it's reaching the end.

**Comment by michalxfanta** [comment]
We try to replicate this behavior.

**Comment by freshmas** [comment]
I have also had this happen at least 3 times after cancelling different prints. Most recently, a clump of white, powdery material fell off just like GitSteek above.

**Comment by LuckyBenni** [comment]
I also experienced this behaviour several time at my Mini with 4.0.1.
It seems that the motor which moves the extrusion carriage from left to right uses too little power which results sometimes already during the mesh bed leveling process in lost steps. Sometimes I noticed that between the first and second measurement point, sometimes between the second and third measurement. Apparently at the second row the carriage then crashed to the Z axis.
After rebooting the Mini and running the exact same gcode the mesh bed levelling succeeds w/o issues.
If it is not related to too little power another reason could be electronic interferences - but they would be a nightmare to find out :-(.

**Comment by michalxfanta** [comment]
We replicated this bug, we will fix this asap.

**Comment by x10102** [comment]
Also happened to me
FW 4.0.1

**Comment by Jivens75** [comment]
Same here
FW 4.0.4

**Comment by JohnnyDeer** [comment]
Hi, this issue should be fixed on 4.1.0-RC1. Please try it out :)

**Comment by JohnnyDeer** [comment]
No responses. I'm closing this issue as solved.
