### ISSUE TITLE
[BUG] Double extruder dial on lcd screen after flashing 4.4.0 RC

### ISSUE THREAD

**Issue by Oxize** [prusa3d/Prusa-Firmware-Buddy#2700]
**Printer type** - [MINI]

**Printer firmware version** - [4.4.0 RC]

**Original or Custom firmware** - [Custom]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
  USB/Octoprint

**Describe the bug**
  After flashing firmware 4.4.0 RC you see an double temp extruder dial on the lcd screen.

**How to reproduce**
  Flash firmware 4.4.0 RC

**Expected behavior**
  Should be only 1 temp dial for the extruder.

**G-code**
  not needed

**Crash dump file**
 Not needed.

![image](https://user-images.githubusercontent.com/3933702/200530743-7452f280-fd65-4aa9-bd49-63a8d449f487.png)

**Comment by Eldenroot** [comment]
Duplication of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2544 and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2545

**Comment by Prusa-Support** [comment]
Thanks for reaching us.
Unfortunately, most of the footers deserve a correction.

This issue will be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2544.

Michele Moramarco
Prusa Research

**Comment by Eldenroot** [comment]
Will be there another RC release or we are waiting for 4.4.0 final? Thx

**Comment by your-friend-alice** [comment]
still present in 4.4.1:
![IMG_20230127_030022](https://user-images.githubusercontent.com/832009/215048106-d2e55501-d0f8-4fce-b297-3b3c03ed6caf.jpg)
