### ISSUE TITLE
[BUG] Missing CZ translation of text "Probing Point" when bed mesh leveling.

### ISSUE THREAD

**Issue by pacaj2am** [prusa3d/Prusa-Firmware-Buddy#2706]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MINI

**Printer firmware version** - 4.4.0-RC1

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
n/a

**Describe the bug**
Missing CZ translation of text "Probing Point" when bed mesh leveling.

**How to reproduce**
Start print with CZ language

**Expected behavior**
CZ translation should be shown, "Měřím bod" in consistency with MKš (https://github.com/prusa3d/Prusa-Firmware/blob/e109da4db9148fc5a36a971815322f69a2393954/lang/po/Firmware_cs.po#L2032)

**G-code**
n/a

**Crash dump file**
n/a

**Picture**
![image](https://user-images.githubusercontent.com/1917365/200692769-bcb57bc1-8209-4659-b41e-9773ac6a48b7.png)

**Comment by Eldenroot** [comment]
Duplication of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2665

**Comment by Prusa-Support** [comment]
This issue will be closed as a duplicate.

Michele Moramarco
Prusa Research
