### ISSUE TITLE
[BUG] Wrong time and progress

### ISSUE THREAD

**Issue by ThomasCZ** [prusa3d/Prusa-Firmware-Buddy#2719]
**Printer type** - [MINI]

**Printer firmware version** - 4.4.0-RC1

**Original or Custom firmware** - Original

**Describe the bug**
Printer did calibration and waiting for reach temperature but time and progress was wrong. I expected zero progress and estimated time. Printer showed that the part will be finished after 5 weeks.

![signal-2022-11-14-165509](https://user-images.githubusercontent.com/7516715/201706129-adfc42ce-040a-480f-ac7c-9d723ef7ec0e.jpeg)

**Comment by Gordontgopher** [comment]
Is it possible that the progress just represented the start code (set temps, bed levelling etc.) within the file that had been completed?

**Comment by ThomasCZ** [comment]
No, it looks like, the displayed progress is counting during heating and leveling and it is reset when printer actually starts printing. For example, printing takes 10 minute and heating 1 minute. When heating is completed, the printer shows 10% progress.

**Comment by reedy** [comment]
Similar to #1067 (amusingly filed similar time of year, with a similar completion date)
