### ISSUE TITLE
[BUG] Printer shows wrong print end time

### ISSUE THREAD

**Issue by TheSithCat** [prusa3d/Prusa-Firmware-Buddy#2795]
**Printer type** - [MINI+]

**Printer firmware version** - 4.4.0

**Original or Custom firmware** - Original 

**Describe the bug**
  Printer show wrong print end time, around hour less. Prusa Link shows correct end time

![printer_time](https://user-images.githubusercontent.com/119744745/205450752-c6bb5934-3b37-41ac-9450-ba44fa10fb2d.jpg)
![prusaLink_time](https://user-images.githubusercontent.com/119744745/205450759-1d4267a7-9157-4bc5-8755-18f7cd0b9ba7.jpg)

**Comment by TheSithCat** [comment]
![TimePrusaLink](https://user-images.githubusercontent.com/119744745/205488836-e9d123d0-5aea-4bc4-9450-4cf39c924ccc.jpg)

**Comment by TheSithCat** [comment]
#136

**Comment by vanboom** [comment]
SUGGESTION:  remove the print ending time and restore the "Time Remaining" metric.  99% of the time I look to the screen to see how much time is remaining and that metric is now gone.
