### ISSUE TITLE
[ENHANCEMENT] Choose date format

### ISSUE THREAD

**Issue by TheSithCat** [prusa3d/Prusa-Firmware-Buddy#2796]
**Printer type** - Mini+

**Describe the expected functionality**
  It would be nice that user would choose date format. Because, honestly, MM-DD is not good and confusing. 

![time_format](https://user-images.githubusercontent.com/119744745/205450902-149c0b2b-686b-4d61-8f96-fec7d586f3d2.jpg)

**Comment by Prusa-Support** [comment]
Thank you for your suggestion.
Our developers will look into this.

Michele Moramarco
Prusa Reseearch
