### ISSUE TITLE
Printing “completes” early, leaving hotend stopped in place at printing temperature in the middle of the print

### ISSUE THREAD

**Issue by laposheureux** [prusa3d/Prusa-Firmware-Buddy#282]
I’m using gcode generated with PrusaSlicer that has successfully printed multiple times while running on 4.0.0 and 4.0.1, but it seems to fail on 4.0.3 (my first test today) and 4.0.4 (updated to this after the first failure) in a dangerous way.

The initial print time shows an expected 5-and-change hour print (both expected and correct from past prints), and two attempts today have “finished” after around 4 hours and 3.5 hours as if complete, but with the bed and hotend still hot. The screen shows a full progress bar, the reprint button available, and an elapsed time that doesn’t match how long the print should have taken.

It appears that without intervention the printer will stay at full printing temperature indefinitely. I will attach the gcode soon.

**Comment by laposheureux** [comment]
![523CE1A6-4554-4593-86C6-E33138E44468](https://user-images.githubusercontent.com/13631960/76157809-11199580-60c3-11ea-9ea0-6f6ec6b5c22c.jpeg)

Here is a photo showing the “end state” of the first print, completed before it should have with the hot end sitting at 210.

**Comment by laposheureux** [comment]
Other observation: even after I told it to go to cooldown and went back to home, after it finished cooling down it left the hotend fan on. I just came back to it hours later and noticed it was still blowing full speed. Here is the gcode that has had these failures: https://www.dropbox.com/s/5tsq0kj0qvuunxo/Edge%20Main%20Pose.gcode?dl=0

**Comment by frankincell** [comment]
I had this occur with a corrupt gcode file.  I had printed the same item a few times from that gcode file and then suddenly it would stop at 75% done and just sit there cooking.   I tried copying the gcode file onto the USB drive again but it did the same thing.  Then I deleted the gcode file, copied a picture to the USB drive, and copied the gcode to the USB again.  From then on it would print perfectly.  Either there's a bad memory spot on the USB drive, or the gcode file became corrupt and copying it over again in Windows didn't fix the corruption.   Give it a try and let us know if it fixed your problem as well.

**Comment by JohnnyDeer** [comment]
Hi @laposheureux , can you please upload Gcode you mentioned? Did this happen with more gcodes, or just with this one? Did you tried it out on 4.0.5?

**Comment by laposheureux** [comment]
It was just the one and the gcode is linked above in a Dropbox shared link. I haven't retried it with the latest firmware yet.

**Comment by JohnnyDeer** [comment]
@laposheureux thank you for info. Unfortunately i can't reproduce it. Please try it with 4.1.0-RC1.

**Comment by JohnnyDeer** [comment]
@laposheureux do you still have this problem with FW 4.1.0?

**Comment by precision** [comment]
I'm not 100% sure, but I think I am seeing the same thing via USB printing on 4.2.1.

Twice since upgrading to 4.2.1 I've printed a GCODE file it stopped mid-print with motors still active and heaters heating.  Cancel the print and send it again and it works fine.

I saved a crash dump the last time it happened via the LCD if that would be of any help.

**Comment by JohnnyDeer** [comment]
@laposheureux is this issue still actual?

**Comment by JohnnyDeer** [comment]
This issue will be closed soon for no responses.
