### ISSUE TITLE
[Bug] Prusa Link displays incorrect gcode being printed

### ISSUE THREAD

**Issue by fabKalix** [prusa3d/Prusa-Firmware-Buddy#2823]
**Issue description**
When uploading a new gcode file during a print, the title of the project being printed changes to the last file uploaded.

**Printer type** - Mini+

**Printer firmware version** - [4.4.0] upgraded both bootloader and firmware.

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint** Prusalink/USB

**Connection** - The upload is done over ethernet

**Steps to reproduce:**
- Start printer and load filament
- Open Prusa Link, check the box "Start  printing after transfer"
- Drag a file to the dashed area and wait for the printer to start its job
- Note the current file in progress is the one just uploaded, as expected.
- During the print upload another gcode file with a different name
- Note the current file in progress is the one just uploaded, which actually is not, because we where already printing...

**Comment by Prusa-Support** [comment]
Thanks for reporting.

This is a duplicate of issue https://github.com/prusa3d/Prusa-Link-Web/issues/268, but I can't tell if the issue is on the Buddy firmware or the Prusa Link side. I'd keep both issues opened for now.

Michele Moramarco
Prusa Research
