### ISSUE TITLE
[ENHANCEMENT] TZ UTC Time in 0.5 increments

### ISSUE THREAD

**Issue by seifer69er** [prusa3d/Prusa-Firmware-Buddy#2847]
WIth the addition of the new wifi support and ethernet support for Prusa Mini+

It would be best to have 0.5hr increments opposed to 1hr increments.
see prusa help below
https://help.prusa3d.com/article/ntp-server-mini_151132

With an active internet connection, my prints are predicted to finish either 0.5 hr early or later due to this feature

**Comment by Gabriel-06** [comment]
This is a duplicate of my issue #1779 from ages ago. Still hasn't been fixed unfortunately :/

**Comment by Prusa-Support** [comment]
Please allow me to close this issue as a duplicate.

Michele Moramarco
Prusa Research
