### ISSUE TITLE
[ENHANCEMENT] Display material, print time, weight and length of filament in PrusaLink web interface

### ISSUE THREAD

**Issue by TojikCZ** [prusa3d/Prusa-Firmware-Buddy#2878]
![image](https://user-images.githubusercontent.com/5272796/210528881-a1dfea61-8c77-40ca-9eca-ffc7b407aecd.png)
Display the gcode metadata from the gcode file on the web interface.
Moved from here: https://github.com/prusa3d/Prusa-Link/issues/612

**Comment by Prusa-Support** [comment]
Possibly related to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2334.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
Prusa Connect is up and running! 🎉 
With the new firmware now available in alpha version (potentially unstable), the printer Prusa MINI is enabled on Prusa Connect too.

Prusa Connect, at the current non-final stage, already includes this and more data from the printer and the print files.
Prusa Link, as of now, is expected to remain the most basic possible interface, as it is hosted on the printer's board, and it acts as a bridge between the printer and Prusa Connect.

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/103262060/0548da57-1b4c-42f0-b768-f6f6e46e7822)

Please allow me to close this issue as solved but feel free to share feedback below.

Michele Moramarco
Prusa Research

**Comment by jhaand** [comment]
Prusa Connect is not a solution for locally monitored Prusa printers.
