### ISSUE TITLE
[BUG] Password (asked?) message when changing filament because of bad translation.

### ISSUE THREAD

**Issue by 4sStylZ** [prusa3d/Prusa-Firmware-Buddy#2883]
**Printer type** - Mini +
**Printer firmware version** -  mini_release_boot_update_pre_4.4_4.4.0+4180.bbf

**MMU upgrade** - no
**MMU upgrade firmware version** - no

**SD card or USB/Octoprint**
SD card only

**Describe the bug**
Note that this was working well just before my firmware update. But since I use a new gcode, I can't only follow this path : 
**On every filament change**, I get a message that completly block the printer : « Mot de passe » which is the french word for « Password ». 
  
**To Reproduce**
I get it on every filament change.
  
**Expected behavior**
 When loading the new filament, I don't want this message to appear.
  
**G-code**
[Top key cover Bicolore PLA ASA_0.15mm_ASA_MINI_31m gcode.txt](https://github.com/prusa3d/Prusa-Firmware/files/10341292/Top.key.cover.Bicolore.PLA.ASA_0.15mm_ASA_MINI_31m.gcode.txt)

**Image**
![image](https://user-images.githubusercontent.com/7487411/210481291-d49d65e7-4cf8-4940-9941-f50aa466cc0a.png)

**Issue origin**

[French Buddy translation line 991](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/src/lang/po/fr/Prusa-Firmware-Buddy_fr.po) is completly wrong.

The new filament change procedure was in fact asking to unload the filament from the sensor but it was completly new to me and the message was perceived like « Please give me a password ». 

It's only a wrong translation, but trust me, I got crazy about it !

![image](https://user-images.githubusercontent.com/7487411/210565569-f95dac58-0aea-466a-9f15-49e561b0eb71.png)

**Comment by Prusa-Support** [comment]
Hello, thank you for reporting this, reported it to the competent department, we'll fix it as soon as possible. 🙂 

Alessandro Pantaleo
Prusa Research

**Comment by Prusa-Support** [comment]
This issue seems to be fixed after the merge of MINI's firmware with the newer MK4/XL version.
However, a confirmation would be appreciated.

Michele Moramarco
Prusa Research

**Comment by michalrudolf** [comment]
The issue is fixed.
