### ISSUE TITLE
Firmware uses Junction Deviation / PrusaSlicer uses Jerk

### ISSUE THREAD

**Issue by dahuafschmied** [prusa3d/Prusa-Firmware-Buddy#292]
Prusa Mini Firmware (4.0.2 - 4.0.4) uses Junction Deviation
shown with M503
```
...
Recv: echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
Recv: echo:  M205 B20000.00 S0.00 T0.00 J0.02
...
```

But PrusaSlicer uses Jerk settings:
`M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
`

the values from slicer are ignored by the firmware.

**Comment by XPila** [comment]
This is fixed in 4.1.0-RC1, M503 now reports following lines:
echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 B20000.00 S0.00 T0.00 X8.00 Y8.00 Z2.00 E10.00
