### ISSUE TITLE
[FEATURE REQUEST] rfc2217 serial over lan support

### ISSUE THREAD

**Issue by redPanther** [prusa3d/Prusa-Firmware-Buddy#2946]
**Printer type** - [MINI]

**Is your feature request related to an existing problem? Please describe.**
If I want to use external printing software like octoprint, but the system that runs octoprint is not near the printer or did not have hardware access to usbserial (like running octoprint on a synology nas/DSM7) via docke). Octoprint did not support serial over lan from the start, a plugin is needed (https://github.com/hellerbarde/OctoPrint-Network-Printing).
I can add a pi or similar near the printer and let the pi do the lan->serial thingy (https://github.com/OutsourcedGuru/Octo-Redirect/tree/master/Zero), but in my opinion it is a bit silly because the prusa mini could do this ... and pi's are kind of hard to get these days.
Would be very nice if the firmware supports the rfc2217 standard. 
 
**Describe the expected functionality**
option in prusa firmware to enable "rfc2217 serial over lan". If turned on a rfc2217 server is started. Example implementation for the server: https://github.com/OutsourcedGuru/Octo-Redirect/tree/master/Zero

**Comment by Prusa-Support** [comment]
Thank you for your suggestion.
Our developers will take it into consideration for future developments.

As of now, our developers a truly busy with further developments of Prusa Link, to further improve it, and for compatibility with Prusa Connect in the near future.
Hopefully one day Prusa Link and Prusa Connect will be beneficial to you too, as a possibly better alternative to Octoprint, offering an advanced suite of tools for remote control over your Prusa printers. 🙂 
If interested, Prusa Link, with basic functionalities, is already available for network connection via ESP Wi-Fi module or Ethernet cable.

Michele Moramarco
Prusa Research
