### ISSUE TITLE
[ENHANCEMENT] Prompt to change sheet profile when changing filament

### ISSUE THREAD

**Issue by JosephMarinier** [prusa3d/Prusa-Firmware-Buddy#2951]
**Printer type** - MINI

#### Is your suggested improvement related to an existing problem? Please describe.
I keep forgetting to go change the sheet profile in the Settings menu after changing filament and sheet. I usually change the sheet (physically) while waiting for the filament change wizard/procedure, but the menu for changing the sheet profile is not accessible during that time, and then I forget. This is dangerous as the difference in thickness might lead to my nozzle crashing on the thicker sheet.

#### Describe the expected functionality
A prompt offering you to change the sheet profile at the end of the filament change wizard/procedure would guarantee you don't forget about it and would avoid damage to the sheets.

**Comment by Eldenroot** [comment]
Great idea!

**Comment by mix579** [comment]
I'm not sure I follow. Usually changing filament doesn't require changing sheet profiles, only if you change, well, sheets. I understand that some people may use sheet profiles to adjust for minute differences between say PLA and PETG but a "feature" like this would be a nuisance for the rest of us who are only changing sheet profiles when swapping out sheets and don't want to be pestered every time we swap filaments.

**Comment by JosephMarinier** [comment]
Good question! Thank you for your input. I am talking about swapping sheets (physically).

For example, I could be printing ABS on the textured PEI powder-coated sheet with the `[Textur1]` profile, and then change filament to print PLA on the smooth double-sided PEI sheet. The latter being much thicker, I absolutely need to change the sheet profile to `[Smooth1]`, otherwise the nozzle will crash on the sheet and damage it. For me, that risk outweighs the nuisance of being asked when it's not necessary.

This feature could go one step further by offering you to change the sheet profile only if the new filament is a different material than the filament that was there before. If it's the same material, we can assume we keep the same sheet.

I understand we all have different use cases, so we can imagine a setting like
`Prompt to change sheet profile along with filament`
1. `Never`
2. `When changing material`
3. `Always`

Do you think that makes sense?

**Comment by mix579** [comment]
Makes more sense. Or just switch to satin sheets, and you never have to change steel sheets again 🙂 90% of what I print these days is satin sheets, with the occasional textured sheet to get the special texture.

**Comment by JosephMarinier** [comment]
That is also very tempting. 😉 Thanks again for your input. 👍

**Comment by Prusa-Support** [comment]
Thanks for sharing your idea.

It sounds like a good idea to me. Our developers will make their considerations about it.

For now, I hope the footers will help catch such accidental oversights. It is possible to have the sheet type always displayed on the main info screen.
Also please take your chance to test the Satin sheet if you haven't yet. 🙂 It is a great trade-off between Smooth and Textured sheets but not intended to take their place after all, and I wouldn't be surprised to see more types of sheets in the future.

Michele Moramarco
Prusa Research

**Comment by JosephMarinier** [comment]
Thank you very much for the kind words. 😊 
I did add the sheet type in the footers. It's nice. 👍 The new customizable footers were a very good idea!
Looking forward to hearing from you again!
