### ISSUE TITLE
[BUG] Print will end display error, as unable to set correct UTC offset.

### ISSUE THREAD

**Issue by leon-matthews** [prusa3d/Prusa-Firmware-Buddy#2953]
**Printer type** MINI+

**Printer firmware version** 4.4.1+4194

**Original or Custom firmware** - Original

**Describe the bug**
Firstly, apologies. It's a timezone bug, and they are always the worst!

I'm unable to set my UTC offset in the settings menu. I live in New Zealand, and it's summer here. Our UTC offset is UTC-13:00 right now. I am not able to set that offset as the settings menu stops at UTC-12:00. I'm submitting this as a bug, not a enhancement request, as the 'time to finish' status line, shown while printing, is incorrect and there is no way to correct it.

A list of non-daylight savings hours can be found below, but note that it shows only the valid standard times offsets - you need to add an hour to allow for daylight savings time too: https://en.wikipedia.org/wiki/Time_zone#List_of_UTC_offsets

I'm very impressed with what you've managed to do with this firmware. The whole experience of building and configuring this new printer has been fantastic. Thank you, and warm greetings from the other side of the planet!

**Comment by Prusa-Support** [comment]
Hello @leon-matthews, thank you for the report, passed this on to our devs. As a possible idea for now, would using +11 "resolve" it? I'd expect it to be equivalent. 🙂 

Alessandro Pantaleo
Prusa Research
