### ISSUE TITLE
[ENHANCEMENT] Wifi module fw info

### ISSUE THREAD

**Issue by krupkaj** [prusa3d/Prusa-Firmware-Buddy#2956]
Please, could you add info about WIFI module firmware version into to screen Info -> System Info?

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.

Our developers will look into this.

Michele Moramarco
Prusa Research

**Comment by bkerler** [comment]
I just wrote a PR for this, enjoy :)

**Comment by CZDanol** [comment]
Internal ticket BFW-5075

**Comment by CZDanol** [comment]
Hello, after consultation within the company, we've decided what we will not implement this.
* The ESP FW number is basically an internal number that doesn't have much significance to the user.
* Each printer FW has its own required ESP firmware and it will not work properly with any other.
* In the upcoming release, there will be a different UI element added showing the status of the Wi-Fi module, including the "Wrong version" (or something along those lines) status.
