### ISSUE TITLE
[BUG] Network Interface setting affecting stability

### ISSUE THREAD

**Issue by TheMoen** [prusa3d/Prusa-Firmware-Buddy#2961]
**Printer type** - Prusa Mini+
**Printer firmware version** - 4.1.1 (final)
**Original or Custom firmware** - Original
**Optional upgrades** - Filament runout sensor, Revo micro hotend
**USB drive or USB/Octoprint** - Original USB drive

**Describe the bug**
The printer is connected with RJ45 to a wifi repeater, that is connected to the main router by wifi(this connection is stable).
IP (dhcp) is set by the mac binding, since I have not found a way to set it static.

The printer is unstable whe interface setting i set to "Ethernet"
It is "stable" when the internet setting is set to "wi-fi"
when interface setting is set to off it is "stable" but it blocks web interface logon

An other issue: 
No matter the interface setting it will not successfully ping from windows 10 or 11.

**How to reproduce**
 Log the pinging response when the printer interface is set to "ethernet, and log ping response when internet is set to wi-fi

**Expected behavior**
Stable connection  when interface = Ethernet
No connection when interface = wi-fi
No connection when interface = Off

Log from home assistant. I used first layer calibration as a marker for changed interface setting.
pings every 5 second and timeout = 500ms
![Prusa Mini interface setting](https://user-images.githubusercontent.com/116985865/215320612-4d18f31c-24b3-435a-838c-5b1469afbe15.png)

**Comment by Prusa-Support** [comment]
Thanks for reporting.

Your test is stability test is surely interesting.
Our developers will look into this.

Unfortunately, the connection modality doesn't work exactly as expected at the moment, regardless of the fact that you are connected to a Wi-Fi repeater via Ethernet, or directly to the router either way.
I'm talking about the fact that regardless of Ethernet, Wi-Fi, or OFF mode, the printer will attempt a connection resulting in mixed functionality.

Michele Moramarco
Prusa Research
