### ISSUE TITLE
[BUG] Wifi is utterly unstable

### ISSUE THREAD

**Issue by rusty-labs** [prusa3d/Prusa-Firmware-Buddy#2987]
**Printer type** - Prusa mini

**Printer firmware version** - [4.4.1]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**Describe the bug**
90% of the time I'm unable to upload gcode by wifi with PrusaSlicer.
After a few percent of progress I get 
![image](https://user-images.githubusercontent.com/18264094/218347395-1e44759c-6727-4eb3-9b4b-c1f4152bb969.png)
Also I'm able to open prusa link front page, but it shows N/A to everything
![image](https://user-images.githubusercontent.com/18264094/218347798-d48660b1-5f0b-4767-93a0-930bf2073037.png)

I've to mention that If I print anything from USB flash drive then I have a much higher chance to print via WiFi afterwards, and prusalink webpage starts to show valid status

Connection to wifi module is 59dBm.

**How to reproduce**
  Send a gcode to a printer by Wifi

**Comment by swalberg** [comment]
I get the same error uploading from Prusa Slicer, though I've only tried maybe 5 times and haven't seen it work. After I've tried that and it fails, the web interface is broken the same way as in the original ticket.

However, if I start the printer up and connect to the web interface, everything works as expected. I can log in, upload files, and print.

So, this works:
* Power on printer
* Log in to web interface
* Upload file
* print

This doesn't work:
* Send gcode to printer from Prusa Slicer 2.5.0+MacOS-64 by wifi
* Watch it fail (not immediately, it'll upload for a bit)
* Try to go to the web interface, see that I get the same thing as the original ticket

**Comment by plandevida** [comment]
Hi,

I am having the same issues, I cannot send GCODES from PrusaSlicer, I got errors all the time.

The most common error is 408 (Time out), I manage to print 1 from 15 tries.

On the other hand, upload to print is very slow, when the file is uploaded on the USB already the printer takes around 1-2 minutes to start printing.

The WIF connection is also appearing and disappearing all the time, but the set up and the test connection from PrusaSlicer is always good and flawless.

**Comment by Pog3k** [comment]
Same here.
After reataching the USB Sticks it works. 
Hope this hint may help.

**Comment by Prusa-Support** [comment]
Thanks for reporting.

We may be looking at yet another sporadic (or too generic) connection failure like the ones reported in issues https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2686, https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2772, https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2898. 

I may be missing something but I couldn't find the steps to controllably reproduce the problem.
Our developers and collaborators need to reproduce the specific problematic scenario to be able to analyze it.

This issue will be closed as a duplicate.
You can take part in the ongoing discussions on the aforementioned issues.

Michele Moramarco
Prusa Research
