### ISSUE TITLE
[FEATURE REQUEST]  Able to select 3x3 or 7x7 mesh bed leveling inside the slicer menu

### ISSUE THREAD

**Issue by robomaniac** [prusa3d/Prusa-Firmware-Buddy#3008]
**Printer type** - [ALL]

**Describe the expected functionality**
I would like to have inside prusa slicer a option to select between 3x3 or 7x7 mesh bed leveling.
<img width="512" alt="mesh3x3x7x7" src="https://user-images.githubusercontent.com/5814871/221372600-faffcbe3-4516-4e06-b55e-54b31cb5b31b.png">

I printed a part in a other region of my print bed and notice that I did not have proper layer adhesion. I was suggested to try the 7x7 which did solve that problem. Very consistent.

The only drawback is that it take so much time. 
7x7 takes ~**1min12sec** of leveling
3x3 takes ~8sec of leveling

I would use that feature if I know that I want to print high quality parts or have bed adhesion problems.

![332506740_225138816586677_7246529677977942135_n](https://user-images.githubusercontent.com/5814871/221372132-70db5a2f-5b9a-4dcf-8c18-59e5838df976.jpg)

For now, after a recommendation from a Prusa forum user, I added this in my prusa start gcode
`G80 N7 ; perform 7x7 bed mesh leveling`

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.
It sounds like a feature request for Prusa Slicer though (wrong repository).

Yeah, the code `G80` allows you to customize a few parameters. The user can save a printer profile in Prusa Slicer including a custom `G80` string.
However, please notice that this code is not suitable to be used on Buddy-based firmware, but on RAMBo-based firmware. This repository is for Buddy-based firmware only.

Also careful when probing near the magnets as they influence the probing. For this reason, the Mesh Bed Levelling settings on RAMBo firmware include a '_magnets compensation_' parameter which should used together with the 7x7 grid.
https://help.prusa3d.com/article/mesh-bed-leveling_112163 

I'll close this issue as invalid now.
Please open the issue in the relevant repository [prusa3d/PrusaSlicer](https://github.com/prusa3d/PrusaSlicer).

Michele Moramarco
Prusa Research
