### ISSUE TITLE
[ENHANCEMENT] Add Clean Nozzle Command

### ISSUE THREAD

**Issue by 1John419** [prusa3d/Prusa-Firmware-Buddy#3019]
Please consider adding a new menu function to facilitate nozzle cleaning.  I would envision something like this:

* The hot end would park near the z-axis (x-max), at a reasonable height (say 100-150mm)
* A material selection menu would be presented
* The nozzle is heated to the appropriate temperature based on selected material
* The command pauses to allow cleaning
* An Exit and/or Cooldown option is available.

I can, of course, accomplish this outcome using several existing commands. This would simply be a convenience which might encourage more frequent nozzle cleaning.

**Comment by Prusa-Support** [comment]
Sounds good. Thanks for your suggestion.

This issue partially duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1795 but is more specific about commands useful for the nozzle's care.
It will stay open as inspiration for future developments.

Michele Moramarco
Prusa Research
