### ISSUE TITLE
Hotend Fan

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware-Buddy#303]
can someone please explain to me where you limited the hot end fan. the fan only runs at approx. 75%, which is probably sufficient for your mini with your delta fan, but I have rebuilt an MK3 with your buddy board, and I can't find the setting for it anywhere. can anyone help me

**Comment by Lino77** [comment]
gefunden

**Comment by PeterDHabermehl** [comment]
> can someone please explain to me where you limited the hot end fan. the fan only runs at approx. 75%, which is probably sufficient for your mini with your delta fan, but I have rebuilt an MK3 with your buddy board, and I can't find the setting for it anywhere. can anyone help me

I've got the same issue, could you share your wisdom, please?
