### ISSUE TITLE
[BUG] When I restart printer, filament sensor turns off

### ISSUE THREAD

**Issue by vinhor** [prusa3d/Prusa-Firmware-Buddy#3038]
**Printer type** - [MINI]

**Printer firmware version** - [4.4.1]

**Original or Custom firmware** - [Custom]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
 I print via USB flash drive

**Describe the bug**
  When I restart 3D printer, filament senzor always turns off.

**Expected behavior**
  I expected the filament sensor to be on even after I restarted the printer.

**Comment by maciejbaur** [comment]
Similar to my case
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3030
