### ISSUE TITLE
[BUG] Sending file to MK4 produces error 404

### ISSUE THREAD

**Issue by reiuwu** [prusa3d/Prusa-Firmware-Buddy#3062]
**Printer type** - MK4

**Printer firmware version** - 4.5.4

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint**
USB

**Describe the bug**
  Selecting "Upload and Print GCode" from PrusaSlicer 2.5.2 generates a 404 file not found dialog in PrusaSlicer, however the print starts correctly. 

**How to reproduce**
  Have the printer on the main home menu. Slice a file in PrusaSlicer 2.5.2. Click Send To Printer, Click Upload and Print. Wait for the file to upload. The printer will start printing the file. PrusaSlicer will report 404 File Not Found

**Expected behavior**
  PrusaSlicer should show the file was successfully uploaded and print started. 

**G-code**
 N/A

**Crash dump file**
  N/A

**Video**
N/A

**Comment by misc2012-DE** [comment]
I got the same problem, prusa slicer reports an error, print starts and ends flawless.

**Comment by BootsSiR** [comment]
I see this on the latest 2.6 alpha as well

**Comment by Hovedskou** [comment]
Same problem here.
I had no problems on my MK3 but it shows only up on the MK4.

**Comment by greggjaskiewicz** [comment]
same, super annoying.

**Comment by semich** [comment]
Me too - same. 
Each time I try to print from the prusa slicer, to prusa link I now get: PrusaSlicer encountered an error: Error uploading to print host: HTTP 404: 404: Not Found.

It was working fine. I rebooted my PC and the printer, same issue.

Although I see the error, the print start normally on the printer.

**Comment by M4rc3lv** [comment]
Me too - same.
Each time I try to print from the prusa slicer, to prusa link I now get: PrusaSlicer encountered an error: Error uploading to print host: HTTP 404: 404: Not Found. After that the print normally starts.

**Comment by csharpe** [comment]
+1 on this issue for me as well.
