### ISSUE TITLE
Repo description discrepency

### ISSUE THREAD

**Issue by reedy** [prusa3d/Prusa-Firmware-Buddy#3063]
![Screenshot 2023-04-28 at 17 30 43](https://user-images.githubusercontent.com/67615/235203280-c0c4ab57-d09e-4a9b-8a77-78585242f747.png)

Is this supposed to say

> Firmware for the Original Prusa MINI, Original Prusa XL and the Original Prusa MK4 3D printers by Prusa Research.

Rather than "Original Prusa XL" twice?

Also, I guess the start of https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/README.md probably wants updating to include "Original Prusa MK4" too...

**Comment by reedy** [comment]
> Also, I guess the start of https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/README.md probably wants updating to include "Original Prusa MK4" too...

Looks like https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/3055 takes care of that...

**Comment by Prusa-Support** [comment]
I think you are right. 🙂 
Thanks for pointing that out.

I suggest keeping the issue open until the text will be updated.

Michele Moramarco
Prusa Research

**Comment by reedy** [comment]
Current text reads

> Firmware for the Original Prusa MINI, Original Prusa MK4 and the Original Prusa XL 3D printers by Prusa Research.
