### ISSUE TITLE
[BUG] Bootloop on update MK4

### ISSUE THREAD

**Issue by jokohoko** [prusa3d/Prusa-Firmware-Buddy#3064]
**Printer type** - [MK4]

**Printer firmware version** - [4.6.0 to 4.6.1]

**Original or Custom firmware** - [Original]

**USB drive or USB/Octoprint**
 USB drive (the provided one)

**Describe the bug**
Once the update was installed the printer resets and got stuck in a bootloop for a while. Always resetting when the orange line was in the middle of the bar (between original and prusa) where it normally beeps and continues.
After a dozen restarts i tried resolving it by turning the machine on and off. This did not help at first. Then i removed the usb stick and restarted and that did help. The screen showed searching for ... board (forgot already, was it buddy...). After a while it did install that as well and then did start back up as normal.

Not sure what the issues was and if i could replicate it? Let me know if i can do anything to pinpoint the reason or if a whole bunch of reboots are normal. 

**How to reproduce**
  No clue

**Expected behavior**
  Maby rebooting once or twice, but this this often in a row

**Crash dump file**
  Attached, the issue was 10min before the dump is made. 
[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/11358909/dump.zip)

**Video**
  Did not think of this when it happened.

**Comment by Prusa-Support** [comment]
Hello, thank you for the report. This is a known issue, it might happen during FW updating - typically, turning off the PSU and on again would resolve it, but I see here it wasn't resolved the first time, we'll keep in mind this point - the reset button wouldn't work to resolve it. 

I'd expect things to be normal from here, but let's keep an eye on this in case more issues might occur. 

Alessandro Pantaleo
Prusa Research
