### ISSUE TITLE
[BUG] MK4 Nozzle Temperature only goes to 290C

### ISSUE THREAD

**Issue by dp250f** [prusa3d/Prusa-Firmware-Buddy#3076]
**Printer type** - [MK4]

**Printer firmware version** - [4.6.2]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Copper/Hardened Steel tip Nozzle with Nextruder V6 Nozzle adapter]

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/PrusaLink

**Describe the bug**
  Printer specs state "Max nozzle temperature 300°C" but it only goes to 290°C

**How to reproduce**
  Try to set nozzle temperature to 300 - it stops at 290

**Expected behavior**
  Nozzle temperature goes up to 300

**G-code**
  N/A

**Crash dump file**
  N/A

**Video**
  N/A

**Comment by dp250f** [comment]
Still the same in 5.0.0-alpha1

**Comment by dp250f** [comment]
Still not fixed in 5.0.0-alpha2

**Comment by dp250f** [comment]
Still a problem in 5.0.0-alpha3

**Comment by dp250f** [comment]
Still a problem in 5.0.0-alpha4

**Comment by dp250f** [comment]
Still a problem in 5.0.0-RC

**Comment by girak49** [comment]
The [specs](https://www.prusa3d.com/product/original-prusa-mk4-2/#specs) now state the max nozzle temp is 290C.
Anyone know why we lost 10 degrees?
