### ISSUE TITLE
[BUG] Printer responds strangely to G-code when paused

### ISSUE THREAD

**Issue by kozross** [prusa3d/Prusa-Firmware-Buddy#3085]
**Printer type** - MINI

**Printer firmware version** - 4.4.1

**Original or Custom firmware** - Original

**Optional upgrades** - 

**USB drive or USB/Octoprint**

USB drive

**Describe the bug**

In an attempt to resolve [the issues described in this other bug](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3084), I attempted to issue the Mini G-codes via a serial line while it was paused. I noticed that this behaved strangely:

1. `M600` would park the toolhead for a change, but not eject the filament.
2. `M104` and `M109` would not work at all.

This seems very odd to me, especially point 1: I can understand all G-codes being ignored, but only partial compliance seems like an odd choice.

**How to reproduce**

1. Start any print.
2. Pause it.
3. Try issuing any of the G-codes listed above via serial.
4. Note what happens.

**Expected behavior**

G-codes should either be honoured in their entirety, or disregarded completely. Also, some documentation of this behaviour should exist.

**G-code**

Not applicable.

**Crash dump file**

Not applicable.

**Video**

None taken.

**Comment by Prusa-Support** [comment]
Thanks for reporting.

I believe this issue is strictly related to the issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3084 indeed, and will probably be solved together at once with it.

Michele Moramarco
Prusa Research
