### ISSUE TITLE
Firmware rollback does not work

### ISSUE THREAD

**Issue by addohm** [prusa3d/Prusa-Firmware-Buddy#3096]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - v5.0.0-alpha1

**Describe the bug**

>  If you want to revert back to stable firmware, please follow the instructions in the handbook. In short: place the stable firmware version on a USB drive, insert it into the printer and during the startup (when the logo is shown), press and hold the knob to force a firmware installation screen. Flash the stable firmware and perform a full factory reset.

This does **NOT** work.

**How to reproduce**
  Just follow your instructions

**Expected behavior**
  Firmware flash

**Comment by neophyl** [comment]
You might want to read https://forum.prusa3d.com/forum/input-shaping/revert-back-to-stable-firmware/  it seems the manual is wrong and it needs a double press.
