### ISSUE TITLE
Repository description (GitHub) seems incorrect

### ISSUE THREAD

**Issue by nmschulte** [prusa3d/Prusa-Firmware-Buddy#3099]
The repository description on GitHub, useful when searching for repositories, seems incorrect; it lists "Original Prusa XL" twice and lacks "Original Prusa MK4".

> Firmware for the Original Prusa MINI, Original Prusa XL and the Original Prusa XL 3D printers by Prusa Research. 

It seems like it should read like:
> Firmware for the Original Prusa MINI, Original Prusa MK4 and the Original Prusa XL 3D printers by Prusa Research.

**Comment by reedy** [comment]
Dupe of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3063; acknowledged in https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3063#issuecomment-1583067091
