### ISSUE TITLE
Filament Sensor NA in web interface

### ISSUE THREAD

**Issue by freshmas** [prusa3d/Prusa-Firmware-Buddy#310]
Testing 4.0.5-RC1 with the web interface. Seems to be working well; however, I noticed the [filament sensor is reporting NA](https://i.imgur.com/rNUCjV3.png).

Tested functionality of the sensor by snipping the filament, and it works as expected.

**Comment by michalxfanta** [comment]
Yes, we know about that. At this version of Prusa Connect Local the data from the filament sensor not propagated to web UI. We will fix it in the final version.

**Comment by danopernis** [comment]
I have just checked this with 6.0.0 firmware and we are not showing filament sensor value in PrusaLink at all. So I guess this is fixed :smile:
