### ISSUE TITLE
Heat only the print area on Prusa XL after the first few layers

### ISSUE THREAD

**Issue by amarilio** [prusa3d/Prusa-Firmware-Buddy#3109]
**Is your feature request related to a problem? Please describe.**
Prusa XL was supposed to save energy by heating only the right bed segments, however it was discovered that this causes some sub-mm distortion on the heat bed that can affect the first layer. Therefore, the neighboring segments are also heated.

**Describe the solution you'd like**
After the first layer (or a few layers above) stop heating the neighboring segments. At this point the small distortion on the print bed would not affect the print

**Describe how it would work**
in the generated gcode, send a custom command to turn off this segments.

**Describe alternatives you've considered**
You could also consider bringing the object back to the middle of the print bed.

**Additional context**
This could save a significant power draw and make the segmented bed more valuable, increasing the differentiation of the XL.

**Comment by Prusa-Support** [comment]
Thanks for your suggestion, however, the part that may deform the most during the print is the sheet, not the bed itself.

Stopping or drastically reducing the power after the first layer may result in print warping or sheet deformations.
The prints generate tension forces on the sheet as the plastic sets down and shrinks so the temperature must be kept reasonably high during the whole print time.

We save power and avoid sheet deformations by heating up the neighboring modular bed tiles only slightly, as little as possible.

Not sure if we can set the temperatures any lower so this suggestion can't be accomplished and the issue will be closed.
Nonetheless, your feedback will be collected and may push the development of further power energy-saving solutions.
Thanks for it.

Michele Moramarco
Prusa Research
