### ISSUE TITLE
[BUG] Tool Light Option Missing

### ISSUE THREAD

**Issue by chrishilbert** [prusa3d/Prusa-Firmware-Buddy#3115]
**Printer type** - XL

**Printer firmware version** - 4.7.0

**Original or Custom firmware** - Original

**Optional upgrades** - Single Tool

**USB drive or USB/Octoprint**
USB

**Describe the bug**
Settings -> User Interface is missing the Tool Light option mentioned in the release notes after upgrade.

**How to reproduce**
 Updated single tool to 4.7.0.  Ran full calibration and restarted printer.

**Expected behavior**
Show Tool Light option as mentioned.

**Comment by Prusa-Support** [comment]
Thanks for repeating.
This seems to be fixed by now.
Please upgrade the firmware and try again, even please try a factory reset if the option is not listed.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
It seems safe to close this issue now.

Michele Moramarco
Prusa Research
