### ISSUE TITLE
[ENHANCEMENT] XL RBG Lights Auto On/Off

### ISSUE THREAD

**Issue by chrishilbert** [prusa3d/Prusa-Firmware-Buddy#3118]
**Printer type** - XL

**Describe the expected functionality**
I would like the RBG light strips to automatically turn on and off.  For example, the print starts and the RBG light strips turn on.  As soon as the print finishes, the lights automatically shut off.  Also would be nice to have a timeout on the lights.  Maybe they shut off at configurable time AFTER the print finishes.

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.

Some sort of customization should be possible in the future.

Michele Moramarco
Prusa Research
