### ISSUE TITLE
[FEATURE REQUEST] Total Print Time When Complete

### ISSUE THREAD

**Issue by tbedore** [prusa3d/Prusa-Firmware-Buddy#3123]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MK4]

**Describe the expected functionality**
 Same way that the MK3s+ would tell you at the end of the print, total print time 3 hrs 26 minutes. Would like to be able to see at the end of the print how long it actually took to print the file

**Comment by gudnimg** [comment]
I agree with this. Maybe it can be added to this screen? There is some space underneath "Print finished" text.

![IMG_3648](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/8218499/11d6e04b-0b72-44de-8e0f-38d036403bfb)

**Comment by murk-sy** [comment]
Duplicate of #3044

**Comment by tbedore** [comment]
as this is a duplicate of #3044 I'll close the ticket :)
