### ISSUE TITLE
[ENHANCEMENT] Printing Time improvements

### ISSUE THREAD

**Issue by inieto** [prusa3d/Prusa-Firmware-Buddy#3126]
**Printer type** - [MINI+]

- "Probing point 1...16/16" could be done while heating the nozzle and bed in parallel. It's sequential actually and it take so many time

- "Probing point 1...16/16" waits the nozzle to cool down to 170ºC. It could actually be done without setting the temperature to 170ºC. Let's imagine the following example:
· First we wait from ambient temperature to 260ºC to load some filament.
· Then we have to wait for cooling down to 170ºC to make the probing point procedure
· After that, we have to wait again to heat up to 260ºC to start printing
We end up waiting 3 heat-cool-heat cycles!

- Loading filament should not wait for bed heating: we only need to wait for the nozzle to heat, not the bed.. This could save us some minutes.

**Proposed Behavior:**
- Start measuring bed leveling with PINDA probe before reaching 170 ºC while heating
- Continue heating the bed while probing with PINDA sensor.
- Start measuring bed leveling with PINDA probe while cooling below 200ºC and FAN at 100% (to prevent oozing)
- Load filament when nozzle hits the filament melting temperature, but not wait for the bed to heat up.
- Avoid probing all 16 points again if there was a previous print not so while ago. Check some points and search for differences (use cache)

**Comment by shledge** [comment]
The problem is that the nozzle and bed expands under heat, so your method will give more inconsistent results. That's why nozzle is at a constant 170C and the bed is heated when levelling.

I reckon retracting the filament slightly before probing would work better in terms of saving time, because it means less time needed to do a nozzle cleaning procedure prior to levelling. The nozzle cleaning could be wiping against the bed rather than going down slowly between each point.

**Comment by neophyl** [comment]
Besides this is all set and controlled by the starting gcode in your Printer Profile in the slicer.  If you don't like the order it does things or want to omit or change temps etc then go and update your profile and get it working the way you want it to.

Shledge is quite correct though on the reasons for it, repeatability of bed levelling, as the sensor is temperature dependant and even though there is some compensation it is limited in effectiveness.
