### ISSUE TITLE
MK4 is DUMB when sending hosted prints

### ISSUE THREAD

**Issue by addohm** [prusa3d/Prusa-Firmware-Buddy#3128]
The UI just sits on the menu screen.  It shows nothing.  The footer is too small to read at a quick glance.  The whole thing where you guys progress fill a thumbnail of the printed part is unnecessary.  I'd personally like to see (regardless of how a job is loaded) the screen replaced with graphing (like what we see in prusalink\prusaconnect) or just bigger text like what we see in the footer, and change the footer to a progress bar.  Theres plenty of options - anything is better then what's there currently.

**Comment by Prusa-Support** [comment]
Thank you for your feedback. The description of the issue and the suggestions are probably too generic though.

A clear list of problems and suggestions, together with reference documentation (pictures, videos, links...) could be of help.

Michele Moramarco
Prusa Research
