### ISSUE TITLE
[BUG] Out of Memory while beeing in idle state

### ISSUE THREAD

**Issue by sturze** [prusa3d/Prusa-Firmware-Buddy#3131]
**Printer type** - MK4

**Printer firmware version** - 5.0 Alpha 3

**Original or Custom firmware** - Original

**Optional upgrades** - none

**USB drive or USB/Octoprint** - USB

**Describe the bug**
Printer started beeping (mid night) and showing Out of Memory while beeing in Idle Mode.

**How to reproduce**
no idea

**Expected behavior**
obviously, not beeping an beeing out of memory while doing nothing XD

**G-code**
no G-code involved

**Crash dump file**
[dump.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/11989759/dump.bin.zip)

#Note: i had this error message before but was still trying to figure out what could have caused it. 
Went to bed yesterday after a successful print and found it beeping/in-error-state today morning... 
I don't know if it's the same thing, but I have no idea how I might reproduce what happened there... 
Printed and left it alone before without an issue several times. Hope this helps to find what's going on in my printers brain.

**Comment by Prusa-Support** [comment]
Thanks for reporting.

The error basically means that the printer's board memory is full and overwhelmed.
Despite being idle, the printer may be running routine refreshing operations, and keep compiling the log.
A simple reboot would free the memory from temporary data and logs, and supposedly solve the problem.

As speculated on https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2351 and other linked issues, the causes of Out of Memory errors (OOM) can vary a lot but the chances of this occurrence may be higher in case of long operating sessions, overlapping inputs, and unstable connections.

As long as the error is not reproducible and only manifests itself on a possibly unstable pre-release of the firmware the issue may not be necessarily relevant.

I wonder if you were able to controllably reproduce the issue, even with stable FW 5.0.0.

Michele Moramarco
Prusa Research
