### ISSUE TITLE
[BUG] Prusa Connect registration fails with v4.7.0 tag

### ISSUE THREAD

**Issue by Cryshedian** [prusa3d/Prusa-Firmware-Buddy#3133]
**Printer type** - XL

**Printer firmware version** - 4.7.0

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint**

USB drive

**Describe the bug**

The "Add printer to Connect" registration option results in a network error with v4.7.0 firmware.  

![thumbnail_IMG_8368](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/8917cd23-b4c3-4b21-9ab8-d7b9ce907283)
![thumbnail_IMG_8369](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/7f064388-510b-4502-9603-6f8e3e5c2e3e)
![thumbnail_IMG_8370](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/6153495d-4ce9-4fa0-96e2-71cbfa9c257d)
![thumbnail_IMG_8371](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/de0816b3-e36f-40f3-9038-ac0b7f3c70ae)

Forum discussion related to this issue:
https://forum.prusa3d.com/forum/introcuctions-instrutctions/new-xl-and-connecting-to-prusa-connect/

**How to reproduce**

I followed the [Adding the printer to Prusa Connect (XL)](https://help.prusa3d.com/guide/adding-the-printer-to-prusa-connect-xl_420001), along with the [Adding the printer to Prusa Connect (MK4)](https://help.prusa3d.com/guide/adding-the-printer-to-prusa-connect-mk4_417586), since the later covered the Printer Code being used with the v4.7.0 firmware.

I am using a wired Ethernet network with a DHCP server on my router.  I have assigned a fixed IP address to my XL based on MAC address.  I have tried specifying both my routers and the public Google DNS (8.8.8.8) as the DNS server, with no difference in behavior.

**Expected behavior**

This menu works correctly in v4.6.1 with the same network settings.  I assume I will see a similar QR code screen with v4.7.0 firmware were it working.

![thumbnail_IMG_8365](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/ab59d746-1fbe-4d4d-b344-fee255dc541f)
![thumbnail_IMG_8366](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/a42c7449-f776-4ee4-b822-ec1a779b9706)
![thumbnail_IMG_8367](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/65690523/974cdf76-a3a2-4e40-b344-e71b25c62941)

**G-code**

N/A

**Crash dump file**

N/A

**Video**

See screenshots above.

**Comment by keyboard-magpie** [comment]
The workaround supplied by tech support at present is to carry out a factory reset, or add the following dummy code to prusa_printer_settings.ini : 
```[service::connect]
hostname = [buddy-a.connect.prusa3d.com](http://buddy-a.connect.prusa3d.com/)
tls = True
port = 443```

**Comment by Prusa-Support** [comment]
Thanks for reporting.

This is a known issue indeed and I seem to understand our developers are close to a solution.
This may be fixed in one of the next few firmware releases.

Michele Moramarco
Prusa Research
