### ISSUE TITLE
[FEATURE REQUEST] Add option to disable forced filament loading on printing

### ISSUE THREAD

**Issue by acorderob** [prusa3d/Prusa-Firmware-Buddy#3136]
**Printer type** - [MK4]

**Is your feature request related to an existing problem? Please describe.**

I always load and unload the filament when i use my printer so each session my printer is not loaded. Right now, when I print, the firmware forces the filament loading procedure or you must disable the filament sensor. If you then load the filament it sends the nozzle temperature to the configured filament temperature, and after loading it starts the gcode and the temperature goes down to some degrees below the plastic temperature, then it levels the bed, heats up again, and starts printing.

**Describe the expected functionality**

What i would like to do is load the filament after bed leveling, just when it is needed, and when the temperature is already the final one. My idea was to add an *M701 W255 S"PLA"* command just before the purge line, but i would need the firmware to not force the filament loading procedure on printing *and* not disable the filament sensor, in case the filament runs out. An option in settings to disable the forced filament detection (without disabling the sensor) would accomplish this.

Also, in my tests with M701 i noticed that, after loading the nozzle, the temperature goes to the predefined preheat temperature of the selected filament type, or starts to cool down if i don't add the S parameter. This can be fixed in the start gcode with another M109 command after M701, but it would be nice if it just kept the current temperature when not choosing a filament type.

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.

Preheating and loading just before the print is not recommended as significant oozing will probably occur. The user will have little time to remove the oozed filament, and yet more filament may ooze and interfere with the start of the print.
However, feel free to experiment around via _start g-code_ in Prusa Slicer and report back.
You can actually report your findings in the [prusa3d/PrusaSlicer](https://github.com/prusa3d/PrusaSlicer) specific repository.

About your ultimate request to disable the filament sensor forced loading without permanently disabling the filament sensor, I believe the codes `M406` and `M405` can be used to disable and reenable the filament sensor as needed.
These codes can be added to the _start g-code_, however, I'm not sure if `M405` and `M406` are actually enabled in the MK4 xBuddy firmware, but they are implemented in the MK3 Eisy firmware and Prusa MK4 is theoretically back-compatible with MK3 gcodes.

I hope this helps and please consider closing this issue if you are satisfied with the answer.

Michele Moramarco
Prusa Research
