### ISSUE TITLE
[FEATURE REQUEST] Time remaining before filament change on MK4

### ISSUE THREAD

**Issue by icepick3000** [prusa3d/Prusa-Firmware-Buddy#3144]
On my MK3s+ it showed the time remaining in the display before I had to change filement (when I selected multiple color layers in prusaslicer). On the MK4 it doesn't show the time remaining. It would be handy if this would be shown again.

**Comment by Prusa-Support** [comment]
Thanks for reporting, however, this issue should be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3107.

Michele Moramarco
Prusa Research
