### ISSUE TITLE
[ENHANCEMENT] <Enter comprehensive title>

### ISSUE THREAD

**Issue by Erech1676** [prusa3d/Prusa-Firmware-Buddy#3146]
When a print finishes the lcd defaults to "print again", I think it would be nice to go to the home screen.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - Mk4

*Eric

**Comment by Prusa-Support** [comment]
Thanks for your suggestion.
Our developers will consider it.

Michele Moramarco
Prusa Research
