### ISSUE TITLE
[BUG] Printer fails to acknowledge that it is printing a model started from the web interface

### ISSUE THREAD

**Issue by neuron-whisperer** [prusa3d/Prusa-Firmware-Buddy#3160]
**Printer type** - MK4 built from kit

**Printer firmware version** - 4.7.0

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint** - USB drive

**Describe the bug**

The MK4 printer appears to have a bug where starting a print (via web interface) causes the model to be delivered to the firmware and printed, but the UI of the printer behaves as if the printer is idle.

I uploaded a model via the web interface and then select Print. The printer immediately started to print the model, but the web interface did not acknowledge the request to print, and the display showed no indication that it is printing anything at any time. Both the printer UI and the web interface remained fully responsive and behaved as if the printer was idle. Upon completion of the print, the printer did not display a "Print Complete" screen.

I presume that this behavior reflects an instance of miscommunication between the UI and the components of the firmware that handle loading and printing a model. The isolated occurrence of this error suggests that it may be a race condition - e.g., the webserver receives the model and delivers it to a print queue, and the firmware takes it out of the print queue and starts printing it before the user interface detects that any model has been enqueued.

**How to reproduce**

Upload a model via the web interface and start printing it. In some circumstances, the UI does not acknowledge that it is printing.

**Expected behavior**

The UI should switch to a printing status screen that shows the model, percent complete, and options like "Tune" and "Pause Print," rather than remaining in the idle main menu.

**G-code** - Not available

**Crash dump file** - Not available (no crash)

**Video** - Not available

**Comment by Prusa-Support** [comment]
Thanks for reporting, however, we have not been able to reproduce this issue and so far it seems there have not been similar reports.

Not sure what went wrong in the first place but we can't confirm the presence of a bug.
Please test again with the most recent firmware version and let us know if you are still able to reproduce the problem. In that case, we would appreciate seeing a video of the problem or possibly getting more precise information to controllably reproduce the problem ourselves.

Michele Moramarco
Prusa Research
