### ISSUE TITLE
[BUG] "Upload was unsuccessful" message after (successful) upload

### ISSUE THREAD

**Issue by neuron-whisperer** [prusa3d/Prusa-Firmware-Buddy#3163]
**Printer type** - MK4 built from kit

**Printer firmware version** - 4.7.0

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint** - USB drive

**Describe the bug**

The web interface shows the message: "Upload was unsuccessful" after uploading a model, even if the model uploaded successfully, appears in the Storage list, and prints fine.

This has happened to me on several occasions, including a moment ago with a small model (6.3 megabytes). The upload completed in a reasonable amount of time, but the web page then showed this message. The Storage tab shows a list of stored files including the newly uploaded file. And selecting it for printing causes the printer to print it without any problems.

**How to reproduce**

Upload a model.

**Expected behavior**

The web interface receives the upload and presents a message of a successful upload. The "Upload was unsuccessful" message should be displayed only if the upload did not succeed.

**G-code** - Attached

**Crash dump file** - None available (no crash)
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video** - None available

[Watch Mount_0.4n_0.2mm_PLA_MK4_7h4m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12152565/Watch.Mount_0.4n_0.2mm_PLA_MK4_7h4m.gcode.zip)

**Comment by blue-hound** [comment]
I had this too on 4.7.0 and PrusaSlicer 2.6.0 but since 4.7.1 (on my replacement printer) it hasn't reoccurred. I didn't get to 4.7.1 on my first printer.
