### ISSUE TITLE
[BUG] XL USB firmware file detection breaks with upper/lower case

### ISSUE THREAD

**Issue by RichiH** [prusa3d/Prusa-Firmware-Buddy#3167]
**Printer type** - [XL]

**Printer firmware version** - 4.7.0 (I upgraded to 4.7.1 from that, but can't test now)

**Original or Custom firmware** - [Original]

**Optional upgrades** - [n/a]

**USB drive or USB/Octoprint** - USB

**Describe the bug**
On a factory new XL, I had two firmware files:
* `xl_firmware_4.7.0.bbf` -- by factory, note the lower case "xl"
* `XL_firmware_4.7.1.bbf `-- unzipped from official download, note the upper case "XL"

Upgrading the firmware only upgraded to 4.7.0. Once I deleted `xl_firmware_4.7.0.bbf` and reset the printer, it detected `XL_firmware_4.7.1.bbf` and upgraded again.
While I can't test this again for obvious reasons, I believe that this means the firmware looks for lower case first, and if it finds anything stops looking for upper case.

As an aside, it would be good to have upper/lower case the same across all releases.

CC @pstrobl96

**Comment by Prusa-Support** [comment]
Thanks for reporting, however, we can't reproduce the problem and there haven't been similar reports so far, so we can't confirm the presence of a bug.

As far as I know, the firmware name is not case-sensitive - still, I recommend not renaming it (to be on the safe side).
The printer would normally only automatically launch the firmware upgrading process if a newer firmware .bbf file is detected on the USB flash drive, after a simple reset. I'm not sure what may have gone wrong but it was probably a temporary unspecified problem.

We would like to know if the problem persists with future firmware releases, and possibly get further instructions for a controlled reproducibility of the problem, or evidence (video) of the problem at least.

Michele Moramarco
Prusa Research
