### ISSUE TITLE
Why have been delayed for so long PrusaConnect for the Prusa Mini+?

### ISSUE THREAD

**Issue by DiomedesDominguez** [prusa3d/Prusa-Firmware-Buddy#3176]
Since the Prusa Mini+, MK4 and the XL share the same firmware, I don't understand why have took so long to have PrusaConnect for the Prusa Mini+? At least allow us to use it through a Raspberry Pi or any other USB connected device.

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4379316/7c9ebee7-7065-4e28-b32a-36fdf0594fa5)

**Comment by mix579** [comment]
It's not just PrusaConnect. Looks like there's been zero (visible) work on the Prusa firmware for a LONG time… ☹️

**Comment by Jerzeek** [comment]
it's happening https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.1.0-alpha1
