### ISSUE TITLE
[BUG] XL: "Reprint" on single tool gcode does not use the same extruder

### ISSUE THREAD

**Issue by Skinnedknuckles49** [prusa3d/Prusa-Firmware-Buddy#3178]
**Printer type** - Prusa XL dual head factory assembled

**Printer firmware version** - 4.7.1

**Original or Custom firmware** - Original

**Optional upgrades** - stock dual head printer

**USB drive or USB/Octoprint** - USB drive (Octoprint compatibility is another subject)
  
**Describe the bug**
  Tool 2 was selected and a print completed.  On the LCD, I selected "reprint" to just duplicate the last print and E1 started to heat instead of E2 (E2 was still in the tool carriage) and it went through the full pre-print routine heating E1 but moving E2 through cleaning/heat soak/leveling/"printing" while E2 was apparently at room temperature (I didn't check with IR thermometer. Behavior continued after a hard reset to FW 4.7.1.

**How to reproduce**
  Simplest and quickest - select Tool 2, then start a print with gcode sliced for a single tool printer and then cancel the print.  When offered the option on the LCD select Reprint.  Alternatively, let the print complete then select Reprint.

**Expected behavior**
  Because Tool 2 is selected and in the carriage, I expect tool 2 to heat up as the print sequence begins on Reprint just as it does on the initial print.

**G-code**
  Any gcode sliced for a single tool printer that I've tried has exhibited this behavior.

**Crash dump file**
  No crash.

**Video**
  Don't have a video but can create one if needed.

**Comment by murk-sy** [comment]
For better findability by developers I recommend changing the bug title to
> [BUG] XL: "Reprint" on single tool gcode does not use the same extruder
