### ISSUE TITLE
[BUG] Uploading gcode via PrusaLink does not work (MINI+)

### ISSUE THREAD

**Issue by VladimirVecera** [prusa3d/Prusa-Firmware-Buddy#3180]
File upload via PrusaLink or PrusaSlicer 2.6.0 does not work. The upload ends at a few tens of percent of the upload.

Failure when receiving data from the peer:
Recv failure: Connection was reset [Error 56]

Can you finally start working on firmware fixes for the Mini+? I went to Průš for updates and what is happening really annoys me!

**Comment by TravisWilder** [comment]
I can confirm - first seen 3.8.23
