### ISSUE TITLE
[FEATURE REQUEST]M73 M117

### ISSUE THREAD

**Issue by alanbrooks12** [prusa3d/Prusa-Firmware-Buddy#3184]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MINI]
**Optional upgrades** - [e.g. Filament Runout Sensor]

**Is your feature request related to an existing problem? Please describe.**

**Describe the expected functionality**
  A clear and concise description of expected functionality.

**Comment by Prusa-Support** [comment]
This issue lacks of description and is most likely a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/189.
Please allow me to close it as invalid and probably as a duplicate too.

Michele Moramarco
Prusa Research
