### ISSUE TITLE
[BUG] PrusaLink didn't create a new folder

### ISSUE THREAD

**Issue by justoeu** [prusa3d/Prusa-Firmware-Buddy#3185]
Printer type
MK4

Printer firmware version
4.7.2

SD card or USB/Octoprint
USB CARD

Describe the bug and Reproduce
This Bug is simple to reproduce, Inside the PrusaLink, access the storage click in add new folder, input new name and waiting... This process its not work.
<img width="1717" alt="258952890-857d87fc-aaf3-4876-b459-236e796608f1" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/304801/a90b6c4c-6bcb-4165-9f8f-07c9c9494c44">

**Comment by m-cas** [comment]
possible duplication of #3165 - except that this one is confirming the problem on 4.7.2 as well.
