### ISSUE TITLE
thermal runaway

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware-Buddy#319]
increase the watch temp period, especially with asa or abs i often had the problem that the temperature was not reached. This happens most often in rooms where the room temperature is below 20 degrees

**Comment by x10102** [comment]
Confirmed this happens to me as well.

**Comment by JohnnyDeer** [comment]
Hi, can you please try this issue on 4.1.0-RC1? This version have reworked temperature regulation, it may solve this issue. Thank you.
