### ISSUE TITLE
[BUG] <5.0 RC on Prusa MK4>

### ISSUE THREAD

**Issue by williamrehndell** [prusa3d/Prusa-Firmware-Buddy#3193]
**Printer type** - [MK4 - Kit]

**Printer firmware version** - [5.0 RC]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Stock]

**USB drive or USB/Octoprint**
USB flash drive

**Describe the bug**
 The 3D printer stopped during the print in the middle of the model, no error messages. The printer directed me to a screen when prints are finished. Self-tests of the printer were completed without any issues.

**How to reproduce**
I dont know

**Expected behavior**
The printer should have been able to complete the print without any issues.

**G-code**
Could not upload .zip, please check download link: 
https://file.io/rKCVEn1INwVp

**Crash dump file**
Could not upload .zip, please check download link: 
https://file.io/rKCVEn1INwVp

**Picture**
Could not upload .zip, please check download link: 
https://file.io/rKCVEn1INwVp

**Comment by jindrichbenes** [comment]
It says files are deleted.
Anyway, are you attaching gcode from your desktop or the actual USB drive?
Please attach file from USB drive.

**Comment by stsfin** [comment]
Are you using the prusa provided usb-stick? if so try with another one. those have alot of issues and most of these kinds of problems go away by using something better.

**Comment by DRracer** [comment]
@williamrehndell Please provide the G-code file **copied from the USB flash** drive you used to print.

**Comment by rtyr** [comment]
Thanks. We were able to reproduce it.
