### ISSUE TITLE
Prusa XL tools get stuck sometimes [BUG] <Enter comprehensive title>

### ISSUE THREAD

**Issue by tmhedesign** [prusa3d/Prusa-Firmware-Buddy#3201]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [XL]

**Printer firmware version** - [Latest standart]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint

**Describe the bug**
  Prusa XL tools get stuck sometimes 

**How to reproduce**
  When tool change often it wont stick to the magnest and hang 

**Expected behavior**

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by murk-sy** [comment]
You should contact support - this is unlikely to be a firmware problem unless the issue is actually how error handling works or doesn't work.
