### ISSUE TITLE
[FEATURE REQUEST] Add the Control tab to PrusaLink on the xBuddy platform

### ISSUE THREAD

**Issue by TojikCZ** [prusa3d/Prusa-Firmware-Buddy#3203]
**Printer type** - [MINI, MK4, XL]

**Is your feature request related to an existing problem? Please describe.**
PrusaLink on the Pi has a Control tab allowing users to move the toolhead and pre-heat

**Describe the expected functionality**
Implement the control tab for the xBuddy platform

**Comment by GRIFFCOMMca** [comment]
+1 for this feature, not sure why the PrusaLink in the embedded is so different..

**Comment by jaakkorop** [comment]
Would be nice, after all Prusa does advertise that we can use the printer locally, but the local network interface just lacks a lot of features.

Often I'd like to start the preheat and then come to the printer for monitoring the start of the print. Especially for Core One I'd suspect the enclosure heating for difficult materials might take a while, so this feature becomes even more relevant for users not wanting the cloud connectivity.
