### ISSUE TITLE
[QUESTION] Printer unable to read usb 

### ISSUE THREAD

**Issue by focusfail** [prusa3d/Prusa-Firmware-Buddy#3204]
**Printer:** Prusa MINI+
**FW Version:** 4.3.1 Original

I left my printer dormant for a few months. Now, when I insert a USB drive, the printer detects it but **_doesn't show any files contained on the drive_**.  I don't get any errors or anything. Besides the home button I don't get anything displayed.

I have tried:
- factory reset
- different USBs
- newly formatted to FAT32
- fw update (didn't work because no files get detected)

all to no avail. 
I have seen similar issues on the internet and not found any fix, What do I do?

**Comment by murk-sy** [comment]
This is more likely a question for support, but let's try anyway. Was the printer turned on in this time, and if so, was a USB drive plugged in? Has it worked originally when new?

If you haven't tried it yet, try completely unplugging the printer from power (from the wall) for a minute and then running a factory reset. If the printer was on all along, ram may have been filled by bad garbage collection and just a reset may not clear the ram.

Alternatively, with the printer turned off, try plugging and unplugging a USB drive 10 times in a row. I'm not sure if a USB drive is detected as "plugged in" if data lines aren't connected, so this might not resolve anything.
