### ISSUE TITLE
Add preheat to 170/60°C

### ISSUE THREAD

**Issue by x10102** [prusa3d/Prusa-Firmware-Buddy#321]
What's the point of heating up to 215/60 for PLA if the extruder is going to cool down for bed leveling anyway? Maybe you should add the option to preheat the bed to 60°C and the extruder to 170°C. It's kinda annoying needing to manually set the temperature in settings.

**Comment by michalxfanta** [comment]
We prepare a new workflow for preheating before Mesh Bed Levelling.

**Comment by tangero** [comment]
Planed for 4.1 FW version.
