### ISSUE TITLE
[FEATURE REQUEST] Set Printer as Ready (for Prusa Connect Queues) on the device itself after clearing the build plate

### ISSUE THREAD

**Issue by DIY-Machines** [prusa3d/Prusa-Firmware-Buddy#3217]
Printer: Mk4 and probably the XL also.

It would be very convenient to be able to clear a completed print job of the build sheet and then be able to confirm on the printer itself that the machine is ready to accept and begin the next print job from the Prusa Connect print queue.

**Comment by wizbongre** [comment]
Yep, I'd love that feature too - find myself getting mixed up between print jobs in PrusaConnect and print files on the machine itself.

**Comment by chaos777b** [comment]
dito

**Comment by kibu7** [comment]
That would be a nice feature

**Comment by ammas09** [comment]
I agree, this seems both very useful and logical.  

When I'm at a specific machine it when I am most certain that it is cleared and ready to start printing a new job.  Needing to go to a web page and possibly select the wrong printer seems like a needles hassle and prone to mistakes.

**Comment by drchslrk** [comment]
dito

**Comment by BlackBird11** [comment]
this is possible unter control -> set printer ready
i would still recommend the printer gives me the option right after a print finished instead of "reprint, home etc." .. just add "printer ready" exactly there after a print is finished! thanks
