### ISSUE TITLE
[QUESTION] M555 documentation (Mk4)

### ISSUE THREAD

**Issue by seppelicous** [prusa3d/Prusa-Firmware-Buddy#3218]
I am missing a documentation for the M555 code.
Is X and Y the center point and H and W the spread in each X/Y direction of the probing area?

Are there also other variables to also use a round probing area? It seems, that M557 is discontinued on MK4s.

Thank you!

**Comment by bkerler** [comment]
According to [here](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/15d5ae0b317a37b69b8e7a4720711b962c25b57d/lib/Marlin/Marlin/src/gcode/feature/print_area/M555.cpp#L31-L46) it spans a bounding rectangle from x to y with w being the width and h being the height.

There are currently no variables that use a round probing area.
