### ISSUE TITLE
Crashes when purging nozzle

### ISSUE THREAD

**Issue by kdpainter** [prusa3d/Prusa-Firmware-Buddy#322]
v4.0.4 crashes very repeatably at 95% when purging nozzle.  Have to reset to recover.

**Comment by thejobbitt** [comment]
Also having this issue. It also happens in 4.0.5 RC1.

**Comment by dahuafschmied** [comment]
I reportet this issue long time ago to Chat Support.

**Comment by Vic-Y** [comment]
I have encountered this when purging after manually stopping a print (two times). When I ran purge after a reset (using display button), the purge completed successfully.

**Comment by bobc** [comment]
Also happens in 4.0.5 final.

**Comment by bildzeitung** [comment]
I’ve also observed this behaviour.

**Comment by JohnnyDeer** [comment]
Hi, this issue is solved on 4.1.0-RC1. Please try it out :)

**Comment by derenma** [comment]
Tested and LGTM!

(The flashing green cool down to 170/215C after leaving the purge menu confused me at first, but that is a really neat feature.)

**Comment by JohnnyDeer** [comment]
Great, then i'm closing this issue as solved.
