### ISSUE TITLE
[BUG] - no more than 5 multiple virtual extruders - blue screen on MK4

### ISSUE THREAD

**Issue by sebowim-cmd** [prusa3d/Prusa-Firmware-Buddy#3222]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - 5.0.0-RC

**Original or Custom firmware** - Original

**Optional upgrades** - none

**USB drive or USB/Octoprint** - USB flash drive

**Describe the bug**

For convenient retraction testing, you can setup virtual extruders in PrusaSlicer2.6 to print many different parts with differentiation in retraction values.

In theory you can create lots of extruders, for your special use-case, but when you use more than 5 - the printer restarts when loading the gcode and a blue-screen appears. 

I just started to use this technique, so I can only try it on the MK4 where for now 5 virtual extruders are the maximum - I guess it has something to do with the mmu supporting 5 „extruders“ but when you search for this technique on the web you can find, that in the past people used it with up to 9 (and maybe more) extruders

https://github.com/magicdroping/How-to-PrusaSlicer-Sequential-printing-with-different-profiles/issues/1

https://www.printables.com/model/378291-retraction-tuning-with-prusaslicer

**How to reproduce**

create more than 5 extruders in your printer profile and assign atleast 5 models a different extruder, check subsequent printing, uncheck wipe-tower

**Expected behavior**

it works with 5 extruders, but not with more, which woule be nice for multiple testing of settings on multiple parts

**G-code**
  
in same zip as crash dump

**Crash dump file**
 
[crash_dump_and_gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12431294/crash_dump_and_gcode.zip)

**Video**

https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/67649479/0014d408-629d-4884-8a4e-408c51694e2c

---EDIT--- 

just had the same issue with a different gcode, with only one extruder - after that I thought it might have smth. to do with the flash-drive and formatted it - now the printer doesnt recognize the flash-drive because it's exFAT and 64GB, the problem was just a incompatible flash-drive - Ill investigate further

**Comment by Blubbertje321** [comment]
same issue here. Went from MK3S+ from 7 virtual extruders to 5 with MK4 due to the firmware. Please fix this so we can do multicolor again with more than 5 colors.
