### ISSUE TITLE
[BUG] Printer restarts partway through print

### ISSUE THREAD

**Issue by willsowerbutts** [prusa3d/Prusa-Firmware-Buddy#3223]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - 5.0.0-RC

**Original or Custom firmware** - Original

**Optional upgrades** - none

**USB drive or USB/Octoprint** - USB drive

**Describe the bug**

Partway through printing the printer stops print and the software restarts. The print does not resume. The print does not complete.

I've confirmed that the GCODE was not corrupted during transfer (compared SHA-256 of file on the memory stick to the file on my PC)

I've tried printing this twice and it failed on both attempts. I checked the printed parts, one set is 7mm high and the other is 7.7mm high, so it failed on different layers each time.

**How to reproduce**

Upload GCODE file 
[bug.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12430359/bug.zip)
 to printer. Print it.

**Expected behavior**

Not crashing and restarting midway through a print

**G-code**

Attached

**Crash dump file**

I can't find any crash dump file.

**Comment by KBalage** [comment]
I have the same problem with some prints with little movements required.

**Comment by willsowerbutts** [comment]
My friend Tony has kindly tested and reproduced the crash on his own MK4, also running 5.0.0-RC -- crashed at 34%, 8.9mm height.  He was using the GCODE file from  "bug.zip". So it does appear to be a bug that is not specific to my individual printer.

**Comment by willsowerbutts** [comment]
I think this might be related/the same as bug #3219
