### ISSUE TITLE
[FEATURE REQUEST] Sleep Mode

### ISSUE THREAD

**Issue by MagicalSpacePope** [prusa3d/Prusa-Firmware-Buddy#3224]
When the printer has been inactive for X minues/hours the screen is blanked (or turned off) and motors are disabled. Any input from the jog wheel wakes the printer and re-energizes the motors. This would keep the motors cool and protect the life of the screen when idle. Thanks!

**Comment by willsowerbutts** [comment]
That's a good idea!

**Comment by TravisWilder** [comment]
+1

**Comment by Graloth** [comment]
+1

**Comment by xtomasnemec** [comment]
+1
