### ISSUE TITLE
Print pause message not shown on mk4 printer screen

### ISSUE THREAD

**Issue by IvanJoel11** [prusa3d/Prusa-Firmware-Buddy#3233]
### Description of the bug

In the Prusaslicer, there is an option to add a pause print at a specific layer line (M601). When you select it, it also asks you to enter a short message to display on Printer display when a print is paused.

![image](https://github.com/prusa3d/PrusaSlicer/assets/70770499/9318b8a3-1845-437c-aecf-174dc098582d)

I entered the message and when printing the printer pauses at the correct layer but it doesn't display on the mk4 screen the short message I had provided. 

I have my printer set up as a physical printer and send the print to the printer via API using PrusaConnect.

### Project file & How to reproduce

[File.zip](https://github.com/prusa3d/PrusaSlicer/files/12443540/File.zip)

### Checklist of files included above

- [X] Project file
- [X] Screenshot

### Version of PrusaSlicer

2.6.0

### Operating system

Windows 10

### Printer model

prusa original mk4

**Comment by Prusa-Support** [comment]
Thanks for reporting.
However, this issue is a duplicate https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3143 and will be closed as such.

Michele Moramarco
Prusa Research
