### ISSUE TITLE
[FEATURE REQUEST] Mk4 layer change timings being displayed on LCD

### ISSUE THREAD

**Issue by tobymould** [prusa3d/Prusa-Firmware-Buddy#3241]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, on my mk4, I set layer filament change on PrusaSlicer and I cant see how long until the next layer change is on the LCD, so I can accurately time when I need to be back to the printer to make the filament changeover.

**Describe the solution you'd like**
Please add on the LCD 'Next layer filament change: 78 mins or 22:09pm' under the time til print complete time.

**Describe how it would work**
Same approach you use for total time, but take the time data for each layer change and display them one at a time as they come up next in the print. Perhaps also a more detailed time list for all of the layer changes and when they will occur if you interact with the menu.

**Describe alternatives you've considered**
Could implement it on the slicer too so we can plan ahead the day and when we need to return to give the printer attention, but it is more helpful on the printer itself. Its a relatively easy software update as you take the time data you already have but put it on the LCD display to be seen.

**Additional context**
Add any other context or paint drawing about the feature request here.

**Comment by naueramant** [comment]
+1

**Comment by Graloth** [comment]
+1

**Comment by naueramant** [comment]
I think the latest stable release might have solved this. Seems to be the conclusion here as well:
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3107
