### ISSUE TITLE
User-defined temperatures for filament changes

### ISSUE THREAD

**Issue by Harry-58** [prusa3d/Prusa-Firmware-Buddy#3243]
**Printer type** -MK4   Firmware 5.0.0-RC

**Is your suggested improvement related to an existing problem? Please describe.**
I have a FlexFilament that is printed at 180-200°C.
When changing filament, the lowest selectable temperature is 215°C (PLA).

**Describe the expected functionality**
There should be a possibility to set custom temperatures for filament change or to select a filament with 180°C.

**Comment by MichaelJLew** [comment]
I would also like to do this.
Is there a way for me to edit the pre-set filament change settings? That would suffice for me if it is too hard to allow me to change the temperature in an ad hoc way.

**Comment by Heliosmaster** [comment]
Same here with my Mini+

**Comment by KlausKraemer** [comment]
Look at issue #3657. I just added all but the same comment. Did you use Willowflex?
