### ISSUE TITLE
[BUG] 5.0.0 RC network (Wifi/Cable nextwork) download speeds is considerably slower (10%) than 5.0.0 Alpha 4

### ISSUE THREAD

**Issue by mkatzNU** [prusa3d/Prusa-Firmware-Buddy#3249]
**Printer type** - MK4

**Printer firmware version** - 5.0.0RC

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint**
WiFi/Cable Ethernet

**Describe the bug**
  Network download speeds are approx. 10% of 5.0.0 Alpha 4 on 5.0.0 RC

**How to reproduce**
   Install 5.0.0 Alpha 4 Firmware
   Time the download of a large file
   Install 5.0.0 RC Firmware
   Time the download of a large file
   Note that the transfer time of 5.0.0 RC2 is approx. 10% of the transfer time of 5.0.0 RC1

**Expected behavior**
   Faster download speeds not slower

**Comment by mkatzNU** [comment]
I'm sorry that is Alpha 4 vs RC.   Please forgive me.

**Comment by TravisWilder** [comment]
to open same issue multi times does not help - double
