### ISSUE TITLE
[BUG] GCODE printed successfully on 2-head XL and then was corrupted

### ISSUE THREAD

**Issue by riddley** [prusa3d/Prusa-Firmware-Buddy#3256]
**Printer type** - XL-2h

**Printer firmware version** - 4.7.2

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** USB

**Describe the bug**
I successfully printed this GCODE on my 2h-XL (my first print on it) via USB and subsequent attempts to print it have failed. I finally pulled it up in the Prusa GCODE Viewer[PGV] and it's clearly corrupted, but neither the XL nor the PGV reported it being so.

**How to reproduce**
I got the STL from printables.com, sliced it on Linux with the 2.6.0 AppImage and wrote it to the USB that I then transferred to the XL. Successful first print. Subsequent corruption.

**Expected behavior**
The GCODE should not become corrupted.

**G-code**
Attached.

[Anti_Sphare_Pot_0.6n_0.2mm_PETG_XL_4h18m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12551481/Anti_Sphare_Pot_0.6n_0.2mm_PETG_XL_4h18m.gcode.zip)

**Comment by langph** [comment]
Did you use the USB stick that came with the printer. It is bad quality unfortunately. Mine got corrupted when writing the WIFI configuration file on it from the printer menu. I threw it away and now use one of my own - had no issues anymore.
