### ISSUE TITLE
[ENHANCEMENT] XL Filament sensor individual control of side and nextruder sensor  

### ISSUE THREAD

**Issue by Arjen-hoekman** [prusa3d/Prusa-Firmware-Buddy#3257]
suggestion to have individual control for enabling and disabling the filament sensors 

currently, when you disable the filament sensors on the single-head XL you disable both sensors.  If these are independent from each other  when one fails the unit still has one working or you can disable the one that is failed or the one that is impossible to calibrate.

**Comment by Cap1a1n** [comment]
+1
On this way it would easier to print TPU and/or to use other places then the spoolholder on the side.

Similar to [FEATURE REQUEST] Different handling of filament runout on XL to allow for less wasted filament #3755 https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3755
