### ISSUE TITLE
[QUESTION] Getting Error Log

### ISSUE THREAD

**Issue by jamesstidard** [prusa3d/Prusa-Firmware-Buddy#3258]
I experience errors of either the printer not connecting to WiFi or the Send to Printer feature in Prusa Slicer resulting in a 4XX/5XX http error code. These behaviours are all inconsistent, and works about 30% of the time.

Is there a way to dump logs from the printer, or have them write to the usb drive so I can hopefully figure out the cause of these issues?

Thanks

**Comment by danopernis** [comment]
Hi @jamesstidard and sorry for taking too long. Please take a look at [https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/doc/metrics.md](doc/metrics.md)

**Warning:** This functionality is not considered stable and may break in future versions. In particular, log messages and metrics can appear, disappear and change between individual versions and gcodes may change too.

Feel free to ask more questions or close the issue if you have none.
