### ISSUE TITLE
[BUG] BSOD after trying to upload GCODE via PrusaLink web

### ISSUE THREAD

**Issue by MartinDejmal** [prusa3d/Prusa-Firmware-Buddy#3280]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI+]

**Printer firmware version** - [5.1.0-alpha1+12820]

**Original or Custom firmware** - Original/

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - N/A

**Describe the bug**
After trying to upload GCODE file via web interface (ethernet, not wifi), printer crashed with BSOD (see photo). 
![IMG_7009](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/18679101/dd60aa73-5061-4402-804f-f63af0266af0)

**How to reproduce**
Use attached file and upload it via PrusaLink web interface.

**Expected behavior**
Should not have crashed.

**G-code**
[BonkersBenchy_PLA_MINI_IS_16m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12665767/BonkersBenchy_PLA_MINI_IS_16m.zip)

**Crash dump file**
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12665740/dump_buddy.zip)

**Comment by danopernis** [comment]
This particular type of BSOD should be permanently fixed since v6.0.0, fixed via https://github.com/prusa3d/Prusa-Firmware-Buddy/commit/99da8a4f253df34dc34f5f81f3607b94498ae96e
