### ISSUE TITLE
Watchdog reset

### ISSUE THREAD

**Issue by OlNissen** [prusa3d/Prusa-Firmware-Buddy#3282]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI+]

**Printer firmware version** - [5.1.0]

**Original or Custom firmware** - [Original]

https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/52970187/fbc1cb9f-91fa-4e25-9055-eff9ff05ab18

**Optional upgrades** - [Filament Runout Sensor]

**USB drive

**Describe the bug**

**Expected behavior**
  print

**G-code**
   Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
   Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
   Please attach a video. It usually helps to solve the problem.
[D.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12671177/D.zip)

**Comment by misan** [comment]
Same problem here. Core dump and gcode file are attached.

[Archivo comprimido.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12675435/Archivo.comprimido.zip)

**Comment by jwidess** [comment]
This is pretty much the same issue as [#3275](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3275) and should probably be merged.

**Comment by OlNissen** [comment]
solved

I could not print Shaper from USB

But try to format the USB and make it from scratch and then it ran again.

**Comment by misan** [comment]
Just deleting files from the USB made it possible to print the same file. I did not need to reformat the pendrive. It had more than one hundred g-code files before and that was causing the problem.
