### ISSUE TITLE
[BUG] 5V Voltage on Prusa XL shows 33V on XL

### ISSUE THREAD

**Issue by schwabe** [prusa3d/Prusa-Firmware-Buddy#3283]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - XL

**Printer firmware version** - 4.7.2

**Original or Custom firmware** - Original

**Optional upgrades** - Stock

**Describe the bug**
  A value for 5V in the info sensor screen on XL shows an unlikely high value.

**How to reproduce**
  navigate to the sensor info screen, scroll down to 5V. This has been confirmed on two other XL.

**Expected behavior**
  The displayed voltage should much closer to 5V.

**Picture**
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1038539/0b60e7e8-27e0-42fb-9079-66dabd750cbd)

**Comment by BrienKing** [comment]
I saw that as well.

**Comment by Voxel3DPrinting** [comment]
I have the same issue
