### ISSUE TITLE
[BUG] <Seam transition catastrophic>

### ISSUE THREAD

**Issue by mozgy** [prusa3d/Prusa-Firmware-Buddy#3286]
**Printer type** - [MK4]

**Printer firmware version** - [5.0.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - []

**USB drive or USB/Octoprint** - USB flash drive

**Describe the bug**
  Seam transition is catastrophic, way too late start of extrusion so huge gaps -
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/5297353/2143050a-cb3b-4738-a89f-dcfaa4a91fe0)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/5297353/4dd7995a-1cc2-4402-a37f-379306d06d83)

**How to reproduce**
  Probably any combination of multiple objects with only one perimeter (like vase mode).

**Expected behavior**
  Perfect print

**G-code**
**Crash dump file**
**Video**

**Comment by murk-sy** [comment]
This is likely not a firmware issue, but more related to gcode generation and material tuning.

You should provide a sample project so it's easier to check if it's actually reproducible on other machines.

**Comment by mozgy** [comment]
@murk-sy You might be right, resliced it with nonIS profile and quite a bit better but still not perfect

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/5297353/51819a5c-b64b-459e-8f96-5a911c5b3992)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/5297353/9ab26748-a37a-47b6-9533-ab2adb44482d)

[IssueWithMK4.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12678492/IssueWithMK4.zip)
Should I reopen this issue in PrusaSlicer section ?

**Comment by darraghbr** [comment]
At least some of these parts appear to be a single perimeter thick, if that is the case you should be using spiral vase mode instead of a conventional print.

**Comment by murk-sy** [comment]
As a side note since you didn't mention the manufacturer, some white filaments can be more problematic to print than others. If other filaments print fine, it's just the white filament that may require some extra tuning.

**Comment by mozgy** [comment]
> At least some of these parts appear to be a single perimeter thick, if that is the case you should be using spiral vase mode instead of a conventional print.

In case you did not notice, there are *several* models *together* on the plate as *that* combination shows the problem. Spiral vase mode works fine for single model.

**Comment by darraghbr** [comment]
> > At least some of these parts appear to be a single perimeter thick, if that is the case you should be using spiral vase mode instead of a conventional print.
> 

> In case you did not notice, there are _several_ models _together_ on the plate as _that_ combination shows the problem. Spiral vase mode works fine for single model. Since it works fine for nonIS sliced it is **huge** regression.

I did notice that there is more than one part on the build plate. What you might not realise is that you can use sequential printing to print multiple objects in vase mode on a single build plate.

![Screenshot 2023-09-22 161638](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/31858409/8d8d34e0-d45b-47c8-98a7-0144501d008e)

**Comment by mozgy** [comment]
> > > At least some of these parts appear to be a single perimeter thick, if that is the case you should be using spiral vase mode instead of a conventional print.
> 
> > In case you did not notice, there are _several_ models _together_ on the plate as _that_ combination shows the problem. Spiral vase mode works fine for single model. Since it works fine for nonIS sliced it is **huge** regression.
> 
> I did notice that there is more than one part on the build plate. What you might not realise is that you can use sequential printing to print multiple objects in vase mode on a single build plate.
> 
> ![Screenshot 2023-09-22 161638](https://user-images.githubusercontent.com/31858409/269981586-8d8d34e0-d45b-47c8-98a7-0144501d008e.png)

You're right, I could've, but 'Issues' section is about bugs and regressions not walkarounds hence specific setup ..

**Comment by FutureSharks** [comment]
I opened this issue for PrusaSlicer: https://github.com/prusa3d/PrusaSlicer/issues/11914

Maybe it's the same issue? Not sure if it's a Slicer or firmware problem because they were both released and updated together in order to get the input shaper feature.

**Comment by GithubUser99999999** [comment]
still not fixed by Prusa

**Comment by danopernis** [comment]
This is not a firmware bug. As already suggested, this could relate either to slicer or the material settings.
