### ISSUE TITLE
[QUESTION] Prusa MINI 5.1.0-alpha1 maximum nozzle temperature question

### ISSUE THREAD

**Issue by Gyrxiur** [prusa3d/Prusa-Firmware-Buddy#3290]
Not sure if bug or feature, but with new firmware, max nozzle temp is 275 °C, with older it is 290 °C. In nozzle replacement guide it says to preheat to 280 °C, and that is not possible with 5.1.0-alpha1 FW. So I guess it is a bug, or not? If not, what is reason for it?

**Comment by marek26340** [comment]
Same issue. Just tried setting 290°C via Gcode and the temp got set back down to 275°C. 
@Prusa-Support Could you please give us an explanation for this? Thank you!

**Comment by allengregoryiv** [comment]
Has this ever been resolved it looks like the official release also caps at 275c from what I have seen.

**Comment by allengregoryiv** [comment]
![PXL_20231128_045349205.MP.jpg](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/336148/4613cf32-36a5-4486-8581-ac6f4e8a4ca5)

Attempting to load PA which defaults to 285C the printer refuses to heat past 275C.

**Comment by Noxmiles** [comment]
Just installed Firmware 5.1.2 from 4.4.1. Manual Nozzle max temperature is 275°. Even the guide for replacing the heatblock says it must be set to 280° - which is not possible anymore!

https://help.prusa3d.com/de/guide/auswechseln-des-heizblock-heatbreak-mini-mini_122769
