### ISSUE TITLE
[BUG] <failed to home Y-axis>

### ISSUE THREAD

**Issue by 85endriss** [prusa3d/Prusa-Firmware-Buddy#3295]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK4]

**Printer firmware version** - [5.0.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Stock kit]

**USB drive or USB/Octoprint**
  USB/Prusa link usb

**Describe the bug**
  After switching to the 5.0.0 stable release, while starting every print, during homing of Y-axis the message appears: Failed to home Y-axis. The print continues normally.

I switched back to the stable and reliable 4.7.2. 

**How to reproduce**
Starting a print

**Expected behavior**
  As with the 4.7.2. Homing without the failed to home message

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by ipsec76** [comment]
Das gleiche Problem habe ich auch beobachtet.

**Comment by marek26340** [comment]
Likely a duplicate #3289 and maybe more.
Try adjusting your belt tension and run a full selftest afterwards. All firmwares after version 5 are super sensitive to wrong belt tensions.

**Comment by jariascr2021** [comment]
Over here, we have been experiencing similar issues where the X-Y test fails every single time, even if the belt is tensioned with the app and there are no print fails. Rolling back to version 4.7.2 resolves the issue.

**Comment by 85endriss** [comment]
After the self test and adjusting the tension it was solved.

**Comment by 85endriss** [comment]
After the self test and adjusting the tension it was solved.
