### ISSUE TITLE
[BUG] MK4 with 5.0.0 encountered Watchdog Reset task:defaultTask?

### ISSUE THREAD

**Issue by craigktreasure** [prusa3d/Prusa-Firmware-Buddy#3297]
**Printer type** - MK4

**Printer firmware version** - 5.0.0

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint**

USB drive

**Describe the bug**

I left a print running during the night. I have printed this particular model\gcode several times. I believe the print completed successfully, but the next morning the printer was beeping with a blue screen indicating an error.

![PXL_20230921_083837773](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6309423/ccc88b2b-c412-4109-8288-c0357d4f16cc)

Transcribed from the image (double check my work):

```
WATCHDOG RESET
  task:defaultTask?
SP:00000000 LR: 2002ffe0 PC:080dc2f9
CPUID:410fc241 ICSR_:0043e80f VTOR_:00020200
AIRCR:fa050300 CCR__:00000210 SHCSR:00000800
DFR__:00100000 CPACR:00f00000
bot:20022c34 top:20021d38 stack:
89000000 08084596 08031553 00000000 2000acd0
040d0871 81d1befd 40000c00 00007000 00000040
00200000 000000d3 ffffffff 200079a4 00001b58
200025e0 fffffbfa 200025e0 00018eb6 04add7c9
08022409 00000000 200021c8 200025e0 080df58b
200021c8 00018eb6 200021c8 200025e0 00007000
20022c14 40021800 00000000 00000000 00000000
  5.0.0                                                                          [A]
```

I reset the printer and it asked if I wanted to create a dump, which I did (see attached).

**How to reproduce**

Not sure.

**Expected behavior**

No blue screens should be encountered.

**G-code**

In case it's useful, this is the last g-code I printed prior to encountering the error.
[catapultcard_square165_prusaslicer_0.4n_0.2mm_PLA_MK4IS_2h13m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12693280/catapultcard_square165_prusaslicer_0.4n_0.2mm_PLA_MK4IS_2h13m.gcode.zip)

**Crash dump file**

[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12693264/dump_buddy.zip)

**Video**

None

**Comment by Velocity11** [comment]
Having the same issue at the moment. Are there any fixes yet?

**Comment by sauloquirino** [comment]
I'm having the same error in my Mini+

**Comment by Mr2201** [comment]
I'm also encountering the same issue with my MK4. The error suddenly appeared after I had successfully printed my specific object once. I attempted it twice, and the error occurred around 20 minutes into the print (2 hours 20 minutes total print time) both times. After that, I restarted the printer (power cycle) and tried again. This time, the crash happened approximately 5 minutes before the print finished. It seems there's no specific time when the issue occurs. For all prints, including the successful one, I used RepetierServer as host. Tomorrow, I'll try it again from the original USB stick to see if that changes anything.

**Comment by jurriaan** [comment]
Just had a similar issue (WATCHDOG RESET task:defaultTask?) with 5.1.0-alpha2 on my MK4. The printer finished printing 5-6 hours before the issue appeared (was just turned on without doing anything before crashing).

**Comment by 7s3** [comment]
This happened the me 3-5 times over the course of the past week.
MK4 version 5.0.0 and 5.0.1

**Comment by F1dla** [comment]
Same here on self upgraded MK3.9.
![photo1702366085](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/25565662/03ed797a-fd6d-47a9-bc8c-9d6bb71542cd)

**Comment by craigktreasure** [comment]
Not stale

**Comment by danopernis** [comment]
@craigktreasure did you test with the latest firmware? Can you provide crash dump?

**Comment by craigktreasure** [comment]
> @craigktreasure did you test with the latest firmware? Can you provide crash dump?

I have not reproduced the issue with the latest firmware. There's a dump in my original post.

**Comment by danopernis** [comment]
Yes, I know that there is a dump in the original post, but that crash happened on the v5.0.1 There were several bugfixes related to watchdog and its interaction with the buggy USB sticks since that version, so that's why I am asking you to provide crash dump (if any) from the latest firmware. Otherwise, I do not understand your earlier "Not stale" comment.

**Comment by craigktreasure** [comment]
Well, from my perspective, there was no indication that anyone had acknowledged or seen the issue. A bot came through saying, "i'm going to close this making it even less likely that they'll see it." So, I said it wasn't stale hoping that it still might get some attention.

Now that's you're acknowledging the issue and indicating that there might have been related fixes, we can certainly close it and re-activate it if we see the issue again in newer firmware.
