### ISSUE TITLE
[BUG] Blue Screen when gcode file uploaded over PrusaLink - Dashboard 

### ISSUE THREAD

**Issue by matejus** [prusa3d/Prusa-Firmware-Buddy#3300]
blue screen when uploaded file over PrusaLink - dashboard page. File successfully uploaded to the USB flash drive, then printer failed to BSD (expect to prepare file for print). after printer restarted, print from the same file start/finish correct.

Printer is not connected to internet (time is not set from timeserver)
g-code prepared by PrusaSlicer 2.6.1

**Printer type** - MINI, buddy board 104
**Printer firmware version** - 5.1.0.alpha1+12820
**USB drive or USB/Octoprint** -USB Flash drive

[gcode_dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12698289/gcode_dump.zip)

**Comment by darraghbr** [comment]
Was the bluescreen image the same as the one in this issue?

#3299

**Comment by matejus** [comment]
Hi, not sure, but i think the screen was full of text. but i don't have photo

**Comment by strugatzki** [comment]
I have the same issue as OP, it was definitely not the bluescreen referred to by darraghbr  above (ie, not a question of previews), but a uhm fully fledged BSOD with lots of text. OK I'll take a pic next time. Occurs when sending a file directly from PrusaSlicer to MINI+, both unter Input Shaper Alpha and with a non Input Shaper-Printer Profile. When saving the same gcode to a USB drive, it works, including a correct preview pic.
