### ISSUE TITLE
[BUG] Mini+ 5.1.0 alpha  BSOD "Imprecise Data Access"

### ISSUE THREAD

**Issue by stefanetzkorn** [prusa3d/Prusa-Firmware-Buddy#3304]
**Printer type** - [MINI]

**Printer firmware version** - [5.1.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor - E3D Revo Micro Hotend]

**USB drive or USB/Octoprint**
  USB

**Describe the bug**
  Got BSOD while printing

**How to reproduce**
  Print the attached Gcode

**Expected behavior**
  Should not get a BSOD

**G-code**
[raketovy motor XL - high poly II_0.4n_0.2mm_PLA_MINIIS_1h44m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12704154/raketovy.motor.XL.-.high.poly.II_0.4n_0.2mm_PLA_MINIIS_1h44m.gcode.zip)

**Crash dump file**
[dump_buddy.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12704160/dump_buddy.bin.zip)

**Picture**
<img width="386" alt="Bildschirmfoto 2023-09-22 um 21 46 22" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4946777/f57c269d-ccc6-4473-a28e-b6fa289adbed">

**Comment by javree** [comment]
[DrawerBoxes_77x102_0.4n_0.2mm_PLA_MINIIS_2h12m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12705991/DrawerBoxes_77x102_0.4n_0.2mm_PLA_MINIIS_2h12m.gcode.zip)
[dump_buddy.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12705992/dump_buddy.bin.zip)
![crash](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/22570850/0cc83195-f30b-4a08-a0e8-bb1bb78505e9)
Seeing an identical issue, model printed fine 4 times, 5th time got a crash
The screen looks identical, my model is a lot easier though. Printing in PLA, with almost stock profile

MINI+ , 100% stock , 5.1.0-alpha , printing from USB (known good stick)
Network link was through cable , IPv4 through DHCP
PrusaConnect was active
PrusaLink was active, webpage was opened for status monitoring

**Comment by Jerzeek** [comment]
Got the same BSOD today

**Comment by Jonty** [comment]
I just experienced the same crash mid-print. Can provide dump_buddy.bin if needed.

**Comment by Ronin0000** [comment]
same here
