### ISSUE TITLE
[BUG] MINI 5.1.0 alpha Unloading filament will not unload it completely.

### ISSUE THREAD

**Issue by ScreennameTaken** [prusa3d/Prusa-Firmware-Buddy#3307]
Modifications: Revo 6 hot end and Bondtech IFS extruder.
After updating the firmware, whenever i'm unloading the filament, it doesn't unload it completely. It now stops pushing out just right at the end, and have to go in the menu to manually spin the extruder motor to push the final bit for the filament to let go.

**Comment by darraghbr** [comment]
Is this the same as #3276 ?

**Comment by ScreennameTaken** [comment]
The difference is that there is no Bondtech PTFE in use.

**Comment by danopernis** [comment]
Let's close this in favor of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3276
