### ISSUE TITLE
[QUESTION] Where is the code responsible for the Input Shape?

### ISSUE THREAD

**Issue by R1kk3r** [prusa3d/Prusa-Firmware-Buddy#3310]
Hi all,
I saw the commit for the release 5.0. Does anyone know where this code comes from? There is no branch nor PR associated with it. Same question for the new Input Shaper, any commit history or documentation about the way it works? Where is the code implementing the feature?

Thank you !

**Comment by rinkek** [comment]
Isn't it just the M593 command in Marlin?

**Comment by murk-sy** [comment]
Unfortunately commit history was essentially killed off when an unreleased Prusaslicer feature in development was released for a different slicer. Now the actual development (of all projects) is essentially completely separate.

There is some info on IS on https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.0.0-alpha1 but I don't think there's good complete documentation anywhere yet.

**Comment by bkerler** [comment]
The input shaper related code can be found [here](https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/b3ee47aa573f4d9b4af82d7a6963f43ab37ccc08/lib/Marlin/Marlin/src/feature/input_shaper)

**Comment by bkerler** [comment]
Related GCode M74 is [here](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/b3ee47aa573f4d9b4af82d7a6963f43ab37ccc08/lib/Marlin/Marlin/src/gcode/feature/input_shaper/M74.cpp#L4)

**Comment by danopernis** [comment]
Question already answered by @bkerler
