### ISSUE TITLE
[BUG]  Mini screen flicker / blinking after firmware update from 4.1.1 to 5.1.0-alpha1

### ISSUE THREAD

**Issue by lammesky** [prusa3d/Prusa-Firmware-Buddy#3314]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - [e.g. 4.0.5, ...]

**Original or Custom firmware** - [Original/Custom]

**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint

**Describe the bug**

**How to reproduce**
  Please describe steps to reproduce the behavior.

**Expected behavior**

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by murk-sy** [comment]
Duplicate of #3277
