### ISSUE TITLE
[BUG] No way to get out of a Crash

### ISSUE THREAD

**Issue by BrienKing** [prusa3d/Prusa-Firmware-Buddy#3316]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [XL Dual Extruder]

**Printer firmware version** - 4.7.2

**Original or Custom firmware** - Original

**USB drive or USB/Octoprint**
USB Drive

**Describe the bug**
When the first tool change occurred, it detected a crash.  "Toolchanger problem has been detected.  Park all tools to docks and leave the carriage free."  Shows T1 spinning and T2 with a green check-mark.   It then sits there and beeps at you.  There is no way to get beyond that screen so I cannot dock anything.   The only thing you can do at this point is reset the printer.

**How to reproduce**
Get it to detect a crash.

**Expected behavior**
I expected it to give me the option to abort or continue just like the MK3S+ does.   On a crash, it probably should home itself and/or dock the current toolhead.

![Prusa XL Crash Screen](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4928793/d19e687b-e299-4d65-aff8-ddf02c529ae3)

**Comment by jeffbarr** [comment]
I would like to see this fixed. I just had it happen on my 5-head XL running firmware 6.0.0, less than 15 minutes before a 25 hour print was due to complete.
