### ISSUE TITLE
[BUG] <Prusa mini blue screen second time like this... >

### ISSUE THREAD

**Issue by TomasJankauskas5** [prusa3d/Prusa-Firmware-Buddy#3318]
![PXL_20230926_083929220 MP](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/105481833/5fc92298-7e51-4c17-a34e-a0872c6c30b1)

Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]+

**Printer firmware version** - [e.g. 4.0.5, ...]

**Original or Custom firmware** - [Original/Custom]

**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint

**Describe the bug**

**How to reproduce**
  Please describe steps to reproduce the behavior.

**Expected behavior**

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
https://drive.google.com/file/d/1AG7uvvHyNvOe6nF02VIZ52J_AVQ2qi6Z/view?usp=sharing

  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by darraghbr** [comment]
Is this the same as #3304 ?
