### ISSUE TITLE
[BUG] Constant crashing and blue screen after upgrading to 5.1.0-alpha

### ISSUE THREAD

**Issue by ErikBuer** [prusa3d/Prusa-Firmware-Buddy#3319]
**Printer type** - [MINI]
Mini

**Printer firmware version** 
5.1.0

**Original or Custom firmware**
Original

**USB drive or USB/Octoprint**
Octoprint

**Describe the bug**
After upgrading we got one good print on one of two minis.
Then they crash every time I attempt to print on either of our two printers.

I get this blue screen on one of them (multiple times).

**How to reproduce**
Start print from Octoprint.

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/47660770/bb73f83c-2068-45da-9442-596ae30d20db)

**Comment by danopernis** [comment]
This particular type of BSOD should be permanently fixed since v6.0.0, fixed via https://github.com/prusa3d/Prusa-Firmware-Buddy/commit/99da8a4f253df34dc34f5f81f3607b94498ae96e
