### ISSUE TITLE
[BUG] Crash on upload large file

### ISSUE THREAD

**Issue by ALD-Models** [prusa3d/Prusa-Firmware-Buddy#3320]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MINI+

**Printer firmware version** - 5.1.0 alpha1 (not using Input shaper when crashed)
**Original or Custom firmware** - Original

**Optional upgrades** -Filament Runout Sensor

**USB drive**

**When Uploading a 26.16mb file to the mini it crashed at 100% when uploading to the local IP address**

**How to reproduce**
Upload a large file

**Expected behavior**
to upload ok and not crash

`[**G-code**]`
Wouldnt let me upload as it it above 25mb

Crash Report:
[dump_buddy.txt](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12731231/dump_buddy.txt)

Photos:
![1000005578](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/79934911/43981850-96be-4524-9858-bb2b3eef8d31)
![1000005579](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/79934911/ae35a900-62ad-434e-b9b6-6c8d803ce91b)

**Comment by danopernis** [comment]
This particular type of BSOD should be permanently fixed since v6.0.0, fixed via https://github.com/prusa3d/Prusa-Firmware-Buddy/commit/99da8a4f253df34dc34f5f81f3607b94498ae96e
