### ISSUE TITLE
[BUG] Mini 5.1.0-alpha1 no longer shows estimated time finished

### ISSUE THREAD

**Issue by Meth0d007** [prusa3d/Prusa-Firmware-Buddy#3325]
**Printer type** - [MINI]

**Printer firmware version** - [5.1.0-alpha1]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive**

**Describe the bug**
  With the new alpha firmware the printer no longer shows the estimated time when the print is fnished, only the remaining print time.

**How to reproduce**
print anything

**Expected behavior**
  show the estimated time based on printers timezone when the print is fnished like in previous firmware

**Comment by jvlobo** [comment]
This was the behaviour that the printer always had before the latest 4.4.0 (or so) update. And, in my opinion and from what I read from other users, I think is the best way, showing the remaining printing time.
It seems like they finally put it back on this version which is great. 
I understand some people may prefer having the estimated finished time, so having the option to put one or the other in settings would be nice, but this is definitely not a bug.
