### ISSUE TITLE
[BUG] mini homing failure y gives non-existing error page 12305

### ISSUE THREAD

**Issue by boekenwuurm** [prusa3d/Prusa-Firmware-Buddy#3326]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]
mini (original)

**Printer firmware version** - [e.g. 4.0.5, ...]
5.1.0 alpha

**Original or Custom firmware** - [Original/Custom]
original alpha software

**Optional upgrades** - [e.g. Filament Runout Sensor]
filament sensor

**USB drive or USB/Octoprint**
via USB

**Describe the bug**
After upgrading, testing belt tension and running a selftest, I run a print of homing. When trying to home the y-axis, it tries ~18 times to reach the end, fails and gives the red error screen, with error code 12305. This error code does not exist, so there are no handles on how to resolve the error.

**How to reproduce**
run homing, and if test fails, the error appears with a QR code that does not lead to a valid prusa page. (prusa.io/12305)

**Expected behavior**
a qr code that goes to a page that helps solving the problem.

**G-code**
-

**Crash dump file**
-

**Video**

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/7584205/b078701c-b823-4601-9a2c-3c9c7ca44674)

**Comment by murk-sy** [comment]
I believe these are generally not added or at least not public until the firmware is final in case there are some major functionality changes.

I would still leave the issue open in case it's missed after release.

**Comment by i-make-robots** [comment]
I have this same issue.  Currently the only fix is to revert firmware?
https://www.instagram.com/stories/archive/18316497640096365/

**Comment by murk-sy** [comment]
@i-make-robots See #3273 for fixes/workarounds, this issue is specifically about missing help pages

**Comment by i-make-robots** [comment]
here was my fix: https://www.instagram.com/p/Cx08ogqPvJg/

**Comment by danopernis** [comment]
@JakoobCZ Please add https://prusa.io/12305 error code for MINI

**Comment by danopernis** [comment]
Fixed, thanks for reporting
