### ISSUE TITLE
[BUG] 5.1 Alpha Mini+: Motor hammers into axis

### ISSUE THREAD

**Issue by Citrullin** [prusa3d/Prusa-Firmware-Buddy#3331]
**Printer type** - [MINI]

**Printer firmware version** - 5.1 Alpha

**Original or Custom firmware** - Original

**Describe the bug**
  When the bed or Hotend is at its limits and you level it, the bed or hotend hammers a little into the end and it creates a short hammering noise until it realizes its the end. This wasn't a behavior I have seen in the previous versions.

**How to reproduce**
  Move the Hotend completly to its right limit, or the bed to its down limit. Start first layer leveling or auto homing. 

**Expected behavior**
  A short end stop noise *DUB* and not *DDDDRRR DRRR*

**Video**
  I can create one, if necessary and required. I don't want to reproduce this behavior if not needed.

**Comment by marek26340** [comment]
Can confirm with my MINI too. I'm pretty sure this behavior isn't harmful to the printer in any way and it's easily preventable by manually pushing the X and Y axis closer to the middle before homing.

**Comment by mtaumike** [comment]
Printer is already homing using stallguard but I don't like this noise either

**Comment by MightyPork** [comment]
I now had it, multiple times, hammer so hard it decided to reboot with "obstacle on X axis".

Sometimes pulling on the belt seems to help, but tension is fine. This never happened with firmware 4.x

https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/2041118/2fa90990-0cac-4f65-a028-314b3083d05d

**Comment by Citrullin** [comment]
Fixed in 5.1
