### ISSUE TITLE
[BUG] Using "Moving E-Axis" Menue heats up accidentally heatbed as well.

### ISSUE THREAD

**Issue by BernhardFe** [prusa3d/Prusa-Firmware-Buddy#3335]
Printer type MK4 with Input Slicer
Printer firmware version 5.0
Original firmware
Optional upgrades no
USB drive is used

Describe the bug
If I want to use the menu "Move Axis" to purge or retract some filament manually, the Nextruder heats up, what is correct and needed.
But then as well the heatbed heats up, what is not expected. Because the only action is to purge some filament. This is consuming more unnecessary energy an it can be burn your hand. Because it should be cold. Why heating the bed hen I want to purge or retract only?
Heatbed heating should be in the menu Temperature as it is.
I added a picture, where you can see the heatbed temperature during this action. For PC it will be 100C... and not necessarily.
Please don't heat up the bed, if the Menu Move E-Axis is used. Please change the firmware of the MK4.

How to reproduce
Allways using the menu.

Expected behaviour
Using the menu Move e-Axis should only preheat the nozzle and not the bed.

Photo
![IMG_0521](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/86232280/ec7992c5-1cf0-41c6-92bf-0a8883db1130)

**Comment by danopernis** [comment]
I just tried this on 6.0.0 and heatbed stays off, only nozzle heats up
