### ISSUE TITLE
Print stopped during printing - BSOD - precise_stepping.cp

### ISSUE THREAD

**Issue by ShadowJediJim** [prusa3d/Prusa-Firmware-Buddy#3337]
Had an error mid print on my MINI+ using the Input Shaper Alpha Firmware 5.1.0

Using USB flash drive and printing with a .25 nozzle  approximately 2 hours into a 5 hour print.

Printer: Mini + running 5.1.0-alpha with filament sensor
Slicer: PrusaSlicer 2.6.1
Filament: Prusament PLA
USB

**Crash dump file**

[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12798205/dump_buddy.zip)

**Comment by ShadowJediJim** [comment]
Here is an additional  crash dump file, situation occurred at a different point in the print when attempting the same item again later.
[dump_buddy2.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12807856/dump_buddy2.zip)

**Comment by ShadowJediJim** [comment]
Had the error happen during a different print as well.  Screen shot of the blue screen error.  The printer freezes during the print and this blue screen error displays along with an alarm.  "precise_stepping.cp"

![20231005_081100](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/146899611/f2cc0833-2bd3-4f0a-8419-d4490a1999e1)

**Comment by sekervin** [comment]
I have the same bug... 
![IMG_0168](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/147093146/3eae0a9d-cd92-4bd4-aceb-5b802101f200)

Here's the gcode file (GitHub forced me to change it to .txt) - the error happens 35 seconds into the print - and it happens every time on my machine.  
[Precise step bug.txt](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12821721/Precise.step.bug.txt)

**Comment by ShadowJediJim** [comment]
This has now reoccurred at almost the same point in my second attempt at this print, approximately 4 hours in 71%..  

I have included the blue screen, the g-code and the error file along with pictures of how the printer stopped mid-extrusion.

![20231005_122225](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/146899611/0fd408d8-63d4-4eaf-a55c-2420e4bcd2a6)
![20231005_122234](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/146899611/ec0ad83a-2159-4416-a745-a4163ee6bd08)
[Torrga Brawnanvil_0.25n_0.05mm_PLA_MINI_5h19m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12822626/Torrga.Brawnanvil_0.25n_0.05mm_PLA_MINI_5h19m.zip)

**Comment by ShadowJediJim** [comment]
Successfully printed 6 more items, then had another error - precise_stepping.cp.   This occurred at around the halfway point of a 3 hour print.  Gcode and crash file also attached.

![20231006_173020](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/146899611/a2fa3ca2-85aa-4825-b2a8-8acfcefb47f1)

[crash info and gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12836197/crash.info.and.gcode.zip)

**Comment by darraghbr** [comment]
Is this a duplicate of #3288 ?

**Comment by ShadowJediJim** [comment]
This appears to possibly be the same type of issue.  My report includes multiple additional occurrences of the problem along with the 3mf gcode and dump files.

 

Thanks you!
