### ISSUE TITLE
[QUESTION] Latest MK4 firmware seems to have Linear advance and Pressure advance?

### ISSUE THREAD

**Issue by welnanick** [prusa3d/Prusa-Firmware-Buddy#3340]
I thought they did the same thing? Am I wrong? Prusament PLA and Generic PLA seem to set both in Start G-Code if you are slicing with an MK4 IS profile.

**Comment by tkircher** [comment]
Internally, there is only pressure advance. In M900.cpp, for the MK4 configuration, M572_internal() is called. So in the slicer profile, the first M900 is redundant, and overridden by the subsequent M572.
