### ISSUE TITLE
[BUG] Filament Runout not working as it used to prior to Alpha 5.1.0

### ISSUE THREAD

**Issue by mtaumike** [prusa3d/Prusa-Firmware-Buddy#3348]
**Printer type**
- MINI+

**Printer firmware version**
- Alpha 5.1.0

**Optional upgrades**
- Filament Runout Sensor

**USB drive or USB/Octoprint**
- Both

**Describe the bug**
- Filament sensor not triggering when reaching end of current spool

**How to reproduce**
- Print with a short piece of filament

**Expected behavior**
- Printer should pause, notifying the user that a filament swap is needed

**Comment by TurboNimitz** [comment]
Noticed the same, also the print ends giving the user no ability to just change filament and continue.
