### ISSUE TITLE
Requirement - on M600 color change play sound

### ISSUE THREAD

**Issue by OndraCerv** [prusa3d/Prusa-Firmware-Buddy#335]
Hi, 

there is no audible warning when the printer stops and waits to color change (M600).
I think it would be useful to acoustically draw attention to this.

Function supports MERLIN. 
https://marlinfw.org/docs/gcode/M600.html  

Thanks

**Comment by Texy** [comment]
I thought it did, but a very short/quiet beep.

**Comment by JohnnyDeer** [comment]
Hi, new FW version 4.1.0-RC1 support sound notifications, please check it out. I´m closing this issue as solved.
