### ISSUE TITLE
[BUG] Nozzle won't automatically cool down after filament unloading

### ISSUE THREAD

**Issue by Zappes** [prusa3d/Prusa-Firmware-Buddy#3355]
**Printer type** - Mk4

**Printer firmware version** - 5.0.0 stable

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint**
  Network transfer from PrusaSlicer via PrusaLink, probably irrelevant here

**Describe the bug**
  When I print something, the heat bed and nozzle will automatically enter cooldown mode after the print has finished. If I use the filament unloading function right after a print has finished, the nozzle will not be cooled down but will stay at the temperature used for unloading until I manually start cooldown mode.

**How to reproduce**
  Print something and when it's done, eject the filament.

**Expected behavior**
  After the filament is unloaded, the nozzle should be cooled down.

**G-code**
  No specific model. It happens all the time.

**Crash dump file**
  Nothing has crashed so far. :)

**Comment by nocakeinc** [comment]
Can confirm. MK4 kit with 5.0.0.
I was also able to reproduce it.
