### ISSUE TITLE
[BUG] BSOD - Octoprint reconnect serial

### ISSUE THREAD

**Issue by mtaumike** [prusa3d/Prusa-Firmware-Buddy#3363]
**Printer type**
- MINI+

**Printer firmware version**
- 5.1.0-alpha1

**USB drive or USB/Octoprint**
  Octoprint 1.9.x

**Describe the bug**
  Disconnect serial and reconnect gives BSOD

  _Note_: Printer display does **not** change when selecting disconnect though this worked with the 4.x branch of code without issue.

**How to reproduce**
  see above

**Expected behavior**
  should reconnect after disconnect but something seems wrong

**Crash dump file**

```
BSOD
fsm
types. cpp: 333
FOM CREATE: Serial printing already opened at Tevel o.
Called from static void
ScodeSuite: M876(),
/home/admin/workspace/RELEASE-in?put_s haptask:defaultT
askSP: 00000001 LR: 10009
ff&PC: 000000
00 CPUID: 410c241 ICSR_:00400
000VTOR
_:00020200 AIRCR: fa050
300CCR
:00000210 DFR
_: 00100
000CPACR: 00f000
00 bot: 1000a15c top: 10009
268sta
ck: 00000006 00000000 20015
2ec00000001
20014c44 080ef
3bb080659af
00000000 04с46
1f120000ebc 08025b11 20002
5.1.0-alpha
[A]
```

I did a quick search and didn't see this reported yet.

**Comment by bkerler** [comment]
Could be related to issue #3554 as well. Can you let me know the displayed PC/LR on the BSOD ?
