### ISSUE TITLE
Display fan speed in footer as a percentage value

### ISSUE THREAD

**Issue by Harry-58** [prusa3d/Prusa-Firmware-Buddy#3365]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - MK4     Firmware 5.0.0

**Is your feature request related to an existing problem? Please describe.**
The fan speed is shown in the footer of the printer display in RPM.

**Describe the expected functionality**
I think it would be better to show the fan speed as a percentage, as it is also set as a percentage in the slicer.

**Comment by loewi1979** [comment]
i agree to this feature request

**Comment by jflyer81** [comment]
I third this request and would extend this desire to the Mini+ as well.
