### ISSUE TITLE
[FEATURE REQUEST] filament type through API

### ISSUE THREAD

**Issue by metebalci** [prusa3d/Prusa-Firmware-Buddy#3367]
**Is your feature request related to an existing problem? Please describe.**
It is not possible to read the filament type (selected when loading the filament) through PrusaLink API.

**Describe the expected functionality**
`/api/v1/status` can return filament_type in printer dictionary.

**Comment by bkerler** [comment]
This is already implemented via `/api/printer` in telemetry->material
