### ISSUE TITLE
[BUG] Wrong french translation

### ISSUE THREAD

**Issue by bgiot** [prusa3d/Prusa-Firmware-Buddy#3372]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK4]

**Printer firmware version** - 5.0.0

**Original or Custom firmware** - Original

**Describe the bug**
  after unloading a filament, the french translation asks for confirmation of "loaded" instead of "unloaded"
Error in po file at line 5258. must be "Le filament a-t-il été bien déchargé?"

<img width="780" alt="Screenshot 2023-10-19 at 15 53 13" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/379959/8a162594-acf4-4148-9ffb-458a15f25dfd">

**Comment by danopernis** [comment]
Duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3935
