### ISSUE TITLE
BSOD: XL 2-tool, cancel current item with single-item print

### ISSUE THREAD

**Issue by ex-nerd** [prusa3d/Prusa-Firmware-Buddy#3373]
**Printer type** - XL, 2-tool

**Printer firmware version** - 5.1.0-alpha2

**Original or Custom firmware** - Original

**Optional upgrades** - N/A

**USB drive or USB/Octoprint** - USB + wifi

**Describe the bug**

Used the new "cancel current object" feature and it cancelled but did a bunch of weird X/Y movements as it was lowering the Z away from the print. Then BSOD.

**How to reproduce**

I just used "cancel object ... current object" in the middle of a print of a single object.

**Expected behavior**

Print should have been cancelled without a BSOD.

**G-code**

Sorry, the file I was printing is licensed such that I cannot provide this.

**Crash dump file**

[dump_buddy.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13057998/dump_buddy.bin.zip)

**Video**

N/A

**Comment by 816-80085** [comment]
I had exact same bug. Same hw, FW, same events.
![20231021_141514](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/147247331/88f1fcf9-e278-4de0-a809-1514bdbb49c3)

**Comment by ex-nerd** [comment]
I missed a screenshot when I filed this. I just noticed from yours that this is the same line of code as the other bug I filed at #3386
