### ISSUE TITLE
Spooljoin holds unused additional toolheads at full temp on XL running 5.1.0

### ISSUE THREAD

**Issue by SamD98** [prusa3d/Prusa-Firmware-Buddy#3379]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - Prusa XL 5 Toolhead

**Printer firmware version** - 5.1.0

**Original or Custom firmware** - Original

**USB drive or USB/Octoprint**
Printing via USB drive

**Describe the bug**
If you select additional toolheads as spooljoin options for when filament is depleted it will hold those additional toolheads at full temp indefinitely until they are needed/print ends.

**How to reproduce**
Set up a print with a single tool and then in the start print screen select a different tool in the spooljoin mode

**Expected behavior**
It to hold other toolheads at a low temp like in a multi material print or just off until needed. 

[Extended v6_0.6n_0.32mm_PETG_XL_10h39m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13062282/Extended.v6_0.6n_0.32mm_PETG_XL_10h39m.zip)

**Comment by BrienKing** [comment]
I would say "as-needed" as it could be many hours before it needs to switch to the next filament.  If it runs out and has to wait an extra 10 mins to swap filament, that's acceptable to me.    Or have an option do either or.
