### ISSUE TITLE
[BUG] Printer indefinitely stuck on Downloading screen when printing from USB

### ISSUE THREAD

**Issue by orian** [prusa3d/Prusa-Firmware-Buddy#3382]
**Printer type** - MK4

**Printer firmware version** - 5.1.0‐alpha2

**Original or Custom firmware** - Original

**Optional upgrades** - no

**USB drive or USB/Octoprint**
 USB flash drive

**Describe the bug**
When I start a print from USB a "Downloading" screen appears and it stays indefinitely.

**How to reproduce**
...

**Expected behavior**
No download screen at all.

**G-code**
No problematic gcode

**Crash dump file**
No crash

**Video**
https://photos.app.goo.gl/RrAm3vuFwMuDbLkZ8

**Comment by matt09546** [comment]
Also have this issue on my Mini+
Seems to be a problem with the .bgcode file being exported from Prusa slicer 2.7.0 alpha1. Prints work when using gcode files exported from prusa slicer 2.6.1
