### ISSUE TITLE
[BUG] Prusa Mini+ 5.1.0 alpha 2 - sequential print BSOD

### ISSUE THREAD

**Issue by NaibCZ** [prusa3d/Prusa-Firmware-Buddy#3383]
**Printer type**
Mini+

**Printer firmware version** - [e.g. 4.0.5, ...]
5.1.0 alpha 1 and alpha 2

**Original or Custom firmware** - [Original/Custom]
original alpha

**Optional upgrades** - [e.g. Filament Runout Sensor]
filament runout sensor

**USB drive or USB/Octoprint**
USB drive

**Describe the bug**
I tried to do a sequential print. The first object printed without problems, but right before the second one, the BSOD appeared. I tried to upgrade from alpha 1 to alpha 2 and repeated the print, but problem persists.

**How to reproduce**
Use included gcode.

**Expected behavior**
Successful print.

[bugreport.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13062779/bugreport.zip)

**Comment by HeiLaut** [comment]
I run into the same issue. Report and G-Code and bin attached.
[PRUSA_MINI.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13120323/PRUSA_MINI.zip)
