### ISSUE TITLE
[BUG] No progress screen - MK4 5.1.0-alpha2

### ISSUE THREAD

**Issue by xcybplx** [prusa3d/Prusa-Firmware-Buddy#3396]
**Printer type** - [MK4]

**Printer firmware version** - [5.1.0-alpha2.]

**Original or Custom firmware** - [Original/Custom]

**USB drive or USB/Octoprint**
  USB + PrusaConnect + PrusaSlicer 2.7.1 Alpha

**Describe the bug**
After starting the print, the print progress screen is not showing. All settings are correct.
![1](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/77123188/cd014e9b-a516-4e3a-bc90-d4b97c894541)

19% (which is around 20 minutes) and still no progress screen.

![2](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/77123188/bfd48c82-904b-4b4e-9596-9cc7090e8eb4)

Settings

**Expected behavior**
Please fix the issue

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.
[Wypelnienia.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13073185/Wypelnienia.zip)

**Comment by xcybplx** [comment]
For some strange reason, it started to work at 43% and now even if I will go to the settings, it works as expected.
![IMG20231023182308](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/77123188/b20ec601-5ae3-47a6-96a1-ec0b1b466ed2)

**Comment by wgentine** [comment]
Showed up later here too...
