### ISSUE TITLE
[ENHANCEMENT] Cancel instance selection process - Mk4

### ISSUE THREAD

**Issue by MJDodgers1** [prusa3d/Prusa-Firmware-Buddy#3397]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK4
**Optional upgrades** - Cancel Instance selection during print

**Is your suggested improvement related to an existing problem? Please describe.**
  When using the new cancel an instance option during print on the Mk4, you can not tell which instance you are selecting as the slicer does not put them in order. Use the print preview picture showing the parts on the build plate to select which instance to cancel by highlighting the object you want to cancel. 

**Describe the expected functionality**
Instead of a list of the instances in the print, use the print preview picture showing all parts on the build plate to select which instance to cancel by highlighting the object you want to cancel. 

This way you can clearly see which model the printer will cancel rather than guessing which instance it is or waiting until the printer is over the broken model and clicking cancel current.

**Comment by sp847242** [comment]
"_When using the new cancel an instance option during print on the Mk4, you can not tell which instance you are selecting as the slicer does not put them in order._"

Related to this:
When I use PrusaSlicer 2.7.1 to make a multi-instance bed of parts, they appear in the Gcode file as:
```
M486 S0
M486 Aprinted object name.stl (Instance 1)
M486 S-1
M486 S1
M486 Aprinted object name.stl (Instance 2)
M486 S-1
M486 S2
M486 Aprinted object name.stl (Instance 3)
M486 S-1
```

I'm looking on the screen of a Prusa XL, but my understanding is that it's using the same firmware, or some of it anyway, as the MK4. 
What I see is:
printed object name.stl
printed object name.stl
printed object name.stl

The "(Instance #)" part is missing. So there's no way to know which instance I'm canceling. On a job with dozens of objects, this is...not good.

So I'm not sure what's keeping it from showing the entire text string after _M486 A_. Is the firmware's interpretation of the text following _M486 A_ getting confused by the opening parenthesis of _(Instance #)_ and then stopping?
