### ISSUE TITLE
[BUG] Uploading a file via PrusaLink while printing causes the printer to pause the print

### ISSUE THREAD

**Issue by rcmaniac25** [prusa3d/Prusa-Firmware-Buddy#3403]
**Printer type** - Prusa MK4 (original, not upgrade)

**Printer firmware version** - 5.1.0 Alpha2

**Original or Custom firmware** - Original

**Optional upgrades** - Stock

**USB drive or USB/Octoprint**
USB flash drive

**Describe the bug**
I was preparing a number of prints to do. I prepped the first using PrusaSlicer 2.7.0 Alpha1 and used the physical machine "Upload" feature to upload it to the printer. Once it finished uploading, the print shows up on the screen ready to print. I walked to the printer and told it to print.

I then returned to PS 2.7 alpha1 and sliced the next model. I again told it to upload to the printer, even though it was already printing. My expectation was that the file would upload and once the print finished, I would clear the print bed and tell the printer to start a different print. Instead, the existing print paused. I walked over to the printer and it said there was an error with the USB drive. I clicked OK and was on the screen asking me if I wanted to resume. Without touching the USB drive, I said resume.

16h later, the print finished without an issue and the 2nd print was ready to go.

My thought is that it tries to trigger a preview of the new upload, but since it's printing, it errors instead. No BSOD or crash, just a paused print that I need to resume.

**How to reproduce**
1. Prep a model in PrusaSlicer 2.7.0 Alpha1 and use the physical machine "Upload" feature to upload it to the printer
2. Start the print. (have not tested if Upload and Print would also work for starting a print)
3. Prep a 2nd model in PrusaSlicer 2.7.0 Alpha1 and use the physical machine "Upload" feature to upload it to the printer.
4. Observe the result on the printer.

**Expected behavior**
I expect that the print continues without stopping and the file upload completes too. No pause, no error.

**Comment by VH-fixer** [comment]
I see this also on an MK4,  FW 6.0.0.  production release.  Printing stops during an upload.   I consider the ability to upload a new file to the printer whil printing a fundamental feature.   I aborted the upload to keep printing.  

 I also have had problems when the printer was idle and doing an upload when it reported the USB stick was full.   It had only a few files and 95% free space on the USB.  It is a 16GB usb stick.   Reset or power on/off to clear the problem. 

Some successful uploads have had redundant data blocks.  This was noticeable with one where part of a first layer was repeated.  

Overall the wifi function of 6.0.0 has gotten very buggy compared to the early 5.x releases.
