### ISSUE TITLE
[FEATURE REQUEST] Pause print when filament runs out

### ISSUE THREAD

**Issue by vasimi** [prusa3d/Prusa-Firmware-Buddy#3421]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches. – done

If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Optional upgrades** - Filament Runout Sensor

**Is your feature request related to an existing problem? Please describe.**
Yesterday, I was printing sth and I ran out of filament in the middle of the print. I didn't have a second spool so I wanted to pause the print until today (because Prusa HQ is closed on weekends and the only store open on weekends that used to sell Prusament stopped selling it), but once the filament runs out, there's no way how to pause the print and I didn't want the printer to keep the bed and nozzle heated up for the whole night.

**Describe the expected functionality**
Option to properly pause the print and cool down the printer when filament runs out.

**Comment by rawlk** [comment]
The bed will stay warm since you don't want your parts to pop off when it cools down but the nozzle should by default stay warm until the safety timeout, right? Are you just looking for a way to short-cut the safety timeout for the nozzle?
