### ISSUE TITLE
[BUG] Uploading some PrusaSlicer gcode causes MK4 to lock up 

### ISSUE THREAD

**Issue by neuron-whisperer** [prusa3d/Prusa-Firmware-Buddy#3425]
Printer type - MK4 built from kit

Printer firmware version - 5.0.0

Original or Custom firmware - Original

Optional upgrades - None

USB drive or USB/Octoprint - USB drive

Describe the bug

Uploading some gcode files generated by PrusaSlicer sometimes causes the MK4 to lock up.

This has occurred sporadically, about eight times, over the last week.

Sometimes, the lockup occurs while the LCD is displaying "Please wait" and showing an hourglass. At other times, the lockup occurs while the LCD is displaying the just-uploaded model. In both cases, the MK4 remained unresponsive, both to LCD dial input and to web access, until the MK4 was power cycled. When power cycled, the MK4 boots normally and then immediately displays the uploaded model, and then remains responsive and can print the model without any problem.

This problem has occurred with a variety of models (all generated by Tinkercad and sliced with PrusaSlicer). There is nothing remarkable or consistent about the models - indeed, I am engaging in a project of repeatedly tweaking the same simple model (consisting of about 30 ordinary geometric shapes and resulting in a gcode file under 1mb). During about 20 uploads of this model with very minor changes, about 18 of the uploads worked fine and two of the uploads produced this lockup problem.

The lockup behavior did not occur on Prusa MK4 firmware prior to 5.0.0. Also, all of the instances occurred with models that were sliced with Input Shaping.

Initial guess:

- Given the new appearance of this problem with 5.0.0, I presume that this problem is specific to the Input Shaping feature.
- Given the timing of the lockups, I presume that the problem is occurring during the post-upload analysis, during which the MK4 evaluates an uploaded model to determine the image to show on the LCD and similar properties.
- Given the sporadic nature of the lockups (e.g., occurring only on some versions of a model and not on other, nearly identical versions; also, occurring immediately after upload but not after power cycling), I presume that this problem is the result of a race condition, such as a memory or storage contention issue.

How to reproduce

Slice a model with PrusaSlicer, probably with the Input Shaping feature. Upload the model. Maybe 5% of the time, the printer will lock up.

Expected behavior

Uploading a model should cause the printer to remain responsive to both LCD dial input and web access.

G-code - Not available (occurs with a variety of gcode files)

Crash dump file - Not available (no crash, just an instantaneous lockup)

Video - Not available

**Comment by gigi84** [comment]
it happens to me as well
