### ISSUE TITLE
Expansion of Cancel Objects to allow reprinting of objects.

### ISSUE THREAD

**Issue by nwielenga** [prusa3d/Prusa-Firmware-Buddy#3434]
The ability to cancel individual objects is great! It saves time and filament. While Prusa printers are generally quite reliable, sometimes I find myself cancelling an individual object. When this occurs, it is frequently due to poor bed adhesion. This always seems to happen within the first couple of layers.

Could the ability to restart individual objects be added? I recognize that there are fundamental clearance issues that preclude  restarting an object at _any_ point in the print, but would it be possible to add the ability to restart objects within the first few layers (a height cutoff)?

This could be implemented in two ways:

1. A user opts to restart an object before a given height cutoff (to avoid collisions). The printer pauses, parks the extruder off on the side, and moves the Y-axis forward. The user will then remove the failed first layer and (optionally) spot clean the print bed. The user will then select Continue on the printer, and the printer will attempt to restart printing the selected object(s). Lift-Z will be offset by the known layer height of the other (so far successful) objects to prevent collisions.
2. A user opts to cancel an object before the height cutoff. The printer will (optionally) pause before the height cutoff is reached and ask the user if they want to restart those objects. If yes, see 1.

For extra credit, if an object experiences repeated failures to print, automate slowing down the first layer speed to attempt to compensate?

**Comment by rtyr** [comment]
Transfered to https://github.com/prusa3d/Prusa-Firmware-Buddy, since it is mainly a task for the FW.
