### ISSUE TITLE
Delete gcode files from LCD screen

### ISSUE THREAD

**Issue by Claghorn** [prusa3d/Prusa-Firmware-Buddy#3439]
Enter what type of printer or upgrade the enhancement applies to.
MK4 (though makes sense for others as well).

I print many one-of tests, I have no use for the gcode again. It would be very handy to be able to delete the gcode files directly from the LCD screen once I see it printed OK.

The printer usually lands on a screen with "Reprint" and "Home" buttons after a print. It would be most useful if there was a "Delete" button on that screen as well (but NOT selected as the default, "Home" should always be the default :-).

As it currently is, I have to either use PrusaLink or physically move the USB stick to my computer.

Also, if I try to delete the just printed file from PrusaLink, I get a "file is in use" error, which is annoying. If it isn't actively printing, it should be willing to delete it and just go "Home" since it can't display that file any longer.

**Comment by Gyrxiur** [comment]
I really want this too <3

**Comment by Claghorn** [comment]
Still seems like a good idea to me.  I hereby un-stale it.

**Comment by Gyrxiur** [comment]
Please add it <3
