### ISSUE TITLE
Selftest does not pass during heat up(4.0.1:4.0.5) or Z(Z=4.0.5_Only)

### ISSUE THREAD

**Issue by bbeller123** [prusa3d/Prusa-Firmware-Buddy#344]
Original Prusa Mini does not pass selftest during heat up

if E3D Heater Cartridge, 24V 40 Watt (High Precision), and E3D Semitec 104GT Thermistor have Molex connectors. This Heater Cartridge was plug and play on MK3/S

https://www.printedsolid.com/products/e3d-thermistor-cartridge?variant=47736245196
https://www.printedsolid.com/products/e3d-high-precision-heater-cartridge?variant=531425918988

Issue occurs from 4.0.1 to 4.0.5

There are issues with 4.0.5 with Z axis if the motor has been replaced with MK3
No issues with Z from 4.0.1 through 4.0.4 with motor swap

**Comment by bbeller123** [comment]
There are issues with 4.0.5 with Z axis if the motor has been replaced with MK3
No issues with Z from 4.0.1 through 4.0.4 with motor swap

**Comment by bbeller123** [comment]
https://shop.prusa3d.com/en/spare-parts/205-hotend-thermistor-e3d.html

https://shop.prusa3d.com/en/spare-parts/384-hotend-heater-cartridge-e3d-24v-40w.html

**Comment by bbeller123** [comment]
Had to replug Prusa hotend. 

Hotend functions normally with E3D High Precision and 104GT if selftest is ignored. PID tuning was accurate

**Comment by JohnnyDeer** [comment]
I am closing this issue for not responding.
