### ISSUE TITLE
[BUG] Can not connect to SSID with "."

### ISSUE THREAD

**Issue by dcs3473** [prusa3d/Prusa-Firmware-Buddy#3446]
**Printer type** - Mini

**Printer firmware version** - 5.1.0 Alpha 2

**Original or Custom firmware** - Original

**Describe the bug**
  When creating the credentials for the WIfi Module I am not able to connect because SSID contains a "."

**How to reproduce**
  Happens every time.  Can make it work with different SSID

**Expected behavior**
  Should be able to see with special characters.  Everything else connects to it.  Phones, etc.

[wifi]
ssid=Stockdale.Home
key_mgmt=WPA
psk=GuestPassword

**Comment by TravisWilder** [comment]
on MK4 it works...
