### ISSUE TITLE
[BUG] Watchdog reset on MK4 while printer is idle

### ISSUE THREAD

**Issue by BRFreshness** [prusa3d/Prusa-Firmware-Buddy#3450]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - 
Original Prusa MK4

**Printer firmware version** - 
5.0.1

**Original or Custom firmware** - 
Original

**Optional upgrades** - 
none

**USB drive or USB/Octoprint**
Octoprint is connected, however no print job was running.

**Describe the bug**
Since upgrading the firmware to 5.0.0 I've been seeing the printer crash (Watchdog reset) for no apparent reason. It was just sitting idle. I've updated the firmware to 5.0.1 but it crashed again. Not sure if it's precisely the same crash signature - did not save the old dump files.

**How to reproduce**
Turn on printer... wait. Eventually it has a watchdog reset crash. Within 24 hours, I think.

**Expected behavior**
Printer shouldn't crash randomly.

**G-code**
n/a - was not printing anything

**Crash dump file**
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13263286/dump_buddy.zip)

**Video**
![PXL_20231106_023808902](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6303108/006988f5-bd0e-4251-80b6-fdb54d107413)

**Comment by BRFreshness** [comment]
Disconnected the USB cable for Octoprint and left the printer alone to idle today. As expected, it crashed again. No print job was running. New dump file attached.
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13276781/dump_buddy.zip)

**Comment by 7s3** [comment]
This happened the me 3-5 times over the course of the past week.
MK4 version 5.0.0 and 5.0.1

**Comment by bdynamic** [comment]
Same with me. FW Version 5.1
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/12560294/3eae1823-ae04-415b-b13e-0e6f1f0b09b0)
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13467972/dump_buddy.zip)

**Comment by Mackalope** [comment]
Same here idle BSOD every time

**Comment by DiederikvandenB** [comment]
Same here
