### ISSUE TITLE
[BUG] Wifi module setup fails and blocks use of printer until reset

### ISSUE THREAD

**Issue by naxxfish** [prusa3d/Prusa-Firmware-Buddy#3451]
**Printer type** - MINI+

**Printer firmware version** - 5.1.0-alpha2+13126

**Original or Custom firmware** - Original

**Optional upgrades** - Filament sensor, ESP wifi module (from Prusa shop), Revo Micro hotend, Prusa squashball feet, MM10 extruder replacement midplate

**USB drive or USB/Octoprint**
Octoprint connected

**Describe the bug**
 During Wifi setup flow The screen appears "Credentials loaded, attempting to connect - You may continue using the printer. The Wi-Fi icon will appear in the status bar once connected." There's two buttons "Yes" and "No" - which a) doesn't make sense - surely this should just be "Continue" b) pressing either button results in a beep but the dialogue does not disappear c) the printer does not appear to connect to the wifi network. 

At this point you must reset the printer to continue using the UI. 

**How to reproduce**
Wifi Setup Dialogue appears shortly after startup when the ESP Wifi module is installed. Going through the Wifi module setup flow with a fresh ESP module - it progresses through flashing firmware, writing credentials file to USB, reading credentials file to USB successfully.

**Expected behavior**
Expected behaviour would be for the dialolgue to be dismissed so that you can continue to use the printer (as the dialogue suggests), and for it to connect to the wifi network successfully. 

**G-code**
N/A (no G-Code being run)

**Crash dump file**
N/A (did not cause a crash)

**[Video](https://youtu.be/dNjPHsW60_o)**

**Comment by TomasJankauskas5** [comment]
Cant flash Wifi module here

**Comment by joachimklug** [comment]
I encountered the same for an upgrade of my MK4 from FW 5.0 to 5.1

**Printer type** - MK4

**Printer firmware version** - 5.1.0 (upgrade from 5.0)

**Original or Custom firmware** - Original

**Optional upgrades** - Stock MK4 Kit Assembly

Encountered the same issue. Not able to continue. Nothing happens after clicking `YES` or `NO`

![IMG_2724](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/36903205/e041027c-cfca-4346-8a4a-0741abe6cd65)

**Comment by echo-devnull** [comment]
Same here. Trying to connect to the wifi, and this page is non-responsive.
