### ISSUE TITLE
[FEATURE REQUEST] Cancel object for mini+

### ISSUE THREAD

**Issue by ErGeeBee** [prusa3d/Prusa-Firmware-Buddy#3455]
**Printer type** - [MINI+]
**Optional upgrades** - [Filament Runout Sensor]

**Describe the expected functionality**
Integration of the  'cancel object function' on the Mini+

**Comment by Ronin0000** [comment]
This can't be done because of limited memory or ram on the mini. Only certain upgraded will be able to be implemented in the mini's firmware.

**Comment by ErGeeBee** [comment]
> Only certain upgraded will be able to be implemented in the mini's firmware.
What exactly do you mean by this? Thanks.

**Comment by Ronin0000** [comment]
It means that because of the limited space only certain features that they will add on the MK4 or XL will be available on the Mini because of the limited space. For example the faster file transfer speeds was added to the mini because of the MK4 and XL, but the  Cancel object feature was not. They will probably only pick the most useful upgrades to add to the mini's firmware.

**Comment by Tommy544** [comment]
Let's not jump to conclusions. This is a very useful feature and my to my understanding from the posted blog post, this feature was supposed to be available on all 32 bit printers. I hope it was just erroneously left out of this MINI alpha firmware and will be added in the following alpha/beta builds.

**Comment by AJErazzor** [comment]
Could the mini USB be used as a way of "adding memory" - write out whatever can be to a USB drive and free up internal memory

**Comment by ErGeeBee** [comment]
It was added om the stable 5.1.0 release

**Comment by ErGeeBee** [comment]
Actually I can't find the function in the Mini's menu. So therefore the re-opening.
is it only for XL & MK4 as described in the release notes for the 5.1.0 alpha2?

**Comment by kozross** [comment]
[Latest firmware release](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.1.2) should fix this?

**Comment by jerrygrey** [comment]
@kozross I'll test now

**Comment by jerrygrey** [comment]
> [Latest firmware release](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.1.2) should fix this?

Can confirm this has been fixed in 5.1.2

**Comment by ErGeeBee** [comment]
> > [Latest firmware release](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.1.2) should fix this?
> 
> Can confirm this has been fixed in 5.1.2

Same here. I’ll close the issue. Thanks.
