### ISSUE TITLE
[FEATURE REQUEST] reverse knob direction

### ISSUE THREAD

**Issue by ps-igel** [prusa3d/Prusa-Firmware-Buddy#3456]
Feature should apply to: Original MINI/+

I had to swap the Encoder component (the one for the turning knob) on my Prusa Mini, because the original knob had become unreliable. Although the swap went flawlessly, now the direction of know is reversed.

Where I usually turned clockwise to advance the menu / scroll down, I have to turn counter-clockwise now.

Since I have no way of changing this physically (the encoder is one component) I though that could be addressed in software rather.

Admittely this is only a minor inconvenience and I would also be happy for a hint where to change this in code so I could do it myself and either do a pull request or build the firmware myself.

Thanks!

**Comment by Gyrxiur** [comment]
This happed to me also. I had to lift 2 side contacts and attach two short cables and cross them, to fix it.
