### ISSUE TITLE
[FEATURE REQUEST] bed leveling wizard

### ISSUE THREAD

**Issue by gigi84** [prusa3d/Prusa-Firmware-Buddy#3457]
**Printer type** - [MK4]

I would like to have the bed leveling wizard (like octoprint) using PrusaLink or PrusaConnect

**Comment by gigi84** [comment]
There are 2 ways to implement this feature:
1. (easier) --> just to report the actual nozzle height for the 9 points where the plate screws are. Based on the results, the user will decide autonomously what to do (add/remove washers and/or tight/loose screws)
2. (more difficult) --> Based on the actual nozzle height (see point 1), the screen will suggest the user what to do, screw by screw (9 times)

**Comment by carlocarlo91** [comment]
It would be great to have it on MINI+ too.
Something similar to Bed Level Visualizer of Octoprint.
