### ISSUE TITLE
[BUG] MK4 BSOD Unknown Error while printing.

### ISSUE THREAD

**Issue by SimGas** [prusa3d/Prusa-Firmware-Buddy#3458]
**Printer type** - [MK4]

**Printer firmware version** - [e.g. 5.1.0-alpha2]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [none]

**USB drive or USB/Octoprint**
USB

**Describe the bug**
First print on the new firmware. I've sent the gcode via Prusa Connect to the printer and the print started(jetfan18650_2***.gcode). I then finished another gcode in the slicer and clicked on Upload(jetfan2_stl***.gcode). about an hour into the print (jetfan18650, maybe 10 minutes after uploading the second print file), I got a BSOD "Unknown Error - Unable to show details". I discovered that the second gcode(jetfan2_stl) seems to have been streamed incomplete (file is full of NUL. I attached the relevant files + a crash-dump from the USB drive. 

**How to reproduce**
  I did not try to reproduce

**Expected behavior**
 Print should have been finished without issues

**G-code**
attached
[crash.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13294528/crash.zip)

**Crash dump file**
attached in same zipfile as gcode

**Video**
 would not be useful. beeping only. picture can be found here:
![prusa-crash](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/33643834/53cd08b1-6772-49b4-a74c-4f56d507b740)

**Comment by Jam-ehz** [comment]
I've just had something similar, this time with a Mini and it actually completed the print:

Prusa Mini+
5.1 Stable FW (Nov 23)

Using OctoPrint

Started a print job overnight, checking it in the morning the print was successful, but it was constantly beeping with this error screen:
![PXL_20231125_132012500](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/54636955/b1f5a8c4-a978-45bb-9fb3-684aee883399)

Unknown Error, and Unable to show details.

Haven't been able to reproduce it, but here's the error dump file and gcode that was used:
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware/files/13515300/dump_buddy.zip)

Not very helpful with an error like this, but might as well throw it out there in case someone else has it!
