### ISSUE TITLE
Add progress % to WebUI page title

### ISSUE THREAD

**Issue by LuKo** [prusa3d/Prusa-Firmware-Buddy#346]
Add progress to page title in WebUI. The same principle is used in Facebook for notify new messages or other notifications. Some examples: 
56 % | Original Prusa Mini - Prusa Connect
100 % | Original Prusa Mini - Prusa Connect
(56 %) Original Prusa Mini - Prusa Connect
(100 %) Original Prusa Mini - Prusa Connect

**Comment by tangero** [comment]
Hi Luko, we will consider that! Thank you
