### ISSUE TITLE
Up load error[BUG] <Enter comprehensive title>

### ISSUE THREAD

**Issue by hgdoolit** [prusa3d/Prusa-Firmware-Buddy#3460]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - XL

**Printer firmware version** -5.1.0-alpha2+13126

**Original or Custom firmware** -N/A

**Optional upgrades** - N/A

**USB drive 
  USB

**Describe the bug**
 With Prusa slicer 2.7.0 Alpha 1 and firmware 5.1.0-alpha2+13126, when trying to download from Prusa slicer to the XL from the slicer i am constantly getting a download error " Error uploading to print host: HTTP 507: 507: insufficient Storage" When i go back to firmware 4.7.2 i don't have the problem. All conditions on the computer and printer are the same with the exception of the firmware and slicer. 

**How to reproduce**
  The problem is not one i can cause to happen. It is an inconsistent behavior. Once the file is downloaded it prints fine. 

**Expected behavior**

**G-code**
 

**Crash dump file**
 

**Video**

**Comment by 7s3** [comment]
Same error for me every singe time. Can't upload any files to the MK4 via Prusa Slicer.
I tested the connection and received "Connection to PrusaLink works correctly."

I'm also able to connect to PrusaLink via IP address in the web browser...but still can't send files to the printer.
