### ISSUE TITLE
[BUG] FW 5.1.0-alpha2 - Unable to print. Print suddenly stops.

### ISSUE THREAD

**Issue by antimix** [prusa3d/Prusa-Firmware-Buddy#3461]
### Description of the bug

**PRINTER:**  MK4
**FIRMWARE:** 5.1.0-alpha2
**SLICER:** PrusaSlicer 2.7.0-alpha1

The print suddenly stop/crashed at layer 1 after few shapes. The printer looked like it was  printing on the LCD, but in reality it was doing nothing, head stopped, no movements, no messages special messages on the LCD, the scrolling printing as usual...

After further investigation the result was:
- the gcode that was sent to the printer via wifi with PrusaSlicer was correct. A binary compare with the one on the PC confirmed it was sent correctly.
- However going in step by step nozzle emulation on PrusaSlicer gcode, showed that at the precise point where it stopped. 
- No idea why the offending line stops the print. May be it was badly uncompressed in the printer memory.
- Offending line: 476 
- I did not have any issue in weeks with other print on the MK3S with this PrusaSlicer version, so the issue may be is affecting the MK4 FW or the decompression.

Attached the BGCODE that hand after one minute, and the PROJECT (is the MMU3 spool buffer).

[BUFFER_PART1_0.4n_0.2mm_PETG_MK4IS_3h23m.zip](https://github.com/prusa3d/PrusaSlicer/files/13307245/BUFFER_PART1_0.4n_0.2mm_PETG_MK4IS_3h23m.zip)
![gcode-inv1-2023-11-09_11-42-47](https://github.com/prusa3d/PrusaSlicer/assets/5182520/599a430c-94c8-4c5f-b21d-a7ab85f1f0b1)

### Project file & How to reproduce
A Zip with the prusaSlicer Project and the .bgcode

1) Open the project
2) Slice
3) Print

or 
Just send the .bgocde to the printer.

### Checklist of files included above

- [X] Project file
- [X] Screenshot

### Version of PrusaSlicer

2.7.0-alpha1

### Operating system

Windows 10

### Printer model

MK4

**Comment by antimix** [comment]
I reprinted the file after having uncompressed it with the PrusaSlicer Gcode Viewer, and it worked without issues.

**Comment by blue0ceanby** [comment]
I can confirm that. I had the same behavior under the exact same constellation.
I currently have the printer FW back to 5.0.0.
Can we test something?

**Comment by blue0ceanby** [comment]
This morning I completely reset the print to factory settings without firmware and then used the 5.1.0 beta. Then everything was put back into operation. The printer has currently been running with 10 prints for 12 hours without any problems
