### ISSUE TITLE
[BUG] MK4 crashes with precise_stepping.cpp Negative step time error when printing specific gcode file

### ISSUE THREAD

**Issue by welnanick** [prusa3d/Prusa-Firmware-Buddy#3463]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK4]

**Printer firmware version** - [5.1.0-alpha2+13126]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [None]

**USB drive or USB/Octoprint** - [USB drive]

**Describe the bug**
 Printer suddenly crashes and reboots with the error "Negative step time" coming from withing precise_stepping.cpp when printing a specific gcode file (attached). It doesn't always stop in the same place, but I've attempted to print this file a few times and it always crashes somewhere within the first 5 to 10 layers of the print.

**How to reproduce**
Attempt to print attached gcode file

**Expected behavior**
Print completes successfully

**G-code**
[gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13324028/gcode.zip)

**Crash dump file**
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13324042/dump_buddy.zip)

**Video**
https://photos.app.goo.gl/4u59rfxxSoYwynNCA

**Comment by GuyH77** [comment]
I have had the same error on the XL 5T. I reprinted the gcode and it repeated at what looks like the same place. 

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/106596720/16c641ed-a0eb-434e-901b-1ab913cf39a8)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/106596720/ac61cc82-d016-45d8-8bff-0c586c91a618)

3mf project 2.6.1 IS beta
[TrashCan.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13325381/TrashCan.zip)
Dump file
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13325383/dump_buddy.zip)

**Comment by vectorstofinal** [comment]
I just got this same crash on my 2-tool XL as well.
[Body1_0.6n_0.32mm_PLA_XL_1h53m.bgcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13328658/Body1_0.6n_0.32mm_PLA_XL_1h53m.bgcode.zip)
<img width="803" alt="Screenshot 2023-11-12 at 10 09 33 AM" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4183714/03e609aa-ad1e-47b7-842d-68bb40ea3fe6">

**Comment by nschimke** [comment]
Just happened on my 5-tool XL, firmware 5.1.0-beta, PS 2.7.0-rc1 on a Mac.
![IMG_1728](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/727923/c0649f16-fbdc-4dbc-b9a5-0f4c8d35cc1d)
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13401264/dump_buddy.zip)

**Comment by GuyH77** [comment]
@nschimke Was this a print using an older 3mf project? I have a theory that there's something in the settings of older projects that the Xl FW doesn't like which causes this error. The project may help the developers reproduce the issue.

**Comment by nschimke** [comment]
> @nschimke Was this a print using an older 3mf project? I have a theory that there's something in the settings of older projects that the Xl FW doesn't like which causes this error. The project may help the developers reproduce the issue.

It might have been but I don't think it was. This was a part I printed months ago but I'm pretty sure I did it with a new scratch project (that I didn't save).

**Comment by ishaid** [comment]
I just had the same error on my MK4.

![WhatsApp Image 2024-01-25 at 09 22 05](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/20211615/d138b91b-ce34-4cc8-bfd6-972163d47c85)

[dump_buddy and bgcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/14048041/dump_buddy.and.bgcode.zip)

new project new step files.
