### ISSUE TITLE
[FEATURE REQUEST] Safety: add a way to detect disconnected loadcell

### ISSUE THREAD

**Issue by Tupson444** [prusa3d/Prusa-Firmware-Buddy#3476]
Printer type: MK4

I wondered what would happen if the loadcell cable gets damaged or disconnected so I decided to test that by disconnecting it.

Normally the loadcell reading on my printer is around 15270. When I disconnected it, it was around -26570. I lifted the print head enough and selected autohome. The printer homed X & Y then started homing Z, so I reset the printer to avoid damage.

Conclusion: if loadcell cable is disconnected by accident (or damaged), the printer will probably damage the buildplate and hotend because it won't sense any change in the loadcell.

There should be some way to detect that something is wrong with the loadcell and prevent Z homing. I don't know how, since the normal "idle" reading can vary (probably different from printer to printer and I think it's not always the same value on mine, might depend on the filament loaded I guess), therefore I don't see a way the printer would know that the reading is false when disconnected, but there may be a way to solve this potential problem.

**Comment by tjhawkey** [comment]
This is a great suggestion! I hope there is a programmatic way to do it. From a mechanical view, I think it's fishy that the top of the nozzle pushes against the filament guide near the gears. Seems to me that the there should only be one load path for consistent behavior

**Comment by Tupson444** [comment]
Commenting to prevent closing.

**Comment by danopernis** [comment]
Closing in favor of #4106
