### ISSUE TITLE
FW update has no function

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware-Buddy#348]
the FW update has no function under settings. when selecting, it always jumps back to the main screen

**Comment by wffbos** [comment]
I can confirm this in the official 4.0.5 FW. Haven't verified if a valid FW-update file needs to be present in the USB-memory for the menu option to work. Did factory reset, but the problem persists.

**Comment by x10102** [comment]
Can confirm it happens with the firmware on the USB stick as well.

Dne pá 10. 4. 2020 21:25 uživatel wffbos <notifications@github.com> napsal:

**Comment by pyro159** [comment]
I am having the same issue. It worked once but after I selected the option to flash firmware on restart, it didn't work again

**Comment by AutomaticMFG** [comment]
Same issue on 2 Minis. 4.0.5 FW

**Comment by nilsstreedain** [comment]
I'm having the same issue on 4.0.5 when going through settings or when forcing it to check the USB by holding the knob button down on startup.

**Comment by x10102** [comment]
Fixed in latest release. Maybe close this issue?

**Comment by JohnnyDeer** [comment]
Hi, as @x10102 wrote, in 4.1.0-RC1 FW Update function have description explained what it mean. I´m closing this issue as solved.
