### ISSUE TITLE
[BUG] BSOD tasks.c:3783; Prusa XL stopped mid single tool print

### ISSUE THREAD

**Issue by crackness** [prusa3d/Prusa-Firmware-Buddy#3481]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - Prusa XL

**Printer firmware version** - 5.1.0-alpha

**Original or Custom firmware** - Original

**Optional upgrades** - N/A

**USB drive or USB/Octoprint**
  Original Prusa USB flash drive

**Describe the bug**
Printer stopped mid print with a bluescreen.  5 Toolhead printer, single toolhead print.  No clue why, though I have also had the printer bluescreen randomly just sitting idle overnight.
![PXL_20231116_111253168](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/73907174/9cdd18ec-6e10-4cce-8f79-c373765271a4)

**How to reproduce**
BGcode attached.

**Expected behavior**
Printer should have completed printing object

**G-code**
[BGcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13382292/BGcode.zip)

**Crash dump file**
[Crash.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13382272/Crash.zip)

**Video**
None available, picture of failure attached.
![PXL_20231116_111234900](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/73907174/4b754353-dfc5-4ae6-a322-37f72a0e4aca)

**Comment by bkerler** [comment]
just to make if your issue relates to my issue #3554 ... do you have anything connected to the usb port of the printer such as beaglecam ?

**Comment by crackness** [comment]
Nothing plugged into USB.  However after updating to the latest stable firmware (5.1 full release) I have not had any blue screen errors.
