### ISSUE TITLE
[FEATURE REQUEST] Give the option to access the loadcell data "real time"

### ISSUE THREAD

**Issue by sassda** [prusa3d/Prusa-Firmware-Buddy#3496]
I would love to be able to read the loadcell data more or less real time during a print, like something every few seconds or something (the shorter interval the better of course)

The ideal would be the ability to give it a webhook so that it posts there, it could open up the possibility of doing high level analysis by users, and could probably set up alerting when something is going wrong.

Worst case, have it report in prusa connect or something, and we could scrape the data or something.

 I know prusa talked about doing that eventually, and it seems in the meantime we could open this up for individuals see what people come up with.

**Comment by danopernis** [comment]
Webhook just for the sake of single metric is not going to be implemented. There is experimental metric support, see documentation at [doc/metrics.md](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/doc/metrics.md)

**Warning:** This functionality is not considered stable and may break in future versions. In particular, log messages and metrics can appear, disappear and change between individual versions and gcodes may change too.
