### ISSUE TITLE
[QUESTION] MK4 stuck on loading-starting screen after flashing firmware.bbf from no_boot

### ISSUE THREAD

**Issue by Atanas-Kolev** [prusa3d/Prusa-Firmware-Buddy#3498]
MK4 is stuck on the loading-starting screen after flashing firmware.bbf from the no_boot folder of the compiled firmware build. I am unable to flash the original firmware. Can you please help me?
Restarting from the PSU didn't help.

![IMG_6015](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/22729661/2d9b90e2-a8b6-47f2-8434-741d5136e39b)

**Comment by Tobiyashi** [comment]
Happened to me too while flashing my MK4 from 5.0.1 to 5.1.0

**Comment by Tobiyashi** [comment]
Got it to work.
I checked the crc from the downloaded file (for the mk4 it is CRC32: B0A65F05) and the file on the stick. They didnt match. Copied the file again on the stick and reflashed the firmware again.

The bar stopped again at the same place. 
Then i pulled the stick from the device and then the printer showed that it was searching for the bbf to update the bootloader. After reinsterting the stick the flashing continued succesfully

**Comment by kwagga** [comment]
Thanks for the tip. Mine was stuck for 30 minutes or so. Pulled out the stick, did a reset and when it looked for the bbf, presented another USB stick. Installation completed and all is good.
