### ISSUE TITLE
feature request: Prusa Mini, hold in the rotator knob to raise/lower the Z axis like it does on the MK3

### ISSUE THREAD

**Issue by iandouglas** [prusa3d/Prusa-Firmware-Buddy#350]
I miss being able to hold in the knob and adjusting the Z height when the printer is otherwise idle. Could this be added as a firmware feature in the future?

**Comment by Lukerson** [comment]
I think it will be in the next version.
After compiling and loading the FW from the current dev version, I had this option.

**Comment by Prusa-Support** [comment]
Thanks for your comments.
Correct. This feature is implemented in the current firmware.

Michele Moramarco
Prusa Research
