### ISSUE TITLE
[BUG] PrusaLink Macintosh file selector should also include `bgcode` along with `gcode` as supported file type

### ISSUE THREAD

**Issue by JohnOCFII** [prusa3d/Prusa-Firmware-Buddy#3502]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - 5.1.0-Beta

**Original or Custom firmware** - Original

**Optional upgrades** -

**USB drive or USB/Octoprint**
PrusaLink

**Describe the bug**
Using FireFox 119.01 on MacBook Pro with M1/arm. While drag and drop works, using the option to open the file selector to choose a file shows `bgcode` files as grayed out.  You CAN work around this by using the `Show Options` feature and switching to ALL, but I believe PrusaLink can/should be include `bgcode` as well as `gcode` as "expected" file types.

**How to reproduce**
Attempt to use PrusaLink to upload a file NOT via drag and drop, but choosing the option to use the local file selector to choose a file.

**Expected behavior**
Both `gcode` and `bgcode` file types should be selectable.

**G-code**
N/A

**Crash dump file**

N/A

**Video**
N/A - screen shot attached. <img width="1175" alt="Screenshot 2023-11-21 at 12 55 04 PM" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/7844212/4d65b566-a2b6-4de9-a4c9-8492d948b632">

**Comment by bbrundert** [comment]
Same issue here on my MINI (running MINI_en_de_firmware_5.1.0.bbf), uploading from MacOS. 

I also tried a potential workaround. I renamed my PrusaSlicer 2.7 generated .bgcode file to .gcode. But the printer detects it is actually a .bgcode file with wrong extension. Unfortunately, the MINI does not offer to proceed anyways or rename the file to .bgcode. So the only workaround is to transfer the file via USB Stick.

**Comment by drake127** [comment]
The same issue is present in final 5.1.0. A workaround on Windows is to select "All Files (*.*)", but it's very unfriendly.

**Comment by eugali** [comment]
Hey guys, the workaround is to press "inspect" in the file uploader and change the accept prop to .bgcode
<img width="689" alt="Schermata 2023-11-30 alle 18 41 18" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/20923553/6e79b285-4a7f-48c6-9ab2-bcad4aed9946">
<img width="624" alt="Schermata 2023-11-30 alle 18 41 29" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/20923553/2ce3bdda-23d7-4487-89b7-99e1bfc4a786">

**Comment by JAngerCAN** [comment]
I see the same problem with Safari browser on Mac. You can't select a .bg file to upload when clicking "click to choose a GCODE file". A workaround is to drag the .bg file from the finder into the upload window - then it uploads. The window says you can drag files in but perhaps it's not obvious you can drag a .bg file in this way.

**Comment by danopernis** [comment]
Duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3406
