### ISSUE TITLE
[BUG] WLAN password length

### ISSUE THREAD

**Issue by Jeggo65** [prusa3d/Prusa-Firmware-Buddy#3505]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - Prusa XL 5h

**Printer firmware version** - [5.1.0 alpha 2]

**Original or Custom firmware** - [Original]

**Optional upgrades** - No

**USB drive or USB/Octoprint**
  USB/Octoprint

**Describe the bug**
  Password with 64 characters is not accepted. Shorter password work.

**How to reproduce**
  Use a long password did not connect to WiFi. Shorter PW does.

**Expected behavior**
  At least 64 character long passwords should work better 128 characters.

**G-code**
  No print issue.

**Crash dump file**
  No crash. Does not work

**Video**
  Used Prusa slicer 2.7.0 rc2 to create credentials. So typing error is not possible.

**Comment by TravisWilder** [comment]
Note that WPA2 passphrases are limited to 64 characters.

**Comment by Jeggo65** [comment]
At least more or less all my other WiFi devices accept my 64 character long PW. So I would expect it to work on the Prusa printers as well. So using a real 64 character long (plus termination character) password should work. If only 63 characters should work, then more or less the whole industry does not care about it.

**Comment by tkircher** [comment]
> At least more or less all my other WiFi devices accept my 64 character long PW. So I would expect it to work on the Prusa printers as well. So using a real 64 character long (plus termination character) password should work. If only 63 characters should work, then more or less the whole industry does not care about it.

The standard says 8 to 63 characters. It would be incorrect for the Prusa to accept a longer password, and nothing of that sort should ever be implemented. It's likely you're confusing the hex key with the password.

**Comment by Jeggo65** [comment]
Sorry, I have to correct my comment/issue. My current Wifi password is only 63 characters long. So it is compliant with the password rules for WPA2 wireless networks. Sure, it is allowed that the password could be shorter. But it is good idea to have the possibility to use the maximum allowed length of 63 characters.
