### ISSUE TITLE
[BUG] OctoPrint integration lacks progress screen

### ISSUE THREAD

**Issue by dirkvranckaert** [prusa3d/Prusa-Firmware-Buddy#3507]
**Printer type** - MK4

**Printer firmware version** - 5.1.0 Beta

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint** Octoprint

**Describe the bug**
  No progress available for serial print with OctoPrint

**How to reproduce**
  Start a print from OctoPrint

**Expected behavior**
  See the progress of the print on the printers LCD

**G-code**
  OctoPrint send M117 commands, those can easily be used

**Crash dump file**
 N/A

**Video**
  N/A

**Image**
![IMG_7363_Original](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4660794/c082883f-678f-4072-bb08-4f160b4af472)

**Comment by thijstriemstra** [comment]
FWIW, this has always been this way (and thus considered an enhancement imo).
