### ISSUE TITLE
feature request: Prusa Mini, support multiple steel sheets like the MK3

### ISSUE THREAD

**Issue by iandouglas** [prusa3d/Prusa-Firmware-Buddy#351]
Would be awesome if the Mini's firmware allowed us to switch more easily between the smooth PEI and the textured PEI like the MK3 firmware.

**Comment by dennisscholing** [comment]
+1 This should have been there by default ..

**Comment by Gordontgopher** [comment]
This is a duplicate. See #223

**Comment by tangero** [comment]
Hi Ian, that is definitely our plan! We will add that in the near future.
