### ISSUE TITLE
[BUG] Firmware upgrade crashed going from 5.1.0-alpha2 to 5.1.0 (released)

### ISSUE THREAD

**Issue by rcmaniac25** [prusa3d/Prusa-Firmware-Buddy#3517]
**Printer type** - MK4

**Printer firmware version** - 5.1.0-alpha2

**Original or Custom firmware** - Original

**Optional upgrades** - Stock

**USB drive or USB/Octoprint**
USB

**Describe the bug**
The new 5.1.0 firmware finally released. I loaded it on the included USB drive, plugged it in, restarted the power on the MK4. It asked me if I wanted to install the new firmware, I said yes. I then turned to get something and heard a bunch of beeping. I went over and had the BSOD. It listed `5.1.0 [A]` as the version on the screen. I pressed the reset button and the install process continued and was successful. But for that one moment, I worried it had corrupted firmware install... which it does not appear to have.

**How to reproduce**
Take a MK4 with 5.1.0-alpha2 firmware and upgrade to the latest 5.1.0 firmware.

**Expected behavior**
Firmware upgrades successfully.

**Crash dump file**
ask for Dump file until #3528 is fixed

**Comment by mixer3d** [comment]
@rcmaniac25 https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3528
