### ISSUE TITLE
[FEATURE REQUEST] Mini - use a local time server

### ISSUE THREAD

**Issue by Gisi0** [prusa3d/Prusa-Firmware-Buddy#3523]
**Printer type** - MINI
**Optional upgrades** - Filament Runout Sensor

**Describe the expected functionality**
Normally my mini has no connection to the internet, so it happened, that I have no actual time on it.
Please make it possible to set a local time server.

Thank you, great work on the mini
Gisi

**Comment by nvtkaszpir** [comment]
Right now the address is hardcoded to `195.113.144.238`
https://github.com/prusa3d/Prusa-Firmware-
Buddy/blob/c2d7108782c8b84fd4ff318926461c7ae99a4543/lib/WUI/sntp/sntp_client.c

Thankfully you can use destination NAT rule on the router firewall to redirect destination address `195.113.144.238` (which is `tak.cesnet.cz`)  your preferred IP address which is serving time.

For example for [Mikrotik]( https://help.mikrotik.com/docs/display/ROS/NAT#NAT-DestinationNAT) assuming your NTP is on `10.0.0.3` then it would be something like below:
```shell
/ip firewall nat add chain=dstnat action=dst-nat dst-address=195.113.144.238 to-addresses=10.0.0.3
```

**Comment by bkerler** [comment]
This PR should make it much more easier and adds support for a local time server: https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/3679 :)
