### ISSUE TITLE
[BUG] Hotend fan spins repeatedly when printing is paused and nozzle is at room temperature

### ISSUE THREAD

**Issue by smn22** [prusa3d/Prusa-Firmware-Buddy#3529]
**Printer type** - MK4

**Printer firmware version** - 5.0.1

**Original or Custom firmware** - Original

**USB drive or USB/Octoprint** - USB

**Describe the bug**
  When printing anything, if you pause the printing process and set the nozzle temp to 0, it cools down to the room temperature and hotend fan stops spinning. However, few minutes later, hotend fan turns up for like 2-3 seconds and then it stops spinning again. This happens every like 20 seconds.

**How to reproduce**
  Pause the printing process and set the nozzle temp to 0. Let it cool down to the room temperature. Wait few minutes.

**Expected behavior**
  When printing a large models, which take a lot of printing time, I do not want to print overnight because of the noise. However, that "fan spinning" is pretty disturbing and it should not happen at all.

**Comment by ellensp** [comment]
This also happens at the end of a print. 

A small print finished and after the hotend had cooled down to room temperature the extruder fan bursts into life for about a second, this repeats a number of times but does stop after the bed has also reached room temperature  

Only started happening today after I updated firmware to MK4_MK3.9_firmware_5.1.3.bbf on my MK4
