### ISSUE TITLE
[BUG] I had a crash when uploading new wifi name

### ISSUE THREAD

**Issue by Niflheim123** [prusa3d/Prusa-Firmware-Buddy#3538]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - 5.1.0

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

USB drive

**Describe the bug**
had a bsod crash 

**How to reproduce**
For me this happened when I uploaded a wifi config file, took it to the printer, then uploaded the new config to the printer and tried to connect it to the wifi, then I realized that the wifi was with the wrong name (I was on the 5GHz one, the wifi has 5Ghz in the name). Took out the stick, erased from the config file - wifi name - the "5Ghz" characters, put the stick back in and reupload to the printer. 

**Expected behavior**
 New connection to be made to the wifi, Instead it crashed

**Comment by Niflheim123** [comment]
..... removed crash dump, will change credentials

**Comment by danopernis** [comment]
Thanks for reporting. This is a known issue, fix is scheduled for 6.1.0 version of the firmware.
