### ISSUE TITLE
[BUG] Prusa MK4 unable to print signle extruder MMU prints on 5.1.0

### ISSUE THREAD

**Issue by sdvaletone** [prusa3d/Prusa-Firmware-Buddy#3543]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** -

MK4

**Printer firmware version** -

5.1.0

**Original or Custom firmware** - 

Original

**Optional upgrades** - [e.g. Filament Runout Sensor]

NONE

**USB drive or USB/Octoprint**
  
USB Drive

**Describe the bug**
  GCODES that are sliced using single extruder MMU such as switching from PETG to TPU do not display a thumbnail and when print is selected, goes to a black screen where the printers reset button must be used to get back to the main menu

**How to reproduce**
  Slice any STL in Single extruder MMU mode switching from one filament type to another and attempt to print on the MK4

**Expected behavior**
  
Print first in PETG then switch to TPU at selected layer height.

**G-code**
  
[1_Tee_No_Divot_0.4n_0.3mm_FLEX,PETG_MK4_1h32m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13508273/1_Tee_No_Divot_0.4n_0.3mm_FLEX.PETG_MK4_1h32m.zip)

**Crash dump file**
  
Not available

**Video**
  
Not available at the moment but can be added later

**Comment by leejoow** [comment]
This is the same problem as https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3539
