### ISSUE TITLE
[QUESTION] Beim Filamentwechsel wurde der Druck nicht mehr weiter ausgeführt

### ISSUE THREAD

**Issue by BigBen2003** [prusa3d/Prusa-Firmware-Buddy#3557]
Während eines Ausdrucks ist das Filament einer Rolle zu Ende gegangen.

Der Rest vom Filament konnte aus dem Extruder entfernt werden.

Das Neue Filament wurde eingeführt. Dennoch ging der Ausdruck nicht weiter. Es wurde nur folgende Meldung angezeigt:

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/42717652/d733a5e8-ab58-4322-84c5-b2d11d55ad21)

Als diese Meldung angezeigt wurde, war kein Filament mehr im Extruder. Auch nach mehreren Minuten hat sich nichts mehr getan.

Auf Betätigung des Drehknopfes wurde nicht reagiert.

Es konnte nur der Reset-Taster betätigt und der letzte Druck komplett wiederholt werden.

Kann mir jemand mitteilen, was da falsch gelaufen ist?

Im MK4 ist die Firmware von der Datei MK4_MK3.9_firmware_5.1.0.bbf vom 23.11.2023  installiert.

**Comment by bkerler** [comment]
Ich vermute es lag am Filamentsensor, der das neue Filament nicht korrekt erkannt hat. Das passiert abundzu, wenn kleinste Filamentteile zwischen dem Filamentsensor liegen oder wenn die Spitze des neuen Filaments nicht spitz zuläuft (oder bei Strings). Auspusten kann da helfen. Aber er hätte dennoch auf Betätigung des Drehknopfes reagieren müssen.
