### ISSUE TITLE
[ENHANCEMENT] Warning sounds louder

### ISSUE THREAD

**Issue by sydios** [prusa3d/Prusa-Firmware-Buddy#3560]
Hello,

can you make the warning sound louder or have an option to change the volume yourself. The same loudness as on the MK3S.

Thanks!

**Comment by m-cas** [comment]
+1

**Comment by bkerler** [comment]
Actually there is a setting to set the sound volume for the Prusa Mini but for not for the MK4 / XL / MK3.5. Not sure if it's in fact HW related (different speaker being used).

**Comment by bkerler** [comment]
According to @vorner, it is HW related. It seems the configuration didn't make any audible difference and thus the function was removed for MK4 / XL / MK3.5. Sorry to say, but unless there is a new hw revision for that (very unlikely) I assume you can close this issue.
