### ISSUE TITLE
[BUG] Slow screen refresh rate with FW5.1.0

### ISSUE THREAD

**Issue by the-powl** [prusa3d/Prusa-Firmware-Buddy#3568]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - 5.1.0

**Original or Custom firmware** - Original

**Describe the bug**
Sometimes the refresh rate of the screen is really slow and it takes a few tens or hundrets of milliseconds for the screen to update.

**How to reproduce**
Just use the printer. The behaviour is everywhere.

**Expected behavior**
Way faster, fluent update rates

**Comment by dstulken** [comment]
Might be related to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3486 and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3407?

**Comment by danopernis** [comment]
Without the specific, this issue can't be addressed.
