### ISSUE TITLE
[FEATURE REQUEST] Cancel object using PrusaConnect web UI

### ISSUE THREAD

**Issue by B-0-B-B-Y** [prusa3d/Prusa-Firmware-Buddy#3575]
Since https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3073 has been merged in, and stable releases of FW 5.1.0 and PrusaSlicer 2.7.0 now fully support this functionality via the physical printer menu, it would be nice to extend this ability to the PrusaConnect web UI, as being physically present on-site with your printer isn't always possible. For scenarios where one part of an entire batch job has failed, it would be nice to be able to remotely still save the entire print process and just cancel the failed part/object via the web UI.

**Describe the expected functionality**
Menu option in the PrusaConnect web UI exists to allow canceling an object, able to select which object to be canceled and sending that command to the printer, remotely, without the need to physically interact with the printer.

**Comment by BugsBunny1403** [comment]
I support your request, and confirm the interest in adding this functionality. I will remain attentive to the rest of the events.

**Comment by Kosaro** [comment]
This already exists, but the option to do so only appears sometimes. I'm not sure why.

**Comment by wafflecart** [comment]
> This already exists, but the option to do so only appears sometimes. I'm not sure why.

Did not know cancel object existed in prusa connect! Will see if I can see it next print 😎

**Comment by tjstansell** [comment]
I printed a 16 object print yesterday after updating to the 6.0.0 firmware (MK4) and using prusaslicer 2.7.4 and I couldn't find any way to access the cancel object feature in prusa connect.  I did initiate the print using prusalink, so not sure if that changes anything.  I would hope not.  🤷

**Comment by wafflecart** [comment]
You access it by clicking on the print on the list then on next screen scroll down to see the build plate. You can click on models there to cancel.

**Comment by whoisdecoy** [comment]
> You access it by clicking on the print on the list then on next screen scroll down to see the build plate. You can click on models there to cancel.

I was able to see this on my MK4. Will this be available on XL with official 6.0.0? My XL is on RC3

<img width="1239" alt="Screenshot 2024-04-23 at 2 29 55 PM" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/40132135/07201163-74c7-457b-85eb-306e97fd76d7">

**Comment by rawlk** [comment]
> I was able to see this on my MK4. Will this be available on XL with official 6.0.0? My XL is on RC3
> 

It showed up for me on my not-yet-6.0 XL today. 

Thanks! A huge help, now just have to figure out how to tell it to resume after canceling the problematic object remotely.

**Comment by danopernis** [comment]
@B-0-B-B-Y can this issue be closed now, or is there anything else?

**Comment by rawlk** [comment]
It seems to not be consistent. I tried several times in the last few days to find this feature when printing with my MK4 MMU and couldn't ever cancel object from prusa connect.

**Comment by ChrisHeerschap** [comment]
I've been sending to connect via a physical printer with the PrusaConnect API in 2.7.x, that didn't work, and now I'm printing direct to PC from 2.8.0 and it's still not showing the cancel object option on anything. Printer always shows cancel object and it works, but somehow the cancel object never shows up in PrusaConnect.

**Comment by B-0-B-B-Y** [comment]
> @B-0-B-B-Y can this issue be closed now, or is there anything else?

It seems the behaviour is inconsistent, so would be good to keep this open still until we can get confirmation that it works on a consistent basis

**Comment by JPMakesStuff** [comment]
I'm still interested in this...  Reason: I'm watching printer remotely on webcam, notice one object is failing, want to skip current object remotely via API call
