### ISSUE TITLE
[BUG] MK4 5.1.0 CRASH on Octoprint reboot

### ISSUE THREAD

**Issue by taquitos** [prusa3d/Prusa-Firmware-Buddy#3584]
**Printer type** - [MK4]

**Printer firmware version** - [5.1.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [N/A]

**USB drive or USB/Octoprint** - [**OctoPrint**]

**Describe the bug**
Rebooting the pi 4b while connected triggers a crash.
OctoPrint 1.9.3

**OctoPrint Plugins installed**
- BGCode (0.2.0)
- Camera Settings (0.4.3)
- OctoPod Plugin (0.3.16)
- UPS (0.0.1)

**How to reproduce**
1. Connect OctoPrint
2. Click "Power" icon on OctoPrint website
3. Select "Reboot System"
4. 💰

**Expected behavior**
I expect a graceful handling of the disconnect

**Crash dump file**

[dump_buddy<with api keys, and wifi credentials redacted, come on now>.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13651950/dump_buddy.with.api.keys.and.wifi.credentials.redacted.come.on.now.bin.zip)

**Comment by mixer3d** [comment]
@taquitos https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3528

**Comment by taquitos** [comment]
> @taquitos #3528

Well f-me. Thank you for pointing this out

**Comment by bkerler** [comment]
@taquitos most probably related to this issue #3554

**Comment by taquitos** [comment]
> @taquitos most probably related to this issue #3554

Yup, the more noise customers make about the issue the more likely the issue will be prioritized, I'm guessing 😅

**Comment by bdlabitt** [comment]
Quite reproducible and annoying for me as well.
MK4, 5.1.2, Octoprint 1.9.3, Octopi 1.0.0
Reboot the RPI4 and watch dog time out occurs on the MK4.  Honestly, not acceptable behavior.
![PXL_20240129_213900130](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/26691788/87522ff0-0ea5-4c3a-ae1a-ce35b9fda1b2)

**Comment by bkerler** [comment]
This bug is already addressed in issue #3554 and is said to be fixed the 5.2 release
