### ISSUE TITLE
[BUG] XL multitool can move active tool into parked tools after a collision causing damage

### ISSUE THREAD

**Issue by tg73** [prusa3d/Prusa-Firmware-Buddy#3586]
**Printer type** - XL multitool

**Printer firmware version** - 5.1.0 release (original)

**Describe the bug**
If collision detection is disabled (which it is by default, and must be disabled for input shaper), the XL can experience collisions leading to significant XY position misalignment, and can then drive the active tool into the parked tools with significant force causing damage.

**How to reproduce**
Any print which can lead to a collision, for example see #3578.

**Expected behavior**
The XL should not be able to move the active tool into the parked tool area except when performing tool change operations and when in a known pre-homed, collision-free state with accurate XY positioning.

**Comments**
The XL now has input shaper (IS) as a release feature (FW 5.1.0, PS 2.7.0) and so Prusa is is actively encouraging and sanctioning its use. However, crash detection must be disabled, and is disabled by default. This means that there is no protection against the active tool being driven with force into the parked tools due to misalignment after a collision. I'd suggest that the XL should either require that collision detection is enabled, or it should have an additional safety sensor that detects when the y carriage moves into the "tool change operations only" zone. This would allow the firmware to detect dangerous movement during normal print operations and then take appropriate action. The additional sensor could be for example a hall effect sensor attached to the chassis with a magnet on one of the y-carriage parts. Even if collision detection is enabled, the additional sensor would provide a second line of defence against the printer damaging itself due to an undetected collision. As far as I am aware, this is the first Prusa printer that has been able to damage itself like this, so a different attitude towards disabling crash detection is needed. For example, the worst that will happen to a MK3 after an undetected collision is hitting an endstop.

**Comment by tg73** [comment]
[Here](https://forum.prusa3d.com/forum/original-prusa-xl-tool-changer-general-discussion-announcements-and-releases/psa-prusa-connect-control-may-move-without-homing-and-collide-with-docked-tools/) you can see an example of the force involved and the kind of damage that can result (in this example, all tools were parked, so the damage was to the toolchanger itself).

Here are some contact point examples (posed by hand when the machine was powered off):

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1101693/9f60b704-1228-4517-b96d-abacaad12375)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1101693/30bd121c-da79-4a4d-b79e-d26f64a0b180)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1101693/8be5b663-2d50-46b9-952e-2700c11facfd)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1101693/d1ac4c8b-493b-48c2-abc8-7c75c951958a)

**Comment by tg73** [comment]
Waiting for Prusa to respond.

**Comment by danopernis** [comment]
@tg73 is this actual bug with actual reproducer, or are we just speculating here?

**Comment by tg73** [comment]
@danopernis The link in a [previous comment](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3586#issuecomment-1853789366) shows the real-world damage made to the toolchanger head by a dock collision. It therefore seems logical to assume that damage could result to a loaded toolhead. [Here](https://youtu.be/3PobTR-zJOU?si=rexgrKTtPmf8Ktga&t=81) is a video showing the toolhead crash into the dock after a layershift (not my video, just from yt searching). Note the camera shake from the force of the collision.
