### ISSUE TITLE
[BUG] Extra filament purge when changing colors

### ISSUE THREAD

**Issue by mashbrno** [prusa3d/Prusa-Firmware-Buddy#3588]
**Printer type** - MK4

**Printer firmware version** - 5.1.0

**Original or Custom firmware** - Original

**Optional upgrades** - [e.g. Filament Runout Sensor]

**Describe the bug**
When changing color the printer asks whether the color is correct or to purge more. Unline standard filament change in this case when I press YES an extra approx. 3cm are purged and the print immediatelly continues, so there is no chance to remove it safely. 

**Expected behavior**
Possible options:
* don't purge if not necessary
* clean the head somewhere outside printed object (if there is enough space around the object, eg. bottom right corner)
* wait few secs to let user to remove it manually

**Comment by bkerler** [comment]
Actually that's no bug but a feature request, however the purge is needed to repressure the nozzle. However I think the easiest would be to enable a wipe tower in prusaslicer in order to prevent the need to clean the nozzle, similar to what the mmu does.

**Comment by miltieIV2** [comment]
I ran into this printing 9x8 MultiBoard panels (nearly full x/y print volume):
Spool change with no where to wipe.
Extra drib after Color ok? YES.

There should be an extra "OK to resume print?" dialog.
