### ISSUE TITLE
[BUG] "Mass (W) must be greater than 0" error

### ISSUE THREAD

**Issue by jerrygrey** [prusa3d/Prusa-Firmware-Buddy#3592]
**Printer type** - MINI+

**Printer firmware version** - 5.1.0

**Original or Custom firmware** - Original

**Describe the bug**
PrusaSilcer emits `M74 W0` on first layer resulting in the error, "Mass (W) must be greater than 0". According to the [comment for M74](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/15d5ae0b317a37b69b8e7a4720711b962c25b57d/lib/Marlin/Marlin/src/gcode/feature/input_shaper/M74.cpp#L44), the g-code sets "the total mass in grams of everything that is currently sitting on the bed." It seems like a value of zero is valid and expected. The [comparison](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/15d5ae0b317a37b69b8e7a4720711b962c25b57d/lib/Marlin/Marlin/src/gcode/feature/input_shaper/M74.cpp#L49) should be changed to allow for zero values. 

**G-code**
`M74 W0`

**Comment by bkerler** [comment]
The error "Mass (W) must be greater than 0" is actually related to the M74 gcode command and not the M572 command afaiks: https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/15d5ae0b317a37b69b8e7a4720711b962c25b57d/lib/Marlin/Marlin/src/gcode/feature/input_shaper/M74.cpp#L54

**Comment by bkerler** [comment]
After testing the firmware, the error "Mass (W) must be greater than 0" does only appear with M74 gcode command if the value is 0. The Smooth time (between 0 and 0.2) would instead indicate the error "Pressure advance smooth time (W) value out of range (0-0.2)". I don't see any relation between M74 and M572 in the code to be honest ...

**Comment by jerrygrey** [comment]
@bkerler I double checked and you're correct the two are not related.

**Comment by jerrygrey** [comment]
Updated, related [PR#3594](https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/3594)

**Comment by bkerler** [comment]
I've updated the PR and can confirm that prusaslicer indeed ALWAYS adds "M74 W0" with IS, so the PR does make sense except if prusaslicer shouldn't set the weight to 0 at all.

**Comment by bkerler** [comment]
It's now merged so this issue can be closed :)
