### ISSUE TITLE
[ENHANCEMENT] API Length of the filament used

### ISSUE THREAD

**Issue by eWuPi** [prusa3d/Prusa-Firmware-Buddy#3595]
[MK4I]

I would like information about the length of the currently used filament for each print, so that I can know how much is left on the spool without measuring the weight of the spool.

This information could be extracted from the extruder, from the number of revolutions. If MMU is used, it would be good to have such information for each filament. You could extend the JSON API "progress" with this information

**Comment by bkerler** [comment]
I'm not sure if length would be a good information as the thickness varies per length, even if you would directly count the revolutions. It would only be a rough estimate imho. Moreover, filament changes happen often not just when the filament spool is fully used, it would also require setting the current length for each spool on change making it very user unfriendly.
