### ISSUE TITLE
[FEATURE REQUEST] Time when will be needed to change color on main screen

### ISSUE THREAD

**Issue by Gyrxiur** [prusa3d/Prusa-Firmware-Buddy#3598]
**Printer type** - All of FDM printers

It would be nice to predict requested filament change and show time when it will occur and also remaining time till it happens on main screen, so we could do something else while printing and know when to come back to printer to swap filament.

**Comment by gdbarron** [comment]
Duplicate of #3107 ?

**Comment by Gyrxiur** [comment]
Oh, so it is already here, sorry.
