### ISSUE TITLE
[BUG] Filament Change (german version) shows [J ][MEH] statt [Ja][nein]

### ISSUE THREAD

**Issue by MagWolfgangPraxl** [prusa3d/Prusa-Firmware-Buddy#3611]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Prusa MINI+** - [MINI]

**5.1.2** - [e.g. 4.0.5, ...]

**Original** - [Original/Custom]

** Filament Runout Sensor** - [e.g. Filament Runout Sensor]

**USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint

**Filament Change (german version) shows [J ][MEH] statt [Ja][nein]**

** Go to "Filament Change (german version)" --  follow instructions**
  Please describe steps to reproduce the behavior.

**Is Filament clean -- [Ja][nein]**

**Comment by bkerler** [comment]
Can you please upload a picture ? This way it's easier to see if that's a translation issue or a bug.

**Comment by bkerler** [comment]
I assume this screen: 
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6317772/97adfd00-5666-462b-b6d3-b13292338968)

**Comment by bkerler** [comment]
That's a translation issue / Screen layout issue:
It should say "JA", "MEHR", "WIEDERHOLEN".
By shortening "WIEDERHOLEN" to "WDH.", the screen would look like this:

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6317772/edaceb65-f4b4-4f80-adb7-5205b5256b81)

Would this be acceptable (Would be easiest to fix) ?

**Comment by Th3Rom3** [comment]
> That's a translation issue / Screen layout issue: It should say "JA", "MEHR", "WIEDERHOLEN". By shortening "WIEDERHOLEN" to "WDH.", the screen would look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/6317772/291421186-edaceb65-f4b4-4f80-adb7-5205b5256b81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Mzk4NjcsIm5iZiI6MTcwMjkzOTU2NywicGF0aCI6Ii82MzE3NzcyLzI5MTQyMTE4Ni1lZGFjZWI2NS1mNGI0LTRmODAtYWRiNy01MjA1YjUyNTZiODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMjI0NjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFiOGRlZDhiNjA2Yzk3ZDc3YmM2ZGE1MWMyMmEzMTI3ZmYzYzczOTYwMzJhODcyYmMyZjNjNDE3MGI4MWVmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L0qKOJubADx4MugVugW0_odCSSm9RcixY5VOK0_3ZpI)
> 
> Would this be acceptable (Would be easiest to fix) ?

I wouldn't say that "Mehr" is the correct negative reply to the question "Ist die Farbe korrekt". It makes sense in context but isn't technically correct. I personally would go with "Ja" "Nein" "WDH."

**Comment by bkerler** [comment]
@Th3Rom3 Yes, exactly that was my feeling about it as well. But the way this menu was designed, it is as it is.
@MagWolfgangPraxl Ok, will push a PR for it tomorrow :)

**Comment by bkerler** [comment]
PR #3614 has been pushed :)

**Comment by danopernis** [comment]
New version of the firmware 6.1.2 should contain the fix, can you test that?

**Comment by bkerler** [comment]
@MagWolfgangPraxl can you then please close the issue if everything is fine by now ? :)
