### ISSUE TITLE
[BUG] PrusaConnect OTA upgrade to 5.1.2 downgraded my printer to 4.6.4

### ISSUE THREAD

**Issue by DominikPalo** [prusa3d/Prusa-Firmware-Buddy#3612]
**Printer type** - [MK4]

**Printer firmware version** - [5.1.0]

**Original or Custom firmware** - [Original]

**Describe the bug**
Today, I tried to upgrade the firmware on my Prusa MK4 printer using the PrusaConnect OTA upgrade functionality. I navigated to the settings page, clicked on the "Select firmware to flash" bolt icon, and chose version 5.1.2 from the dropdown menu:
<img width="503" alt="image" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1623257/3772daea-a281-42da-b94b-aead7cad57b4">

However, instead of flashing version 5.1.2 (I'm 100% sure I clicked on the last/5.1.2+13478 item), PrusaConnect unexpectedly displayed a message "Transferring firmware 4.6.4.": 🤯
<img width="449" alt="image" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1623257/3f00ebcb-27f9-4295-8d51-8f172a533b2a">

I hoped it was just a UI issue, but unfortunately, after a while, the printer restarted and downgraded itself to 4.6.4. To make things even worse, the printer was not only downgraded, but all my printer settings were gone (like factory reset) - I had to recalibrate everything, set up the Wi-Fi, and configure PrusaConnect all over again. Then I manually upgraded the printer to version 5.1.2 using the USB flash drive.

Guys, this is a really serious issue that needs to be addressed ASAP - I spent maybe 30 minutes resolving it and applying all my custom settings back (and I'm still unsure if I might have overlooked something). 😞

**Comment by danopernis** [comment]
@DominikPalo sorry for taking so long. Seems like you are the only one experiencing this issue so far. This is not an issue in buddy firmware, rather the Prusa Connect. They unfortunately don't have a github repository, but I was told that there is a button to report feedback in the Prusa Connect itself.
