### ISSUE TITLE
[Bug] Remote printing w/ Octoprint - filament change not working

### ISSUE THREAD

**Issue by Isaac12x** [prusa3d/Prusa-Firmware-Buddy#362]
Further to issue #360 during remote printing when the printer reaches the M600 command in GCODE
extruder pulls out the filament and waits for user input (a.k.a. continue when the new filament is loaded).

So, while doing that, when the new filament is loaded and I press continue, the printer comes back to the remote printing screen without loading the filament. Funny thing is it doesn't come back to print either.

Prusa mini FW version 4.0.5, Prusa slicer 2.2.0

**Comment by d-sko** [comment]
Same here, also with FW 4.0.5 and PrusaSlicer 2.2.0. Seemingly there is no way to resume the print after the filament is unloaded.

**Comment by Isaac12x** [comment]
I've dug a bit more in the issue trying to execute the G-code sequence manually. However, the receiver seems to be stuck in some sort of loop.

I guess it's expecting user input (press continue button when the new filament is loaded) but not registering the button press.

Message is:
"Recv: echo:busy: paused for user"

**Comment by derpicknicker1** [comment]
Same problem here...

**Comment by davetyra** [comment]
This may be related, M601 M602 as inserted in the preview screen of PrusaSlicer 2.2.0 has similar behavior, printer pauses, but will not resume when button is pushed, this is printing from USB, not remote. FW 4.0.5 and PrusaSlicer 2.2.0

**Comment by Iqwertz** [comment]
I have the same Problem!

**Comment by JohnnyDeer** [comment]
Hi, in new FW version 4.1.0-RC1 is M600 repaired for printing via OctoPrint. Please try it out. I´m closing this issue as solved.

**Comment by dwineman** [comment]
Just tried it — the problem has not been fixed. Filament unloads, printer returns to the Octoprint screen. Never prompts to load new filament. "Change Filament" in the Tune menu does nothing. It is impossible to resume the print.

**Comment by ifekali** [comment]
Same here, not fixed yet.

**Comment by Crowlord** [comment]
Confirm not fixed. Multi coloured prints have to be done from USB stick.

**Comment by deltwalrus** [comment]
Confirmed here as well, not fixed.

**Comment by JohnnyDeer** [comment]
I can confirm too. Sorry to all, lesson for me... test everything by myself.

**Comment by JohnnyDeer** [comment]
Finally this issue should be fix in 4.1.0 final. Please try it and confirm that it is fixed :)

**Comment by olsw** [comment]
Can confirm this is definitely working now. Thanks!

**Comment by danielo515** [comment]
> Finally this issue should be fix in 4.1.0 final. Please try it and confirm that it is fixed :)

4.1.0 of which software? Prusa-slicer? Octorpint? Something else?

**Comment by danielo515** [comment]
Whatever it was, it's working for me now, haha

**Comment by s-taylor** [comment]
So I’m on the latest firmware 4.3.3 and this did not work for me. I have since done a factory reset and now it works for me, hope this helps someone else.

**Comment by twobit0** [comment]
Still Not addressed on 4.3.4

**Comment by Crowlord** [comment]
Why was this ever closed. Its never been fixed?

**Comment by danielo515** [comment]
Stale doesn't mean fixed

**Comment by danopernis** [comment]
Stale indeed doesn't mean fixed, but it does mean that the issue did not receive any updates in a long time.

@danielo515 can you test if the issue is still present in the newest version of the firmware? There have been several improvements and bugfixes since 4.0.5
