### ISSUE TITLE
Random Filament changes during print now on 5.1.2, also present during 5.1.0[BUG] <Enter comprehensive title>

### ISSUE THREAD

**Issue by b4de4nd** [prusa3d/Prusa-Firmware-Buddy#3620]
So ive run into a couple of random filament changes during some prints. Its not been a lot, but now ive had 2 changes in the same print randomly at both 16% and at 24% into the print.

Sliced with Prusaslicer 2.7.1 to printer MK4 on firmware 5.1.2 sliced with generic petg profile, MK4 IS 0.4 profile standard and structural 0.2 layer. Sliced into the new Bgcode and send via prusalink to the printer and print started on the printer it self.

This happened a couple of times on the 5.1.0 firmware also, but never more than 1 time on a print.

**Comment by mix579** [comment]
Sounds a lot more like an issue with the filament sensor than a slicer bug?

**Comment by bkerler** [comment]
Doesn't sound like a fw bug, as mix579 said, more like a filament sensor issue, maybe due to filament/plastic parts blocking the sensor.

**Comment by danopernis** [comment]
Not a firmware bug
