### ISSUE TITLE
Issue printing multicolor OBJ files with single extruder on latest firmware

### ISSUE THREAD

**Issue by Dmalin3D** [prusa3d/Prusa-Firmware-Buddy#3623]
Printer type - MK4
Printer firmware version - 5.1.2

SD card or USB/Octoprint
USB Drive

Describe the bug
When printing a OBJ with mutliple colors and a tool change between each color the screen goes blank when you press print (the time and date or w/e is still there but the rest is black). If I revert to the 5.0.0. Firmware it prints fine

To Reproduce
Try to print this 3mf
https://drive.google.com/file/d/1o_Frxv_obycrUB4JjUKvbszUhyORSPVz/view?usp=sharing

G-code
Please attach a G-code. This will make it easier for us to replicate the error.
gcode file on attached google drive link
https://drive.google.com/file/d/1eWKwu8L52aaGpylit99Z1Kh3-EZpao2B/view?usp=sharing

**Comment by bkerler** [comment]
Related to issue #3525
