### ISSUE TITLE
sensorinfo temp heatbrake+boardtemp not shown

### ISSUE THREAD

**Issue by Cbokar** [prusa3d/Prusa-Firmware-Buddy#3626]
After some time of printing, 1 hour or so, there are no more temperatures shown under: settings— info —sensors: heatbreak and boardtemperature are shown as: not initialized. 
After a reset the temps are shown properly again.
Printer type - Mk4, factory assembled. FW 5.1.2 slicer 2.7.1

No matter what gcode file, gcode or bgcode, no matter printed from usb directly ore send via connect
    
At the beginning of a print:
https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/153955662/d08ad9e6-4f1b-440a-8006-b5fbd845312d

At the end of the print.
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/153955662/ccf1bdba-e08f-426f-b90d-8f638d7fcd0a)

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/153955662/92555e92-70a8-4198-b00b-b7c8d4dd1a1a)

**Comment by Cbokar** [comment]
https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/153955662/23b69871-41f0-4cf6-a465-8b49b69d4678

If slowed down. One sees, that each reading is switching from not initialized to the correct reading.
Somehow, after a while only those two values are stuck: not initialized?

**Comment by bkerler** [comment]
Could be related to issue #3554

**Comment by bkerler** [comment]
I can confirm the same behaviour on my MK4. So clearly a bug.

**Comment by H0Z0** [comment]
FW 6.0.0 still has this phenomenon. By the way, not only the board and heatbreak temperatures are not displayed ("not initialized"), but the print fan and heater fan are also N/A in this case. If the board and heatbreak temperatures sometimes show up, it also shows the fans well.
