### ISSUE TITLE
[FEATURE REQUEST] Disabling Thermal Model

### ISSUE THREAD

**Issue by wszeto9** [prusa3d/Prusa-Firmware-Buddy#3638]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - [MINI]
**Optional upgrades** - [For non-stock hotends]

**Is your feature request related to an existing problem? Please describe.**
 I installed a mosquito hotend on my prusa mini and the thermal model keeps complaining that the temperature doesn't match what's expected. There's currently no way to fix this, and the current answer is "the model works perfectly so we don't need to change it" ... except it doesn't work perfectly. I know for a fact my hardware works, as it has been working before I updated the fw to the newer thermal model. It tends to overshoot by ~ 10 degrees and the firmware shuts off the heater, but it is stable when I re-heat the heater. Changing PID values decreases overshoot, but the model still complains of temperature mismatch. 

**Describe the expected functionality**
Works like on the MK3 as described in https://help.prusa3d.com/article/thermal-model-calibration_382488 , where there is a menu button to disable the new thermal model or a G-code command.

**Comment by dpark12300** [comment]
There is a GCODE Command. 
M310 S0
then send
M500
