### ISSUE TITLE
[BUG] 0.6 nozzle sporadic underextrusion

### ISSUE THREAD

**Issue by bdynamic** [prusa3d/Prusa-Firmware-Buddy#3639]
**Printer type** -  MK4

**Printer firmware version** - 5.1,2

**Original or Custom firmware** -[Original/

**Optional upgrades** - 0.6 Nozzle

** Used USB drive

**Describe the bug**
  When using the 0.6 Nozzle there is a sporadic underextrusion in the first layer (see photos). This bug existed at least in the last two FWs. If the error occures it seems to persist. Reset of printer and restarting the very same GCODE normally solved the problem. If the problem exists there is no difference in printing via Octopring or from USB. The problem strength seem to differ. Sometimes there is even a visible gap between the outer printlines.

**How to reproduce**
  unknown. Sporradic occurence

**Expected behavior**
  Always a good print

**G-code**
[Remote_holder.3mf.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13769735/Remote_holder.3mf.zip)
[Remote_holder_0.6n_0.2mm_PETG_MK4IS_37m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/13769930/Remote_holder_0.6n_0.2mm_PETG_MK4IS_37m.gcode.zip)

**Crash dump file**
The Crashdump file was generated after the reset (when everything was fine again). A new one can be provided as soon as the problem occures again. File sent by Email

Bad example:
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/12560294/856b37ca-6a27-4443-b836-07e2b7671145)

Good print, same GCODE:
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/12560294/4b3626df-91ad-4e91-9979-2b0b7204592b)

**Comment by TheMoen** [comment]
I had this issue yesterday, It appears to be from oozing after the last print etc..
The reason it is an issue is that both cleaning and probing with the nozzle happens at 175°C. PETG simply is not soft enough at that teperature, so the printer belive the printbed is higher than it actually is. Leading to incorrect "first layer calibration". make sure the nozzle is clean if you are having this issue.


Not sure if this is a slicer setting or firmware..

**Comment by alecharp** [comment]
Thank you @TheMoen for the explanation. I just got that problem and you are right, I'm only seeing this with PETG.

> The reason it is an issue is that both cleaning and probing with the nozzle happens at 175°C. PETG simply is not soft enough at that teperature, so the printer belive the printbed is higher than it actually is. Leading to incorrect "first layer calibration". make sure the nozzle is clean if you are having this issue.

But in that case, couldn't the "nozzle cleaning" step be done at a different temperature, higher for filament requiring it? That could be done in the FW, no? 

I would like to add that I clean the nozzle, pre-heating (to not mess with the auto leveling / pushing on the nozzle). However, it is possible that some PETG filament "leak" through the nozzle when it comes to temperature. So it gets soft enough to leak, but not enough to be cleaned correctly before the leveling.

**Comment by Eriobis** [comment]
I am seeing the same kind of issue, but with PLA.
Firmware 6.0.0 using 0.6 nozzle.
PETG + textured bed  always work fine but with PLA and PEI smooth sheet I get nasty result for the 1st layer. :(
