### ISSUE TITLE
Does not allow upload of .bgcode (binary)

### ISSUE THREAD

**Issue by jackdesert** [prusa3d/Prusa-Firmware-Buddy#3654]
Prusa-Link lets me upload .gcode files, but not .bgcode.

Using MINI+ with prusa-buddy 5.1.0 firmware.

**Comment by dpark12300** [comment]
Maybe update to 5.1.2
Not sure if it will fix, but always good to try

**Comment by dpark12300** [comment]
Huh.

**Comment by bkerler** [comment]
This issue should be closed and reopened [here](https://github.com/prusa3d/Prusa-Link-Web) instead, as it's not related to the xbuddy fw but to PrusaLink.
