### ISSUE TITLE
[ENHANCEMENT] Option to disable filament color confirmation

### ISSUE THREAD

**Issue by FutureSharks** [prusa3d/Prusa-Firmware-Buddy#3659]
By default the printer asks for confirmation that the filament color is correct when loading or changing filament. I think this is a waste of time for many users because:
- The filament spool is normally right next to the printer
- The teflon filament tubes are partially transparent

i.e. the filament color is pretty obvious

An option to disable this confirmation would be great and would save a bit of time for many users.

**Comment by bkerler** [comment]
Can you please got more into detail ? (Screenshot of the confirmation display that you mean)
Do you mean the confirmation that the old filament was unloaded ?
For me, the confirmation of filament change is important as the color normally isn't clean for the change for some filaments (for example switching from black to white), thus more filament has to be purged to get a clean color. But if you use virtual extruders in combination with a wipe tower, I agree that disabling the confirmation would be an useful option.

**Comment by FutureSharks** [comment]
> Can you please get more into detail ? (Screenshot of the confirmation display that you mean)

I mean this:

<img width="447" alt="image" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/5198883/aec26fc7-16db-46a5-b920-92ae9e904b7d">

> For me, the confirmation of filament change is important as the color normally isn't clean

Interesting, I've never had this so for me it's just waste of time. I imagined it's like that for most users but perhaps this assumption is wrong?

**Comment by bkerler** [comment]
That's the purge screen. In my case I really need it for filament switches when the color purged isn't clean enough. Of course if you always use the same color, this menu shouldn't appear (but it does for now).
