### ISSUE TITLE
Total print statistics

### ISSUE THREAD

**Issue by josecoelho96** [prusa3d/Prusa-Firmware-Buddy#366]
Similar feature to others like the MK3, show a total summary of some statistics:
- Total Print Time
- Total Filament
- Total Number Prints

Just for enhancement and curiosity.

**Comment by x10102** [comment]
Totally would like to see that!


Dne út 14. 4. 2020 17:13 uživatel José Coelho <notifications@github.com>
napsal:

**Comment by iandouglas** [comment]
I'd love to see these stats even if printing with tools like OctoPrint. I've printed miles and miles of filament through OctoPrint on mhy MK3/MK3S as well, but none of it gets reported via firmware unless printing via USB. Would be nice to see this on the Mini as well.

**Comment by 4nthonylin** [comment]
Any update on this? +1 For this. Another great feature with stats would be the ability to inform users of maintenance.

For example:
1) Every 100 hours, inform users to clean/lubricate rods, and then confirm when done. Printer can internally track next cycle
2) Check belt tensions
3) Replace any consumables (PTFE Tubes) etc

Basically something like a car maintenance cycle.

**Comment by hemdrup** [comment]
Yes, this would be cool.

**Comment by DanidCH** [comment]
Even if the calculation isn't 100% perfect this would be of great help to know when is a good time to do maintenance!

**Comment by JohnnyDeer** [comment]
Hi, this feature is implemented in new 4.3.3-RC. You can try it out https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.3.3-RC.

**Comment by Eldenroot** [comment]
@Prusa-Support - this is done :)

**Comment by Prusa-Support** [comment]
Closing. Thanks 🙂 

Michele Moramarco
Prusa Research
