### ISSUE TITLE
[BUG] Stuck on "delete credentials file" after 5.1.2 upgrade (MK4)

### ISSUE THREAD

**Issue by albancreton** [prusa3d/Prusa-Firmware-Buddy#3661]
**Printer type**
MK4

**Printer firmware version**
5.1.2

**USB drive or USB/Octoprint**
USB drive

**Describe the bug**
After installing 5.1.2, my MK4 updated the wifi and got stuck on this screen:
![screen](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/100890/00be98ed-3432-4a4e-97bc-43aa93d772f2)
Neither button work. I pressed the physical reset button and the printer rebooted just fine, but with no wifi connection.

**How to reproduce**
Update from 5.0.1 to 5.1.2

**Video**
https://we.tl/t-fmdwpPgHVm

**Comment by bkerler** [comment]
Seems the esp32 firmware wasn't upgraded correctly. Downgrade to 5.0.1 and the reupgrade to the next firmware version (do not skip firmware versions in between). Other users had similar issues and were able to fix this issue that way (some had to downgrade to pre-IS firmware 4.x before it worked). If it still persists, make sure to set the factory default before upgrading.

**Comment by albancreton** [comment]
I tried what @bkerler recommended and the problem persisted.
Eventually, I completely reset the printer and reinstalled it from 5.1.0
The bug stopped occurring, the exp32 firmware process goes to the end and the credentials appears to be loaded, but my printer won't connect to the wifi network anymore. Not sure own to do further diagnostic (network log ?)

**Comment by bkerler** [comment]
I guess you should then contact the support, most probably your esp32 board is defective.
