### ISSUE TITLE
[BUG] Spool Join in XL does not prime next tool before printing

### ISSUE THREAD

**Issue by hickengr** [prusa3d/Prusa-Firmware-Buddy#3666]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI, MK4, XL]  XL

**Printer firmware version** - [e.g. 4.0.5, ...]  5.1.2

**Original or Custom firmware** - [Original/Custom]  Original

**Optional upgrades** - [e.g. Filament Runout Sensor]  No upgrades - purchased with 5 tool heads

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint
Use USB flash drive only

**Describe the bug**
Using spool join, the next tool used after the original tool runs out of filament does not purge filament before printing which causes under extrusion in small part of print.

**How to reproduce**
  Please describe steps to reproduce the behavior.
Select tool 2 as primary tool head and select tool 3 as joined tool.  Let the print run until tool 2 runs out of filament and switch to tool 3.  Tool 3 will be heated to running temperature and, once reached, the XL will immediately start printing without priming the nozzle.

**Expected behavior**
After tool 3 heats up and gets picked up, the XL should prime the tool for that filament just like it did for tool 2 at the beginning of the print.

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.
This is not G-code dependent.

**Crash dump file**
  Please send the crash dump file to Prusa by emailing it to reports@prusa3d.com. Sharing this file is important and helps us investigate the bug.
No crash was detected.

  Do not share the file publicly, as the crash dump contains a raw snapshot of the printer's memory and may include unencrypted sensitive information.

**Video**
  Please attach a video. It usually helps to solve the problem.
No video needed as this is easy to replicate and I do not have a spool that is running low of filament at the moment.

**Comment by ManuelS383** [comment]
Have the same Problem at 6.0.1 would be glad if this could be fixed. Just lost some TreeSupports and so the print, because of underextrusion after SpoolJoin switch.
