### ISSUE TITLE
[FEATURE REQUEST] Add CPE to preheat menu

### ISSUE THREAD

**Issue by brunofresco** [prusa3d/Prusa-Firmware-Buddy#3667]
**Printer type** - [Prusa XL]

**Is your feature request related to an existing problem? Please describe.**
When I print with CPE there is no preheat function to it but there is an option on the slicer for Filamentum CPE but the printer says it is not the correct filament type.

**Describe the expected functionality**
When I put the CPE in it should not say wrong filament as I had to preheat with a different filament profile.

**Comment by bkerler** [comment]
Also referring to PR #3657.
