### ISSUE TITLE
[FEATURE REQUEST] Option for customised filament preheating

### ISSUE THREAD

**Issue by brunofresco** [prusa3d/Prusa-Firmware-Buddy#3668]
**Printer type** - [Prusa XL]

**Is your feature request related to an existing problem? Please describe.**
Because I sometimes use different filaments, I always get errors that the correct filament is not loaded.

**Describe the expected functionality**
There should be a functionality to add custom filaments to the preheat menu and name them, or when it is time to preheat to load a filament, a function called "load custom filament".

**Comment by bkerler** [comment]
There's already a PR for that: #3657. However naming them individually won't be possible with the current state of the firmware.

**Comment by Prusa-Support** [comment]
This issue can actually be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1258.

Michele Moramarco
Prusa Research
