### ISSUE TITLE
Temp during mesh bed leveling on first layer calibration isn't "cold" temp

### ISSUE THREAD

**Issue by nwalke** [prusa3d/Prusa-Firmware-Buddy#368]
During mesh bed leveling the mini cools to 170c, unless you're using the first layer calibration.  I just had it leave little blobs all over my print bed due to it running mesh bed leveling at 215c instead of 170c.

**Comment by JohnnyDeer** [comment]
Hi @nwalke  , thank you for reporting, but this issue is already reported. I'm closing this one as duplicate of #157
