### ISSUE TITLE
[FEATURE REQUEST] <Print Planner or Timer>

### ISSUE THREAD

**Issue by brunofresco** [prusa3d/Prusa-Firmware-Buddy#3687]
**Printer Type** - [XL5]

**Does your feature request relate to an existing problem? Please describe.**.
I would like to be able to start a print job at 8:00 in the morning before I get up.

**Describe the functionality you expect**.
I expect it to have a menu, maybe called print queue, and it could ask me what time I want to start what print. And then just show a countdown timer with time left to start the print.

**Comment by BugsBunny1403** [comment]
Cool idea
