### ISSUE TITLE
[BUG] When uploading files to prusa connect printer pauses stating, "USB drive or file error".

### ISSUE THREAD

**Issue by akubiczek** [prusa3d/Prusa-Firmware-Buddy#3689]
The bug similar to bug described here: https://github.com/prusa3d/PrusaSlicer/issues/11544 still exists for Mini+.

When uploading files to prusa connect printer does not start printing, displaying instead: "USB drive or file error". It happens like every 4 or 5 prints.

**Printer type** - MINI+

**Printer firmware version** - 5.1.2+13478

**Original or Custom firmware** - Original

**Optional upgrades** - None

**Comment by TechnoSwiss** [comment]
I've only noticed this when I'm trying to re-upload the last file I sent via PrusaConnect, what I've noticed is that after uploading the printer has already loaded the file and is waiting for me to hit continue to start the print (this is when I DON'T have print after upload selected). If I go to the printer and hit cancel, then I can go back to PrusaConnect and re-upload the file without the error. It does seem to be intermittent though.
