### ISSUE TITLE
Prusa Mini Stop button in display while filament is loading without function

### ISSUE THREAD

**Issue by Jan200696** [prusa3d/Prusa-Firmware-Buddy#370]
Since there is sometimes a mechanical error while loading filament, I want to stop the process without having to restart the printer. A stop button is shown on the display, but this cannot be selected.

**Comment by JohnnyDeer** [comment]
Hi @Jan200696 , it is purpose to not allow cancel during action, user can do it just before. Let's make this issue a feature request, about allowing user use cancel during action...

**Comment by JohnnyDeer** [comment]
I´m closing this issue as duplicate of #222.
