### ISSUE TITLE
[ENHANCEMENT] Automatic temperature based on speed

### ISSUE THREAD

**Issue by terminal-cs** [prusa3d/Prusa-Firmware-Buddy#3701]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - Any printer running prusa buddy firmware
**Optional upgrades** - not applicable

**Is your suggested improvement related to an existing problem? Please describe.**
With input shaping being added to all prusa printers that run the prusa buddy firmware, we have much higher speeds, but this also comes with the downside of needing to manually set temperatures for materials, as they have less time to melt in the hotend. It would be nicer to instead have an option in the firmware to calculate better temperatures based on speed and material, while taking into account limits to some materials, i.e. some may not print well when that hot.

**Describe the expected functionality**
  A clear and concise description of expected functionality.
I myself am not a developer for any of the software for prusa so i would not know if there's a better way to add it, but perhaps an option in the firmware to calculate better temperatures, and have it optional for those who don't want it. Or, if memory is a limiting factor, it could probably be implemented into the slicer.

I hope this reaches a developer and is considered, as i enjoy using prusaslicer and the default profiles, but i am not able to save to them, as they are read only, and personally i would be more comfortable with calculating the needed temps instead of entering them in myself.

Also to add to why this is needed in the first place, i have had issues with materials being not fully melted and causing the nozzle to drag on infill. Raising the temperature 10-20c seems to fix it entirely.

**Comment by murk-sy** [comment]
What you're describing is more akin to the hotend auto-tuning itself based on a particular material and speed.
Theoretically, the MK4/XL extruder with a hotend strain gauge *might* be capable of that, but Mini's certainly isn't.

What you should actually do is take a filament profile that works well, then adjust temperatures that give you good results and save it as its own filament profile.
Filaments of the same type from different manufacturers (or even from the same manufacturer) can have vastly different properties. Defaults can only get you so far and while I believe the strain gauge is the long term magic bullet to *improve* the printing experience and print quality, we've yet to see its theoretical capabilities in action.
