### ISSUE TITLE
[FEATURE REQUEST] Firmware update progress does not show bootloader update progress

### ISSUE THREAD

**Issue by twshield** [prusa3d/Prusa-Firmware-Buddy#3707]
**Printer type** - MINI+

**Printer firmware version** - 5.1.2

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
  USB flash drive (but not a printing issue)

**Describe the bug**
  Upgrading firmware from 4.4.1 with bootloader 2.0.2 to firmware 5.1.2:
 After the firmware installs, there is a verify step with a progress bar.
It got to 100% completed on the verify progress bar and then just sat there with no indication that it was still working.
It was long enough that I wondered if it had hung.
Then it started installing the 2.3.4 bootloader, which I'm guessing it was downloading (printer is connected to internet via wired ethernet) or maybe extracting when it appeared hung after the verify step.
This all completed successfully, I'm happy to say.

**How to reproduce**
  Upgrade from 4.4.1 firmware with bootloader 2.0.2 to version 5.1.2
  (only the single MINI_english-french_firmware_5.1.2.bbf file in the USB drive root directory)
 (with printer connected to internet -- if it was a download)
 Watch the progress indications.

**Expected behavior**
  Progress indication to make it clear that there is not a problem and that processing is still continuing.
  A downloading (or extracting, etc) bootloader progress bar would have been comforting to see.

**G-code**
 n/a

**Crash dump file**
  n/a

**Video**
  n/a

**Comment by bkerler** [comment]
This is a feature request, please relabel :)
