### ISSUE TITLE
[BUG] Load Filament to Extruders 2 to 5 will always heat up extruder 1 to 170°C

### ISSUE THREAD

**Issue by dhyananbho** [prusa3d/Prusa-Firmware-Buddy#3715]
**Printer type** - XL

**Printer firmware version**
  XL Firmware Version 5.1.2+13478

**Original or Custom firmware**
  Original

**Optional upgrades**
  Non

**USB drive or USB/Octoprint**
  Ethernet and USB flash drive

**Describe the bug**
  If you select the menu for loading the filament into one of the extruders 2 to 5, extruder 1 is always heated up to 170°C. This makes no sense.

**How to reproduce**
  see above

**Expected behavior**
  Only heat up the extruder that was selected for loading the filament.

**G-code**
  Non

**Crash dump file**
  –

**Video**
  –

**Comment by DoubleStrike** [comment]
Just got hit by this again, when loading Tool 5.  Magically, Tool 1 heated to 170 for no reason.

**Comment by geek5d** [comment]
To add to this, when loading all 5 tools, starting with 1, load complete, I select load 2, 1 parks and temp sits at 170, good. After 2 loads, and I then move to select 3, I notice 2 stays at the laod temp and does not drop to 170. In order to stop the oozing, I manuall drop 2 to 170, grab the ooze, then load 3, etc. Once the load is successful, can we automatically drop the temp to 170?

**Comment by ulab** [comment]
I can not reproduce this in 6.0.3+14902.

I have used the menu to load PETG into Extruder 5 and only this extruder is being heated up.

![Screenshot 2024-07-17 at 17 08 41](https://github.com/user-attachments/assets/b7375f55-c05c-4be0-ab52-3f2e9101ef68)

(Tool 3 is cooling down after being loaded)

**Comment by DoubleStrike** [comment]
This is still happening on 6.0.4+14924.  Any chance this can get bumped up the priority list?  I can see this as a potential fire hazard or injury risk when doing maintenance.

If I have tool 1 undocked and set to the side on a cardboard box for some maintenance, and I go to load filament into another head, an unexpected preheat could be VERY bad.  This is admittedly an edge case, but certainly not an unforseeable one.
