### ISSUE TITLE
Latest release is source-only

### ISSUE THREAD

**Issue by kozross** [prusa3d/Prusa-Firmware-Buddy#3725]
A new release [has been tagged](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v5.2.0), but it contains no prebuilt firmware (or any changelogs). Is this intentional or an oversight? As-current, unless you build it yourself, and have a broken appendix, you can't even use this, to say nothing of not knowing which printer(s) have any functionality changed.

**Comment by murk-sy** [comment]
This usually happens some time before release, but some other factory may be delaying it (for example, writing up the changelog or updates to other services that must be made before this version can be released).

You can *probably* expect the release within a few days.

**Comment by kozross** [comment]
Seems like the release notes and one image have been added. Closing this.
