### ISSUE TITLE
[BUG] Remote printing tuning

### ISSUE THREAD

**Issue by Isaac12x** [prusa3d/Prusa-Firmware-Buddy#374]
When using the remote printing option introduced in RC1 FW v4.0.5, where you can see the Octoprint logo on the screen this is what happens.

Remote printing screen --> tune --> change filament --> Nothing happens.

**Comment by jurcja1** [comment]
Same issue but during printing from USB. During print "change filament" - nothing happens.

**Comment by tangero** [comment]
Duplicated to #362

**Comment by tangero** [comment]
Hi Isaac,
Try please Factory reset. It looks like you have heating off.

**Comment by Isaac12x** [comment]
Hi @tangero, I already did that. Let me be more explicit.

While it is remote printing and the machine hits an M600 instruction, the filament is unloaded but you can't load a new one.  So in theory heating is on as the filament which was printing with gets unloaded.

Any other ideas?

**Comment by derpicknicker1** [comment]
Same problem here

**Comment by aaaaron** [comment]
Same problem, M600 issued through Octoprint never succeeds.

**Comment by JohnnyDeer** [comment]
Hi, this bug is fixed in 4.1.0, please try it out. I´m closing this issue as solved.
