### ISSUE TITLE
[BUG] Mk3.5 info show wrong bootloader version 

### ISSUE THREAD

**Issue by Lino77** [prusa3d/Prusa-Firmware-Buddy#3740]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK3.5] show incorekt bootloader see pic 
![prusa_mk4](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/11890989/2045c14a-2bfc-459f-b823-917fae63db78)

**Comment by arekm** [comment]
Note - when using "English" it shows correct bootloader version (2.3.4).

**Comment by bkerler** [comment]
@Lino77 Can you change to english language, does it show the right bootloader version ? And if you change back to german, does it still show the wrong version ?

**Comment by Lino77** [comment]
English shoes the right  bootloader back to german Shows thr wrong

**Comment by bkerler** [comment]
Ok, will dig into the issue

**Comment by Tomcus** [comment]
This issue seems to be fixed in 6.0.X, can you confirm that @Lino77 and then close the issue?
