### ISSUE TITLE
[BUG] MK3.5 - X Axis check fails

### ISSUE THREAD

**Issue by balcanusebi** [prusa3d/Prusa-Firmware-Buddy#3742]
Printer: MK3.5 Original Firmware 5.2.0
The X axis test fails. Please see attached video.
Went through all of the hardware checks with the Prusa Support team and no issues were found.

https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/22098405/cbd749ef-2f5a-491d-a078-3242b014d55b

**Comment by bkerler** [comment]
@balcanusebi The video is rather small. Can you do a higher quality video so that the x values can be seen on the display while the self-test is running ?

**Comment by balcanusebi** [comment]
> @balcanusebi The video is rather small. Can you do a higher quality video so that the x values can be seen on the display while the self-test is running ?

Sure, I've attached a new video.
Thanks for having a look at it!

https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/22098405/1c6803c5-4b74-49ce-8ca6-d879ae7395ec

**Comment by bkerler** [comment]
Ok, I think the problem might be that when the x-endstop is reached, the value is 250.67, but it should be 251 instead. Is there some kind of obstacle on the right size of your extruder or maybe the bearing that is too far on the right side ?

**Comment by bkerler** [comment]
Note: I'm referring to my MK4 here, no idea if for the MK3.5 250.67 is ok, but I don't think so.

**Comment by balcanusebi** [comment]
@bkerler there’s no obstacle on the X axis. I’ve even went that far and disassembled the entire X axis, replaced the bearings and made sure that everything is as it should be according to the instructions manual. 
The weird thing is that, with the MK3S+, the X axis checked without any issues. 
Would it be an idea to increase the “tolarence” on the X length? For example, everything that goes over the value of 250, to be considered as passed. 
Thanks for you help!

**Comment by bkerler** [comment]
I need to review the firmware, but I think this is something Prusa needs to have a look.

**Comment by Quantenradierer** [comment]
It looks like your heater fan screws are not fully in. Only the lower right fan screw seems to be correctly in.
Try to screw them more in - or remove them and test it without the screws at first.

The screws are propably hitting the y-axis on the left side when you test the x-axis, therefore the missing 3.3mm.
