### ISSUE TITLE
[ENHANCEMENT] Allow for skipping first time calibration (because I already did it)

### ISSUE THREAD

**Issue by slicedbread** [prusa3d/Prusa-Firmware-Buddy#3768]
**Printer type** - [XL]
**Optional upgrades** - [none]

**Is your suggested improvement related to an existing problem? Please describe.**
I did a firmware update on my XL and its asking me to re-run the first-time calibration now. I assume this is a bug but it would be really nice to be able to dismiss this warning somehow.

**Describe the expected functionality**
It would be really nice if there was an ability to remove this warning buried somewhere in the options, even if it was hidden in some way.

**Comment by bkerler** [comment]
If you do get this screen, it means that on the firmware update most likely the eeprom values have been wiped. I'd strongly recommend to rerun the first time calibration. After running the first time calibration, the warning should disappear. If not, then down- and reupgrade the firmware. If it then stays as well, contact support as your eeprom might be faulty then.
