### ISSUE TITLE
[ENHANCEMENT] Display numbers in a user-friendly form

### ISSUE THREAD

**Issue by dhlavaty** [prusa3d/Prusa-Firmware-Buddy#3771]
Printer: Prusa MK4
FW: v5.1.3

Would it be possible to display the numbers in a user-friendly form?

![IMG_3705](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/513138/aa905763-4088-44c7-bdbe-8845a1e09277)

**Comment by thomasloven** [comment]
That's approximately 1 % of the size of the visible universe. I don't think the way the number is displayed is your main problem...

**Comment by dhlavaty** [comment]
The observable universe is a sphere with a diameter of about 93 billion light-years. So...

Can we agree that `1.0e+21 km` is not a user-friendly form?

**Comment by thomasloven** [comment]
Don't mean to derail this topic, but I think 1.0e+21 km is rather user friendly. It's standard exponential notation for very large numbers and in my opinion better than `0.001 lyr` or `1000000000000000000000000 m` which would be two options to display roughly the same number.

Seriously though, something has gone horribly wrong in your printers estimation of the ammount of distance it has traveled - and expecting the user inteface to cater for that is pointless.
