### ISSUE TITLE
[ENHANCEMENT] Moving up footer indicators by a few pixels

### ISSUE THREAD

**Issue by ubermlin** [prusa3d/Prusa-Firmware-Buddy#3780]
**Printer type** - [MK4]

**Is your suggested improvement related to an existing problem? Please describe.**
I know this probably is a totally p5 feature/enhancement request, but I would love the GUI to have the feature of bumping the indicators in the footers by a few pixels upwards.

The attached photo shows the screen the screen at my current eyesight level (the MK4 is positioned in an elevated position in my setup).
![IMG_2592](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/142048316/0cbf528e-738a-41ad-87e5-b83e70a8bbbc)

It's not unusable by any definition, but it's also far from comfortable.

**Describe the expected functionality**
Create a mechanism to bump the footer up by a few pixels / bump up the footer globally for next releases.

[PRUSA INTERNAL NOTE] Mentioned in BFW-5050

**Comment by CZDanol** [comment]
Mentioned in BFW-5050
