### ISSUE TITLE
[BUG] Crash detection stops 3D preview

### ISSUE THREAD

**Issue by lggomez** [prusa3d/Prusa-Firmware-Buddy#3783]
**Printer type**
MK4

**Printer firmware version**
5.1.2

**Original or Custom firmware** 
Original

**USB drive or USB/Octoprint**
USB

**Describe the bug**
  The crash detection, after showing the screen warning and resuming the print successfully it stops the 3D render preview screen:

![Untitled](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6326271/ed704539-ae8d-4821-81b7-51ad2b81f59a)

**How to reproduce**
1. Trigger a nozzle crash of any type so the warning is shown on xLCD
2. Wait for the printer to re-home and resume printing

If I go back to the menu the view is restored and shows correctly after some time

**Expected behavior**
3D render preview should work after events during print initialization that cause view transitions

**G-code**
Not applicable

**Crash dump file**
Not applicable

**Comment by DRracer** [comment]
Crash detections are not supported on MK4
