### ISSUE TITLE
[FEATURE REQUEST] Add "PMMA" as a basic filament type to MK4 firmware

### ISSUE THREAD

**Issue by bryn51** [prusa3d/Prusa-Firmware-Buddy#3786]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** -[All] Including MK4, Mini and XL.]

**Is your feature request related to an existing problem? Please describe.**
 Poly Methyl Methacrylate (Acrylic) filament is a technical filament available from several sources.  Its characteristics differ from other filaments.  If incorrect type is selected, a nozzle clog can occur during the initialisation process.
When filament is loaded, the Nozzle and Bed temp need to be heated to the correct temp for filament to extrude properly and not to ooze.  The user need to recognise the name of she filament for selection.

**Describe the expected functionality**
Add PMMA as a basic filament type to MK4 (and other) printers, with characteristics compatible with the following:
Nozzle temperature: 220-260°C (start with 240°C and adjust as needed)
Bed temperature: 85-110°C (start with 100°C and adjust as needed)
Print speed: 30-60 mm/s (start with slower speeds and increase as needed)
Cooling fan: Off or low (important to prevent warping)

**Comment by bkerler** [comment]
This is already handled/implemented in PR #3657.
