### ISSUE TITLE
[BFW-4988] [ENHANCEMENT] Steelsheet configuration needs Satin steel sheet as an option 

### ISSUE THREAD

**Issue by Acidham** [prusa3d/Prusa-Firmware-Buddy#3788]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3.5
**MMU Upgrade** - no

**Is your enhancement related to a problem? Please describe.**
Available steelsheet configurations are only available for Smooth, Textured and Custom. 
  
**Describe the solution you'd like**
Please add Satin steel sheet to the selection

**Comment by CZDanol** [comment]
Closing in favor of #1318 .
