### ISSUE TITLE
[BUG] 6.0.0 alpha Z offset when printing from Octoprint

### ISSUE THREAD

**Issue by daavery** [prusa3d/Prusa-Firmware-Buddy#3795]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [ XL]

**Printer firmware version** - [6.0.0.alpha]

**Original or Custom firmware** - [Original]

**Describe the bug**
 when printing from Octoprint, Z starts about 1 mm above the bed for 1st layer. z set and mesh bed both look correct. same gcode prints correctly from USB stick

**Comment by bobjoejeff** [comment]
Unsure if it is linked but it also fails the tool offset test as the bed lowers too much
