### ISSUE TITLE
Feature Request: Change the default selection after starting print

### ISSUE THREAD

**Issue by drdelaney** [prusa3d/Prusa-Firmware-Buddy#38]
Currently the default selection, after a print is started is highlighting "Pause".

Being used to some other printers, where a double click of the dial brings up live Z adjust, this just triggers a pause a few lines into the first layer.

I would like to change the default action to "Tune" after a print is started. This way others do not accidentally hit pause a few lines into the first layer as I did.

**Comment by michalxfanta** [comment]
Yes, it is a good idea. We will change it.
