### ISSUE TITLE
[BUG] Crazy Layer Shift

### ISSUE THREAD

**Issue by beelsebob** [prusa3d/Prusa-Firmware-Buddy#3810]
**Printer type** - Mk4

**Printer firmware version** - 5.1.2

**Original or Custom firmware** - Original

**Optional upgrades** - Frankenprinter made of bear frame, Mk3.9 kit, LDO motors, and some random parts

**USB drive or USB/Octoprint**
  USB drive via Prusa Link

**Describe the bug**
My printer had a huge layer shift while printing a simple model.  Normally, I'd put this down to a crash, but in this case, I don't think that's possible.  Each side of the print layer shifted in a different way.  The rear of the print shifted backwards by a small amount each layer (somewhere around 0.5-1mm), while the front of the print shifted backwards about 3cm in one big chunk.  See attached photo

**How to reproduce**
Uhhhhh, good luck?  I've attached the bgcode, see if you can make it happen?

**Expected behavior**
No crazy layer shifts

**G-code**

[Case_0.4n_0.2mm_PETG_MK4IS_3h5m.bgcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/14487030/Case_0.4n_0.2mm_PETG_MK4IS_3h5m.bgcode.zip)

![IMG_0571](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/660483/b467cb26-50bc-486a-89a5-ca5cae285417)

**Comment by akamakamak** [comment]
I had twice the same issues.
