### ISSUE TITLE
[FEATURE REQUEST] Camera connection for XL PrusaLink

### ISSUE THREAD

**Issue by Sunspot007** [prusa3d/Prusa-Firmware-Buddy#3814]
XL Printer PrusaLink

Presently there are no XL PrusaLink Camera options.  I respectfully request an addition to the buddy board for remote viewing.

**Comment by amoose136** [comment]
I have a feeling the cpu available overhead for prudalink that can be spared without impacting motion planing is not large and the entirety of prusalink must be kept simple. What I would request is just that in the served html there’s a tag that embeds an external configurable camera stream so there’s no additional overhead on the board.  Like a form that would let you save the credentials for a webRTC stream would be great.
