### ISSUE TITLE
[BUG] MK4 Load Filament repeat cycle from time to time

### ISSUE THREAD

**Issue by yaronze** [prusa3d/Prusa-Firmware-Buddy#3815]
Hi,
I am using MK4 printers (2 printers) for a few month.
Both printer with firmware version 5.1.2 and works great.
I noticed that from time to time, not always, while loading filament into extruder , when i press "Purge More" the printer do it an when finished purging i press "Return" to go to the main menu and from some reason the printer does the purge cycle again. After that the display shows the filament type selection display and by pressing "Return" it unloads part of filament (not all of it).
I can not reproduce this issue but it is occasionally happens.
The start printing after this happens i have to purge manually or unload filament and load again because part of the filament was unloaded.

**Comment by bkerler** [comment]
This is most likely the "repressuring" of the nozzle and not a bug.
