### ISSUE TITLE
[BUG] Missing USB drive folders on Prusa XL

### ISSUE THREAD

**Issue by EveryAmp** [prusa3d/Prusa-Firmware-Buddy#3817]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches. - No issues found.

**Printer type** - XL

**Printer firmware version** - 5.1.2

**Original or Custom firmware** - Original

**Optional upgrades** - 2T

**USB drive or USB/Octoprint** - USB flash drive

**Describe the bug**
  Folders with gcode files that are copied from Google Drive on Windows are missing on the Prusa XL. Folders copied similarly on MacOS work as expected. Folders copied similarly to SD cards work as expected on MK3S. I believe the issue is that Google Drive on Windows adds a system attribute to the folder. I can run "attrib d:\folder" and see that it is set on the folders that are missing on the XL.

**How to reproduce**
  Copy a folder containing gcode files from Google Drive to a USB flash drive. Alternatively, run the command "attrib +s d:\folder" to set the system attribute and it will not be displayed on Prusa XL. Run "attrib -s d:\folder" and the folder will work again on the XL.

**Expected behavior**
  All folders with gcode would show on the Prusa XL, similar to how MK3S works currently.

**G-code** - n/a

**Crash dump file** - n/a

**Video** - n/a

**Comment by CZDanol** [comment]
I'd argue not displaying system files is a feature, not a bug. So rather blame Google for marking the files as system...
