### ISSUE TITLE
[BUG] Filament Runout Sensor Failed, Stuck Filament

### ISSUE THREAD

**Issue by blcarlson01** [prusa3d/Prusa-Firmware-Buddy#3823]
**Printer type** - [MK4]

**Printer firmware version** - [5.1.3]

**Original or Custom firmware** - [Original]

**USB drive or USB/Octoprint**
  Print via Prusa Link

**Describe the bug**
  MK4 thought there was still filament and continued to attempt to print until it said it was 100% complete even though it was roughly 75% complete and the filament had run out and a chunk was stuck in the print head, attached photo of what I found.  No idea if this is a bug or "it can happen," but wanted to report to provide an additional data point in case it is a "one off."  The filament would not unload or purge and eventually I was able to get it out by inserting new filament and it pushed it through.

**How to reproduce**
  Filament was Prusament PLA Pristine White that had run out.
  Print until the Pristine White runs out and gets stuck.

**Expected behavior**
 I expected to the printer to detect that the filament had run out and wait for me to replace the filament.

**G-code**
 No error codes were produced.

**Crash dump file**
  No crash dump available as there was no error detected..

**Image**
![IMG_4472](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/11358446/17b858a7-9793-45b5-b5e6-b6937987a469)

**Comment by bkerler** [comment]
Duplicate of issue #3756
