### ISSUE TITLE
6.0.0-alpha: Random layer shifts

### ISSUE THREAD

**Issue by gbzh01** [prusa3d/Prusa-Firmware-Buddy#3824]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

XL 5 head

6.0.0-alpha

I experienced some layer shifts on that firmware. Since downgrading, they seem to be gone.

**How to reproduce**
The files had several copies of the same design.

**G-code**
 I can't say that it is G-code specific.

**Comment by DoubleStrike** [comment]
I had one of these.  As you can see in this picture, the top layer shifted around 10mm to the lower right at a perfect 45 degree angle (which seems to indicate that only 1 of the 2 CoreXY motors was involved somehow).

![20240310_6263](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/17889466/7972b797-8f73-49f7-ab3d-e1571ceeeb9d)

**Comment by danopernis** [comment]
Hi folks, the patch version 6.0.2 should contain some fixes to rare race conditions in phase stepping, can you test that?
