### ISSUE TITLE
[BUG] No Time Remaining displayed when printing from OctoPrint

### ISSUE THREAD

**Issue by ClutchplateDude** [prusa3d/Prusa-Firmware-Buddy#3825]
**Printer type** - [MINI, MK4, XL]
MK3.5

**Printer firmware version** - [e.g. 4.0.5, ...]
5.2.0+13881

**Original or Custom firmware** - [Original/Custom]
Original

**Optional upgrades** - [e.g. Filament Runout Sensor]
None

**USB drive or USB/Octoprint**
Octoprint

**Describe the bug**
I use OctoPrint to print and it was great with the MKS3+ because the 20x4 LED would show the very accurate remaining time (OctoPrint's calculation was always waaaaay off). After upgrading to MKS3.5, I no longer have remaining time displayed on the printer screen. I would like to see Time Remaining somewhere else on the screen (that octopus logo doesn't need to take up half the screen like that :-) )  

**How to reproduce**
Start a print from Octoprint

**Expected behavior**
The firmware should display all printing information on the LCD that it displays when not printing from Octoprint. I don't want to leave the browser on my PC open to monitor the print, that's what the printer screen is for!

**G-code**
N/A

**Crash dump file**
N/A

**Comment by danopernis** [comment]
Closing in favor of #3846
