### ISSUE TITLE
Spontaneous Filament change at random time intervals.

### ISSUE THREAD

**Issue by rocrail** [prusa3d/Prusa-Firmware-Buddy#3833]
**Printer type** - [MK4]
**Printer firmware version** - [5.1.3]
**Original or Custom firmware** - [Original]

Prisa Slicer 2.7.2

Printing an object multiple times, same gcode, will sometimes trigger a spontaneous filament change which is definitely not in the gcode.
This behaviour seems to be introduced since firmware version 5.1.3

**Comment by rocrail** [comment]
IMHO its a filament sensor issue; Firmware seems to detect "End of filament".
I also recalibrated the filament sensor.

**Comment by bkerler** [comment]
@rocrail Sounds like a hw defect, did you contact prusa support ?

**Comment by danopernis** [comment]
This doesn't seem like a firmware issue.
