### ISSUE TITLE
[ENHANCEMENT] Add contrasting object outlines/highlights/shadows to image previews

### ISSUE THREAD

**Issue by TheOneTrueRazor** [prusa3d/Prusa-Firmware-Buddy#3834]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - XL
**Optional upgrades** - N/A

**Is your suggested improvement related to an existing problem? Please describe.**
  Objects that are printed with a black material appear as a black blob in the printers preview display. Objects printed in any other color appear fine because all "shadows" and detail lines are drawn in black in the preview.

**Describe the expected functionality**
  Any item that is printed in black material should have contrasting (white or grey perhaps?) contrasting lines and shadows in the print preview image. This way the item does not appear as just a black blob on the printer's screen. This behavior also occurs (and I'm guessing originates) in PrusaSlicer.

**Comment by danopernis** [comment]
@TheOneTrueRazor This issue should probably be open in the Slicer and not the firmware. Can't really do image processing on STM32 while also printing :slightly_smiling_face:
