### ISSUE TITLE
[BFW-4898] [ENHANCEMENT] add Satin as value for Sheets on MK3.5

### ISSUE THREAD

**Issue by hebbet** [prusa3d/Prusa-Firmware-Buddy#3842]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3.5

**Is your suggested improvement related to an existing problem? Please describe.**
  On hardware sheets it is not possible to select satin. Have to use custom1 etc
**Describe the expected functionality**
  Add satin as an option

**Comment by td010** [comment]
It would be better if we can use custom names. like in the MK3S+

**Comment by CZDanol** [comment]
Closing in favour of #1318
