### ISSUE TITLE
[BUG] Wifi credentials loaded screen has yes/no buttons, but does not specify what they do

### ISSUE THREAD

**Issue by DFEvans** [prusa3d/Prusa-Firmware-Buddy#3858]
**Printer type** - Prusa Mini+

**Printer firmware version** - 5.1.2+13478

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor, Wifi

**USB drive or USB/Octoprint**
  USB Drive

**Describe the bug**
  The Wi-fi "credentials loaded" screen has "Yes"/"No" buttons, but the text shown does not indicate any action that requires a yes/no. 

**How to reproduce**
* Insert USB with new Wifi credentials file
* Accept prompt to load settings
* Problem screen is then shown after loading is successful

**Expected behavior**
  Either there is some missing text about what the options do, or they just need to be replaced with an "OK" button.

**Photo**
![PXL_20240327_183551654](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/28623784/42e5f740-0237-4e19-b1cb-f00b1bff4e66)

**Comment by CZDanol** [comment]
Hey, I have fixed this in BFW-4706 (internal ticket number) I believe in January. Should get out in the next FW release for the Mini (I don't know the schedule though, sorry).
