### ISSUE TITLE
[ENHANCEMENT] escape nozzle diameter confirmation with no action, or more nozzle sizes

### ISSUE THREAD

**Issue by rob-miller** [prusa3d/Prusa-Firmware-Buddy#3863]
**Printer type** - [XL]
**Optional upgrades** - [5 tool]

If you change nozzles and then go into 'nozzle diameter confirmation' on the way to 'tool position calibration', you can only set all tools to 0.4 or 0.6.  Hitting reset to escape without changing anything (because I already set to 0.25) leaves the setting wiped, so have to go in and choose on of those two anyway and then go back to the Settings menu and set them all again one at a time.

**Describe the expected functionality**
This seems clearly for the first time setup wizard, it would be nice if there were a way to get out without wiping the setting in the eeprom.  Alternatively it would also be nice here to set all the nozzles at once to 0.25 or any of the other supported sizes.

**Comment by KlausKraemer** [comment]
The XL must be enabled to use different nozzle sizes in every single toolhead!
