### ISSUE TITLE
[FEATURE REQUEST] Time of next filament change (M600, single extruder)

### ISSUE THREAD

**Issue by MOtt** [prusa3d/Prusa-Firmware-Buddy#3867]
It would be helpful if the next filament change (M600, single extruder) was shown as the time on the display.

Currently, you have to read the duration in the slicer and then calculate the time. Possible, but not quite as convenient, especially if you later print another file directly from the printer's memory.

**Comment by KrisasMan** [comment]
Great feature on the old Rambo board firmware that is missing on the Buddy board firmware.
