### ISSUE TITLE
[BUG] Cold pull procedure doesn't set filament to unloaded state

### ISSUE THREAD

**Issue by giacomosiena** [prusa3d/Prusa-Firmware-Buddy#3869]
**Printer type** - MK4

**Printer firmware version** - 6.0.0-RC1

**Describe the bug**
Filament is still flagged as loaded after guided cold pull procedure is done.

**How to reproduce**
Do a guided cold pull procedure.

**Expected behavior**
After cold pull the filament should be set to unloaded state.

**Comment by BlueFyre** [comment]
Can confirm I saw the same issue. I started from not having any filament loaded for this procedure (not that it should matter)

**Comment by mody** [comment]
Confirmed and created internal ticket BFW-5304. Thanks.

**Comment by CZDanol** [comment]
Should be fixed in 6.0.0-RC2. Please let us know if not.
