### ISSUE TITLE
[BFW-6223] [BUG] Footer nozzle size showing one decimal digit only

### ISSUE THREAD

**Issue by giacomosiena** [prusa3d/Prusa-Firmware-Buddy#3870]
**Printer type** - MK4

**Printer firmware version** - 6.0.0-RC1

**Describe the bug**
Footer nozzle size info shows only one decimal digit making 0.25 mm nozzle show as 0.2 mm

**How to reproduce**
Set Hardware > Nozzle size as 0.25 mm

**Expected behavior**
Footer nozzle size info should show 2 decimal digits

**Comment by CZDanol** [comment]
Internal ticket: BFW-6223
