### ISSUE TITLE
[BUG] Blue Screen Crash - 5T XL

### ISSUE THREAD

**Issue by GuyH77** [prusa3d/Prusa-Firmware-Buddy#3876]
Came back to the printer beeping, print seems to have completed but had a blue screen.

XL 5T - Printing on T1 0.6n, 2-5 = 0.4n

6 Alpha

USB Thumb drive

Came to a beeping printer with blue screen

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/106596720/7c9d9a3c-5b31-4a42-873e-d9979fe32cde)
[XL_Crash.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/14816176/XL_Crash.zip)

gcode and crash log attached.

[Internalt ticket: BFW-5302]

**Comment by michaelaswood1980** [comment]
I have had the exact same issue today. Printing fine and then as I started a new print via connect I heard the printer beeping and on inspection saw the blue screen crash.... Same firmware version.

**Comment by danopernis** [comment]
@GuyH77 Thanks for your report and especially the attached crash dump. After the initial examination this looks like a deadlock involving config store mutex. I will open internal ticket and hopefully I will be able to fix this. Sorry for your troubles :disappointed:

**Comment by GuyH77** [comment]
> @GuyH77 Thanks for your report and especially the attached crash dump. After the initial examination this looks like a deadlock involving config store mutex. I will open internal ticket and hopefully I will be able to fix this. Sorry for your troubles :disappointed: 
> 
> 
> 
> BFW-5302

I'm running the alpha, I know that comes with some instability. Happy to help in some small way. Thanks.

**Comment by rcmaniac25** [comment]
I hit a similar issue with my single tool and sent my dump to prusa email. My BSOD has the exact same numbers on everything, so it makes me think I may have hit the same config store mutex issue.

**Comment by ubermlin** [comment]
Similar issue on MK4.

**Comment by CZDanol** [comment]
Hey, should be fixed in the 6.0.0-RC (release for the XL should follow soon-ish). Closing, please create a new ticket if the issue happens with the 6.0 firmware.
