### ISSUE TITLE
G-code for reading filament settings

### ISSUE THREAD

**Issue by urholaukkarinen** [prusa3d/Prusa-Firmware-Buddy#388]
There does not seem to be a way to read the current filament settings from printer. 
Perhaps it could be done with M503 g-code, but at least for Prusa Mini it reports `echo:Filament settings: Disabled`.

When a filament is changed to printer, the filament type must be specified. Filament type is also specified in PrusaSlicer. It is possible to accidentally print with the wrong filament settings, so I have been thinking about writing a OctoPrint plugin that checks whether the current filament type matches the gcode's filament type (temp settings).

**Comment by JohnnyDeer** [comment]
Similar theme as #403

**Comment by JohnnyDeer** [comment]
I close this FR for same reason as #403 thank you for understanding.

**Comment by HarkonenBade** [comment]
Is there any hope that this might be reconsidered? As I would like to develop an octoprint plugin to validate the filament type, and reading it from the printer would be the ideal way to check what is currently loaded.
