### ISSUE TITLE
[BUG] Printer displays "Next change in" message, even when no change planned.

### ISSUE THREAD

**Issue by anghelos** [prusa3d/Prusa-Firmware-Buddy#3885]
**Printer type** - [MK4]

**Printer firmware version** - 6.0.0-RC1

**Describe the bug**
  When printing, while cycling through "Remaining time", etc. messages, the message "Next change in - N/A" appears.

**How to reproduce**
  Flash firmware 6.0.0-RC1 and print an object that doesn't require any tool/color changes.

**Expected behavior**
  This message should only appear when a tool/color change exists in the g-code.

**Comment by cozmo14047** [comment]
I too notice this on a mk3.5, please remove it if no change is due
