### ISSUE TITLE
[ENHANCEMENT] Option to Disable WiFi Connectivity

### ISSUE THREAD

**Issue by stefanboca** [prusa3d/Prusa-Firmware-Buddy#3886]
**Printer type** - MK4, XL (or any printer with WiFi and Ethernet)

Currently, printers connected via Ethernet retain their previous WiFi connection. My printers were initially connected to my local network via WiFi. Recently, I switched them over to Ethernet, yet they still connect to WiFi and there is no option to disable it.

It would be useful to have an option to disconnect the current WiFi connection.

**Comment by yasars** [comment]
That was the case for me too... just send an empty WiFi file via USB to the printer and it deletes it...

**Comment by shledge** [comment]
You can take the wifi module out
