### ISSUE TITLE
[BUG] Cancel Object non-operational

### ISSUE THREAD

**Issue by Brandon541** [prusa3d/Prusa-Firmware-Buddy#3887]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK3.5

**Printer firmware version** - 5.2.2

**Original or Custom firmware** - Original

**Optional upgrades** - N/A

**USB drive or USB/Octoprint** - Prusa Connect

**Describe the bug**
When Using the cancel object from the printer's interface whether selecting "Cancel Current object" or individually selecting objects to cancel the Printer does not cancel the selected objects -- it should be noted that the interface does state that the object is canceled.

**How to reproduce**
start a print with multiple objects, then select cancel object, then watch the canceled object object print.

**Expected behavior**
 when canceling an object, I would expect the printer to stop printing the object selected and continue to print the next object in the file.

**G-code**
G-code is bgcode and is not supported by github. uploading a .txt, please edit the file extension.

[Label_Scoop_Label_Insert_x1_0.4n_0.2mm_PLA_MK3.5_4h50m.txt](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/14884346/Label_Scoop_Label_Insert_x1_0.4n_0.2mm_PLA_MK3.5_4h50m.txt)

**Comment by Fluffybunny96** [comment]
I cant even access the cancel object menu on 6.0 RC
