### ISSUE TITLE
Mk3.5 mmu3 doesent load fully

### ISSUE THREAD

**Issue by cozmo14047** [prusa3d/Prusa-Firmware-Buddy#3890]
Hi there, with mk3.5 mmu3 if you start a single mmu print non mmu profile on ps due to it being single color, when it goes to load that fillament it doesent load it all through the extruder this causes when the print starts to miss the first layer due to the fillament being just passed the gear. Happy to provide video if needed.

**Comment by cozmo14047** [comment]
Update, so ive been having to use multicolor option in ps and just turn the purge tower off

**Comment by CZDanol** [comment]
Internal ticket: BFW-5280

Should be fixed in 6.0.0-RC2

**Comment by cozmo14047** [comment]
> Internal ticket: BFW-5280
> 
> Should be fixed in 6.0.0-RC2

Yep is fixed in 6 rc2
