### ISSUE TITLE
[BUG] BSOD when changing input shaper parameters while printing (tune menu)

### ISSUE THREAD

**Issue by marmotton** [prusa3d/Prusa-Firmware-Buddy#3892]
**Printer type** - MK3.5

**Printer firmware version** - 5.2.2+13941

**Original or Custom firmware** - Original

**Optional upgrades** - No

**USB drive or USB/Octoprint** - USB flash drive

**Describe the bug**
I changed the Input Shaper X-axis freq. using the Tune menu while printing. This resulted in a BSOD with error "Write to marlin variable from non marlin thread", see photo:
![bsod prusa](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/24893706/44283d8c-53ac-49e1-907c-d515a2e31fea)

**How to reproduce**
- Launch a print
- Wait for the axes to start moving
- Tune menu > Input Shaper > Change X-Axis freq. or Y-Axis freq. or X-Axis filter or Y-Axis filter
- Note: it is possible to change these settings in the tune menu without issues before the axes start moving (while heating up)
- Note2: the new value is stored successfully

**Expected behavior**
Being able to update the input shaper frequency while printing, without BSOD.

**G-code**
[porte chaussures chien_0.4n_0.2mm_PLA_MK3.5_6h0m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/14893417/porte.chaussures.chien_0.4n_0.2mm_PLA_MK3.5_6h0m.zip)

**Crash dump file**
Will be emailed to reports@prusa3d.com shortly.

**Video**
no video

**Comment by CZDanol** [comment]
Hey, this bug should be fixed in 6.0.0-RC1. Yes, the adjusting as a whole is disabled IIRC, but the underlying issue should be fixed as well :D

Closing.

Internal ticket: BFW-5251
