### ISSUE TITLE
[FEATURE REQUEST] Add in  "Are you sure" (Yes/No) prompts to some selection options.

### ISSUE THREAD

**Issue by Xstell132** [prusa3d/Prusa-Firmware-Buddy#3899]
Printer - MK4

A couple of times while in the "Tune" page while a print is running and i've finished what needed to be adjusted, I want to back out to the main run screen and have accidentally clicked on "Change Filament" due to it being right next to the return selection. 

I'd like to see if it's possible to put a "Are you sure yes/no" prompt after you click on the change selection so that you don't accidentally pause and unload the filament mid-print.

It would be nice to see this yes/no prompt with the "Pause" and "Stop" selections on the main run menu as well as currently it leaves an easy opportunity to ruin a print job if you accidentally click something on the screen.

**Comment by danopernis** [comment]
This duplicates #1387
