### ISSUE TITLE
Filament runout has no sound

### ISSUE THREAD

**Issue by drdelaney** [prusa3d/Prusa-Firmware-Buddy#39]
Though this is probably an issue for the LCD, I noticed when testing the runout sensor, there was no audible beeps.  There was only text showing up on the display.  Since there is a peizo on the LCD, there should be a audible notification.

**Comment by drdelaney** [comment]
Unsure if related, but it seems the plat tone gcode M300 does not work either.  However I do hear chirps at button presses, so I know the peizo works.  Guessing it just has sound turned off or not enabled for these.

**Comment by michalxfanta** [comment]
Thanks for the idea, we'll consider implementing it.
