### ISSUE TITLE
[QUESTION] Enable translations

### ISSUE THREAD

**Issue by xtomasnemec** [prusa3d/Prusa-Firmware-Buddy#3901]
Please, before you create a new question, please make sure you searched in open and closed issues and couldn't find anything that matches.

How can i enable translations while compiling MINI firmware?
![Screenshot 2024-04-11 104328](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/40271551/6ee4c90c-358c-4416-85a3-f06fcd350ed4)
There aren't any flags to do so.

**Comment by danopernis** [comment]
There is a cmake option for that. Or you can use a preset. How exactly are you trying to build the firmware?

https://github.com/search?q=repo%3Aprusa3d%2FPrusa-Firmware-Buddy%20TRANSLATIONS_LIST&type=code

**Comment by xtomasnemec** [comment]
> There is a cmake option for that. Or you can use a preset. How exactly are you trying to build the firmware?
Not in debug mode

**Comment by xtomasnemec** [comment]
nevermind i used --help
