### ISSUE TITLE
[ENHANCEMENT] Add a reasonable g-code for parking the current tool

### ISSUE THREAD

**Issue by smurfix** [prusa3d/Prusa-Firmware-Buddy#3903]
**Printer type** - XL

**Is your suggested improvement related to an existing problem? Please describe.**
Parking the current tool with `P0` is a bad idea because this does not fit the gcode standard.

Some gcode analysis tools complain loudly when they see it.

**Describe the expected functionality**
Use / enhance an existing command to park the tool head. `G27` seems like a reasonable option here.

NB: Frankly, using `T0` for the first extruder has been a bad idea. Zero is commonly used to load No Tool and would have been a very reasonable choice for this command.

**Comment by mtaumike** [comment]
Ooh this would be super neat and useful, and being serious, doing custom things with the toolheads.

The other thing with `T0` is that everything else looks like it is actually `T1` through `T5` and not ordinal starting at `0`. Makes the nerd in me anxious (not really) when nomenclature is not consistent.
