### ISSUE TITLE
[ENHANCEMENT] Option to move extruder to the centre when changing filament (not the left edge).

### ISSUE THREAD

**Issue by ax42** [prusa3d/Prusa-Firmware-Buddy#3912]
Applies to all printers.

My printer is in an enclosure, so the default position to change filament (top left) is quite inconvenient. Middle/middle on X and Z would be better for me, so this should probably be an option in the menus.

**Comment by shoro** [comment]
I would like to be able to set my own home coordinates for change filament and finish printing

**Comment by ax42** [comment]
@shoro - a workaround for head position to finish printing is to put a post-print GCODE into the slicer. Challenge of course is (generically) knowing where you can put the head without touching or knocking over whatever you printed.
