### ISSUE TITLE
[BUG] Stealth mode don't work?

### ISSUE THREAD

**Issue by flinke-flasche** [prusa3d/Prusa-Firmware-Buddy#3914]
**Printer type** - MK3.5
**Printer firmware version** - 6.0.0 RC2
**Original or Custom firmware** - Original
**USB drive or USB/Octoprint** - USB and Repetier Server

Can't hear a different between stealth mode on/off.
Shouldn't it be much more quiet?

**How to reproduce**
  Activate in the Stealth Mode Printer settings with firmware 6.0.0 RC2

**Comment by ClaGre** [comment]
> **Printer type** - MK3.5
> 
> **Printer firmware version** - 6.0.0 RC2
> 
> **Original or Custom firmware** - Original
> 
> **USB drive or USB/Octoprint** - USB and Repetier Server
> 
> 
> 
> Can't hear a different between stealth mode on/off.
> 
> Shouldn't it be much more quiet?
> 
> 
> 
> **How to reproduce**
> 
>   Activate in the Stealth Mode Printer settings with firmware 6.0.0 RC2

Me too.

**Comment by CZDanol** [comment]
It does work alright, you're quite just not reaching the speeds at which it starts clipping. 0.2 layer height prints on structural or even speed profile don't usually exceed the speeds, and if they do, usually just by little. If you try out like 0.1 mm speed profile with gyroid infill, it will be pretty noticeable.

**Comment by flinke-flasche** [comment]
Thank you.
I don't print with 0,1mm very often, because i don't need it.
On the MK3s+ i can use it with every layer height.

On the MK3.5 i don't recognize it. it's always the same noise.
I sliced an object in Prusa Slicer 2.7.4 with stealth support in the slicer but when i activate an deactivate the stealth mode nothing happens.

I thought, that the stealth mode is like in the MK3s+.
Activating and deactivating is a big difference.
