### ISSUE TITLE
[BUG] Printing time on screen resets after every tool change

### ISSUE THREAD

**Issue by LidorBaum** [prusa3d/Prusa-Firmware-Buddy#3918]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - XL 5TH

**Printer firmware version** - 5.1.2

**Original or Custom firmware** - Original

**USB drive or USB/Octoprint** - USB Drive.

**Describe the bug**
when printing multi-tool, the Printing Time on the screen is since the last change, and not from the start of the print (it resets every change)
The remaining time is accurate though.
In the image you can see it states printing time 7H 40M, but the print actually started about 12H ago.
![photo_2024-04-16_12-31-52](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/86967825/fc47a6ff-5f13-4b8b-b91f-9e5c79a80596)

**How to reproduce**
It happend for me in every multi tool print.

**Expected behavior**
Time should not reset since the real start of the print.

**G-code**
I am using Prusa slicer 2.7.4 with original profile of XL 5TH.

**Crash dump file**
  Please send the crash dump file to Prusa by emailing it to reports@prusa3d.com. Sharing this file is important and helps us investigate the bug.

  Do not share the file publicly, as the crash dump contains a raw snapshot of the printer's memory and may include unencrypted sensitive information.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by danopernis** [comment]
Hi @LidorBaum can you please try with the lastest 6.0.x firmware?
