### ISSUE TITLE
[FEATURE REQUEST] MK3.5 - Display sheet in footer

### ISSUE THREAD

**Issue by Xav83130** [prusa3d/Prusa-Firmware-Buddy#3925]
MK3.5

### **Display sheet in footer**

Would it be possible to add the possibility of displaying the sheet in use in the footer.

In the "_user interface_" --> "_footer_" menu
Add "_sheet_" selected.

Displays the selected sheet in the footer.

This will be even more useful when you rename the sheets ^^.

**Comment by danopernis** [comment]
:weary: https://github.com/search?q=repo%3Aprusa3d%2FPrusa-Firmware-Buddy++Display+sheet+in+footer++&type=issues

**Comment by Xav83130** [comment]
sorry I didn't find it. I closed it.

**Comment by danopernis** [comment]
Duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3789
