### ISSUE TITLE
[BUG] Prusa connect file transfer stuck waiting

### ISSUE THREAD

**Issue by dpark12300** [prusa3d/Prusa-Firmware-Buddy#3928]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - 6.0.0 RC2

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint**
  USB Drive

**Describe the bug**
  Trying to transfer file from prusa connect. just stays waiting. prusa connect network menu says "connecting - bug"

**How to reproduce**
  Send the FW 6.0.0 BBF to the printer on Prusa connect.

**Expected behavior**
 A succesful transfer/flash.

**G-code**
  The BBF file from the releases page for 6.0.0

**Comment by jakefreese** [comment]
This is affecting the MK4 on 6.0.1 also.
