### ISSUE TITLE
[BUG] Custom feedrate parameters for Stealth mode set in PrusaSlicer do not affect the printing speed

### ISSUE THREAD

**Issue by jonnieZG** [prusa3d/Prusa-Firmware-Buddy#3938]
**Printer type** - MK4

**Printer firmware version** - 6.0.0

**Original or Custom firmware** - Original/Custom

**Optional upgrades** - N/A

**USB drive or USB/Octoprint**
  USB

**Describe the bug**
  Values set in PrusaSlicer 2.7.4 under Printer Settings >> Machine Limits >> Maximum feedrates do not affect the actual printer behavior.

**How to reproduce**
  1. Create 3 cubes 25x25x25mm
  2. Set the Object spacing to 50mm or some other larger value
  3. Click auto arrange (the 3 cubes should be now arranged in a triangular pattern, so you can observe different X and Y feed rates)
  4. In Printer Settings >> Machine Limits >> Maximum feedrates set a very low value for X and Y max feed rates (for example 5).
  5. Set "How to apply limits" to "Emit to G-code"
  6. Slice the model and print it
  7. When you turn on the Stealth mode in the printer, the actual head speed does not respect the set limits.

**Expected behavior**
  When the Stealth mode is turned on, the limits set in PrusaSlicer should be respected by the printer.

**Comment by CZDanol** [comment]
Hello, the feedrates for stealth mode are hardcoded in the machine. Settings in the PrusaSlicer are only used for the print time duration calculation. This is intended behavior.
