### ISSUE TITLE
[ENHANCEMENT] Addition of screen turn off in the settings

### ISSUE THREAD

**Issue by AvariCe-git** [prusa3d/Prusa-Firmware-Buddy#3940]
**Printer type** - [MK4]

Hi, I think it would be useful if there was an option to turn off the screen in the settings after some amount of time after which no input has been given, like phones do after idling for a few minutes. Much like phones, the screen should wake up at the first input, whether it is a touch or a press/turn of the button.

**Comment by danopernis** [comment]
Duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3224
