### ISSUE TITLE
[FEATURE REQUEST] PrusaLink Webcam Instance - a RPI Camera hub for MK3.5/MK3.9/MK4/Mini+/XL

### ISSUE THREAD

**Issue by AndersEid** [prusa3d/Prusa-Firmware-Buddy#3941]
Prusa Connect - PrusaLink Webcam Instance on a RPI, acting as a camera hub for printers with native Prusa Connect and Wifi (MK3.5, MK4, Mini+ etc.). 

-----------------
Many people wish they were able to use webcams they already have with Prusa Connect. 
A webcam is cheap compared to buying a phone or something similar - if you don't already have it. 

After seeing the "Chris's Basement" youtube-video "Multi-Prusa Link - Multiple cameras", it made me try installing PrusaLink on a RPI to see if I could tell Prusa Connect that "This is a RPI with PrusaLink, it has webcams connected to it, this camera belongs to this and this printer which is already set up in Prusa Connect". This did not work.

Something similar could work though. 
A RPI running its own PrusaLink instance made for connecting multiple webcameras instead of printers, could utilize the API functionality already set up to work in Prusa Connect. Cameras could automatically start and stop with the print, since the "PrusaLink Webcam Instance" could be seen as "another printer" in Prusa Connect, and could have the ability to assign its cameras to other already set up printers because it was part of the ecosystem. 

I am not a programmer, so excuse my lack of knowledge. I know everything isn't as easy as "just do this and that". 
To see if something like it would work, I set up a RPI, flashed with Raspbian, connected two webcameras and scanned the QR code for each of my two printers - setting up one with firefox and one with chromium, both directed at webcam.connect.prusa3d.com. 
This method works and sends pictures to Prusa Connect, but I think it would work even better if it was part of the Prusa ecosystem instead of running on Raspbian. 

I hope this feature request helps in any way, shape or form as to give customers of Prusa a way of checking in on their print. 
If not, maybe somebody else reads about the Raspbian way of "solving" it and could use it to their benefit. 
Anyway, thank you for making great printers - keep at it. 

-Andy.

**Comment by firetech** [comment]
I made a solution for exactly that a couple of months ago: https://github.com/firetech/ConnectCam/
Has been working well for me.

Prusa also stated [in January](https://blog.prusa3d.com/prusa-connect-a-network-solution-for-remote-control-of-3d-printers_90364/) that they are working on an easy-to-use product for this (not reusing old webcams, though):

> Original Prusa Connect Camera
> 
> We are currently working on easy-to-use solution, involving an inexpensive microcontroller with a camera module, paired with a wide-angle lens. We would like to offer it with a pre-flashed firmware on our e-shop for purchase once it’s finished.
