### ISSUE TITLE
[BUG] Hotend fan fails calibration Revo Mini ask to continue to print.

### ISSUE THREAD

**Issue by shawnchr** [prusa3d/Prusa-Firmware-Buddy#3942]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version** - [6.0.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Revo Mini and Bondtech]

**USB drive or USB/Octoprint**
  Prusa Connect

**Describe the bug**
  I upgrade to 6.0.0 previous versions failed but would continue to print. Now I can get it to print but I have to click continue on the screen before it will print very annoying.

**How to reproduce**
  Please describe steps to reproduce the behavior.

**Expected behavior**
  I expect it to fail the hotend calibration and continue to print.

**Comment by torkildr** [comment]
Seeing the same. Not sure if this is a result of use the smaller Revo Mini fant they used initially.

Should be noted that I have disabled the "Fan Check", but calibration does not seem to care about that setting.

I suspect the only solution is to print out the latest hotend holder that fits the original fan and rerun all the wires 😫
