### ISSUE TITLE
[FEATURE REQUEST] Sticky temperature adjustment for multitool XL

### ISSUE THREAD

**Issue by TojikCZ** [prusa3d/Prusa-Firmware-Buddy#3946]
**Printer type** - XL
**Optional upgrades** - 2T or 5T

**Is your feature request related to an existing problem? Please describe.**
  Say I want to adjust the temperature of tool 3 after i start the print. The temperature gets reset every toolchange making the temperature adjustment pointless.

**Describe the expected functionality**
  The tool remembers the temperature I have set until a new one is set to it. Or we disable the temperature adjustment on multitool prints.

OP: https://forum.prusa3d.com/forum/bugs-errors/prusa-xl-nozzle-temperature-changes-do-not-stick/#post-708726

**Comment by wafflecart** [comment]
Think this is the same as #3669. Maybe add your findings to that ticket.

**Comment by TojikCZ** [comment]
I think that "manually set temperature resets on toolchange during print" is not the same as "For example, when preheating for a filament change on tool 3, tool 1 and tool 2 will also heat up."
Please go away

**Comment by wafflecart** [comment]
Ok my bad sorry I read the issue wrong and didn’t see the “during print” part. but don’t need to be so rude and say to me “go away”. You’re a prusa employee and should not be addressing people like that there’s politer ways dude.

**Comment by TojikCZ** [comment]
How do you say go away without being rude?

Say, “ I am in a terrible mood and just want some space and be left alone for a while. I do not want to hurt anyone's feelings, but I just am not up for company.”

Okay, here we go: I am in a terrible mood and just want this out of the "to-do" pile. Please stop moving it back in there. I do not want to hurt anyone's feelings, but I am not up for debating the legitimacy of this issue, I think I checked well enough.

Sorry for giving you the short version.

**Comment by wafflecart** [comment]
Yes that’s worse 🤣. I’ll leave you be and delete my original comment so people don’t get confused and think it is related to that other issue. Hope you have a good day!

**Comment by TojikCZ** [comment]
Yes sorry, was fed up and not in the mood for being corrected. Thanks for the effort, it's great you genuinely try to weed out duplicates. Thank you for that

**Comment by TojikCZ** [comment]
Yes sorry, was fed up and not in the mood for being corrected. Thanks for the effort, it's great you genuinely try to weed out duplicates. Thank you for that
I'd like to delete all of these if that's fine with you, but they stay if you say no

**Comment by TojikCZ** [comment]
Duplicate of #3343
