### ISSUE TITLE
[BFW-5652] Needless Filament Unload Procedure, when MMU Print is cancelled in the Warm Up Phase

### ISSUE THREAD

**Issue by JWartenberg** [prusa3d/Prusa-Firmware-Buddy#3955]
Printer: MKS 3.5 + MMU3
Printer FW: 6.0.0
MMU FW 3.0.3

Scenario:

- Starting a MMU Print
- Cancel the print in the heating phase, before filament is loaded for the first time

Printer proceeds the filament unload procedure (heating up, ramming, ...) although no filament is loaded.
The procedure is needless in this case.

Best regards
Jochen

**Comment by firetech** [comment]
Was just about to report this, glad someone else did it already. One would think that the printer would realize that no filament is loaded, since both FINDA and FSensor are showing OFF on the unloading screen...

**Comment by Mercur13** [comment]
have the same issue here MK3.5 Fw: 6.0.1

**Comment by firetech** [comment]
There is a workaround, albeit slightly annoying.

If you reset the printer (reset button) _instead of_ stopping the print in this stage, you will not need to unload (if you reset _after_ stopping the print, the printer will think it has filament loaded even after reboot).

**Comment by danopernis** [comment]
This is scheduled for next minor (not patch) version of the firmware.

**Comment by danopernis** [comment]
New version of the firmware 6.1.2 should contain the fix, can you test that?

**Comment by JWartenberg** [comment]
Not before mid of next week

Von: Dano Perniš ***@***.***>
Gesendet: Donnerstag, 22. August 2024 18:27
An: prusa3d/Prusa-Firmware-Buddy ***@***.***>
Cc: JWartenberg ***@***.***>; Author ***@***.***>
Betreff: Re: [prusa3d/Prusa-Firmware-Buddy] [BFW-5652] Needless Filament Unload Procedure, when MMU Print is cancelled in the Warm Up Phase (Issue #3955)


New version of the firmware 6.1.2 should contain the fix, can you test that?

-

**Comment by JWartenberg** [comment]
Tested
Issue is fixed

Sorry for the delay

Regards
Jochen


Von: Dano Perniš ***@***.***>
Gesendet: Donnerstag, 22. August 2024 18:27
An: prusa3d/Prusa-Firmware-Buddy ***@***.***>
Cc: JWartenberg ***@***.***>; Author ***@***.***>
Betreff: Re: [prusa3d/Prusa-Firmware-Buddy] [BFW-5652] Needless Filament Unload Procedure, when MMU Print is cancelled in the Warm Up Phase (Issue #3955)


New version of the firmware 6.1.2 should contain the fix, can you test that?

-
