### ISSUE TITLE
Display showing wrong temperature setpoint after filament load

### ISSUE THREAD

**Issue by Hanier** [prusa3d/Prusa-Firmware-Buddy#3958]
Printer: MK4
FW: 6.0.0

Steps to reproduce:

Unload Filament - PETG in this case
Reset Button - Go to known state
Allow nozzle to cool below 150C - Arbitrary chosen value

Push-Load Filament into Nextruder
Select PETG when asked
   Waiting for nozzle to reach setpoint = 230C

Purge OK - Select Yes

With no additional user interaction

    Display goes to main screen
    Lower-Left shows nozzle temperature dropping
    Setpoint Shows 230C
    Temperature stabilizes at 170C
    So... Lower-Left now shows 170C/230C
    

![20240428_DisplayShowing230C-lowerLeft](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/9752446/8346e42f-1743-4d5d-a63b-42906e74ab48)
![20240428_Temp-dropping_Actual-Setpoint-is-170C-yetDisplayShows230C](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/9752446/75b0453d-99eb-4d5f-a98b-2455f15d4b70)

**Comment by murk-sy** [comment]
Duplicate of / related: 
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3074 Displaying wrong temperature
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3691 Not cooling off after load (maybe related? depends what you consider intended behaviour)
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1795 My proposed enhancement

The nozzle currently remains heated at auto bed leveling temperature after load/change/unload while showing the final temperature. It's intended behaviour, but I don't think it should be (see comments on the issues).
