### ISSUE TITLE
Menu, Info, Odometer, amount of filament used in Kilometers is way off. 

### ISSUE THREAD

**Issue by VH-fixer** [prusa3d/Prusa-Firmware-Buddy#3968]
Printer MK4, FW 6.0.0  MMU enabled. 
See the attached picture
This odometer shows I have used over 4 MILLION kilometers of filament.  
 
![PXL_20240502_211211153](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/118006785/dd3547d8-c682-495c-891e-355df605ba69)

My printer overall has only moved a few hundred kilometers.
I think someone forgot to devide mm by 1,000,000 to get to KM.

**Comment by thijstriemstra** [comment]
it's issues like this that really doubt my trust in the firmware dev at prusa: rushed, incomplete and buggy.

**Comment by VH-fixer** [comment]
In 6.0.4 I did a factory reset to clear out all statistical data.  After recalibrating and configuring the MK4 I ran a new part.
Meters of filament are being reported correctly.    
I am wondering if this number was data on the card from the factory.  That needs to be checked.    It is the first factory reset I have done.   Will keep an eye on it.

**Comment by danopernis** [comment]
Basically the same as https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4095 I will copy my answer here as well:

> Clearly there is something wrong with the statistics. For now, this invalid value is already committed to EEPROM so there is nothing to do about that other than performing factory reset 😟

> There are some improvements related to EEPROM consistency scheduled for next release which should hopefully prevent this from happening again.

As to your question about filament number reported not changing, it is basically so large that any addition in order of meters is basically invisible.

No, the data was not there from the factory, but during the print, somehow an invalid number was stored there. Once such mistake is committed, it can't be reverted.
