### ISSUE TITLE
Option to delete file from xLCD control panel

### ISSUE THREAD

**Issue by OopAck** [prusa3d/Prusa-Firmware-Buddy#3975]
**Printer type** - [Mk3.5]
**Optional upgrades** - [xLCD option to delete gcode from menu]

**Is your suggested improvement related to an existing problem? Please describe.**
Improvement

**Describe the expected functionality**
Able to keep the USB clean and without disconnecting it from xLCD.

**Comment by murk-sy** [comment]
Duplicate of:
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3439
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1145
