### ISSUE TITLE
Prusa XL - Printing with different nozzle sizes / Octoprint Progress Screen

### ISSUE THREAD

**Issue by Investegate** [prusa3d/Prusa-Firmware-Buddy#3986]
It would be wonderful if you could print with several toolheads with different nozzle sizes in the same project with the Prusa XL.
In addition, Octoprint, etc. lacks the progress bar...

**Comment by murk-sy** [comment]
Different nozzle size support is more of a slicer issue and while I'm having a hard time finding the exact issue I'm thinking of, here's one of them
- https://github.com/prusa3d/PrusaSlicer/issues/393

Regarding octoprint progress bar:
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3653
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3846
