### ISSUE TITLE
[FEATURE REQUEST] Option to save Live Adjust Z values on Prusa XL between prints

### ISSUE THREAD

**Issue by m00dawg** [prusa3d/Prusa-Firmware-Buddy#3987]
**Printer type** - [XL]

**Is your feature request related to an existing problem? Please describe.**
Yes and no. The factory first layer height is ok but I would like to experiment with lowering it just a bit as I get lifting on the XL that I don't get on my MK3s and I noticed it looks like I have my preferred height a bit lower on the MK3s. I know you can tune it per-print but the face of the bottom layer is often important in the models I print and having to do that everytime is both tedious and if done when the first layer is already going done also inconsistent.

**Describe the expected functionality**
A way to save the preferred Z height instead of having to use live Z adjust at the start of every print. Essentially something like the MK3s where the live adjust can be set at any time and is preserved. In the case of the MK3s it's per build plate but in my case I don't really need that option as I don't swap plates all that often.

The Prusa XL is good, but I think a feature like this for power users (that bought a power printer for $$ of note) would make it go from good to great.

**Comment by murk-sy** [comment]
Having a gcode that can just be inserted into filament profiles would probably be the easiest solution

- Does not affect the printer's settings
- Needs very little documentation
- No added menus
- Can easily be limited to something like +-0.95 mm to prevent malicious use
