### ISSUE TITLE
Change filament assumes "yes" on second check

### ISSUE THREAD

**Issue by drdelaney** [prusa3d/Prusa-Firmware-Buddy#40]
I mis-loaded my mini a few times, and unlike the mk2.5s/mk3s where it keeps asking if the filament is the right color, the mini only asked once, then assumed "yes" on the second check and started to print right away.

There was clearly no filament going down to the hotend.
I would suggest enabling a check loop to keep asking if it is the right color.  And perhaps if the 2nd or 3rd answer is "No", ask if the filament was loaded correctly.
If yes, keep asking for color, or possibly cancel (who needs to hit it that many times), but if no, start the load cycle over again, so the filament can be re-inserted back down the bowden.

I lost a print an hour in, because I ran out of filament, and mis-loaded the new filament (I pushed in as far as it would go, but it was not grabbed)

**Comment by Area5142** [comment]
Related to: Load Filament and Color Change Bug #15

**Comment by drdelaney** [comment]
> Related to: Load Filament and Color Change Bug #15

Here I go trying to be helpful and I messed that up too. 😅

**Comment by michalxfanta** [comment]
We are working on adjusting the filament loading behavior. The fix will appear in one of the other releases.
