### ISSUE TITLE
[BUG] <Prusa MK3.5 MBL only 7x7>

### ISSUE THREAD

**Issue by abit11w** [prusa3d/Prusa-Firmware-Buddy#4003]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**MK3.5** - []

**6.0.0** - [e.g. 4.0.5, ...]

**Original** - [Original/Custom]

**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive and Prusalink/connect and Octorprint for Plugins**

**Describe the bug**
MK3.5 only offers 7x7 MBl automatically without the option of 3x3 with different Probes as the Mk3s+ used to.

**How to reproduce**
Meshbedleveling under Control will result in 7x7 MBL
or using Octoprint Leveling / Visualizer Plugins with give GCODE will result in 7x7 instead of 3x3 

**Expected behavior**

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please send the crash dump file to Prusa by emailing it to reports@prusa3d.com. Sharing this file is important and helps us investigate the bug.

  Do not share the file publicly, as the crash dump contains a raw snapshot of the printer's memory and may include unencrypted sensitive information.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by LoakAudio** [comment]
Hi, I don't think it's a bug. The MK3.5 use a different method of leveling :  max is 7x7 but if you print a small thing it will do a 3x3 or whatever to stick to the surface used by the print.
