### ISSUE TITLE
[BUG] mk4: strange ping response

### ISSUE THREAD

**Issue by Gottox** [prusa3d/Prusa-Firmware-Buddy#4007]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4

**Printer firmware version** - 6.0.0

**Original or Custom firmware** - Original

**Optional upgrades** - NONE

**USB drive or USB/Octoprint**
USB

**Describe the bug**
I just observed a strange behavior when pinging my mk4:

```
# ping mk4       
PING mk4.lan (192.168.69.238) 56(84) bytes of data.
64 bytes from mk4.lan (192.168.69.238): icmp_seq=1 ttl=254 time=2304959886645937 ms
wrong data byte #16 should be 0x10 but was 0xde
#16	de e0 8 3a 8d ce 6b 80 8 0 45 0 0 54 8f 2 40 0 ff 1 89 c7 c0 a8 45 ee c0 a8 9b 9f 0 0 
#48	b4 eb 38 5d 0 2 be df 
64 bytes from mk4.lan (192.168.69.238): icmp_seq=3 ttl=254 time=15658 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=4 ttl=254 time=14635 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=6 ttl=254 time=12589 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=7 ttl=254 time=11566 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=8 ttl=254 time=10542 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=9 ttl=254 time=9519 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=10 ttl=254 time=8495 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=11 ttl=254 time=7474 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=12 ttl=254 time=6452 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=13 ttl=254 time=5431 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=14 ttl=254 time=4409 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=16 ttl=254 time=2361 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=19 ttl=254 time=8.73 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=20 ttl=254 time=5.57 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=21 ttl=254 time=9.88 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=22 ttl=254 time=6.58 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=23 ttl=254 time=10.4 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=24 ttl=254 time=14.5 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=25 ttl=254 time=22.3 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=26 ttl=254 time=18.0 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=27 ttl=254 time=19.9 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=28 ttl=254 time=21.0 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=29 ttl=254 time=15.3 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=30 ttl=254 time=15.2 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=31 ttl=254 time=96.4 ms
64 bytes from mk4.lan (192.168.69.238): icmp_seq=32 ttl=254 time=46.2 ms
^C
--- mk4.lan ping statistics ---
32 packets transmitted, 27 received, 15.625% packet loss, time 31435ms
rtt min/avg/max/mdev = 5.571/85368884694643.680/2304959886645937.380/2781467.665 ms, pipe 18
```

**How to reproduce**
No idea yet

**Expected behavior**
ping responses without garbaged data

**G-code**
none

**Crash dump file**
none

**Video**
none

**Comment by BigAl66** [comment]
Could not reproduced here. My MK4s are connected via WiFi. Could it come from your network?

C:\Users\...>ping prusamk4-1 -t

Ping wird ausgeführt für prusamk4-1.fritz.box [192.168.178.35] mit 32 Bytes Daten:
Antwort von 192.168.178.35: Bytes=32 Zeit=6ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=7ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=4ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=5ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=8ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=6ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=6ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=6ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=4ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=5ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=4ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=7ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=7ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=7ms TTL=255
Antwort von 192.168.178.35: Bytes=32 Zeit=6ms TTL=255

Ping-Statistik für 192.168.178.35:
    Pakete: Gesendet = 15, Empfangen = 15, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 4ms, Maximum = 8ms, Mittelwert = 5ms
