### ISSUE TITLE
[ENHANCEMENT] MMU3 MK4 single mode filament load after MBL

### ISSUE THREAD

**Issue by peterbenedicic** [prusa3d/Prusa-Firmware-Buddy#4021]
**Printer type** - [Mk4]
**Optional upgrades** - [MMU3]

When you start printing in single mode, nozzle heats up, then selected filament is loaded to nozzle. After load, nozzle starts to drop temperature to 175 deg. C prior to MBL and during that time filament oozes from the nozzle (even worse with PC, because it drops only to 250 deg C).

In my opinion it would be much more convenient if filament would be loaded after MBL is done, like when printing in multimaterial mode.
Regards,
Peter

**Comment by d-z-o** [comment]
This should be enabled.
