### ISSUE TITLE
Warn user about incorrect filament loaded

### ISSUE THREAD

**Issue by Lee-Hickman** [prusa3d/Prusa-Firmware-Buddy#403]
I had an issue where my daughter tried to print the Prusa Buddy (meant for PLA), but the printer had PETG filament loaded. She hit print and walked away. She came back 30 minutes later to a glob of plastic stuck to the nozzle.

I would like to see the printer do a self check against the filament type currently loaded vs. the filament type being attempted to print. if there is a conflict, allow the user to self correct by cancelling the print and loading the correct filament or continuing through with abnormal settings.

The way I see it, the enhancement should look like:
Part 1 (Saving the filament type if not already done in the system):
   - Save the selection from the LOAD FILAMENT selection.
   - Upon a selection of UNLOAD FILAMENT clear the entry

Part 2 (Comparing loaded filament vs. gcode):
   - I know I select the filament type in Prusa Slicer (I am not too familiar with others to know if this is true there). Perhaps this information could be leveraged to do the comparison, otherwise, a temperature comparison could be done (But that seems yucky and complicated). Before the print begins there could be a check to compare the 2 setting (loaded filament and gcode from the Slicer) to determine if the filaments match
   - If check succeeds. Nothing changes. Print as usual.

Part 3 (Check fails):
   - An on-screen prompt alerts the user user that the filament check has failed.
   - The user is given options to handle the failed check.
      - [Only need if doing temp range logic] OK through the check (loaded filament matches the desired filament for printing and the user is using outside of range temperatures. Proceed normally
      - Option to cancel the print in order to change filament
         - The user realizes they are trying to print a PLA gcode with PETG loaded in the printer
      - Option to set the current Loaded Filament to match the gcode
         - The user has done a manual change and the printer does not know. This allows for correction to the correct filament type

**Comment by x10102** [comment]
I rarely print anything other than PLA, but this still sounds like a great and convenient feature

**Comment by JohnnyDeer** [comment]
Hi @thank you for suggestion. This feature would depend on slicer used for generating Gcode. Every slicer may use different kind of filament info saved to Gcode and that's reason why we can't make it functional. I´am closing this FR as wontfix. Thank you for understanding.
