### ISSUE TITLE
[BFW-5692] [BUG] PRUSA MK4 and MMU3 Power Panic Bug

### ISSUE THREAD

**Issue by seifer69er** [prusa3d/Prusa-Firmware-Buddy#4037]
### Printer model

Mk4 with MMU3

### Firmware version

6.0.2

### Upgrades and modifications

MMU3

### Printing from...

USB Drive

### Describe the bug

During a power panic, the MK4 does not detect filament missing

### How to reproduce

During print, the mmu3 detected the end of filament and ejected the filament, 
this filament was loaded to selector 3,
I decided to switch to selector 1 but hte MMu3 did not accept the filament that was loaded there, so i switched back to selector 3,
THe Mk4 had no options on the screen to select wich locked me into waiting for hte selector , feeder tofinsih
i then turned off the power tot the Mk4 for 10seconds and turned it back on,
the Mk4 detected that it went into power panic and reheated the print bed, realigned the axis, but it did not acknowledge the MMU3,
This made the Mk4 start printing without filament and lost the print.,
Then selected stop the print.

### Expected behavior

On power restart, MK4 detect if filament loaded in MMu3 before resuming

**Comment by CZDanol** [comment]
Internal ticket: BFW-5692
