### ISSUE TITLE
[ENHANCEMENT] Prusa MINI - Preheat - Preselect corresponding filament type

### ISSUE THREAD

**Issue by ondrej-kratochvil** [prusa3d/Prusa-Firmware-Buddy#4045]
### Printer model

MINI+

### Describe the enhancement

When e.g. PET-G type filament is inserted, the printer knows it (displays it in the lower right corner), but I always have to select the filament type for preheating.  Let this one already default and I'll just confirm it.

**Comment by murk-sy** [comment]
Duplicate of
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1795

Related pull request
- https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/3709
