### ISSUE TITLE
[ENHANCEMENT]  starting a print and showing options with the tool heads 

### ISSUE THREAD

**Issue by Peewee0512** [prusa3d/Prusa-Firmware-Buddy#4053]
### Printer model

XL 5 tool heads 

### Describe the enhancement

Ok so when you get ready to start a print and it show pla and on the first tool head and what not. I feel we should be able to pick a tool head that we want to print with. I don’t wanna unload tool head 3 filament to 1 just to use that filament

**Comment by Tomcus** [comment]
Hi, I am not 100% what are you referring to, but it looks to me you are looking for tool mapping feature, that is already implemented: https://cdn.help.prusa3d.com/article/tools-mapping-xl_668277. Please ether verify that this is what you want or please be more specific about your feature.

**Comment by Peewee0512** [comment]
Oh ok I’m sorry Sent from my iPhoneOn Jun 24, 2024, at 12:48 AM, Tomas Vybiral ***@***.***> wrote:﻿
Hi, I am not 100% what are you referring to, but it looks to me you are looking for tool mapping feature, that is already implemented: https://cdn.help.prusa3d.com/article/tools-mapping-xl_668277. Please ether verify that this is what you want or please be more specific about your feature.
