### ISSUE TITLE
[BUG]  XL printer identifies itself as MK4 over WIFI

### ISSUE THREAD

**Issue by langph** [prusa3d/Prusa-Firmware-Buddy#4068]
### Printer model

XL multi 5 heads

### Firmware version

6.0.3

### Upgrades and modifications

None

### Printing from...

Prusa Link

### Describe the bug

The WIFI name of the XL shows as MK4 in my client list. LOL. I cannot change the name in the printer.

### How to reproduce

Activate WIFI, add it to a network, look at all WIFI clients in the router..

### Expected behavior

The WIFI client name is "Prusa XL", or "The Mighty One" or "The 5 Headed Prusa".

**Comment by langph** [comment]
<img width="500" alt="Scherm­afbeelding 2024-07-03 om 11 35 55" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4465182/cb5720d2-9f47-4c95-b784-48f7bb6d412a">

**Comment by bryn51** [comment]
Adding the ability for the Network Identified name of the Printer device would be a great enhancement for all the Prusa Printers.  It could be implemented by adding a Printer Name to the settings.ini file, alongside the wifi credentials.

**Comment by murk-sy** [comment]
This is a Unifi issue, not related to the firmware. Unifi identifies device manufacturer (and type) by its MAC address.

It seems someone submitted just about every MAC address prusa used to be a MK4 (which it's not).

Click on the icon and then click "No icon available".

Before
![image](https://github.com/user-attachments/assets/b02cff33-fa56-42c8-abca-a5b1ce534f7e)

After
![image](https://github.com/user-attachments/assets/72995666-5732-40fa-8d2c-8ace0e360a24)
