### ISSUE TITLE
[BFW-4938] [FEATURE REQUEST] The ability to ready from print summary page

### ISSUE THREAD

**Issue by andgju** [prusa3d/Prusa-Firmware-Buddy#4069]
### Printer model

MK4, MK3.9, MK3.5, MINI & XL

### Describe the feature

The ability to set the printer status to ready from the post-print screen. Instead of going into [Control>Set Ready]

Like in the photo below, where I've replaced the greyed out "tune" button with a ready button. 
![screenshot_1](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/53541993/e9da58db-eb25-4e35-a8c0-551f2daea6c9)
compared to the original:
![original](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/53541993/cfbed565-ea0a-49f1-b659-119754dc8494)

**Comment by CZDanol** [comment]
Internal ticket: BFW-4938

**Comment by bryn51** [comment]
I do not agree that implementing this request would be a good use of scarce resources.
I vote against this enhancement.,

**Comment by andgju** [comment]
It would save a lot of clicks when using the queue function in Prusa Connect

**Comment by CZDanol** [comment]
Some sort of solution like this is in our plans :) Can't promise you when though

**Comment by bryn51** [comment]
> Some sort of solution like this is in our plans :) Can't promise you when though

The process used by prusa in deciding what work to do on software development is totally opaque. I wonder who they ask if a particular new feature is welcome of unwelcome, indeed what are the priorities and development roadmap. Certainly I've not seen anything like a survey put out to customers.
Whats strange is that in recent times we see new features released before they are ready for prime time: they come out half baked and not fully functional, and with almost zero documentation on usage. Release notes incomplete, user guide not updated etc.
Is this a product of the fact this is not a paid product and in the public domain ?
Whatever the case I observe the folks coming on here are arrogant in the extreme and appear to be faceless and  unaccountable.

**Comment by dillenburg** [comment]
I would love this soloution, it would save me a lot of time

**Comment by BugsBunny1403** [comment]
Nice idea

**Comment by Prusa-Support** [comment]
Thanks for the suggestion.
The "set ready" option is available right in the "print finish" screen from now with [FW 6.2.0-alpha2](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.2.0-alpha2).

Michele Moramarco
Prusa Research
