### ISSUE TITLE
[ENHANCEMENT] Disable Printed object 

### ISSUE THREAD

**Issue by ingbrzy** [prusa3d/Prusa-Firmware-Buddy#4072]
### Printer model

PRUSA XL 6.0.3 FW

### Describe the enhancement

Currently it is possible to disable up to MAX 16 objects during the printing on PRUSA XL

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1762519/ad55ca03-6c03-46e6-8cf8-e687cce9132a)

### Expected functionality

If are printing 100 objects, it should be possible to disable any of them, not just up to 16..

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1762519/67a7bb1b-7249-4a2c-bc02-304b450b96b8)

**Comment by danopernis** [comment]
Duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3646
