### ISSUE TITLE
[BUG] MK3.5 heatbed selftest error

### ISSUE THREAD

**Issue by rafalr100** [prusa3d/Prusa-Firmware-Buddy#4076]
### Printer model

MK3.5

### Firmware version

6.0.3

### Upgrades and modifications

None

### Printing from...

USB drive

### Describe the bug

After the upgrade from MK3s+ to MK3.5 I was running a selftest. During a selftest all test are passed except the heatbed which is failing. I was discussing this on a chat with many Prusa technical guys and checked all the possible components but all the results were correct (voltage, resistance etc.). I even replaced a thermistor but the error still exists. It also exists in older firmware version, even below 6.0.

One of the Prusa tech guy mentioned that this may be a firmware issue so I'm raising this for your feedback. 

Right now every time I start a printer and before each print I'm getting an error that a testing and calibration has not been done (only heatbed test is failing). I can start and successfuly complete a print, this error is not stopping me from printing. Heating bed is functioning correctly and heating up correctly.

During a self test it heats up to around 70 degrees, then a test time comes to end and is showing a red X.

**Comment by rafalr100** [comment]
![IMG_4302](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/4a41ce16-843d-4a66-bf0f-05032674755d)
![IMG_4303](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/8572fd2d-f2ba-4324-b304-f16afabd6da5)
![IMG_4304](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/17857cd9-e669-4598-88a6-50a1cc9fcf10)
![IMG_4305](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/321ba198-2636-4603-a830-5cc3a14c8a89)
![IMG_4306](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/7ed67ea0-c4c6-4e10-879e-a91167a6b406)
![IMG_4307](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/4a8e854f-4039-40fa-ad80-ade76ca6413d)
![IMG_4289](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/a178499d-aae5-42d7-9459-34b7df0c8157)
![IMG_4288](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/c5dbbc27-86ae-4057-97cb-64e421b7bd6e)
![IMG_4287](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/6bcffe18-5620-433b-8cd4-ce61e6025437)
![IMG_4291](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/d71ca045-6843-4d2f-90bc-e3382fe09dd8)
![IMG_4273](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/c710d939-f1d8-4adb-bdf2-5aa4f9440e4e)
![IMG_4306](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/d3509aa8-cda4-4d8e-aa8f-4d965c7ef5fa)
![IMG_4307](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/22fb10e0-ba8d-42a0-8599-1087e53f9759)
![IMG_4305](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/63d34893-7505-4f55-80d8-d7e21ad2a2e2)
![IMG_4304](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/bbb72891-3d8b-4894-b3f2-edfbc280a27d)
![IMG_4303](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/90fdd585-3e7e-498b-b135-232be0b6ac7e)
![IMG_4302](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/89075353/12c74866-19ec-49d5-a26a-1e51eb26952b)

**Comment by Prusa-Support** [comment]
Hello. Not sure what may have gone wrong in the troubleshooting session with Tech Support but something is clearly wrong on the hardware side.
Feel free to write to my attention - my name is in the signature (info@prusa3d.com) - so I can review, correct and report any negligence on our side if that is the case.

The heatbed test would hardly go beyond ∼60°C during the test, and for a large range of conditions, **unless the spring sheet is missing**. The test would be already doomed to fail if the heatbed reaches ∼65°C before the progress bar fills up.

So **make sure to put the spring sheet on the heatbed** and, if the test still fails, we may be looking at very specific environmental conditions or something wrong with the printer.

Your heatbed reached 70°C so the firmware is doing it right and this issue could be closed as non-firmware related.

Michele Moramarco
Prusa Research

**Comment by geekcouplettv** [comment]
I have the same issue but with MK4 on firmware 6.0.1 and 6.0.3.
I have two printers.

I wanted to check on one printer heatbed self test and hotend test because My old termistor on hotend end it's life.
And after installing it i went to calibration and check if it okay.

First on that printer where i changed the themistor i had fail because of hotbead was only going to 70 degress and then fails.

And I tested on my 2nd MK4 Printer witch is on 6.0.3 firmware. 

The 2nd printer some time ago went all self test without problem but now it is also saying error in heatbed selftest. It dosent go beyond 70 degress and it is showing fail.

So for me there is a problem with firmware not hardware. Printers are printing without problem PLA/PETG/ASA/PC

But cannot pass the selftest

**Comment by Kikkawaryu** [comment]
I had similar issue when upgrading to MK3.5

I took the Kapton tape off, ensured the bed thermistor was in the dead centre of the circle and orientated correctly it should be flat side down with the wires facing towards, put both sets of tape back down pressing all around the thermistor to create a good seal 

It now self tests with no issues.
