### ISSUE TITLE
[BUG] MMU filament change not reported

### ISSUE THREAD

**Issue by deimosfr** [prusa3d/Prusa-Firmware-Buddy#4079]
### Printer model

MK4 with MMU3

### Describe the bug

Hi,

When using MMU and filament requires to be replaced, the status is not correctly reported. Here is the output I have with `curl -H "X-Api-Key: xxx" http://prusa/api/v1/status | jq` command:
``` json
{
  "job": {
    "id": 418,
    "progress": 78.00,
    "time_remaining": 840,
    "time_printing": 3390
  },
  "storage": {
    "path": "/usb/",
    "name": "usb",
    "read_only": false
  },
  "printer": {
    "state": "PRINTING",
    "temp_bed": 60.0,
    "target_bed": 60.0,
    "temp_nozzle": 220.0,
    "target_nozzle": 220.0,
    "axis_z": 30.4,
    "flow": 100,
    "speed": 100,
    "fan_hotend": 8309,
    "fan_print": 6238
  }
}
```
The reported status should be "Attention", as without MMU.

Thanks

**Comment by PinkPandaKatie** [comment]
I did a bit of digging, and it looks like this case is supposed to be handled, in `src/state/printer_state.cpp`:

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1084661/b44892d7-5c42-4ced-8176-1d6a28c93aad)

`load_unload_attention_while_printing` looks for `MMU_ERRWaitingForUser`, which the `FILAMENT_EJECTED` error should set:

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1084661/59586453-a787-4a8a-9691-2f2aeb035e09)

I` can't really debug it at the moment but this just happened to me so I can confirm it.

**Comment by zeroflow** [comment]
I also ran into this bug / missing element yesterday.
Any MMU attention, e.g. not able to feed to Extruder, Filament Runout etc. should lead to a status change.

In my case, the filament ran out - which the printer detected and remedied - but the status didn't change and the printer stayed at "Printing".
This would be really convenient to have, e.g. to alarm you via HomeAssistant.
