### ISSUE TITLE
MINTEMP - Reset Printer

### ISSUE THREAD

**Issue by AutomaticMFG** [prusa3d/Prusa-Firmware-Buddy#408]
4.0.5 FW

Error details:
"The requested Bed temperature was not reached.
Nozzle temp: 210/210
Bed temp 53/60"

This threshold is too narrow and should pause the print to allow temp to recover.

//Received error printing PLA  (12 hours into a 15 hour print). 
//Reduced feedrate on this print to 80%
//New Mini, have checked cables to heatbed and TC and do not see any variations in reported temps.

**Comment by x10102** [comment]
What's your room temperature? The ERR_MINTEMP error used to happen to me when my room was too cold.

**Comment by JohnnyDeer** [comment]
Hi, @x10102 that's good point, room temperature have big impact to  mintemp, also wind from open window can trigger it. @AutomaticMFG can you confirm any of this situations, or it´s happen in common conditions?

**Comment by pjenkin** [comment]
OT (apologies), but as a noob i saw this message in the calibration wizard when first setting up a Prusa Mk 3 Mini - in my case, tightening the cable clamp on the buddy board/electronics box (step 28 in the handbook) had pulled out the connection for the heatbed heater (step 24), hence the bed not heating. Reconnected, all ok.

**Comment by AutomaticMFG** [comment]
On our system the issue proved to be a faulty cable to the thermistor. The issue got worse as time went and it was easier to determine root cause. New sensor resolved the issue. 

Thanks

**Comment by JohnnyDeer** [comment]
@AutomaticMFG good to hear, that you found problem and is already solved. I'll close this issue as solved.

**Comment by fabthefabulousfab** [comment]
Hi @AutomaticMFG 

I just got the exact same issue, symptom and context, could you indicate me more precisely the cable that you changed : is it the red/black/green/red cable that is going from below the mini ?

Thks!

**Comment by JohnnyDeer** [comment]
Hi @fabthefabulousfab please contact our Support with this issue. Chat in right down corner https://shop.prusa3d.com/en/ . Thank you.
