### ISSUE TITLE
[FEATURE REQUEST] Modifiable input shaping values directly in firmware.

### ISSUE THREAD

**Issue by HalloSpaceBoy5** [prusa3d/Prusa-Firmware-Buddy#4094]
### Printer model

MK4

### Describe the feature

It would be allowing the values in the input shaping section of the settings menu to allow for custom values. This would improve the printer by allowing the user to input their own measured frequencies, enabling better quality prints for all MK4s. This would be beneficial by improving the print quality of the MK4 on an individual basis.

### Expected functionality

You would be able to click on the value and turn the knob to change it. Maybe even being able to change the type of input shaper too. Already you can modify the values by putting them in GCODE, but it requires a custom profile making it more inconvenient.

**Comment by danopernis** [comment]
This was actually implemented
