### ISSUE TITLE
[BUG] Printer claims that hotend fan isn't spinning

### ISSUE THREAD

**Issue by Printer606** [prusa3d/Prusa-Firmware-Buddy#4104]
### Printer model

MINI+

### Firmware version

6.0.2/6.0.3/6.0.4

### Upgrades and modifications

Filament Runout Sensor

### Printing from...

USB Drive with Prusa Connect setup

### Describe the bug

Every layer when it's printing, it claims it isn't spinning, even though it is. I ran the fans test, and both fans passed. It is very frustrating and confusing.

### Expected behavior

It only should alert if the hotend fan is not spinning.

### Files

[gcode.zip](https://github.com/user-attachments/files/16396692/gcode.zip)

**Comment by adynis** [comment]
Which was the solution for this ?
