### ISSUE TITLE
[BFW-5949] [BUG] Impossible to change diameter of nozzle

### ISSUE THREAD

**Issue by ClaGre** [prusa3d/Prusa-Firmware-Buddy#4151]
### Printer model

XL multiple

### Firmware version

6.1.2

### Upgrades and modifications

None

### Printing from...

Prusa Connect

### Describe the bug

After upgrading from 6.0.4 > 6.1.2 I can't chose different nozzle diameter from the first and second head (I have two head configuration but I think 5 head have the same issue).
I've followed this guide: [https://help.prusa3d.com/guide/how-to-replace-the-prusa-nozzle-xl-multi-tool_506481](url) step 17
![IMG_0507](https://github.com/user-attachments/assets/72077bde-3c71-4370-b206-9cdc849832eb)

### How to reproduce

Install firmware, Go to Settings > Tools > Tool > Nozzle Diameter and set it to the corresponding size.
No nozzle diameter is shown.
Normally I use 0.6 at first head and 0.4 to second head.

**Comment by CZDanol** [comment]
Confirmed. Internal ticket: BFW-5949

**Comment by janecker** [comment]
Also just stumbled about this problem. Changed my nozzle and now I am unable to change it in the settings.

**Comment by ClaGre** [comment]
> Also just stumbled about this problem. Changed my nozzle and now I am unable to change it in the settings.

Don't worry, be patient normally this problem will be fixed soon from dev team.
To work I've rollback the FW.

**Comment by janecker** [comment]
> Don't worry, be patient normally this problem will be fixed soon from dev team. To work I've rollback the FW.

Yeah, hope so. Did not want to bother rolling back the firmware. Will ignore the warning for now (or might even disable it). Currently only one of the nozzles ist "wrong" so easy enough to ignore for now.

**Comment by albjerre** [comment]
Same issue here om my Prusa XL dual-head.

**Comment by ClaGre** [comment]
> > > Also just stumbled about this problem. Changed my nozzle and now I am unable to change it in the settings.
> 
> > 
> 
> > Don't worry, be patient normally this problem will be fixed soon from dev team. To work I've rollback the FW.
> 
> 
> 
> Which FW did you roll back? I am unable to install 6.0.4 due to "ESP error". Did you have the same error?

Absolutely not; I reinstalled 6.0.4 and everything works correctly (2 heads).
No ESP errors.

Have you tried reinstalling firmware from USB?
Have you tried to do an hard reset and after try to reinstall 6.0.4 from USB?

**Comment by Karkovski** [comment]
> > > > Also just stumbled about this problem. Changed my nozzle and now I am unable to change it in the settings.
> > 
> > 
> > > 
> > 
> > 
> > > Don't worry, be patient normally this problem will be fixed soon from dev team. To work I've rollback the FW.
> > 
> > 
> > Which FW did you roll back? I am unable to install 6.0.4 due to "ESP error". Did you have the same error?
> 
> Absolutely not; I reinstalled 6.0.4 and everything works correctly (2 heads). No ESP errors.
> 
> Have you tried reinstalling firmware from USB? Have you tried to do an hard reset and after try to reinstall 6.0.4 from USB?

I have tried a FW reinstall, but do not want to go through hard reset and full Selftest. I have 5T though.

Also, what is worth mentioning, I was seeing a lot of Dwarf-related errors after the update to 6.1.2 and these two issues (Dwarf and ESP errors) might be related.
However, I have made some progress in solving the issue, I think.
After disconnecting the XL Splitter (and effectively disabling T3-T5), the errors went away. When doing that (yesterday), I have taken out the XL Splitter board and cleaned the fuse blades (they were surprisingly, very much tarnished).
After that I did not get any Dwarf errors, but I have not tried downgrading to 6.0.4 yet, as I had to launch 30h print immediately after. Will try again when it's finished.

**Comment by CZDanol** [comment]
Guys, this is a ticket about a nozzle diameter menu item. If you have issues with dwarves/ESP, please use a different ticket.

We should be publishing a fix release very soon. If you need to change the diameter before it is released, you can downgrade the FW, change, then upgrade back. Sorry for the inconvenience :(

**Comment by danopernis** [comment]
Hi folks, v6.1.3 was just released and this should be fixed :rocket:

**Comment by nazar-pc** [comment]
Confirm as fixed on dual-head XL
