### ISSUE TITLE
[BFW-5949] [BUG] Per-tool nozzle diameter setting is missing in FW 6.1.2 (XL multi-tool)

### ISSUE THREAD

**Issue by tg73** [prusa3d/Prusa-Firmware-Buddy#4152]
### Printer model

XL multi-tool

### Firmware version

6.1.2

The `Settings->Tools->Tool->Nozzle Diameter` setting has accidentally been removed in fw 6.1.2, confirmed by livechat support. Devs are aware.

**Comment by CZDanol** [comment]
Confirmed. Internal ticket: BFW-5949

**Comment by ClaGre** [comment]
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4151

**Comment by CZDanol** [comment]
I see. Closing as a duplicate then :)
