### ISSUE TITLE
Stealth Mode / lights should be choose-able in prusaslicer or prusa connect

### ISSUE THREAD

**Issue by ufgum** [prusa3d/Prusa-Firmware-Buddy#4155]
### Printer model

XL 5 head

### Describe the enhancement

Describe the solution you'd like:

A switch to enable/disable "stealth mode" in prusaslicer before send the file to connect. Changing in connect would also be a solution.

Switch off all lights should also be an option, so it would be possible to make an "silent print" with one or two switches.

Many users has their printer in the living area. Switching always on the display is annoying.

### Expected functionality

Describe how it would work:
checkbox/es?

**Comment by bkerler** [comment]
For requesting such feature in prusaslicer, please post an issue at the prusaslicer repo, which would likely require a specific gcode in the prusa firmware (not sure if such gcode already exists).

For prusa connect I assume such option would be easier to integrate and would make much more sense.

**Comment by ufgum** [comment]
@bkerler 
Thanks, I did:
[PrusSlicer Repro](https://github.com/prusa3d/PrusaSlicer/issues/13324)
