### ISSUE TITLE
[BUG] Ethernet connection problem after upgrade firmware 6.1.2 on XL

### ISSUE THREAD

**Issue by Merlerault** [prusa3d/Prusa-Firmware-Buddy#4160]
### Printer model

XL 5 tools

### Firmware version

6.1.2+7894

### Printing from...

PrusaConnect

### Describe the bug

Since i have upgrade the Prusa XL with the last firmware 6.1.2+7894, the ethernet connect fail. The wifi work fine.
I have downgrade to the 6.0.4 firmware and the ethernet connection works.
I try to flash the XL to the last firmware... same problem, no IP with the ethernet cable

### How to reproduce

I reproduce the issue everytime I flash the xl with the Firmware 6.1.2 not with the firmware 6.0.4

**Comment by danopernis** [comment]
@Merlerault Since v6.1.2 there is a "Network Status" screen under "Info" menu. It may help with troubleshooting the internet connection problems.

**Comment by Merlerault** [comment]
Yes i see these new info but with le 6.1.2 firmware on the initial screen : no logo of ethernet 
In these new menu : no information IPV4, DNS, Passerelle are empty. Like if the network card is missing or ethernet cable not plug
I have change, the ethernet cable, swap the RJ45 but nothing, no connection
I try again with the 6.0.4 firmware, the same ethernet cable and the ethernet connection work fine.
I don't try with a manuel IP instead DHCP

So i have 23 solution... use the wifi connection with the 6.1.2 Firmware ou wait with the 6.0.4 firmware... i hope that the next firmware work better than this 6.1.2...

**Comment by danopernis** [comment]
@Merlerault Can you please post a screenshot of the network status screen on 6.1.2?

**Comment by Merlerault** [comment]
Hello. Ok i try to configure the XL with static IP. I have load the config and the ethernet connection work but i have lost the Prusaconnect link (i have a refused message) i thing that my load config is incomplete.
So the problem is on dhcp. 
![IMG_20240831_115620](https://github.com/user-attachments/assets/659ab7a6-6e7a-47b9-b915-4a040b36ee16)
![IMG_20240831_115650](https://github.com/user-attachments/assets/054841c7-3f7d-4eda-b264-294272478c49)
![IMG_20240831_115701](https://github.com/user-attachments/assets/040981fd-8623-4f66-abf1-f9aa6b1eeebc)
![IMG_20240831_115714](https://github.com/user-attachments/assets/ed4484f5-b126-4615-91b6-d8405eb1a8fb)

**Comment by Merlerault** [comment]
Oups sorry i have make a mistake i've close the issue...

**Comment by danopernis** [comment]
Just to be clear, you are reporting DHCP working on 6.0.4 but not working on 6.1.2? This is going to be difficult to track down. Maybe the packet capture or logs from the printer would help troubleshooting this, but those are pretty advanced debugging techniques. I am not aware of any recent changes to DHCP subsystem.

**Comment by Merlerault** [comment]
Hello This morning I flashed the XL printer with version 6.0.4 to take some screenshot of the Ethernet connection parameters and you prove that it works perfectly with version 6.0.4. Once the screenshoot were taken, I flashed the XL printer with the latest firmware (6.1.3) without going through version 6.1.2 and there, surprise, the Ethernet connection works again... This confirms that my Prusa XL does not didn't like firmware 6.1.2 at all.
