### ISSUE TITLE
[ENHANCEMENT] Material missing selection on the printer

### ISSUE THREAD

**Issue by romainpp** [prusa3d/Prusa-Firmware-Buddy#4163]
### Printer model

MK4, XL 

### Describe the enhancement

When I change the material on the printer, I cannot select PCTG or PVB for exemple.

The result is when I slice PCTG on PrusaSlicer it leads to a warning message when the print start. 

Would be great to add all material available in PrusaSlicer into the material selection within the printer.

**Comment by murk-sy** [comment]
Duplicate of:
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3915

It's scheduled so it's probably gonna be added in one of the next few releases
