### ISSUE TITLE
[BUG] Unstable wifi connection

### ISSUE THREAD

**Issue by VladimirVecera** [prusa3d/Prusa-Firmware-Buddy#4167]
### Printer model

Mini+

### Firmware version

6.1.2

### Printing from...

USB

### Describe the bug

After the last firmware update on the MINI+, I have a big problem with connection stability. Neither connect nor local connection works. If I reboot I get to local. I start uploading the gcode file and it ends up at 22% and the network connection drops again. I'm running on wifi with 98% signal.
Here is the ping.

Pinging 192.168.0.102 with 32 bytes of data:
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Request timed out.
Request timed out.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Request timed out.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Reply from 192.168.0.179: Destination host unreachable.
Request timed out.
Reply from 192.168.0.102: bytes=32 time=31ms TTL=255
Reply from 192.168.0.102: bytes=32 time=18ms TTL=255
Reply from 192.168.0.102: bytes=32 time=7ms TTL=255
Reply from 192.168.0.102: bytes=32 time=17ms TTL=255
Reply from 192.168.0.102: bytes=32 time=11ms TTL=255
Reply from 192.168.0.102: bytes=32 time=15ms TTL=255
Reply from 192.168.0.102: bytes=32 time=21ms TTL=255
Reply from 192.168.0.102: bytes=32 time=26ms TTL=255
Reply from 192.168.0.102: bytes=32 time=11ms TTL=255
Reply from 192.168.0.102: bytes=32 time=36ms TTL=255
Reply from 192.168.0.102: bytes=32 time=10ms TTL=255
Reply from 192.168.0.102: bytes=32 time=17ms TTL=255
Request timed out.
Request timed out.
Reply from 192.168.0.102: bytes=32 time=17ms TTL=255
Reply from 192.168.0.102: bytes=32 time=5ms TTL=255
Reply from 192.168.0.102: bytes=32 time=17ms TTL=255
Reply from 192.168.0.102: bytes=32 time=138ms TTL=255
Reply from 192.168.0.102: bytes=32 time=12ms TTL=255
Reply from 192.168.0.102: bytes=32 time=12ms TTL=255
Reply from 192.168.0.102: bytes=32 time=70ms TTL=255
Reply from 192.168.0.102: bytes=32 time=88ms TTL=255
Request timed out.
Request timed out.
Reply from 192.168.0.179: Destination host unreachable.
Request timed out.
Request timed out.
Reply from 192.168.0.179: Destination host unreachable.
Request timed out.
Request timed out.
Reply from 192.168.0.179: Destination host unreachable.

Ping statistics for 192.168.0.102:
    Packets: Sent = 50, Received = 38, Lost = 12 (24% loss),
Approximate round trip times in milli-seconds:
    Minimum = 5ms, Maximum = 138ms, Average = 28ms

**Comment by danopernis** [comment]
Since v6.1.2 there is a "Network Status" screen in the "Info" menu which may help you with troubleshooting network issues. Also, there are some more logs if you connect to serial line on baudrate 57600.
