### ISSUE TITLE
[BUG] Printer goes offline when extruder heat command is send via PrusaConnect

### ISSUE THREAD

**Issue by ingbrzy** [prusa3d/Prusa-Firmware-Buddy#4180]
### Printer model

XL 5 Head

### Firmware version

6.1.2+7894

### Upgrades and modifications

None

### Printing from...

PrusaConnect

### Describe the bug

issue reference
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3922

### How to reproduce

Set extruder temperature in the PrusaConnect

### Expected behavior

Heat extruder to the target temperature

**Comment by danopernis** [comment]
@ingbrzy I would rather reopen #3922 as it contains more info
