### ISSUE TITLE
Add more Print Specs to printing page, print complete page, Info area

### ISSUE THREAD

**Issue by gjsman** [prusa3d/Prusa-Firmware-Buddy#42]
This isn't as much of a bug as a request I have myself and seen elsewhere. If we could see the meters/grams of filament used during and after the print, this would be very, very useful.

Also, the Info page only displays CPU usage and something about Display test. "How many meters used" over the printer's lifetime (kind of like a print odometer) would be useful.

Last, but not least, for those of us without filament sensors (or even those with sensors), perhaps we could have a way to keep track of used filament. For example, if I load a spool, I could choose to mark it as a Full Spool, and the printer knows that if I don't unload it or otherwise object, it will keep track of how much I have left - until, when I attempt to print something with low filament, it suggests that I don't have enough and gives me the option to pause the print automatically shortly before it believes I will run out.

**Comment by michalxfanta** [comment]
Thank you for your ideas. We are already working on some and will consider others for the future.
