### ISSUE TITLE
[BUG] Spooljoin fails to unload filament

### ISSUE THREAD

**Issue by jsrumsey** [prusa3d/Prusa-Firmware-Buddy#4205]
### Printer model

MK3.5 MMU3

### Firmware version

6.1.3

### Printing from...

Prusa Connect

### Describe the bug

When using the Spooljoin function and first filament runs out, it tries to unload the filament, but fails, then MMU3 switches to the next filament position and tries to load the next filament in while the first filament is still present.  The MMU3 grinds and repeats.

### How to reproduce

Setup Spooljoin on the MK3.5 screen, let the first filament run out and observe the results.

### Expected behavior

It should have made a successful unload so the MMU3/PTFE tube was empty, then it would switch to the next filament position and be able to load the new filament.

**Comment by DRracer** [comment]
The most probable cause in this case is a misconfigured FINDA. The unload phase must finish OK on the MMU side, otherwise the MMU will refuse to move the selector to another slot.

Or the filament broke inside the PTFE tube and the unload actually finished OK (even though this scenario is unlikely)
