### ISSUE TITLE
[BUG] MMU3 Leds for selected filament are now off after upgrade to MK3.5 FW 6.1.3+7898 

### ISSUE THREAD

**Issue by antimix** [prusa3d/Prusa-Firmware-Buddy#4209]
### Printer model

MK3.5 REVO + MMU3

### Firmware version

6.1.3+7898 

### Upgrades and modifications

REVO 40W NOZZLE

### Printing from...

any

### Describe the bug

After bumping to MK3.5 FW 6.1.3+7898 the MMU3 Selection LEDs are always off.  They are on just during the MMU3 boot reset.
The filament selection buttons seems to work, the selector moves, but ALL the led are always off.
The MMU is "on" in the LCD panel. The MMU3 LED have the same behaviour of when the MMU3 is off (all off).

MMU has the latest FW 3.0.3 - nothing was changed from the MMU3 side.

### How to reproduce

Install the MK3.5 FW 6.1.3+7898 on a MK3.5 printer with MMU3 installed.
The LED will go off.

### Expected behavior

The MMU3 should behave normally with the LED on on the current selected filament.

**Comment by CZDanol** [comment]
Hello, MMU has it's own firmware and it is not possible for the firmware update on the printer to change leds behavior of the MMU.

I suppose you also upgraded your MMU3 firmware? There is leds behavior changed in the MMU firmware 3.0.0, as documented here: https://help.prusa3d.com/cs/article/status-led-explained-mmu3_510059
