### ISSUE TITLE
[BUG] MINI+ Randomly won't connect to PrusaConnect

### ISSUE THREAD

**Issue by Printer606** [prusa3d/Prusa-Firmware-Buddy#4212]
### Printer model

MINI+

### Firmware version

6.2.0-alpha1

### Upgrades and modifications

Filament Runout Sensor; Improved Fan Duct

### Printing from...

USB Drive with Prusa Connect setup

### Describe the bug

It works fine for a while, but then it drops connection with PrusaConncet, so I have to re-setup the Wi-Fi(thank goodness it has been effortless though since 6.1.2, but still annoying). 

### Expected behavior

It should not randomly disconnect from PrusaConnect.

**Comment by danopernis** [comment]
Is this possibly a duplicate of #4199 or #4200 ?
