### ISSUE TITLE
[BUG] MINI+: Print statistics / Odometer page has truncated text

### ISSUE THREAD

**Issue by plaes** [prusa3d/Prusa-Firmware-Buddy#4214]
### Printer model

MINI+

### Firmware version

v6.2.0-alpha1

### Upgrades and modifications

None

### Printing from...

USB / Prusalink

### Describe the bug

Odometer (print statistics) display has truncated text for "Print time" in v6.2.0-alpha1:
![image](https://github.com/user-attachments/assets/85aa1725-09ea-40ab-9e4e-a09594a9d272)

Unfortunately I don't remember whether this was an issue in earlier firmware.

**Comment by CZDanol** [comment]
Hello, that is fine. When you select the line, it will scroll.
