### ISSUE TITLE
[BUG] Crash during print (BOSD)

### ISSUE THREAD

**Issue by kerios69780** [prusa3d/Prusa-Firmware-Buddy#4217]
### Printer model

MK 3.5

### Firmware version

6.1.2

### Upgrades and modifications

E3D Revo hotend, MMU3 connected but desactivated.

### Printing from...

Octoprint

### Describe the bug

Mid print the printer crashed with a BOSD.

**Comment by CZDanol** [comment]
Hello, based on this information only, we cannot really do anything. Please send us a crash dump.
