### ISSUE TITLE
Text with Pause command not shown in printer display

### ISSUE THREAD

**Issue by KimA998** [prusa3d/Prusa-Firmware-Buddy#4220]
### Description of the bug

After you have sliced your project and have inserted a pause in the print - the text you have typed is NOT shown in the printers display on my MK3.9. 

Another issue/bug is when the printer has paused you have three options: tune, resume and stop. The stop bottom is selected by default!!! IT should be the RESUME.

### Project file & How to reproduce

![PauseThePrint](https://github.com/user-attachments/assets/3c376a8f-c08e-4dbc-807b-372b5eac10ae)

### Checklist of files included above

- [ ] Project file
- [X] Screenshot

### Version of PrusaSlicer

2.8.0

### Operating system

Win11

### Printer model

MK3.9 with MMU3

**Comment by nkappler** [comment]
I have a MK4S and noticed the same problem.
The text is actually shown on the display, but only for about 1 second or so.

**Comment by RodKimmell** [comment]
It's overwritten by the Time Remaining messages.  Time remaining should be suspended until user responds to the Pause options.

**Comment by RodKimmell** [comment]
This exact problem existed in the Einsy RAMBo board for the MK3.  It was fixed in that firmware.
Kindly assign this task to help get it resolved.

**Comment by CZDanol** [comment]
Kindly closing this as a duplicate of #3143
