### ISSUE TITLE
Tool changer crashes right side and drops tool after cancel 

### ISSUE THREAD

**Issue by WeaselWasher** [prusa3d/Prusa-Firmware-Buddy#4235]
### Printer model

XL 2 head

### Firmware version

6.2.0a1

### Upgrades and modifications

Shielded ribbon cable LCD to buddy

### Printing from...

Prusa connect, Ethernet 

### Describe the bug

Unfortunately I was in another room for the actual instance, but I'll describe what I did.

I finished loading new filament, set it to preheat PLA and went upstairs to slice my print and send it to the printer. I sliced a real simple print (vase mode trash can) and sent it via Ethernet connect. (Selected radio button, set printer ready and print)
I then realized that I forgot to scale a dimension to make it more oblong. I cancelled it after 3 min.. then I sliced the new one, and sent it via connect. Set printer ready and print. Connect was saying it was idle. I went ahead and deleted two files from printer via connect.. the one I had previously uploaded and another that I didn't need anymore.
A couple of minutes later I went downstairs to check on the print and found that the tool changer had gone all the way to the right, reached it's extent and unlocked and subsequently dropped the tool.
![PXL_20241004_034242135](https://github.com/user-attachments/assets/8984ebc4-b1af-42e4-8a2a-945a5881a2ad)
![PXL_20241004_034302861](https://github.com/user-attachments/assets/863346ce-029f-4929-a2c9-fd682a5c6a3f)

I checked the tool out and then placed it back in it's dock. The screen registered this, with a green checkmark then it flashed a screen I missed and then ended up giving me a USB fault. 
![PXL_20241004_034956596](https://github.com/user-attachments/assets/ee8d1f83-310b-461a-95b7-f6e432e0b42e)
I removed the USB, reconnected and resumed. It began heating, but I chose to stop the print and re-started it via the printer ui

### How to reproduce

I haven't tried. But I described exactly what I did above. 

### Expected behavior

The tool changer shouldn't ever travel that far to the right with a tool in it.

### Files

https://www.printables.com/model/665632-strong-vase-mode-garbage-bin-can 
Used this STL. Scaled up the z to 32cm and then sliced in vase mode 0.25 structural with prusa PLA in tool 1 (everything else default). Then cancelled that, and narrowed it. Made it a little longer, rotated it so it was near max on the diagonal and set it to the printer again.

**Comment by WeaselWasher** [comment]
In retrospect, that USB file error could be because the print had crashed and paused when I deleted the file via connect

**Comment by CZDanol** [comment]
Hello, this looks like #4337, should hopefully be fixed in the next release candidate.
