### ISSUE TITLE
[ENHANCEMENT] Make SpoolJoin work from Prusa Connect and minimise interaction

### ISSUE THREAD

**Issue by caprazzo** [prusa3d/Prusa-Firmware-Buddy#4264]
### Printer model

MK4, MMU3

### Describe the enhancement

I need to print 48 objects all of different weight between 400g and 600g, about 20kg in total, all using the same material. As projects like this will keep repeating, I need to maximise the time the printer can run unattended or attended by non trained people.

With a stock MK4 and all models queued in Prusa Connect, at the end of each print I would swap the printing plate with a clean one and set "Printer Ready" in connect.  This is 47 interactions for swapping plates, plus 20 roll swaps when the filament runs out. 

The plate swap is really easy to and happens at predictable times, but the roll swap is more problematic because it happens at essentially unpredictable times.

I think MMU3 SpoolJoin would be able to help here, but there are a number of issues that make this difficult to achieve with the current implementation:
* SpoolJoin requires to trigger the prints form the control panel, negating the benefits of the Prusa Connect queue, for example you need to remember exactly which item was just completed and find the correct next one in the menu. This is time consuming and error prone
* In addition, before each SpoolJoin requires to manually set the filament configuration which is fiddly and requires additional training

### Expected functionality

What I would expect to happen for my use case:
* I slice and load all my models on Prusa Connect and queue all the prints
* Before starting the first print, I enable Spool Join, and assign which slots I want to use for joining (in my case, all 5)
* The setting remains default for all subsequent single filament prints (It resets at the first multi filament print or manually)
* I set the printer to Ready to start the first print
* When the filament runs out on the first spool, the printer starts using the next one
* When a print ends, I just need to swap plate and set Printer Ready again
* When the last spool is reached, I refill al five and continue printing
* Optionally when the printer is idle in between objects, I can refill any empty slot

Alternatively I think this flow could be achieved entirely non-interactively by baking the SpoolJoin configuration in the GCODE.

Thank you!

**Comment by eqdeng** [comment]
I know this is closed, but @caprazzo's situation is similar to scenarios we have. I would be very curious to know how Prusa manages their print farm, because the described functionality seems like it would be common in any commercial print lab.
