### ISSUE TITLE
[BUG] UI issue with file menu

### ISSUE THREAD

**Issue by me25542** [prusa3d/Prusa-Firmware-Buddy#4267]
### Printer model

MK4

### Firmware version

6.1.3+7898

### Upgrades and modifications

[Custom smart enclosure](https://github.com/me25542/pico-smart_enclosure) connected via I2C connector on xBuddy

### Printing from...

USB (some files transferred via connect)

### Describe the bug

When I scroll down the file menu a ways, click on a file, then go back and scroll down (or up) one swipes worth (swiping up or down once) the name of the file that was selected is highlighted in white. One thing to note, I am using touchscreen control exclusively.

### How to reproduce

To reproduce issue:
- Make sure there are lots of files on the USB stick
- Scroll down a ways (several swipes), and select a file (with the touchscreen)
   - The file info screen will appear
- Select back (with the touchscreen)
- Swipe up or down once with the touchscreen

### Expected behavior

The previously selected file's name will appear the same as the others (white text on a black background) instead of highlighted (black text on a white highlight on a black background).

### Files

![IMG_20241024_101350](https://github.com/user-attachments/assets/66c24e95-210e-4c65-9e8a-de7abf53336f)
![IMG_20241024_10149](https://github.com/user-attachments/assets/8efe1aae-10ff-4362-8c85-2baff28b81a9)
![IMG_20241024_101327](https://github.com/user-attachments/assets/49f2c37a-64d7-495e-8ee6-31153710728d)

**Comment by CZDanol** [comment]
Hey, this is already fixed in 6.2.0-alpha.
