### ISSUE TITLE
HardFault on access to Web-Control

### ISSUE THREAD

**Issue by Luzifer** [prusa3d/Prusa-Firmware-Buddy#43]
Setup:
- Firmware: `4.0.1-final+1974`  
(from shipped stick, latest release from GH does not trigger an update)
- Browser: Firefox 71.0 on Linux
- Hardware: Prusa Mini + Filament Sensor

Steps to reproduce:
- Boot up printer
- Let an IP get assigned
- Open `http://<ip of printer>/` in browser
- Experience crash and fan spin-up on printer while getting only a partial website

Note:
- In **some** cases the site gets loaded without image but with stylesheet
- Most times the site looks like displayed below
- After reset on crash the (broken) website can refresh temperatures without issues
- Possibly related to / duplicate of #18 but in my case not related to an active print but occurring after freshly starting the printer without any print task, therefore opening a separate issue for this

Trace:
![IMG_20191229_162140](https://user-images.githubusercontent.com/20142/71558860-93e0fd00-2a4f-11ea-8b67-6d9a69dd1ade.jpg)

Website:
![image](https://user-images.githubusercontent.com/20142/71558869-a5c2a000-2a4f-11ea-97f2-66bfcedb9f2e.png)

**Comment by Lichtjaeger** [comment]
Perhaps I should also mention that a Jumper was sent after me. I haven't put it in because I don't use custom firmware. Is it possible that I still need to place it somewhere?

**Comment by michalxfanta** [comment]
We tested it and yes it's known bug.

**Comment by JohnnyDeer** [comment]
Hi, bluescreen bug is already fixed on newest versions of firmware, i´m closing this issue.
