### ISSUE TITLE
[ENHANCEMENT] signed -DCONNECT=NO builds

### ISSUE THREAD

**Issue by buhman** [prusa3d/Prusa-Firmware-Buddy#4315]
### Describe the enhancement

Create signed `-DCONNECT=NO` builds. This would allow people to create completely offline printers without installing unsigned firmware.

**Comment by danopernis** [comment]
Sorry, no. This is unmanageable from the combinatorics standpoint. There are already 10 firmware files in each release. After we add this, there will be 20. After somebody comes up with another toggle, there will be 40. To create completely offline printer, you are free to not connect it to the ethernet and remove wifi chip.

Arguably this could be beneficial for XL, but even still, you can solder out the chip or flash your custom firmware.
