### ISSUE TITLE
[BUG] Brim printed for CANCELLED object(s)

### ISSUE THREAD

**Issue by ninjubohra** [prusa3d/Prusa-Firmware-Buddy#4327]
### Printer model

XL

### Firmware version

6.1.3

### Upgrades and modifications

None

### Printing from...

Pursa Link

### Describe the bug

Brim for CANCELLED objects are still printed

### How to reproduce

Send a job with multiple objects ALL AT THE SAME TIME and use a brim
Cancel one of objects BEFORE printing starting but after job begins
It still prints all the brims

### Expected behavior

It should not print ANYTHING related to cancelled object(s)

**Comment by CZDanol** [comment]
Hello, this behavior is determined by the slicer – so I would direct you in the PrusaSlicer repository: https://github.com/prusa3d/PrusaSlicer/issues

Please first check if the issue was not already reported.
