### ISSUE TITLE
[BUG] All brims are printed first

### ISSUE THREAD

**Issue by ninjubohra** [prusa3d/Prusa-Firmware-Buddy#4328]
### Printer model

XL

### Firmware version

6.1.3

### Upgrades and modifications

None

### Printing from...

Prusa Link

### Describe the bug

Brims for all objects are printed first even when using print ONE AT A TIME

### How to reproduce

Add multiple objects on the jobs
Use print ONE AT A TIME option
Use print Brim option
Send job to printer
The printer will printer ALL THE BRIMS first and then start printing one object a time

### Expected behavior

Brim should be printed at the beginning of each object print

**Comment by CZDanol** [comment]
Hello, this behavior is determined by the slicer – so I would direct you in the PrusaSlicer repository: https://github.com/prusa3d/PrusaSlicer/issues

Please first check if the issue was not already reported.
