### ISSUE TITLE
Connecting or disconnecting USB causes version info menu to disappear

### ISSUE THREAD

**Issue by x10102** [prusa3d/Prusa-Firmware-Buddy#433]
I'm on the latest firmware. If a USB flash drive is inserted or removed while on the "Version info" screen all the text on the screen (except for "Return" and the page title) disappears.

It's a really minor bug but maybe you should look into it.

**Comment by JohnnyDeer** [comment]
Hi @x10102 , issue reproduced and confirmed, thank you for reporting.
