### ISSUE TITLE
[ENHANCEMENT] Rearrange Preheat menu options

### ISSUE THREAD

**Issue by zehkaiser** [prusa3d/Prusa-Firmware-Buddy#4333]
### Printer model

XL

### Describe the enhancement

Allow adjusting the order in which items are displayed in the Filament Preheat menu. I frequently use 3 options on the menu. One of which is Cooldown, which is at the very bottom. It would be nice to set my most used options at the top to save a bit of scrolling.

### Expected functionality

Long press on a filament in the Preheat menu to change the sort order. Or create a new menu in the settings menu to adjust the order.

**Comment by LoakAudio** [comment]
Hi,
I think it's already on the way for 6.2 : https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.2.0-alpha1
