### ISSUE TITLE
[BUG] Cancel object does not alter print preheating times

### ISSUE THREAD

**Issue by Demolux** [prusa3d/Prusa-Firmware-Buddy#4358]
### Printer model

XL

### Firmware version

6.2.0-alpha2

### Upgrades and modifications

None

### Printing from...

USB

### Describe the bug

Cancelling objects does not affect the preheating time:

I printed 20x dual color door knobs and cancelled 18 of them because I needed 2 and did not want to reslice.
I wondered why the printer pauses so long between tool changes - and saw that its because the extruder was not up to temperature yet.

I assume that is because the preheating command does not arrive in time due to lots of cancelled objects. That may be g-code limited and it is not a critical bug but I thought why not report it anyways.

### How to reproduce

Print 20x small drawer sized objects with 2 or more colors (toolchange required) and cancel all but 2 of them.
I assume these numbers are quite flexible. Print 10 and cancel 9 for example probably leads to the same long waiting times for heating the extruders.

### Expected behavior

The printer should know that less objects are being printed and should preheat in time so that it does not have to wait upon tool pickup.

**Comment by CZDanol** [comment]
Hello, I'm sorry, but fixing this would be technically very challenging - the slicer basically inserts the heatup commands in advance at a precalculated time. Cancelling objects throws a wrench in that completely.

Thanks for the report anyway :)
