### ISSUE TITLE
[BUG] Y-axis calibration fails

### ISSUE THREAD

**Issue by Scrazzled** [prusa3d/Prusa-Firmware-Buddy#4361]
### Printer model

MK4

### Firmware version

6.1.3

### Printing from...

USB

### Describe the bug

Y axis calibration fails on every firmware since 5.0. When I need to calibrate I have to roll back to 4.7.2 in order for it to complete successfully.  Ticket 3521 was closed due to inactivity but this issue has not been resolved. It's not a hardware issue.

**Comment by CZDanol** [comment]
Hello,
this **is** a hardware issue, even though your printer passed in the previous FW versions. Please contact our support for instructions on how to align your Y bearings correctly.
