### ISSUE TITLE
Printing Screen shows current design and layer

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#440]
I think the printing screen could be optimized. The settings, pause and stop buttons are pretty big and if they would be smaller (Since it's not touch they don't have to be that big :) there could be space for gcode preview of the design the printer is currently printing. It would be awesome if the printed layers would be orange and the layers that aren't printed would be grey. Also some kind of layer indication would be nice so for example: "Layer 25/55".

I just think that the space on the printing screen could be used in a better way and could display more or more accurate informations about the print and the printer :)
(Feature Request)

**Comment by HolgerMA** [comment]
+1

**Comment by CZDanol** [comment]
I believe we do have this now.
