### ISSUE TITLE
Gcode preview in file explorer

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#441]
Since the name of the file is not always describing it perfectly esspecially when there are designs bodies combined in one gcode, a small image of the gcode next to the filename would be awesome.

This would just simplify the way you find and choose files and how you use the file explorer :)

 (Feature Request)

**Comment by jkavalik** [comment]
@Fliens check https://github.com/jkavalik/GcodeThumbnailExtension (disclaimer: I did it and I am NOT affiliated with Prusa)
I tested it on Windows 8 and 10.

**Comment by Fliens** [comment]
@jkavalik that's pretty great but my request was for the prusa mini file explorer :)

**Comment by jkavalik** [comment]
@Fliens ah, I see now, sorry then.. Yes, that woud be useful. Or maybe have a <previous>/<next> in the preprint preview that shows the thumbnail already to browse files with details.

**Comment by Eldenroot** [comment]
I think that you can see the gcode preview when you open it in the printer... this should be enough, the image is large and you can see what you need.

@Prusa-Support

**Comment by Prusa-Support** [comment]
The current enlarged preview image (upon clicking) can be satisfactory in most cases, but that is not the object of this feature request I believe.
The request is to have an image right next to the filename in the list - without selecting the file - if I understand correctly.

Michele Moramarco
Prusa Research

**Comment by Eldenroot** [comment]
It could save some time to find the right file

Now the text scrolling speed for longer file names is really slow... this could be really helpful
