### ISSUE TITLE
Allow greater than 4x4 mesh leveling

### ISSUE THREAD

**Issue by gjsman** [prusa3d/Prusa-Firmware-Buddy#45]
The Prusa Mini currently uses 4x4 bed leveling, and while this is good and useful for most uses, some tools require I have a perfect middle spot, which can only be done using a 5x5 or 7x7 or other odd-numbered Mesh Leveling option. This is also very useful for users who want as perfectly flat of a bed as physically possible.

Relevant Forum Thread: [https://forum.prusaprinters.org/forum/general-discussion-announcements-and-releases/4x4-mesh-bed-leveling-why/#post-182333](https://forum.prusaprinters.org/forum/general-discussion-announcements-and-releases/4x4-mesh-bed-leveling-why/#post-182333)

**Comment by michalxfanta** [comment]
Now we think that 4x4 Mesh Bed Leveling is enough for MINI, but in the future, we may extend the settings with more options as we did on MK3S.
