### ISSUE TITLE
Changing filament menu goes back to general filament settings

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#461]
Hi when changing the filament the option to select the filament type and then change it just vanishes after a couple of seconds(while I'm still putting the old filament back on the spool) and I end up in the general filament settings screen. This timer should be increased a lot or you could just add a "back" button so that there is no need for a timer :)

**Comment by JohnnyDeer** [comment]
Hi @Fliens , shank you for suggestion.

**Comment by JohnnyDeer** [comment]
@Fliens this is not happening in latest FW version. Can you please confirm it and close this issue?

**Comment by Fliens** [comment]
Can confirm
