### ISSUE TITLE
Annoying prusa connect website message that the data can only be seen when the printer is on

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#463]
The title pretty much says everything :) When opening the prusa connect website there is a popup that the data is only available on this site when the printer is on. It's pretty annoying and the footer would be a better place for such a message :)
It's especially annoying when the website is opened on a phone (the "x" button is extremely small) or when using this website in an obs stream (always have to interact with the website because this popup is always there when the stream is started)
:)

**Comment by zoltan-l** [comment]
Is going to be replace see please https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/master/doc/ESP
