### ISSUE TITLE
Sound when the print is finished

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#464]
A small beep sound or something similar when the print is finished. It would also be great if we could de- or activate it in the printer settings (maybe also volume, so you could deactivate it by setting the volume to 0)

Feature Request :)

**Comment by x10102** [comment]
Already wrote that a while back #230

**Comment by JohnnyDeer** [comment]
@x10102 thank you for find out. I´m closing this one as duplicate.
