### ISSUE TITLE
Feature request - Define "prohibited area" of no extrusion during print

### ISSUE THREAD

**Issue by Tomik1598** [prusa3d/Prusa-Firmware-Buddy#481]
When printing large parts along with smaller ones. Those small ones may break loose and mess-up the big part. ("Spagetti" of freely extruded filament embedded into the big part...)
In such case it would be great to be able to pause print and somehow define a "prohibited area" on the XY plane, where the printer simply would not extrude. This would allow you to salvage the big part.
Definition of the area may be done in 2 steps by moving a line 1st side to side, 2nd left to right... 
It also might require some planning ahead, when placing your parts, but it could save filament, time and frustration... :)
In my last case, I improvised a small physical "fence" that allowed me to save the big part by wiping off the wasted filament. See enclosed pic...
![20200402_105053](https://user-images.githubusercontent.com/65625671/82374519-7244da00-9a1f-11ea-8a14-71dbb7961738.jpg)

**Comment by hawwwran** [comment]
Possibility to cancel part object of currently printing print would be very useful.
