### ISSUE TITLE
X axis homing, while website is open, belt skips

### ISSUE THREAD

**Issue by Gisi0** [prusa3d/Prusa-Firmware-Buddy#491]
When the website is open, homing of x axis not working well. I think, he is moving until a timeout. Belt is skipping.
When he stops, x axis homing is successful and he is going further.
I don't know if it is every time.
When the website is not open, no problems.

**Comment by JohnnyDeer** [comment]
Hi @Gisi0 , could you please describe steps needed to reproduce this issue? Which FW version is on your printer?

**Comment by Gisi0** [comment]
I will try to make a video.
Firmware is 4.0.5

**Comment by JohnnyDeer** [comment]
Could i please ask you for more information, and mentioned video @Gisi0 ? Thank you.

**Comment by JohnnyDeer** [comment]
Thank you @Gisi0 , then i'll close this issue. If you find out how to reproduce it, or you will create video, we can reopen it.
