### ISSUE TITLE
Feature Request: Lift and Park after "First Layer Cal."

### ISSUE THREAD

**Issue by Area5142** [prusa3d/Prusa-Firmware-Buddy#50]
Firmware Version: 4.0.1

**Problem:**
After running _first layer calibration_, the nozzle returns to front right position 10 mm over the build plate. I now have the choice of rerun the calibration. Doing so requires the build plate and the nozzle to be cleaned, but doing so it is very difficult when the build plate and nozzle is in this position:

![P1130559 - GitHub](https://user-images.githubusercontent.com/1320126/71773395-93b79480-2f5c-11ea-82e9-807461078488.JPG)

Running this test with PETG or other sticking filament requires the nozzle to be cleaned between runs.

**_Solution:_**
When the calibration is finished, lift z to 100 mm and centre the nozzle over the build plate. This way it is easy to clean the nozzle, remove the test print and prepare for another print (applying windows cleaner ;-)
If this is the last print, the printer would also be in a position where it could be turned off and moved (if required).

**Comment by michalxfanta** [comment]
Thanks for the idea, we'll consider implementing it.
