### ISSUE TITLE
[FEATURE REQUEST] [Mini] Preheat to Probing Temp (on Startup)

### ISSUE THREAD

**Issue by avrcore** [prusa3d/Prusa-Firmware-Buddy#535]
Preheat (170/60°C) in the Menu or optional on Startup. This is a easy workaround for the first layer calibration Temperature dependency. 

Thank you Guys!

**Comment by jkavalik** [comment]
Looks like this is already in the works - #321

**Comment by avrcore** [comment]
Oh, didn’t see that. But The Idea of Preheat on startup / power-on is still new.

**Comment by JustAnother1** [comment]
Wouldn't heating on power on be an safety issue in case of (longer) power outages ? (Just asking, should be considered before implementing this)

**Comment by avrcore** [comment]
1. Should be optional. The Mini just cant be used from a cold-start. 
2. This would straight up mean heating in general is a safety issue (which is not).
3. The SOC can restore default settings on power loss or critical events.
4. Doesnt make sense for me. A power outage would restore the the state i want anyways. Cold -> outage -> Cold. Or Warm -> outage -> Warm. But never Cold -> Warm, which would be undesired.

**Comment by JustAnother1** [comment]
@avrcore The Heaters are the things that burn down the house if something goes wrong. And yes that already happened also more than once.

I just wanted to make people aware that there are safety concerns with heating.

Making this feature a default off one will already help.

**Comment by JohnnyDeer** [comment]
Hi @avrcore  , this feature request cannot be done because of safety. I'll close this issue as invalid. Thank you for understanding.
