### ISSUE TITLE
[ENHANCEMENT]<4.0.5 firmware will not allow filament change at manual print pause>

### ISSUE THREAD

**Issue by scubagregory** [prusa3d/Prusa-Firmware-Buddy#547]
**Printer type** - [MINI]
**Optional upgrades** - [Filament Runout Sensor]

I frequently do color changes (up to 5 during a print).  Today, I accidentally loaded the wrong filament.  I caught it before restarting.  I restarted print and then paused the print once it resumed.  I went to click on "Change Filament" and the option was in the menu but noting happens when clicking "Change Filament"

The mini needs to add the ability to manually pause a print and do a filament change.  This feature is in the MK3S.  Recommend it be implemented similar to the MK3S.

**Comment by JohnnyDeer** [comment]
Hi @scubagregory , changing filament during pause is not allowed, same on MK series, this behavior is right. If you want to change filament just go to tune / change filament, without pausing print. I´ll close this issue as invalid.
