### ISSUE TITLE
[FEATURE REQUEST]<Add a "beep" when printer pauses for user intervention>

### ISSUE THREAD

**Issue by scubagregory** [prusa3d/Prusa-Firmware-Buddy#548]
**Printer type** - [MINI]
FW 4.0.5

When the mini stops for color changes it just pauses and provides no audible tone like the MK3S.  Need to add the option to turn on a "beep" when printer requires user intervention.

**Comment by x10102** [comment]
Related #464 and #230. Duplicate of #335.
