### ISSUE TITLE
[FEATURE REQUEST] Revert to non-Octoprint mode after Octoprint disconnects from serial.

### ISSUE THREAD

**Issue by derenma** [prusa3d/Prusa-Firmware-Buddy#587]
**Printer type** - [MINI]

**Optional upgrades** - Filament Runout Sensor, Bondtech Extruder, Raspberry PI w/ Octoprint

**Is your feature request related to an existing problem? Please describe.** - Not that I am aware of.

**Describe the expected functionality** - When Octoprint connects to the Mini and it is put into "Octoprint mode", stock functionality is not returned after the serial connection is disconnected. A reboot is required to revert the printer to "stock", or USB, mode. Detecting when the printer is disconnected from Octoprint, should revert the printer back to USB mode.

**Comment by JohnnyDeer** [comment]
Hi @derenma , this issue is similar to #360 . I´ll close this one as duplicate.
