### ISSUE TITLE
[BUG] Nozzle heating display during filament runout while printing

### ISSUE THREAD

**Issue by nwalke** [prusa3d/Prusa-Firmware-Buddy#604]
**Printer type** - [MINI]

**Printer firmware version**-  4.1.0 - rc1

**Original or Custom firmware** Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - USB

**Describe the bug**
  During a print I ran out of filament, the printer did everything correctly and as I would expect (parked, began cooling nozzle, indicated via buzzer, display asking me to load new filament, old filament excess unloaded).  However, even though the nozzle was cooling, the display indicated it was actually heating (flashing orange).  When I loaded new filament and told it to continue, it waited until the nozzle was back up to temp and continued on as expected.

**How to reproduce**
  Print a model, run out of filament, watch display.

**Expected behavior**
  The display should show the nozzle temp as flashing blue since it is cooling.

**G-code**
  I can do this if requested, but don't think it's related to the model.

**Crash dump file**
  No crash.

**Video**
  Didn't think to take a video of it.

**Comment by JohnnyDeer** [comment]
Work as expected on 4.3.1 during runout (after safety timer drop on) pause and stop. I´m closing this issue.
