### ISSUE TITLE
Config Menu for Sensorless Homing Sensitivity

### ISSUE THREAD

**Issue by ChengQian1007** [prusa3d/Prusa-Firmware-Buddy#609]
Could you please create a menu for config the sensorless homing sensitivity?

**Comment by x10102** [comment]
Why do you need this? If the sensorless homing doesn't work correctly you probably got a hardware problem.

**Comment by ChengQian1007** [comment]
Reassemble the Axises, belt tension, bearing, grease, not parallel X Axis and so on, all these could lead to increase the fiction and have influence on the Sensorless Homing Sensitivity value and thus result the failure to homing. Cannot home can not print easily. It is also much more easier to tune the sensitivity value a litte bit as to find out which one component of many leads to the problem.
I have also read in the forum that some printers have this problem directly after arrival.
