### ISSUE TITLE
[BUG]<Bed Temp Drop cause error/ abort>

### ISSUE THREAD

**Issue by Eggman663-t** [prusa3d/Prusa-Firmware-Buddy#615]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version**-  [4.1.0 RC 1]

**Original or Custom firmware** [Original]

**Optional upgrades** - [no upgrades]

**USB drive or USB/Octoprint**
  usb flashdrive, new one with extension cable

**Describe the bug**
  Print starts but after a short time it fails because of heatbed temperature drop

**How to reproduce**
  how can i send files, drag and drop is not working for .gcode

**Expected behavior**
  I dont get it?

**G-code**
sorry,first time on github how should I can attach something

**Crash dump file**
see above

**Video**
  same here

**Comment by JohnnyDeer** [comment]
Hi @Eggman663-t , this issue is very likely broken 
cable of bed thermistor. Please contact our Tech Support, they will help you :) ( chat is on right side down ... https://shop.prusa3d.com/en/ ).
