### ISSUE TITLE
[BUG] Flash drive sometimes needs to be reconnected

### ISSUE THREAD

**Issue by x10102** [prusa3d/Prusa-Firmware-Buddy#632]
**Printer type** - MINI

**Printer firmware version**-  4.1.0 RC1

**Original or Custom firmware** Original

**Describe the bug**
Since updating to 4.1.0 RC1  Sometimes the printer shows a "no USB" message after turning it on even though USB is plugged in. Removing and re-inserting the USB fixes this.

**How to reproduce**
  1. Insert the USB drive
  2. Shut down the printer
  3. Turn the printer back on

**Expected behavior**
  The USB should always show up when inserted

**Comment by JohnnyDeer** [comment]
Hi @x10102 , thank you for reporting. Are you using original usb stick?

**Comment by x10102** [comment]
@JohnnyDeer Yes I am using the original stick.

**Comment by JohnnyDeer** [comment]
@x10102 unfortunately i can't reproduce it. Did it happens to you also on 4.1.0 final?

**Comment by x10102** [comment]
It doesn't, nice.
