### ISSUE TITLE
[ENHANCEMENT] Please bring back relative remaining time

### ISSUE THREAD

**Issue by noxhirsch** [prusa3d/Prusa-Firmware-Buddy#648]
**Printer type** - [MINI]
**Printer firmware version** - 4.1.0 - RC1

**Is your suggested improvement related to an existing problem? Please describe.**
  With the new release candidate the expected end time is calculated from relative remaining time. While that is really neat when selecting a file it gets pretty annoying while the print is running. I always have to check the clock to get a feeling of how many minutes remaining - or I have to "calculate" the remaining minutes in my head using the printing time and percentage.

**Describe the expected functionality**
  For me it would be perfect to have the absolute end time only in the file preview screen before printing. In the printing screen relative remaining time would be enough.
Alternatively the printing screen could show both types of time e.g. above each other (but not switching because then you check the display at the wrong moment half the time) or it could be an option.

**Comment by caro-coder** [comment]
I'll second that! It drives me nuts! 🤯

**Comment by nicolasvac** [comment]
I agree with that. Put both infos, like 2h 58 minutes remaining (23:58)

**Comment by mlgold** [comment]
I'm would prefer to have either the estimated completion clock time and minutes and seconds remaining, or the estimated completion time and the current time. This should be on both the LCD and web page.

**Comment by colingg** [comment]
Give us the option as a setting please:

1. Show ETA time ( eg: 14:05 )
2. Show relative time ( eg: 27 minutes remaining )
3. Show both: ( eg 27 minutes remaining [14:05] )
4. Switch between 2 times **1 AND 2**

**Comment by adynis** [comment]
I vote for showing both (or at least (additional to ETA time) to add current time in the top, like any mobile phone)

**Comment by Gyrxiur** [comment]
Yeah, show both, screen is large enough.

**Comment by Ondrashek** [comment]
I want relative time too. :-)

**Comment by anymouse404** [comment]
This problem affects me as well. 
Currently there is no decent way to know what time the MINI is set to, and if it gets confused by DST (and it does) then the estimate is off by an hour, which is very frustrating.

**Comment by chillygithub** [comment]
Another vote for relative time.
I have resorted to blocking NTP from the Mini at my router so that the relative time is shown.

**Comment by Eldenroot** [comment]
Showing both! So number 2)!

**Comment by Eldenroot** [comment]
Also the worst thing - if you connected to the internet (4.4.0_RC1) - the time is switched to relative... annoying!

**Comment by Prusa-Support** [comment]
Thank you for sharing your ideas.
As the latest firmware 4.4.0 will possibly "democratize" the connection capabilities, and leverage related features, we may see an increasing interest in the topic.

We are taking notes and discussing them with the developers.

Michele Moramarco
Prusa Research

**Comment by DrBomb** [comment]
I hope it can be brought back.

**Comment by dimitarsp** [comment]
I recently upgraded the firmware, and yes, like everyone else, I desparately miss seeing the remaining print time on the prusa mini display. Please bring this back!

**Comment by Prusa-Support** [comment]
I may seem to understand that the behavior is different with the new FW 5.1.0-alpha1.

The relative remaining time is back and displayed even if the printer is connected to the network.
The estimated end time is available through Prusa Link/Connect interface.
I can't tell if this will be definitive though so the issue can stay open for the time being.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
(you may receive email notifications but the last two messages will be deleted)

That was totally my bad.
Later I noticed the wi-fi signal was not stable on the router.
Now it is stable and I can see the print end time and not the remaining time.

Michele Moramarco
Prusa Research

**Comment by espr14** [comment]
### Like in [Snake FW](https://github.com/Snake-FW/P32-FW/releases)?

![IMG_20231217_223557](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/46957311/24e976c2-34f3-4cd3-94ed-785584a47cc1)

**Comment by Prusa-Support** [comment]
I seem to understand this request has been implemented and the commit is probably this one as the time information will appear in a cyclical alternation https://github.com/prusa3d/Prusa-Firmware-Buddy/commit/cc4936cee1c0ba7a7c152a3ebb6ca5c5f8f77cbb.

However, it won't be available until the next firmware public release, which will probably occur in several weeks or even a few months as there are big projects in progress. We don't have an estimated time but please stay tuned.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
The commit that addresses this issue was merged and included already in FW 5.2.0 (MK3.5 only) and spread on MK4/MK3.9/XL printers with the more recent FW 6.0.0.

The issue will be closed as solved.

Michele Moramarco
Prusa Research

**Comment by anymouse404** [comment]
> [...]included already in FW 5.2.0 (MK3.5 only) and spread on MK4/MK3.9/XL printers[...]

> The issue will be closed as solved.

Does that mean that it's acutally a WONTFIX for the MINI that *this* issue is about?

**Comment by Prusa-Support** [comment]
That was my mistake in the listing. The same firmware base code is shared with Prusa MINI so the change should apply to all "Buddy-based" products. I've corrected my previous comment.

Michele Moramarco
Prusa Research
