### ISSUE TITLE
[BUG] Firmware Downgraded

### ISSUE THREAD

**Issue by hebbet** [prusa3d/Prusa-Firmware-Buddy#670]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MINI

**Printer firmware version**-  it was on 4.1.0-RC1

**Original or Custom firmware** Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
USB flash drive

**Describe the bug**
The printer was running on 4.1.0-RC1 and i attached an usb stick with the gcode i was going to print in it and started the printer.

Unfortunately there as an old firmware file on the stick and it flashed it.

i didn't notice it at first, as i search for the correct filament in my boxes.

all the settings are gone after that and i had to re run the wizard.

**How to reproduce**
install firmware rc on the mini insert an usbstick with an older firmware
boot it up

**Expected behavior**
i expect that the prusa mini doesn't downgrade without asking for confirmation.

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by JohnnyDeer** [comment]
Hi @hebbet it's a new function, not bug. You can choose in menu automatic FW update on power on or reset printer if FW is on usb stick. If is this function set on OFF printer will ask you about update as in previous versions. I´m closing this issue as invalid.
