### ISSUE TITLE
[BUG] G28 home should not ignore M206 Home Offsets afterwards

### ISSUE THREAD

**Issue by 4nthonylin** [prusa3d/Prusa-Firmware-Buddy#693]
Not sure if this is the intended behavior but logically doesn't seem to be correct.

**Printer type** - [MINI]

**Printer firmware version**-  [4.1.0]

**Original or Custom firmware** [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint** - USB Drive

**Describe the bug**
When M206 Offsets are set and then G28 Auto-home is run, it will set the origin with the M206 Home offsets nullifying the home offset.

**How to reproduce**
G28 ; Home
G1 Y0; Goes to machine Y0
M206 Y-5; Sets Home Offsets
; Optional: G1 Y0 will now go to machine Y5
G28 ; Home Again
G1 Y0; will now go to machine Y0 instead of Y5

**Expected behavior**
After G28 is run with M206 offsets, the offsets should still work afterwards.

G28 ; Home
G1 Y0; Goes to machine Y0
M206 Y-5; Sets Home Offsets
; Optional: G1 Y0 will now go to machine Y5
G28 ; Home Again
G1 Y0; should go to machine Y5

**G-code**
 Pasted above;

**Crash dump file**
[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/4933484/dump.zip)

**Video**
  Can make one if required. G-Code and expected behavior should be enough.

**Comment by JohnnyDeer** [comment]
Hi @4nthonylin thank you for reporting. Actually we know about this bug but have low priority at this time.
