### ISSUE TITLE
[BUG] Load filament procedure doesn't wait for temp to cool down.

### ISSUE THREAD

**Issue by simonbugler** [prusa3d/Prusa-Firmware-Buddy#698]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]
Mini

**Printer firmware version**-  [e.g. 4.0.5, ...]
4.1.0

**Original or Custom firmware** [Original/Custom]
Original

**Optional upgrades** - [e.g. Filament Runout Sensor]
None

**USB drive or USB/Octoprint**
USB

**Describe the bug**
Nozzle heated to 275 manually in settings.

Then load filament used and PLA selected. It immediately loads the filament without waiting for it to cool down.

**How to reproduce**
Manually select temperature in Settings and set to 275

Load filament and chose PLA

**Expected behavior**
Wait for correct temp for PLA before loading.

**G-code**
None
**Crash dump file**
None
**Video**
None

**Comment by JohnnyDeer** [comment]
Hi @simonbugler I can confirm this bug. Thank you for reporting.
