### ISSUE TITLE
The printing time is incorrect

### ISSUE THREAD

**Issue by mrunhart** [prusa3d/Prusa-Firmware-Buddy#7]
On the display it reports that the printing time elapsed is "13d  3h 16m" and it should report "1d  3h 16m", must be wrong because the printer has not even existed that long! lol.

V4.0.0 firmware provided on USB stick with printer

I did not watch the time rollover past 24 hours so I am not sure of the exact problem but I can try things if it helps to solve.

I am an amateur programmer so I doubt I can find it in the source conclusively on my own, and I am unwilling to break the tab off my mainboard to try to test it to contribute.

![IMG_20191220_210937](https://user-images.githubusercontent.com/59106834/71303119-8e115a80-2371-11ea-94c0-535a9d018c87.jpg)
![IMG_20191220_210940](https://user-images.githubusercontent.com/59106834/71303120-8e115a80-2371-11ea-9168-c23193062457.jpg)

**Comment by dragomirecky** [comment]
Hi @mrunhart,

thanks for the bug report! I created a PR fixing this issue. 

Enjoy your new Original Prusa MINI! :)
