### ISSUE TITLE
Prusa Mini Firmware 4.1.0 time remianind on Prusa Connect shows as seconds instead of Hrs / Min

### ISSUE THREAD

**Issue by rockytoptim** [prusa3d/Prusa-Firmware-Buddy#700]
After update to firmware 4.1.0 on Prusa Mini the time remainin on Prusa Connect shows at seconds not Hrs & Minutes.  See attached screenshot.
![TimeReminainPrusaMini](https://user-images.githubusercontent.com/6663883/88019884-afe5e200-caf8-11ea-8876-867408e22147.PNG)

**Comment by JohnnyDeer** [comment]
Hi @rockytoptim ,we will have look at this. Thank you for reporting.

**Comment by zoltan-l** [comment]
Resolved in release 4.3.3
