### ISSUE TITLE
[BUG] Entering the tuning menu while octoprinting screws up head movement.

### ISSUE THREAD

**Issue by d4rken** [prusa3d/Prusa-Firmware-Buddy#717]
**Printer type** - [MINI]

**Printer firmware version**-  v4.2.0-RC1

**Original or Custom firmware** [Original]

**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint** Octoprint

**Describe the bug**
While printing via OctoPrint, if I enter the tune menu, the head moves up and out of the while (while extruding), and then moves back to the print, printing in the air.

**How to reproduce**
Start print via OctoPrint, enter tuning menu on the printer. In some cases also reproducible while bedleveling.

**Expected behavior**
Headmovement not being interrupted by entering the tuning menu.

**G-code**
It's not specific to a print.
[GEPRC_Mark4_BN-880Q_GPS_Mount_v2_0.2mm_FLEX_MINI_1h16m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/4977527/GEPRC_Mark4_BN-880Q_GPS_Mount_v2_0.2mm_FLEX_MINI_1h16m.zip)

**Crash dump file**
Didn't crash.

**Video**
If you can't reproduce it, I'll make one, currently don't want to break my ongoing print.

**Comment by JohnnyDeer** [comment]
Hi @d4rken did you noticed this issue on 4.1.0 or there was no problem?

**Comment by d4rken** [comment]
I have not tried `4.1.0`.

**Comment by d4rken** [comment]
Doesn't happen on the `4.1.0` release.

**Comment by JohnnyDeer** [comment]
@d4rken thank you for find out.

**Comment by RobeeeJay** [comment]
I have this happening to me as well on `4.2.0-RC1`, it hasn't happened on `4.1.0` or any earlier release that I know of. It specifically happens when I adjust Live Z up or down. It instantly ruins a print, but thankfully I am only doing this on the first layer.

**Comment by RobeeeJay** [comment]
@d4rken have you noticed this happening in the release version of 4.2.0? I've changed settings a few times now in the Tune menu and it doesn't seem to be happening to me any more. Maybe it was fixed in final?

**Comment by d4rken** [comment]
I have not had the time to test this. I'd have expected this issue to be mentioned in a commit or PR if it was fixed?

**Comment by Chleba** [comment]
Hi,
This has been fixed in FINAL release version 4.2.0.

**Comment by JohnnyDeer** [comment]
I can confirm it's fixed. I'm closing this issue as solved
