### ISSUE TITLE
[BUG] Watchdog does not display error or wait for confirmation after crash when using OctoPrint

### ISSUE THREAD

**Issue by derenma** [prusa3d/Prusa-Firmware-Buddy#741]
**Printer type** - MINI

**Printer firmware version**-  4.1.0 Final

**Original or Custom firmware** - Original

**Optional upgrades** -Filament Runout Sensor

**USB drive or USB/Octoprint** - Octoprint

**Describe the bug**
Due to a failing bed thermistor, watchdog would terminate the print and immediately reboot. I then switched to USB and watchdog would then report the error and prompt me for confirmation.

**How to reproduce**
Start print with OctoPrint and simulate bed thermistor failure by unplugging it during a print.

**Expected behavior**
Watchdog provides error description when a crash occurs in OctoPrint mode.

**Comment by JohnnyDeer** [comment]
@derenma this bug is fixed in 4.3.0-RC1, thank you for reporting. I'm closing this issue as solved.
