### ISSUE TITLE
[ENHANCEMENT] German translation of "return"

### ISSUE THREAD

**Issue by dahuafschmied** [prusa3d/Prusa-Firmware-Buddy#756]
Mini 4.2.0 Final

Please change the german translation of "return" (first menu entry) to "Zurück" the used translation "Rückkehr" hurts the eyes of Germans :-)
"Zurück" is the common used word for this.

**Comment by JohnnyDeer** [comment]
Hi @dahuafschmied thank you for reporting.

**Comment by dahuafschmied** [comment]
Fixed in 4.3.0 RC1
Thank You
