### ISSUE TITLE
WATCHDOG RESET followed by crash dump(BSOD)

### ISSUE THREAD

**Issue by ve3mic** [prusa3d/Prusa-Firmware-Buddy#763]
[dumpdotbin.txt](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5043291/dumpdotbin.txt)

**Printer type** - MINI

**Printer firmware version** - 4.2.0 (Final)

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - USB flash drive

**Describe the bug** - WATCHDOG RESET (RED SCREEN) followed by crash dump (BSOD)

**How to reproduce** - Happens shortly after mesh bed leveling and purge line is printed

**Expected behavior**
  

**G-code** - Doesn't matter
  
**Crash dump file** - see attached

**Video** - not required

![20200806_154744](https://user-images.githubusercontent.com/5625125/89598460-e1fe8000-d82a-11ea-940e-7710e258b2ab.jpg)

**Comment by ve3mic** [comment]
[dumpdotbin.txt](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5043329/dumpdotbin.txt)

Dump.bin

**Comment by JohnnyDeer** [comment]
Hi @ve3mic, thank you for reporting.

**Comment by JohnnyDeer** [comment]
We are constantly working on finding reason for this bug. Hopefully it will be fixed in next release. Thanks for understanding.
(Same for #771 & #791)

**Comment by gameroptimizer** [comment]
Hi
My BSOD on prusa mini cause by Special marks on usb on one Gcode name.
language pack got messed up i took that out and my printer is working like dream again

**Comment by DRracer** [comment]
@inferior-minion Does your error look like in issue #771? If yes, please try FW 4.2.1 and report back. Thank you.

**Comment by JohnnyDeer** [comment]
If there isn't more BSOD cases I´ll close this issue soon. Please leave comment here if anyone will have BSOD on 4.2.1.

**Comment by vintagepc** [comment]
I'll bite. Got a BSOD with the same message after a Watchdog reset on 4.2.1; this was the second or third layer of the print, if that matters. Will retrieve dump from USB after print finishes...

![IMG_0006](https://user-images.githubusercontent.com/53943260/96351031-e8a93f00-1086-11eb-8fe4-c8c2e1478293.JPG)

**Comment by vintagepc** [comment]
[dump.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5396403/dump.bin.zip)

**Comment by JohnnyDeer** [comment]
@vintagepc thank you for reporting, its new case.

**Comment by DRracer** [comment]
@vintagepc Hmmm, this is really new ... tbh the second report like this on FW 4.2.1. You say it happened while printing? If it happens again, please try connecting the USB flash drive via a USB extension cable and/or use another USB flash.

**Comment by vintagepc** [comment]
Correct - During the second or third layer (I'd watched the first one go down). 

Interesting you mention USB - After the reboot I went to restart the print and it choked up after selecting the print. 

I was able to browse the USB files, went to select the one in question and it froze for a few seconds and then displayed an empty directory listing. 

I checked the drive was securely inserted (it was) but I had to disconnect and reconnect it to get it to show again. After that I could select the file and the print completed without issue. I'd chalked that up to it being left in a bad state after the crash but it sounds like you think it might be a sketchy USB drive? (FWIW I'm using the stock one that came with the printer).

**Comment by DRracer** [comment]
@vintagepc can you please do a fsck and may be also badblocks (nondestructive read/write) test of the USB flash drive on linux?

**Comment by vintagepc** [comment]
Badblocks came back clean as well - as corroborated by the fact I was able to print the same file again without issue. 

```
# badblocks -nsv /dev/sdc1 
Checking for bad blocks in non-destructive read-write mode
From block 0 to 7864287
Checking for bad blocks (non-destructive read-write test)
Testing with random pattern: done                                                 
Pass completed, 0 bad blocks found. (0/0/0 errors)

```

**Comment by marekmosna-prusa3d** [comment]
Hi @vintagepc,

can you please provide us your USB stick structure layout(folders, files, ...)? When you find out the way how to reproduce such an issue, that would be awesome and of course the most helpful. Basically, is before such a crash anything extraordinary during the process?

Thank you very much for your effort.

**Comment by vintagepc** [comment]
Sure - nothing untoward; I simply added a few additional sliced files to the USB drive as received from the factory. 
![image](https://user-images.githubusercontent.com/53943260/96586923-a7e03e80-12af-11eb-9d21-0885066381bd.png)

So far it has not recurred but I will do my best to keep an eye out and note anything unusual surrounding the event.

**Comment by marekmosna-prusa3d** [comment]
Hi @vintagepc,

Thank you again for your prompt answer. After some investigation I need to ask you another questions just to confirm what could happened:

1. Did the BSOD occur immediately after the printer startup? (< 20 seconds)
2. Last what you did was press the knob
3. Did you do anything else? (plug/unplug the USB stick, ethernet cable,...)

Thank you for your contribution.

**Comment by JohnnyDeer** [comment]
I created a separate issue to make workaround more clear. All comments please write to #990, thank you.
