### ISSUE TITLE
Filament and temperature settings changed after filament run out

### ISSUE THREAD

**Issue by MilanNXT** [prusa3d/Prusa-Firmware-Buddy#764]
[MF_crossway_module_0.2mm_PETG_MINI_2h51m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5041108/MF_crossway_module_0.2mm_PETG_MINI_2h51m.gcode.zip)

Printer type - MINI

Printer firmware version - 4.2.0-final

Original or Custom firmware - Original

USB drive or USB/Octoprint - USB flash drive

Describe the bug
While printing  PETG model filament run out. Then temperature and filament settings has been changed to PLA (bed: 90, noozle: 240). Seems its not even proper temperature even for PLA print. Printing GCode attached.

Expected behavior
Keep filament and temperature settings

![viber_image_2020-08-07_13-37-25](https://user-images.githubusercontent.com/22826910/89642068-5977f200-d8b3-11ea-8470-2f47289a5aed.jpg)

**Comment by JohnnyDeer** [comment]
Hi @MilanNXT, there is no bug. In Gcode is command to set temperatures 240/90 and it´s not related to filament runout. I'm closing this issue as invalid. 


![BFW #764](https://user-images.githubusercontent.com/55742006/89763795-87e41000-daf3-11ea-8704-1b0b3a2c2ffb.png)
