### ISSUE TITLE
[BUG] Timeout setting is not saved after turning off printer.

### ISSUE THREAD

**Issue by Gyrxiur** [prusa3d/Prusa-Firmware-Buddy#768]
**Printer type** - [MINI]

**Printer firmware version** -  4.2.0

Timeout setting is not saved after turning off printer. It always resets to On.

**Comment by JohnnyDeer** [comment]
Hi @Gyrxiur, I can confirm that. Thank you for reporting.

**Comment by JohnnyDeer** [comment]
@Gyrxiur this bug is fixed in 4.3.0, please try it out. I´m closing this issue as solved.
