### ISSUE TITLE
Kalibrace menší plochy

### ISSUE THREAD

**Issue by espr14** [prusa3d/Prusa-Firmware-Buddy#77]
Prusa slicer by mohl spočítat bounding box první vrstvy a podle toho vytvořit G29 parametry (L, R, F, B), aby se kalibrovala pouze plocha, na které se bude tisknout. FW by pak našel nejbližší kalibrační body (směrem k okraji podložky) a kalibroval by jen daný prostor. Kalibrace by tak byla rychlejší a přesnější. V případě počtu kalibračních bodů méně než 3 (v každém směru) by se přidaly body, aby jich bylo minimálně 3x3. Pokud je kalibrovaná plocha malá, tak by se případně mohlo přidat o 1 (či více) měření navíc. Čas by tak byl srovnatelný s běžnou kalibrací celé podložky, ale přesnost by byla větší, což je u malých výtisků důležitější.

Smysl to bude mít více pro i3 a nejvíce pro CoreXY (Prusa MAXI). Případně to může být jedno z témat příštího Hackatonu.

**Comment by michalxfanta** [comment]
Toto je určitě velmi zajímavý nápad a zvážíme jeho implementaci.
