### ISSUE TITLE
[BUG] Printing crashed with message: webServerTask

### ISSUE THREAD

**Issue by drakor007** [prusa3d/Prusa-Firmware-Buddy#771]
**Printer type** - [MINI]

**Printer firmware version**-  [4.2.0 finall]

**Original or Custom firmware** [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
  print via USB flash drive

**Describe the bug**
 
Print crash approx. after 17hours

see for more details:

[https://forum.prusaprinters.org/forum/hardware-firmware-and-software-help/printing-crashed-with-message-webservertask-precise-data-access-error-precise-bot-any-ideas/](url)

[https://forum.prusaprinters.org/forum/hardware-firmware-a-software-pomoc/error-screen-po-17h-tisku/](url)

**Comment by JohnnyDeer** [comment]
Hi @drakor007, thank you for reporting.

**Comment by loveolsson** [comment]
I had the same issue, with the same version, also printing from USB, but died after ~4h.


![Capture](https://user-images.githubusercontent.com/6653043/89958898-6beb8600-dc3b-11ea-822f-0ede6066e516.PNG)

**Comment by JohnnyDeer** [comment]
@loveolsson could you upload crash dump please?

**Comment by Nosepicker2112** [comment]
![20200812_103647](https://user-images.githubusercontent.com/69595202/90039435-9ddd0680-dc94-11ea-8b24-81362a5809f0.jpg)

**Comment by Nosepicker2112** [comment]
^^^ crash load dump -->  extrapolted from bin to notepad--> 
G1 X157.713 Y107.263 E0.00530
G1 X157.733 Y107.444 E0.00324
G1 X157.706 Y107.721 E0.00495
G1 X157.558 Y107.993 E0.00552
G1 X157.371 Y108.117 E0.00401
M204 S1250
G1 X157.175 Y108.040 F9000.000
G1 E-1.40000 F4200.00000
G1 F7200.000
G1 X157.141 Y108.183 E-0.13235
G1 X156.916 Y108.117 E-0.12976
G1 X156.729 Y107.946 E-0.14045
G1 X156.688 Y107.856 E-0.05490
G1 X156.642 Y107.658 E-0.11254
G1 E-0.03000 F4200.00000
G1 Z121.300 F9000.000
G1 X158.600 Y105.035
G1 Z120.800
G1 E2.00000 F2400.00000
M204 S800
G1 F1500.000

**Comment by Nosepicker2112** [comment]
[dump - Copy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5065315/dump.-.Copy.zip)

**Comment by OptionMan** [comment]
I had the same issue, with the same version, also printing from USB, but died after ~2h.
![Prusa_mini_blue_screen](https://user-images.githubusercontent.com/6620505/90063568-dc50e080-dce9-11ea-9c59-e77ab1ea94db.jpg)

**Comment by fuelflo** [comment]
Hey, I also got a crash while printing, roughly after 2hrs, on the 4.2.0 firmware. Network connection enabled. filament sensor, english language enabled.

But as I can see, there are a few different error messages. So I'm not sure if I was supposed to create a new issue.

Mine was:

> webServerTask, Illegal unaligned load or store

![IMG_20200814_192653](https://user-images.githubusercontent.com/8934762/90279735-476cf500-de59-11ea-8c2c-56f33f8665ac.jpg)


Is it safe to just flash firmware 4.1.0 on top of 4.2.0 in order to be able to continue printing until it's fixed?

**Comment by Nosepicker2112** [comment]
I have raised the issue with prusa. Presently exchanging info.... Their initial direction is to re-flash the firmware and then do a factory reset.  Then run a test print.  Sucks thou because seems like the crashes come on after hours and hours.....  That is all I have ATT.

**Comment by LittleJono** [comment]
I'm also getting this error. I'm downgrading back to 4.1.0 to see if it fixes it.

**Comment by schluppy** [comment]
I had the same issue twice. Is there anything I can do to help to find the bug? The prusa mini is my first 3d printer, and it's sad with these malfunctions. 

[https://1.bp.blogspot.com/-HDz9ZEbrGVo/XzecJ69BVBI/AAAAAAACm6s/v4HvyE5-k4Y1EJbkSa8ROje4z8yiLAGvgCPcBGAsYHg/s4032/20200814_225126.jpg](url)

**Comment by JohnnyDeer** [comment]
Many thanks to all for Dumps. We are working on this issue with high priority.

**Comment by ghnu** [comment]
So what to do now? How long Prusa needs to fix that?

Since I like to continue to print: Better downgrade to 4.1.0?

**Comment by JohnnyDeer** [comment]
@ghnu yes you rather downgrade to 4.1.0. Unfortunately no one can tell any date but it will take few weeks I think.

**Comment by schluppy** [comment]
@ghnu I have no problems if the network cable is not plugged in. My last print run lasted 36 hours.

**Comment by mlcdev** [comment]
Same error here, bluescreen and webServerTask. I have LAN enabled but no cable plugged in. Also got the Filament Sensor option enabled. I disabled LAN for now, maybe it helps? See my dump file attached.

[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5089531/dump.zip)

**Comment by drakor007** [comment]
So, a workaround could be: disable LAN & unplug LAN cable?

**Comment by schluppy** [comment]
> So, a workaround could be: disable LAN & unplug LAN cable?

It works for me. LAN cable unplugged. I haven't had a crash since. I'd run a project for 38 hours without any issues since I unplugged the cable.

**Comment by drakor007** [comment]
may be .... https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/835

**Comment by mweisshaupt1988** [comment]
![IMG_20200826_122318](https://user-images.githubusercontent.com/3426126/91310244-e70f7900-e7b1-11ea-9bde-7cd87a09fb67.jpg)
Just had this happen too. My Mini is not connected to a network, but it was once because I wanted to try out the web ui.

**Comment by adamhovorka** [comment]
Adding my dump. Printing from USB, neither Ethernet nor ESP plugged in at all, about halfway through a large print.

![IMG_20200826_002415](https://user-images.githubusercontent.com/1766747/91607566-51025c80-e931-11ea-851d-7deddff6d72e.jpg)

**Comment by rtyr** [comment]
New firmware version fixing BSOD issues. https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.2.1

**Comment by JohnnyDeer** [comment]
If there isn't more BSOD cases I´ll close this issue soon. Please leave comment here if anyone will have BSOD on 4.2.1.
