### ISSUE TITLE
Mini firmware crash / error, "blue screen of death"

### ISSUE THREAD

**Issue by randomev** [prusa3d/Prusa-Firmware-Buddy#791]
21h print was almost done, about 1-2 hours left, left it print during night. In the morning I noticed blue screen on my Mini display.

Both printer fans were on. Heater was cold and bed was cold so safety was not compromized.

Firmware 4.2.0-final+2067. Just before print I had upgraded to this firmware. 
I have not experienced this kind of behaviour before.

My printer USB could be the reason, it seems that I need sometimes "wiggle" the USB-stick to get printer to recognize the USB-stick. Using USB-stick provided with the Mini.

Can provide GCODE of the print if needed (about 100 mb).

Picture of BOD attached and crash-dump file attached.
[dump.bin.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5067337/dump.bin.zip)

![4-2-0-mini-fw-bod](https://user-images.githubusercontent.com/541276/90098552-2fa24d80-dd41-11ea-8d69-85857e680a4f.jpeg)

**Comment by Miyagi414** [comment]
I am getting the same error. First print after upgrading to 4.2.0 
 
Here is the gcode that I was running:
[CardBoxV3_0.2mm_PLA_MINI_9h13m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5097072/CardBoxV3_0.2mm_PLA_MINI_9h13m.gcode.zip)


![IMG_5751](https://user-images.githubusercontent.com/38472806/90647114-fae13b00-e205-11ea-8e0e-c63eb9587d38.jpeg)

**Comment by MartinMajewski** [comment]
Right after the upgrade and during restart the above-mentioned crash.

Two hours into the first print with FW 4.2.0 and the same crash again.

![IMG_3834](https://user-images.githubusercontent.com/2221289/90822005-0df22900-e334-11ea-8537-1e4414e4d48b.jpeg)

What's going on and how to downgrade?


Best wishes,
Martin

**Comment by MartinMajewski** [comment]
Another insight into that issue, and as @adynis has also said, the blue screen seems to be also (Micro-) USB related. After several successful long-time prints from the USB stick (after removing the aforementioned German Umlaut letter) I connected the printer to a RaspberryPi running OctoPrint. Tonight, a few hours into a print, the MINI crashed again.

I cannot recall it correctly, but I think I had the MINI also connected to my Mac, while the first bluescreens happened.

For the time being, I will revert to 4.1.0 to avoid losing print-results and time.

**Comment by itsthejoker** [comment]
I have the same error that @MartinMajewski does -- a displayTask with a precise data access error. Photo here: https://twitter.com/filamentcolors/status/1299117013449797634 Worth noting that I do not have any non-ASCII characters on my USB drive, though I am still using the one that came with the printer. I have run the same gcode (and others) off of the same USB stick since the error with no problems.

**Comment by rtyr** [comment]
New firmware version fixing random BSOD issues. https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.2.1

**Comment by DRracer** [comment]
@MartinMajewski please note the issue with non-ASCII characters on the USB flash drive is still not fixed. This has never worked before and is still not supported. We'll fix the BSOD in this case to at least not crash the FW soon as well.

However, the BSOD randomly appearing during printing shall be fixed and hopefully never return - that applies to reports from @Miyagi414 and @adynis .

**Comment by brentday** [comment]
Hello 

What does it mean when the printer stops printing and goes to a white screen. I'm using the USB stick that came with Mini.

**Comment by JohnnyDeer** [comment]
Hi @brentday, white screen mean issue with LCD communication. Please check if your connectors are properly connected.

**Comment by MartinMajewski** [comment]
> @MartinMajewski please note the issue with non-ASCII characters on the USB flash drive is still not fixed. This has never worked before and is still not supported. We'll fix the BSOD in this case to at least not crash the FW soon as well.

Thanks for the information! Usually, I don't use non-ASCII characters, this was a typo from my side.
I will raise a feature request at the PrusaSlicer repository because I think it would be a good addition to prevent those typos beforehand.
