### ISSUE TITLE
Support of M500 GCode command

### ISSUE THREAD

**Issue by cnEUL** [prusa3d/Prusa-Firmware-Buddy#802]
**Printer type** - [MINI] V4.2

**Describe the expected functionality**
I would like M500 command on the mini firmware. The reason is, tzhat i am using the extruder upgrade from Bondtech. This needs another stepping rate (M92 E415). I can insert this as custom gcode, but it would be more comfortable if that value could be saved in the eeprom.

If it is not possible for some reasons, please give us soime information, why exists this limit.

Thank you

**Comment by JohnnyDeer** [comment]
Hi @cnEUL this issue is dupicate of #767. I´m closing this one.
