### ISSUE TITLE
[ENHANCEMENT] UX - Add Confirmation Dialogue From "Stop" Command to "Pause" / "Filament Change" Commands

### ISSUE THREAD

**Issue by mooluk26** [prusa3d/Prusa-Firmware-Buddy#838]
**Printer type** - [MINI]
**Optional upgrades** - [e.g. Filament Runout Sensor]

**Is your suggested improvement related to an existing problem? Please describe.**
While adjusting settings during a print, it is sometimes possible to accidentally select the wrong menu item. Clicking on "Pause" or "Change Filament" results in the print stopping immediately and, in the latter case, results in the filament being unloaded immediately too. If these features are selected by accident (i.e. because the knob was rotated slightly too much), it is highly likely the print will be affected adversely due to the wasted time, oozing etc.

**Describe the expected functionality**
As with the "Stop" command, **a recommended enhancement would be to include the confirmation dialogue (i.e. "Are you sure you would like to Pause the print?") to prevent accidental selection**. This would only marginally delay the process for users doing this intentionally, but it would avoid causing frustrating ruined prints for users who have selected this by accident.

**Comment by JohnnyDeer** [comment]
Hi, within the framework of unification our printers we decided to not implement this suggestion. I3 series have same behavior while stop/pause/change filament therefore this wont be changed on MINI. Thank you for understanding.
