### ISSUE TITLE
Octoprint connection screen does not appear is octoprint connects while on the load filament screen

### ISSUE THREAD

**Issue by greetoz** [prusa3d/Prusa-Firmware-Buddy#845]
I was loading a different filament while starting up octoprint. Finished loading the filament and octoprint said it was connected. Started a print on octoprint and the printer started to print but the printer just had the normal home screen and no indication it was being controlled by octoprint or even printing.

Firmware 4.1.0

**Comment by JohnnyDeer** [comment]
Hi @greetoz please try this issue on version 4.2.0 there are some changes in Octoprint connection.

**Comment by andreas4all** [comment]
Same n 4.2.1
