### ISSUE TITLE
Sleep Display During Prints

### ISSUE THREAD

**Issue by freshmas** [prusa3d/Prusa-Firmware-Buddy#85]
It would be nice if there was an option in the Tune menu to to have the display automatically sleep after 10 seconds while printing. Any input by the user should wake the screen when this mode is enabled.

If possible, the display should also wake any time one of the printer axes has not moved for more than 2 seconds.

**Comment by michalxfanta** [comment]
This is a very good idea, we will definitely implement this feature in some of the next releases.
