### ISSUE TITLE
[BUG] BSOD on reconnect, if printer is still connected

### ISSUE THREAD

**Issue by onkelpit** [prusa3d/Prusa-Firmware-Buddy#944]
**Printer type** - [MINI]

**Printer firmware version**-  4.2.1-final+2072

**Original or Custom firmware** Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** USB/Octoprint

**Describe the bug**
The printer was connected via serial with the Octoprint Server. I installed a plugin an restarted the server. The printer still shows that little Octoprint logo in the screen. I clicked on "Connect" in the freshly started Octoprint. A BSOD was shown and the fans started to go on.

**How to reproduce**
1. Connect printer via USB serial
2. Restart Octoprint (via Packageupdater)
3. check if the Octoprint logo stays on the screen of the Mini
4. click "Connect" in freshly restarted Octoprint instance

**Expected behavior**
Eather drop the old session and reconnect or deny the connection.

**G-code**
-

**Crash dump file**
Insidie the zip-archive.

**Video**
-

[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5336327/dump.zip)
![IMG_20201006_203917](https://user-images.githubusercontent.com/7003446/95253049-2227b200-081e-11eb-825f-35d8c7642c72.jpg)

**Comment by JohnnyDeer** [comment]
Hi @onkelpit thank you for reporting.

**Comment by Ringous1** [comment]
What was the plugin? I tried to call the BSOD with these steps unsuccessfully. Normal behavior

**Comment by d-zalewski** [comment]
I'm not sure if my issue is related but occasionally when I press disconnect Octoprint from the Mini screen and then go to Calibration menu, it hangs for few seconds, then a beep and watchdog error appears followed by a BSOD and a reboot.

**Comment by JohnnyDeer** [comment]
@onkelpit @d-zalewski  unfortunately we are not able to reproduce it. Could you please try it on 4.3.0-RC1?

**Comment by JohnnyDeer** [comment]
@onkelpit is this issue still relevant?

**Comment by onkelpit** [comment]
@JohnnyDeer i was not able to reproduce it nor had the issue again. Can be closed. If it will happen again, I'ld open a new ticket.

**Comment by JohnnyDeer** [comment]
@onkelpit thank you for update :)

**Comment by blejdfist** [comment]
I have had something similar happen a couple of times, but unfortunately I didn't get a picture of the screen but I did save a crash dump after reset.

[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/6196540/dump.zip)
