### ISSUE TITLE
[BUG] Hotend cooling fan insufficient supply voltage

### ISSUE THREAD

**Issue by jack-aaron-cooper** [prusa3d/Prusa-Firmware-Buddy#977]
**Printer type** - MINI
**Printer firmware version** -  4.2.1 - final+2072

**SD card or USB/Octoprint**
USB

**Describe the bug**
The hotend cooling fan on boot will have the correct 5V (4.99V), however, when preheating or printing it will have approximately 2.2V. As a result of this the fan will not spin without a push start and at that voltage the fan will not spin fast enough to provide enough cooling to the hotend.
  
**To Reproduce**
- Check hotend cooling fan voltage on boot.
- Check hotend cooling fan voltage on preheat or printing.
  
**Expected behavior**
When preheating or printing the voltage should be 5V, when it is above the fan activation temperature

**Images**

Boot
![IMG_7526](https://user-images.githubusercontent.com/70938136/96360200-9d665d80-1166-11eb-8385-ac425b1a0fd4.JPG)

Preheating/Printing
![IMG_7529](https://user-images.githubusercontent.com/70938136/96360204-a1927b00-1166-11eb-9efd-60c0e26a5830.JPG)

Measurement points
![IMG_7527](https://user-images.githubusercontent.com/70938136/96360202-a0614e00-1166-11eb-984d-d00abcbfe49b.JPG)

**Comment by dominickuznik** [comment]
I have the same problem with a clone, at first I thought that the firmware recognizes a "foreign" fan when booting and does something stupid :)
when my original came, I saw how much air it promotes.
you can take the 5 v from the filament sensor slot, I did that to cool the buddyboard :)

**Comment by x10102** [comment]
My cooling fan works just fine during printing so I assume the voltage is okay as well. It's probably a problem on your board.

**Comment by dominickuznik** [comment]
Although the correct 5v is present when booting - if there is a problem with the board it will be replaced by prusa.

**Comment by jack-aaron-cooper** [comment]
I'm pretty sure it is a preset PWM value in the firmware, to keep the fan quiet.

**Comment by jack-aaron-cooper** [comment]
https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/95447c177e0d3301713266200ed2620fe10551ae/src/common/config_a3ides2209_02.h#L83

**Comment by JohnnyDeer** [comment]
Hi @jack-aaron-cooper as you wrote, the PWM value in the firmware is to keep fan quiet. So this wont be changed. I close this issue, thank you for understanding.
