### ISSUE TITLE
[BUG] Messages not translated

### ISSUE THREAD

**Issue by x10102** [prusa3d/Prusa-Firmware-Buddy#984]
**Printer type** - [MINI]

**Printer firmware version**-  4,2,1

**Original or Custom firmware**- Original

**USB drive or USB/Octoprint**- USB

**Describe the bug**
  The messages are displayed in English even though the language is set to Czech. Haven't tested if this happens with other 
  languages.

**How to reproduce**
  1. Set language to Czech
  2. Start a print
  3. Open "Messages" from the Tune menu

![IMG_20201021_103830](https://user-images.githubusercontent.com/29236660/96695741-480a9600-138a-11eb-9d0f-ea82ea75f8d9.jpg)

**Comment by JohnnyDeer** [comment]
Hi @x10102 thank you for reporting.
