### ISSUE TITLE
BSOD after a Watchdog reset on 4.2.1

### ISSUE THREAD

**Issue by JohnnyDeer** [prusa3d/Prusa-Firmware-Buddy#990]
I'll bite. Got a BSOD with the same message after a Watchdog reset on 4.2.1; this was the second or third layer of the print, if that matters. Will retrieve dump from USB after print finishes... repeating the print did not make it recur, so it does not seem to be G-code specific.

![IMG_0006](https://user-images.githubusercontent.com/53943260/96351031-e8a93f00-1086-11eb-8fe4-c8c2e1478293.JPG)

_Originally posted by @vintagepc in https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/763#issuecomment-711063459_

**Comment by vintagepc** [comment]
> Thank you again for your prompt answer. After some investigation I need to ask you another questions just to confirm what could happened:
> 
> Did the BSOD occur immediately after the printer startup? (< 20 seconds)

No, this was after it had been on for a bit; this was a second or third print after poweron. 

> Last what you did was press the knob

Correct - I inserted the USB stick with a newly sliced file, and pushed "Print" on the confirmation screen that pops up.

> Did you do anything else? (plug/unplug the USB stick, ethernet cable,...)

No - I remember I watched the first layer stick down, a little bit of the second layer, and then walked away; A few moments later I heard the printer stop moving, looked over,  and the watchdog error was on screen.

**Comment by marekmosna-prusa3d** [comment]
Hi @vintagepc 

Such a bug will be fixed with the next version of Firmware-Buddy. I hope it will not be disturbing you and your printing too much. If anything happened please let us know. We appreciate your attitude and effort that help us make the firmware better.

Thank you
Development team

**Comment by vintagepc** [comment]
Thanks - so far no recurrences yet, but good to hear you've got something in the works for the next version!

**Comment by inferior-minion** [comment]
I've gotten at least 4 resets on my Mini running 4.2.1. I updated as soon as it came out. I've attached the dump file from the latest one. Please help, this is very annoying and has been ongoing for a while.
[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5680965/dump.zip)

**Comment by JohnnyDeer** [comment]
This bug is fixed in 4.3.0-RC1. I'm closing this issue.
